//! Translated from PostgreSQL src/include/tcop/cmdtaglist.h
//
// The C file is an x-macro list expanded via PG_CMDTAG(symbol, name, ...). Here
// it becomes a `CommandTag` enum plus a static table carrying each tag's textual
// name and its three boolean properties. The table stays sorted alphabetically
// by name so it can be binary-searched (cf. GetCommandTagEnum).

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CommandTag {
    Unknown,
    AlterAccessMethod,
    AlterAggregate,
    AlterCast,
    AlterCollation,
    AlterConstraint,
    AlterConversion,
    AlterDatabase,
    AlterDefaultPrivileges,
    AlterDomain,
    AlterEventTrigger,
    AlterExtension,
    AlterForeignDataWrapper,
    AlterForeignTable,
    AlterFunction,
    AlterIndex,
    AlterLanguage,
    AlterLargeObject,
    AlterMaterializedView,
    AlterOperator,
    AlterOperatorClass,
    AlterOperatorFamily,
    AlterPolicy,
    AlterProcedure,
    AlterPublication,
    AlterRole,
    AlterRoutine,
    AlterRule,
    AlterSchema,
    AlterSequence,
    AlterServer,
    AlterStatistics,
    AlterSubscription,
    AlterSystem,
    AlterTable,
    AlterTablespace,
    AlterTextSearchConfiguration,
    AlterTextSearchDictionary,
    AlterTextSearchParser,
    AlterTextSearchTemplate,
    AlterTransform,
    AlterTrigger,
    AlterType,
    AlterUserMapping,
    AlterView,
    Analyze,
    Begin,
    Call,
    Checkpoint,
    Close,
    CloseCursor,
    CloseCursorAll,
    Cluster,
    Comment,
    Commit,
    CommitPrepared,
    Copy,
    CopyFrom,
    CreateAccessMethod,
    CreateAggregate,
    CreateCast,
    CreateCollation,
    CreateConstraint,
    CreateConversion,
    CreateDatabase,
    CreateDomain,
    CreateEventTrigger,
    CreateExtension,
    CreateForeignDataWrapper,
    CreateForeignTable,
    CreateFunction,
    CreateIndex,
    CreateLanguage,
    CreateMaterializedView,
    CreateOperator,
    CreateOperatorClass,
    CreateOperatorFamily,
    CreatePolicy,
    CreateProcedure,
    CreatePublication,
    CreateRole,
    CreateRoutine,
    CreateRule,
    CreateSchema,
    CreateSequence,
    CreateServer,
    CreateStatistics,
    CreateSubscription,
    CreateTable,
    CreateTableAs,
    CreateTablespace,
    CreateTextSearchConfiguration,
    CreateTextSearchDictionary,
    CreateTextSearchParser,
    CreateTextSearchTemplate,
    CreateTransform,
    CreateTrigger,
    CreateType,
    CreateUserMapping,
    CreateView,
    Deallocate,
    DeallocateAll,
    DeclareCursor,
    Delete,
    Discard,
    DiscardAll,
    DiscardPlans,
    DiscardSequences,
    DiscardTemp,
    Do,
    DropAccessMethod,
    DropAggregate,
    DropCast,
    DropCollation,
    DropConstraint,
    DropConversion,
    DropDatabase,
    DropDomain,
    DropEventTrigger,
    DropExtension,
    DropForeignDataWrapper,
    DropForeignTable,
    DropFunction,
    DropIndex,
    DropLanguage,
    DropMaterializedView,
    DropOperator,
    DropOperatorClass,
    DropOperatorFamily,
    DropOwned,
    DropPolicy,
    DropProcedure,
    DropPublication,
    DropRole,
    DropRoutine,
    DropRule,
    DropSchema,
    DropSequence,
    DropServer,
    DropStatistics,
    DropSubscription,
    DropTable,
    DropTablespace,
    DropTextSearchConfiguration,
    DropTextSearchDictionary,
    DropTextSearchParser,
    DropTextSearchTemplate,
    DropTransform,
    DropTrigger,
    DropType,
    DropUserMapping,
    DropView,
    Execute,
    Explain,
    Fetch,
    Grant,
    GrantRole,
    ImportForeignSchema,
    Insert,
    Listen,
    Load,
    LockTable,
    Login,
    Merge,
    Move,
    Notify,
    Prepare,
    PrepareTransaction,
    ReassignOwned,
    RefreshMaterializedView,
    Reindex,
    Release,
    Reset,
    Revoke,
    RevokeRole,
    Rollback,
    RollbackPrepared,
    Savepoint,
    SecurityLabel,
    Select,
    SelectForKeyShare,
    SelectForNoKeyUpdate,
    SelectForShare,
    SelectForUpdate,
    SelectInto,
    Set,
    SetConstraints,
    Show,
    StartTransaction,
    TruncateTable,
    Unlisten,
    Update,
    Vacuum,
}

/// Properties carried for each command tag (the trailing PG_CMDTAG fields).
pub struct CommandTagBehavior {
    pub tag: CommandTag,
    pub name: &'static str,
    pub event_trigger_ok: bool,
    pub table_rewrite_ok: bool,
    pub display_rowcount: bool,
}

// Sorted alphabetically by `name` for binary search (GetCommandTagEnum).
pub const COMMAND_TAGS: &[CommandTagBehavior] = &[
    CommandTagBehavior { tag: CommandTag::Unknown, name: "???", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterAccessMethod, name: "ALTER ACCESS METHOD", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterAggregate, name: "ALTER AGGREGATE", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterCast, name: "ALTER CAST", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterCollation, name: "ALTER COLLATION", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterConstraint, name: "ALTER CONSTRAINT", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterConversion, name: "ALTER CONVERSION", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterDatabase, name: "ALTER DATABASE", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterDefaultPrivileges, name: "ALTER DEFAULT PRIVILEGES", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterDomain, name: "ALTER DOMAIN", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterEventTrigger, name: "ALTER EVENT TRIGGER", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterExtension, name: "ALTER EXTENSION", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterForeignDataWrapper, name: "ALTER FOREIGN DATA WRAPPER", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterForeignTable, name: "ALTER FOREIGN TABLE", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterFunction, name: "ALTER FUNCTION", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterIndex, name: "ALTER INDEX", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterLanguage, name: "ALTER LANGUAGE", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterLargeObject, name: "ALTER LARGE OBJECT", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterMaterializedView, name: "ALTER MATERIALIZED VIEW", event_trigger_ok: true, table_rewrite_ok: true, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterOperator, name: "ALTER OPERATOR", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterOperatorClass, name: "ALTER OPERATOR CLASS", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterOperatorFamily, name: "ALTER OPERATOR FAMILY", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterPolicy, name: "ALTER POLICY", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterProcedure, name: "ALTER PROCEDURE", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterPublication, name: "ALTER PUBLICATION", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterRole, name: "ALTER ROLE", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterRoutine, name: "ALTER ROUTINE", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterRule, name: "ALTER RULE", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterSchema, name: "ALTER SCHEMA", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterSequence, name: "ALTER SEQUENCE", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterServer, name: "ALTER SERVER", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterStatistics, name: "ALTER STATISTICS", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterSubscription, name: "ALTER SUBSCRIPTION", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterSystem, name: "ALTER SYSTEM", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterTable, name: "ALTER TABLE", event_trigger_ok: true, table_rewrite_ok: true, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterTablespace, name: "ALTER TABLESPACE", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterTextSearchConfiguration, name: "ALTER TEXT SEARCH CONFIGURATION", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterTextSearchDictionary, name: "ALTER TEXT SEARCH DICTIONARY", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterTextSearchParser, name: "ALTER TEXT SEARCH PARSER", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterTextSearchTemplate, name: "ALTER TEXT SEARCH TEMPLATE", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterTransform, name: "ALTER TRANSFORM", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterTrigger, name: "ALTER TRIGGER", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterType, name: "ALTER TYPE", event_trigger_ok: true, table_rewrite_ok: true, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterUserMapping, name: "ALTER USER MAPPING", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::AlterView, name: "ALTER VIEW", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::Analyze, name: "ANALYZE", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::Begin, name: "BEGIN", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::Call, name: "CALL", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::Checkpoint, name: "CHECKPOINT", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::Close, name: "CLOSE", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CloseCursor, name: "CLOSE CURSOR", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CloseCursorAll, name: "CLOSE CURSOR ALL", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::Cluster, name: "CLUSTER", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::Comment, name: "COMMENT", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::Commit, name: "COMMIT", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CommitPrepared, name: "COMMIT PREPARED", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::Copy, name: "COPY", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: true },
    CommandTagBehavior { tag: CommandTag::CopyFrom, name: "COPY FROM", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateAccessMethod, name: "CREATE ACCESS METHOD", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateAggregate, name: "CREATE AGGREGATE", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateCast, name: "CREATE CAST", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateCollation, name: "CREATE COLLATION", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateConstraint, name: "CREATE CONSTRAINT", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateConversion, name: "CREATE CONVERSION", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateDatabase, name: "CREATE DATABASE", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateDomain, name: "CREATE DOMAIN", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateEventTrigger, name: "CREATE EVENT TRIGGER", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateExtension, name: "CREATE EXTENSION", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateForeignDataWrapper, name: "CREATE FOREIGN DATA WRAPPER", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateForeignTable, name: "CREATE FOREIGN TABLE", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateFunction, name: "CREATE FUNCTION", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateIndex, name: "CREATE INDEX", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateLanguage, name: "CREATE LANGUAGE", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateMaterializedView, name: "CREATE MATERIALIZED VIEW", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateOperator, name: "CREATE OPERATOR", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateOperatorClass, name: "CREATE OPERATOR CLASS", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateOperatorFamily, name: "CREATE OPERATOR FAMILY", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreatePolicy, name: "CREATE POLICY", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateProcedure, name: "CREATE PROCEDURE", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreatePublication, name: "CREATE PUBLICATION", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateRole, name: "CREATE ROLE", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateRoutine, name: "CREATE ROUTINE", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateRule, name: "CREATE RULE", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateSchema, name: "CREATE SCHEMA", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateSequence, name: "CREATE SEQUENCE", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateServer, name: "CREATE SERVER", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateStatistics, name: "CREATE STATISTICS", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateSubscription, name: "CREATE SUBSCRIPTION", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateTable, name: "CREATE TABLE", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateTableAs, name: "CREATE TABLE AS", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateTablespace, name: "CREATE TABLESPACE", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateTextSearchConfiguration, name: "CREATE TEXT SEARCH CONFIGURATION", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateTextSearchDictionary, name: "CREATE TEXT SEARCH DICTIONARY", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateTextSearchParser, name: "CREATE TEXT SEARCH PARSER", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateTextSearchTemplate, name: "CREATE TEXT SEARCH TEMPLATE", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateTransform, name: "CREATE TRANSFORM", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateTrigger, name: "CREATE TRIGGER", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateType, name: "CREATE TYPE", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateUserMapping, name: "CREATE USER MAPPING", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::CreateView, name: "CREATE VIEW", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::Deallocate, name: "DEALLOCATE", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DeallocateAll, name: "DEALLOCATE ALL", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DeclareCursor, name: "DECLARE CURSOR", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::Delete, name: "DELETE", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: true },
    CommandTagBehavior { tag: CommandTag::Discard, name: "DISCARD", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DiscardAll, name: "DISCARD ALL", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DiscardPlans, name: "DISCARD PLANS", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DiscardSequences, name: "DISCARD SEQUENCES", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DiscardTemp, name: "DISCARD TEMP", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::Do, name: "DO", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropAccessMethod, name: "DROP ACCESS METHOD", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropAggregate, name: "DROP AGGREGATE", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropCast, name: "DROP CAST", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropCollation, name: "DROP COLLATION", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropConstraint, name: "DROP CONSTRAINT", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropConversion, name: "DROP CONVERSION", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropDatabase, name: "DROP DATABASE", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropDomain, name: "DROP DOMAIN", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropEventTrigger, name: "DROP EVENT TRIGGER", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropExtension, name: "DROP EXTENSION", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropForeignDataWrapper, name: "DROP FOREIGN DATA WRAPPER", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropForeignTable, name: "DROP FOREIGN TABLE", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropFunction, name: "DROP FUNCTION", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropIndex, name: "DROP INDEX", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropLanguage, name: "DROP LANGUAGE", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropMaterializedView, name: "DROP MATERIALIZED VIEW", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropOperator, name: "DROP OPERATOR", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropOperatorClass, name: "DROP OPERATOR CLASS", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropOperatorFamily, name: "DROP OPERATOR FAMILY", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropOwned, name: "DROP OWNED", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropPolicy, name: "DROP POLICY", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropProcedure, name: "DROP PROCEDURE", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropPublication, name: "DROP PUBLICATION", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropRole, name: "DROP ROLE", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropRoutine, name: "DROP ROUTINE", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropRule, name: "DROP RULE", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropSchema, name: "DROP SCHEMA", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropSequence, name: "DROP SEQUENCE", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropServer, name: "DROP SERVER", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropStatistics, name: "DROP STATISTICS", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropSubscription, name: "DROP SUBSCRIPTION", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropTable, name: "DROP TABLE", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropTablespace, name: "DROP TABLESPACE", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropTextSearchConfiguration, name: "DROP TEXT SEARCH CONFIGURATION", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropTextSearchDictionary, name: "DROP TEXT SEARCH DICTIONARY", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropTextSearchParser, name: "DROP TEXT SEARCH PARSER", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropTextSearchTemplate, name: "DROP TEXT SEARCH TEMPLATE", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropTransform, name: "DROP TRANSFORM", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropTrigger, name: "DROP TRIGGER", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropType, name: "DROP TYPE", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropUserMapping, name: "DROP USER MAPPING", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::DropView, name: "DROP VIEW", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::Execute, name: "EXECUTE", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::Explain, name: "EXPLAIN", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::Fetch, name: "FETCH", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: true },
    CommandTagBehavior { tag: CommandTag::Grant, name: "GRANT", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::GrantRole, name: "GRANT ROLE", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::ImportForeignSchema, name: "IMPORT FOREIGN SCHEMA", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::Insert, name: "INSERT", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: true },
    CommandTagBehavior { tag: CommandTag::Listen, name: "LISTEN", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::Load, name: "LOAD", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::LockTable, name: "LOCK TABLE", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::Login, name: "LOGIN", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::Merge, name: "MERGE", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: true },
    CommandTagBehavior { tag: CommandTag::Move, name: "MOVE", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: true },
    CommandTagBehavior { tag: CommandTag::Notify, name: "NOTIFY", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::Prepare, name: "PREPARE", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::PrepareTransaction, name: "PREPARE TRANSACTION", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::ReassignOwned, name: "REASSIGN OWNED", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::RefreshMaterializedView, name: "REFRESH MATERIALIZED VIEW", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::Reindex, name: "REINDEX", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::Release, name: "RELEASE", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::Reset, name: "RESET", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::Revoke, name: "REVOKE", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::RevokeRole, name: "REVOKE ROLE", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::Rollback, name: "ROLLBACK", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::RollbackPrepared, name: "ROLLBACK PREPARED", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::Savepoint, name: "SAVEPOINT", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::SecurityLabel, name: "SECURITY LABEL", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::Select, name: "SELECT", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: true },
    CommandTagBehavior { tag: CommandTag::SelectForKeyShare, name: "SELECT FOR KEY SHARE", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::SelectForNoKeyUpdate, name: "SELECT FOR NO KEY UPDATE", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::SelectForShare, name: "SELECT FOR SHARE", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::SelectForUpdate, name: "SELECT FOR UPDATE", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::SelectInto, name: "SELECT INTO", event_trigger_ok: true, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::Set, name: "SET", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::SetConstraints, name: "SET CONSTRAINTS", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::Show, name: "SHOW", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::StartTransaction, name: "START TRANSACTION", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::TruncateTable, name: "TRUNCATE TABLE", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::Unlisten, name: "UNLISTEN", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
    CommandTagBehavior { tag: CommandTag::Update, name: "UPDATE", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: true },
    CommandTagBehavior { tag: CommandTag::Vacuum, name: "VACUUM", event_trigger_ok: false, table_rewrite_ok: false, display_rowcount: false },
];
