//! Build-time generators for data-driven PostgreSQL tables kept as upstream `.dat`
//! files (we read them from the `ref/postgres` submodule, the single source of
//! truth). Per the project's mechanism rule, build.rs is used only for these
//! `.dat`-backed families; the flat-list families are Rust macros instead.
//!
//! Currently: the fmgr tables (Gen_fmgrtab.pl) from `catalog/pg_proc.dat`.

use std::path::PathBuf;

fn main() {
    let pg = PathBuf::from("ref/postgres/src/include/catalog");
    let proc_dat = pg.join("pg_proc.dat");
    println!("cargo:rerun-if-changed={}", proc_dat.display());
    println!("cargo:rerun-if-changed=build.rs");

    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let text = std::fs::read_to_string(&proc_dat)
        .unwrap_or_else(|e| panic!("read {}: {e}", proc_dat.display()));
    let procs = parse_dat(&text);

    std::fs::write(out.join("fmgroids_generated.rs"), gen_fmgroids(&procs)).unwrap();
    std::fs::write(out.join("fmgrtab_generated.rs"), gen_fmgrtab(&procs)).unwrap();
}

struct Proc {
    oid: u32,
    proname: String,
    proargtypes: String,
    strict: bool,
    retset: bool,
    lang: String,
    prosrc: String,
    nargs: i16,
}

/// Minimal parser for pg_proc.dat: `{ key => 'value', ... },` records (flat, no
/// nested braces), with `#` comment lines. Good enough for the fields fmgr needs.
fn parse_dat(text: &str) -> Vec<Proc> {
    // Drop comment lines (first non-space char is '#').
    let mut buf = String::with_capacity(text.len());
    for line in text.lines() {
        if line.trim_start().starts_with('#') {
            continue;
        }
        buf.push_str(line);
        buf.push('\n');
    }

    let bytes = buf.as_bytes();
    let mut procs = Vec::new();
    let mut i = 0;
    while let Some(open) = buf[i..].find('{') {
        let start = i + open + 1;
        let close = buf[start..].find('}').map(|p| start + p);
        let Some(close) = close else { break };
        procs.push(parse_record(&buf[start..close]));
        i = close + 1;
        let _ = bytes;
    }
    procs.into_iter().flatten().collect()
}

fn parse_record(rec: &str) -> Option<Proc> {
    let mut kv = std::collections::HashMap::new();
    let b = rec.as_bytes();
    let mut i = 0;
    while i < b.len() {
        // find an identifier key
        if !(b[i] as char).is_ascii_alphabetic() {
            i += 1;
            continue;
        }
        let ks = i;
        while i < b.len() && (b[i].is_ascii_alphanumeric() || b[i] == b'_') {
            i += 1;
        }
        let key = &rec[ks..i];
        // expect '=>'
        while i < b.len() && (b[i] == b' ' || b[i] == b'\t' || b[i] == b'\n') {
            i += 1;
        }
        if !(i + 1 < b.len() && b[i] == b'=' && b[i + 1] == b'>') {
            continue;
        }
        i += 2;
        while i < b.len() && (b[i] == b' ' || b[i] == b'\t' || b[i] == b'\n') {
            i += 1;
        }
        if i < b.len() && b[i] == b'\'' {
            i += 1;
            let vs = i;
            while i < b.len() && b[i] != b'\'' {
                if b[i] == b'\\' {
                    i += 1;
                }
                i += 1;
            }
            kv.insert(key.to_string(), rec[vs..i].to_string());
            i += 1; // closing quote
        }
    }

    let oid: u32 = kv.get("oid")?.parse().ok()?;
    let proname = kv.get("proname")?.clone();
    let proargtypes = kv.get("proargtypes").cloned().unwrap_or_default();
    let nargs = match kv.get("pronargs") {
        Some(n) => n.parse().unwrap_or(0),
        None if proargtypes.trim().is_empty() => 0,
        None => proargtypes.split_whitespace().count() as i16,
    };
    Some(Proc {
        oid,
        proname,
        proargtypes,
        strict: kv.get("proisstrict").map(|s| s == "t").unwrap_or(false),
        retset: kv.get("proretset").map(|s| s == "t").unwrap_or(false),
        lang: kv.get("prolang").cloned().unwrap_or_else(|| "internal".into()),
        prosrc: kv.get("prosrc").cloned().unwrap_or_default(),
        nargs,
    })
}

/// Sanitize a string into an upper-case Rust identifier fragment.
fn ident(s: &str) -> String {
    s.chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect::<String>()
        .to_uppercase()
}

fn gen_fmgroids(procs: &[Proc]) -> String {
    use std::collections::HashMap;
    let mut counts: HashMap<&str, u32> = HashMap::new();
    for p in procs {
        *counts.entry(p.proname.as_str()).or_default() += 1;
    }
    let mut sorted: Vec<&Proc> = procs.iter().collect();
    sorted.sort_by_key(|p| p.oid);

    let mut seen: HashMap<String, u32> = HashMap::new();
    let mut out = String::from(
        "// Generated by build.rs from pg_proc.dat (Gen_fmgrtab.pl). F_<proname>;\n\
         // overloaded pronames get _<proargtypes> appended.\n",
    );
    for p in &sorted {
        let mut name = p.proname.clone();
        if counts[p.proname.as_str()] > 1 {
            name.push('_');
            name.push_str(&p.proargtypes);
        }
        let mut sym = format!("F_{}", ident(&name));
        let n = seen.entry(sym.clone()).or_insert(0);
        if *n > 0 {
            sym = format!("{sym}_{}", p.oid); // disambiguate residual collisions
        }
        *n += 1;
        out.push_str(&format!("pub const {sym}: Oid = Oid({});\n", p.oid));
    }
    out
}

fn gen_fmgrtab(procs: &[Proc]) -> String {
    let mut builtins: Vec<&Proc> = procs.iter().filter(|p| p.lang == "internal").collect();
    builtins.sort_by_key(|p| p.oid);
    let last_oid = builtins.last().map(|p| p.oid).unwrap_or(0);

    let mut out = String::from("// Generated by build.rs from pg_proc.dat (internal-language builtins).\n");
    out.push_str("pub static fmgr_builtins: &[FmgrBuiltin] = &[\n");
    for p in &builtins {
        out.push_str(&format!(
            "    FmgrBuiltin {{ foid: Oid({}), nargs: {}, strict: {}, retset: {}, func_name: \"{}\", func: None }},\n",
            p.oid, p.nargs, p.strict, p.retset, p.prosrc
        ));
    }
    out.push_str("];\n");
    out.push_str(&format!("pub const fmgr_nbuiltins: usize = {};\n", builtins.len()));
    out.push_str(&format!("pub const fmgr_last_builtin_oid: Oid = Oid({last_oid});\n"));

    // oid -> index map (InvalidOidBuiltinMapping for unused oids), like C.
    let mut index = vec![u16::MAX; (last_oid as usize) + 1];
    for (i, p) in builtins.iter().enumerate() {
        index[p.oid as usize] = i as u16;
    }
    out.push_str("pub static fmgr_builtin_oid_index: &[u16] = &[\n");
    for chunk in index.chunks(20) {
        out.push_str("    ");
        for v in chunk {
            out.push_str(&format!("{v},"));
        }
        out.push('\n');
    }
    out.push_str("];\n");
    out
}
