[package]
name = "pepperdb"
version = "0.0.0"
edition = "2024"
license = "MIT"

[workspace]
members = ["crates/pepperdb-derive"]

[dependencies]
bitflags = "2"
pepperdb-derive = { path = "crates/pepperdb-derive" }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "sync", "net", "time", "io-util", "macros"] }
futures-util = "0.3"
