//! PostgreSQL-style regression test harness.
//!
//! Each test has a .sql input file and a .out expected output file,
//! mirroring PostgreSQL's src/test/regress/ layout. Both sql/ and
//! expected/ are symlinked to the PostgreSQL 18 submodule, so passing
//! a test means PepperDB output matches PostgreSQL exactly.

mod common;

// -- Test runner --------------------------------------------------------

async fn run_regress_test(name: &str) {
    let setup = match name {
        "varchar" => vec![
            "CREATE TABLE VARCHAR_TBL(f1 varchar(4));",
            "INSERT INTO VARCHAR_TBL (f1) VALUES ('a');",
            "INSERT INTO VARCHAR_TBL (f1) VALUES ('ab');",
            "INSERT INTO VARCHAR_TBL (f1) VALUES ('abcd');",
            "INSERT INTO VARCHAR_TBL (f1) VALUES ('abcd    ');",
        ],
        "char" => vec![
            "CREATE TABLE CHAR_TBL(f1 char(4));",
            "INSERT INTO CHAR_TBL (f1) VALUES ('a');",
            "INSERT INTO CHAR_TBL (f1) VALUES ('ab');",
            "INSERT INTO CHAR_TBL (f1) VALUES ('abcd');",
            "INSERT INTO CHAR_TBL (f1) VALUES ('abcd    ');",
        ],
        _ => vec![],
    };
    common::run_test("tests/regress", name, &setup).await;
}

// -- Test declarations --------------------------------------------------

macro_rules! regress_test {
    ($($name:ident),* $(,)?) => {
        $( #[tokio::test] async fn $name() { run_regress_test(stringify!($name)).await; } )*
    };
}

// Raw-identifier tests (Rust keywords as test names)
// #[tokio::test] async fn r#async() { run_regress_test("async").await; }
// #[tokio::test] async fn r#box() { run_regress_test("box").await; }
// #[tokio::test] async fn r#enum() { run_regress_test("enum").await; }
// #[tokio::test] async fn r#union() { run_regress_test("union").await; }

regress_test!(
    comments,
    md5,
    // advisory_lock,
    // aggregates,
    // alter_generic,
    // alter_operator,
    // alter_table,
    // amutils,
    // arrays,
    // bit,
    // bitmapops,
    boolean,
    // brin,
    // brin_bloom,
    // brin_multi,
    // btree_index,
    // case,
    char,
    // circle,
    // cluster,
    // collate,
    // combocid,
    // combocid,
    // compression,
    // constraints,
    // conversion,
    // copy,
    // copy2,
    // copydml,
    // copyencoding,
    // copyselect,
    // create_aggregate,
    // create_am,
    // create_cast,
    // create_function_c,
    // create_function_sql,
    // create_index,
    // create_index_spgist,
    // create_misc,
    // create_operator,
    // create_procedure,
    // create_role,
    // create_schema,
    // create_table,
    // create_table_like,
    // create_type,
    // create_view,
    // database,
    // date,
    // dbsize,
    delete,
    // dependency,
    // domain,
    // drop_if_exists,
    // drop_operator,
    // encoding,
    // equivclass,
    // errors,
    // euc_kr,
    // event_trigger,
    // event_trigger_login,
    // explain,
    // expressions,
    // fast_default,
    // float4,
    // float8,
    // foreign_data,
    // foreign_key,
    // functional_deps,
    // generated_stored,
    // generated_virtual,
    // geometry,
    // gin,
    // gist,
    // groupingsets,
    // guc,
    // hash_func,
    // hash_index,
    // hash_part,
    // horology,
    // identity,
    // incremental_sort,
    // index_including,
    // index_including_gist,
    // indexing,
    // indirect_toast,
    // inet,
    // infinite_recurse,
    // inherit,
    // init_privs,
    // insert,
    // insert_conflict,
    // int2,
    // int4,
    // int8,
    // interval,
    // join,
    // join_hash,
    // json,
    // json_encoding,
    // jsonb,
    // jsonb_jsonpath,
    // jsonpath,
    // jsonpath_encoding,
    // largeobject,
    // limit,
    // line,
    // lock,
    // lseg,
    // macaddr,
    // macaddr8,
    // maintain_every,
    // matview,
    // md5,
    // memoize,
    // merge,
    // misc,
    // misc_functions,
    // misc_sanity,
    // money,
    // multirangetypes,
    // mvcc,
    // name,
    // namespace,
    // numa,
    // numeric,
    // numeric_big,
    // numerology,
    // object_address,
    // oid,
    // oidjoins,
    // opr_sanity,
    // partition_aggregate,
    // partition_info,
    // partition_join,
    // partition_prune,
    // password,
    // path,
    // pg_lsn,
    // plancache,
    // plpgsql,
    // point,
    // polygon,
    // polymorphism,
    // portals,
    // portals_p2,
    // predicate,
    // prepare,
    // prepared_xacts,
    // privileges,
    // psql,
    // psql_crosstab,
    // psql_pipeline,
    // publication,
    // random,
    // rangefuncs,
    // rangetypes,
    // regex,
    // regproc,
    // reindex_catalog,
    // reloptions,
    // replica_identity,
    // returning,
    // roleattributes,
    // rowsecurity,
    // rowtypes,
    // rules,
    // sanity_check,
    // security_label,
    // select,
    // select_distinct,
    // select_distinct_on,
    select_having,
    select_implicit,
    // select_into,
    // select_parallel,
    // select_views,
    // sequence,
    // spgist,
    // sqljson,
    // sqljson_jsontable,
    // sqljson_queryfuncs,
    // stats,
    // stats_ext,
    // stats_import,
    // strings,
    // subscription,
    // subselect,
    // sysviews,
    // tablesample,
    // tablespace,
    // temp,
    // test_setup,
    // text,
    // tid,
    // tidrangescan,
    // tidscan,
    // time,
    // timestamp,
    // timestamptz,
    // timetz,
    // transactions,
    // triggers,
    // truncate,
    // tsdicts,
    // tsearch,
    // tsrf,
    // tstypes,
    // tuplesort,
    // txid,
    // type_sanity,
    // typed_table,
    // unicode,
    // updatable_views,
    // update,
    // uuid,
    // vacuum,
    // vacuum_parallel,
    varchar,
    // window,
    // with,
    // without_overlaps,
    // write_parallel,
    // xid,
    // xml,
    // xmlmap,
);
