// Generated by Snowball 2.2.0 - https://snowballstem.org/
// Ported file-for-file from postgres/src/backend/snowball/libstemmer/stem_ISO_8859_1_indonesian.c
// (header stem_ISO_8859_1_indonesian.h merged in).
// ISO_8859_1 is single-byte: uses the non-_U grouping fns (in_grouping/out_grouping).

use crate::prelude::*;
use crate::snowball::api::{symbol, SN_env, among, SN_create_env, SN_close_env};
use crate::snowball::utilities::{
    find_among, find_among_b, slice_from_s, slice_del, eq_s, in_grouping, out_grouping,
};

static S_0_0: [symbol; 3] = [b'k' as symbol, b'a' as symbol, b'h' as symbol];
static S_0_1: [symbol; 3] = [b'l' as symbol, b'a' as symbol, b'h' as symbol];
static S_0_2: [symbol; 3] = [b'p' as symbol, b'u' as symbol, b'n' as symbol];

static A_0: [among; 3] = [
    among { s_size: 3, s: S_0_0.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 3, s: S_0_1.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 3, s: S_0_2.as_ptr(), substring_i: -1, result: 1, function: None },
];

static S_1_0: [symbol; 3] = [b'n' as symbol, b'y' as symbol, b'a' as symbol];
static S_1_1: [symbol; 2] = [b'k' as symbol, b'u' as symbol];
static S_1_2: [symbol; 2] = [b'm' as symbol, b'u' as symbol];

static A_1: [among; 3] = [
    among { s_size: 3, s: S_1_0.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 2, s: S_1_1.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 2, s: S_1_2.as_ptr(), substring_i: -1, result: 1, function: None },
];

static S_2_0: [symbol; 1] = [b'i' as symbol];
static S_2_1: [symbol; 2] = [b'a' as symbol, b'n' as symbol];
static S_2_2: [symbol; 3] = [b'k' as symbol, b'a' as symbol, b'n' as symbol];

static A_2: [among; 3] = [
    among { s_size: 1, s: S_2_0.as_ptr(), substring_i: -1, result: 1, function: Some(r_SUFFIX_I_OK) },
    among { s_size: 2, s: S_2_1.as_ptr(), substring_i: -1, result: 1, function: Some(r_SUFFIX_AN_OK) },
    among { s_size: 3, s: S_2_2.as_ptr(), substring_i: 1, result: 1, function: Some(r_SUFFIX_KAN_OK) },
];

static S_3_0: [symbol; 2] = [b'd' as symbol, b'i' as symbol];
static S_3_1: [symbol; 2] = [b'k' as symbol, b'e' as symbol];
static S_3_2: [symbol; 2] = [b'm' as symbol, b'e' as symbol];
static S_3_3: [symbol; 3] = [b'm' as symbol, b'e' as symbol, b'm' as symbol];
static S_3_4: [symbol; 3] = [b'm' as symbol, b'e' as symbol, b'n' as symbol];
static S_3_5: [symbol; 4] = [b'm' as symbol, b'e' as symbol, b'n' as symbol, b'g' as symbol];
static S_3_6: [symbol; 4] = [b'm' as symbol, b'e' as symbol, b'n' as symbol, b'y' as symbol];
static S_3_7: [symbol; 3] = [b'p' as symbol, b'e' as symbol, b'm' as symbol];
static S_3_8: [symbol; 3] = [b'p' as symbol, b'e' as symbol, b'n' as symbol];
static S_3_9: [symbol; 4] = [b'p' as symbol, b'e' as symbol, b'n' as symbol, b'g' as symbol];
static S_3_10: [symbol; 4] = [b'p' as symbol, b'e' as symbol, b'n' as symbol, b'y' as symbol];
static S_3_11: [symbol; 3] = [b't' as symbol, b'e' as symbol, b'r' as symbol];

static A_3: [among; 12] = [
    among { s_size: 2, s: S_3_0.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 2, s: S_3_1.as_ptr(), substring_i: -1, result: 2, function: None },
    among { s_size: 2, s: S_3_2.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 3, s: S_3_3.as_ptr(), substring_i: 2, result: 5, function: None },
    among { s_size: 3, s: S_3_4.as_ptr(), substring_i: 2, result: 1, function: None },
    among { s_size: 4, s: S_3_5.as_ptr(), substring_i: 4, result: 1, function: None },
    among { s_size: 4, s: S_3_6.as_ptr(), substring_i: 4, result: 3, function: Some(r_VOWEL) },
    among { s_size: 3, s: S_3_7.as_ptr(), substring_i: -1, result: 6, function: None },
    among { s_size: 3, s: S_3_8.as_ptr(), substring_i: -1, result: 2, function: None },
    among { s_size: 4, s: S_3_9.as_ptr(), substring_i: 8, result: 2, function: None },
    among { s_size: 4, s: S_3_10.as_ptr(), substring_i: 8, result: 4, function: Some(r_VOWEL) },
    among { s_size: 3, s: S_3_11.as_ptr(), substring_i: -1, result: 1, function: None },
];

static S_4_0: [symbol; 2] = [b'b' as symbol, b'e' as symbol];
static S_4_1: [symbol; 7] = [b'b' as symbol, b'e' as symbol, b'l' as symbol, b'a' as symbol, b'j' as symbol, b'a' as symbol, b'r' as symbol];
static S_4_2: [symbol; 3] = [b'b' as symbol, b'e' as symbol, b'r' as symbol];
static S_4_3: [symbol; 2] = [b'p' as symbol, b'e' as symbol];
static S_4_4: [symbol; 7] = [b'p' as symbol, b'e' as symbol, b'l' as symbol, b'a' as symbol, b'j' as symbol, b'a' as symbol, b'r' as symbol];
static S_4_5: [symbol; 3] = [b'p' as symbol, b'e' as symbol, b'r' as symbol];

static A_4: [among; 6] = [
    among { s_size: 2, s: S_4_0.as_ptr(), substring_i: -1, result: 3, function: Some(r_KER) },
    among { s_size: 7, s: S_4_1.as_ptr(), substring_i: 0, result: 4, function: None },
    among { s_size: 3, s: S_4_2.as_ptr(), substring_i: 0, result: 3, function: None },
    among { s_size: 2, s: S_4_3.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 7, s: S_4_4.as_ptr(), substring_i: 3, result: 2, function: None },
    among { s_size: 3, s: S_4_5.as_ptr(), substring_i: 3, result: 1, function: None },
];

static G_vowel: [c_uchar; 3] = [17, 65, 16];

static S_0: [symbol; 2] = [b'e' as symbol, b'r' as symbol];
static S_1: [symbol; 1] = [b's' as symbol];
static S_2: [symbol; 1] = [b's' as symbol];
static S_3: [symbol; 1] = [b'p' as symbol];
static S_4: [symbol; 1] = [b'p' as symbol];
static S_5: [symbol; 4] = [b'a' as symbol, b'j' as symbol, b'a' as symbol, b'r' as symbol];
static S_6: [symbol; 4] = [b'a' as symbol, b'j' as symbol, b'a' as symbol, b'r' as symbol];

unsafe extern "C" fn r_remove_particle(z: *mut SN_env) -> c_int {
    (*z).ket = (*z).c;
    if (*z).c - 2 <= (*z).lb
        || (*(*z).p.offset(((*z).c - 1) as isize) != 104
            && *(*z).p.offset(((*z).c - 1) as isize) != 110)
    {
        return 0;
    }
    if find_among_b(z, A_0.as_ptr(), 3) == 0 {
        return 0;
    }
    (*z).bra = (*z).c;
    {
        let ret = slice_del(z);
        if ret < 0 {
            return ret;
        }
    }
    *(*z).I.offset(1) -= 1;
    return 1;
}

unsafe extern "C" fn r_remove_possessive_pronoun(z: *mut SN_env) -> c_int {
    (*z).ket = (*z).c;
    if (*z).c - 1 <= (*z).lb
        || (*(*z).p.offset(((*z).c - 1) as isize) != 97
            && *(*z).p.offset(((*z).c - 1) as isize) != 117)
    {
        return 0;
    }
    if find_among_b(z, A_1.as_ptr(), 3) == 0 {
        return 0;
    }
    (*z).bra = (*z).c;
    {
        let ret = slice_del(z);
        if ret < 0 {
            return ret;
        }
    }
    *(*z).I.offset(1) -= 1;
    return 1;
}

unsafe extern "C" fn r_SUFFIX_KAN_OK(z: *mut SN_env) -> c_int {
    if *(*z).I.offset(0) == 3 {
        return 0;
    }
    if *(*z).I.offset(0) == 2 {
        return 0;
    }
    return 1;
}

unsafe extern "C" fn r_SUFFIX_AN_OK(z: *mut SN_env) -> c_int {
    return (*(*z).I.offset(0) != 1) as c_int;
}

unsafe extern "C" fn r_SUFFIX_I_OK(z: *mut SN_env) -> c_int {
    if *(*z).I.offset(0) > 2 {
        return 0;
    }
    {
        let m1 = (*z).l - (*z).c;
        let _ = m1;
        'lab0: {
            if (*z).c <= (*z).lb || *(*z).p.offset(((*z).c - 1) as isize) != b's' as symbol {
                break 'lab0;
            }
            (*z).c -= 1;
            return 0;
        }
        (*z).c = (*z).l - m1;
    }
    return 1;
}

unsafe extern "C" fn r_remove_suffix(z: *mut SN_env) -> c_int {
    (*z).ket = (*z).c;
    if (*z).c <= (*z).lb
        || (*(*z).p.offset(((*z).c - 1) as isize) != 105
            && *(*z).p.offset(((*z).c - 1) as isize) != 110)
    {
        return 0;
    }
    if find_among_b(z, A_2.as_ptr(), 3) == 0 {
        return 0;
    }
    (*z).bra = (*z).c;
    {
        let ret = slice_del(z);
        if ret < 0 {
            return ret;
        }
    }
    *(*z).I.offset(1) -= 1;
    return 1;
}

unsafe extern "C" fn r_VOWEL(z: *mut SN_env) -> c_int {
    if in_grouping(z, G_vowel.as_ptr(), 97, 117, 0) != 0 {
        return 0;
    }
    return 1;
}

unsafe extern "C" fn r_KER(z: *mut SN_env) -> c_int {
    if out_grouping(z, G_vowel.as_ptr(), 97, 117, 0) != 0 {
        return 0;
    }
    if eq_s(z, 2, S_0.as_ptr()) == 0 {
        return 0;
    }
    return 1;
}

unsafe extern "C" fn r_remove_first_order_prefix(z: *mut SN_env) -> c_int {
    let among_var: c_int;
    (*z).bra = (*z).c;
    if (*z).c + 1 >= (*z).l
        || (*(*z).p.offset(((*z).c + 1) as isize) != 105
            && *(*z).p.offset(((*z).c + 1) as isize) != 101)
    {
        return 0;
    }
    among_var = find_among(z, A_3.as_ptr(), 12);
    if among_var == 0 {
        return 0;
    }
    (*z).ket = (*z).c;
    match among_var {
        1 => {
            {
                let ret = slice_del(z);
                if ret < 0 {
                    return ret;
                }
            }
            *(*z).I.offset(0) = 1;
            *(*z).I.offset(1) -= 1;
        }
        2 => {
            {
                let ret = slice_del(z);
                if ret < 0 {
                    return ret;
                }
            }
            *(*z).I.offset(0) = 3;
            *(*z).I.offset(1) -= 1;
        }
        3 => {
            *(*z).I.offset(0) = 1;
            {
                let ret = slice_from_s(z, 1, S_1.as_ptr());
                if ret < 0 {
                    return ret;
                }
            }
            *(*z).I.offset(1) -= 1;
        }
        4 => {
            *(*z).I.offset(0) = 3;
            {
                let ret = slice_from_s(z, 1, S_2.as_ptr());
                if ret < 0 {
                    return ret;
                }
            }
            *(*z).I.offset(1) -= 1;
        }
        5 => {
            *(*z).I.offset(0) = 1;
            *(*z).I.offset(1) -= 1;
            {
                let c1 = (*z).c;
                'lab0: {
                    'lab1: {
                        let c2 = (*z).c;
                        if in_grouping(z, G_vowel.as_ptr(), 97, 117, 0) != 0 {
                            break 'lab1;
                        }
                        (*z).c = c2;
                        {
                            let ret = slice_from_s(z, 1, S_3.as_ptr());
                            if ret < 0 {
                                return ret;
                            }
                        }
                        break 'lab0;
                    }
                    // lab1:
                    (*z).c = c1;
                    {
                        let ret = slice_del(z);
                        if ret < 0 {
                            return ret;
                        }
                    }
                }
                // lab0:
            }
        }
        6 => {
            *(*z).I.offset(0) = 3;
            *(*z).I.offset(1) -= 1;
            {
                let c3 = (*z).c;
                'lab2: {
                    'lab3: {
                        let c4 = (*z).c;
                        if in_grouping(z, G_vowel.as_ptr(), 97, 117, 0) != 0 {
                            break 'lab3;
                        }
                        (*z).c = c4;
                        {
                            let ret = slice_from_s(z, 1, S_4.as_ptr());
                            if ret < 0 {
                                return ret;
                            }
                        }
                        break 'lab2;
                    }
                    // lab3:
                    (*z).c = c3;
                    {
                        let ret = slice_del(z);
                        if ret < 0 {
                            return ret;
                        }
                    }
                }
                // lab2:
            }
        }
        _ => {}
    }
    return 1;
}

unsafe extern "C" fn r_remove_second_order_prefix(z: *mut SN_env) -> c_int {
    let among_var: c_int;
    (*z).bra = (*z).c;
    if (*z).c + 1 >= (*z).l || *(*z).p.offset(((*z).c + 1) as isize) != 101 {
        return 0;
    }
    among_var = find_among(z, A_4.as_ptr(), 6);
    if among_var == 0 {
        return 0;
    }
    (*z).ket = (*z).c;
    match among_var {
        1 => {
            {
                let ret = slice_del(z);
                if ret < 0 {
                    return ret;
                }
            }
            *(*z).I.offset(0) = 2;
            *(*z).I.offset(1) -= 1;
        }
        2 => {
            {
                let ret = slice_from_s(z, 4, S_5.as_ptr());
                if ret < 0 {
                    return ret;
                }
            }
            *(*z).I.offset(1) -= 1;
        }
        3 => {
            {
                let ret = slice_del(z);
                if ret < 0 {
                    return ret;
                }
            }
            *(*z).I.offset(0) = 4;
            *(*z).I.offset(1) -= 1;
        }
        4 => {
            {
                let ret = slice_from_s(z, 4, S_6.as_ptr());
                if ret < 0 {
                    return ret;
                }
            }
            *(*z).I.offset(0) = 4;
            *(*z).I.offset(1) -= 1;
        }
        _ => {}
    }
    return 1;
}

#[no_mangle]
pub unsafe extern "C" fn indonesian_ISO_8859_1_stem(z: *mut SN_env) -> c_int {
    *(*z).I.offset(1) = 0;
    {
        let c1 = (*z).c;
        'mark: loop {
            let c2 = (*z).c;

            'lab1: {
                {
                    let ret = out_grouping(z, G_vowel.as_ptr(), 97, 117, 1);
                    if ret < 0 {
                        break 'lab1;
                    }
                    (*z).c += ret;
                }
                *(*z).I.offset(1) += 1;
                continue 'mark;
            }
            // lab1:
            (*z).c = c2;
            break;
        }
        (*z).c = c1;
    }
    if *(*z).I.offset(1) <= 2 {
        return 0;
    }
    *(*z).I.offset(0) = 0;
    (*z).lb = (*z).c;
    (*z).c = (*z).l;

    {
        let m3 = (*z).l - (*z).c;
        let _ = m3;
        {
            let ret = r_remove_particle(z);
            if ret < 0 {
                return ret;
            }
        }
        (*z).c = (*z).l - m3;
    }
    if *(*z).I.offset(1) <= 2 {
        return 0;
    }
    {
        let m4 = (*z).l - (*z).c;
        let _ = m4;
        {
            let ret = r_remove_possessive_pronoun(z);
            if ret < 0 {
                return ret;
            }
        }
        (*z).c = (*z).l - m4;
    }
    (*z).c = (*z).lb;
    if *(*z).I.offset(1) <= 2 {
        return 0;
    }
    'lab2: {
        let c5 = (*z).c;
        'lab3: {
            let c_test6 = (*z).c;
            {
                let ret = r_remove_first_order_prefix(z);
                if ret == 0 {
                    break 'lab3;
                }
                if ret < 0 {
                    return ret;
                }
            }
            {
                let c7 = (*z).c;
                'lab4: {
                    let c_test8 = (*z).c;
                    if *(*z).I.offset(1) <= 2 {
                        break 'lab4;
                    }
                    (*z).lb = (*z).c;
                    (*z).c = (*z).l;

                    {
                        let ret = r_remove_suffix(z);
                        if ret == 0 {
                            break 'lab4;
                        }
                        if ret < 0 {
                            return ret;
                        }
                    }
                    (*z).c = (*z).lb;
                    (*z).c = c_test8;

                    if *(*z).I.offset(1) <= 2 {
                        break 'lab4;
                    }
                    {
                        let ret = r_remove_second_order_prefix(z);
                        if ret == 0 {
                            break 'lab4;
                        }
                        if ret < 0 {
                            return ret;
                        }
                    }
                }
                // lab4:
                (*z).c = c7;
            }
            (*z).c = c_test6;

            break 'lab2;
        }
        // lab3:
        (*z).c = c5;
        {
            let c9 = (*z).c;
            {
                let ret = r_remove_second_order_prefix(z);
                if ret < 0 {
                    return ret;
                }
            }
            (*z).c = c9;
        }
        {
            let c10 = (*z).c;
            'lab5: {
                if *(*z).I.offset(1) <= 2 {
                    break 'lab5;
                }
                (*z).lb = (*z).c;
                (*z).c = (*z).l;

                {
                    let ret = r_remove_suffix(z);
                    if ret == 0 {
                        break 'lab5;
                    }
                    if ret < 0 {
                        return ret;
                    }
                }
                (*z).c = (*z).lb;
            }
            // lab5:
            (*z).c = c10;
        }
    }
    // lab2:
    return 1;
}

#[no_mangle]
pub unsafe extern "C" fn indonesian_ISO_8859_1_create_env() -> *mut SN_env {
    return SN_create_env(0, 2);
}

#[no_mangle]
pub unsafe extern "C" fn indonesian_ISO_8859_1_close_env(z: *mut SN_env) {
    SN_close_env(z, 0);
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::snowball::api::SN_set_current;
    use crate::snowball::api::SIZE;

    unsafe fn stem_word(word: &[u8]) -> Vec<symbol> {
        let z = indonesian_ISO_8859_1_create_env();
        SN_set_current(z, word.len() as c_int, word.as_ptr());
        let rc = indonesian_ISO_8859_1_stem(z);
        assert!(rc >= 0);
        let out = std::slice::from_raw_parts((*z).p, SIZE((*z).p) as usize).to_vec();
        indonesian_ISO_8859_1_close_env(z);
        out
    }

    #[test]
    fn short_root_unchanged() {
        // A short word below the syllable threshold is returned unchanged.
        unsafe {
            let w = b"ada";
            let out = stem_word(w);
            assert_eq!(out, w.to_vec());
        }
    }

    #[test]
    fn idempotent_and_nonempty() {
        // Several words: stemming is idempotent and produces a non-empty stem.
        unsafe {
            for w in [
                &b"perbaikan"[..],
                &b"membaca"[..],
                &b"kebijakan"[..],
                &b"pembelajaran"[..],
            ] {
                let once = stem_word(w);
                assert!(!once.is_empty());
                let twice = stem_word(&once);
                assert_eq!(once, twice);
            }
        }
    }
}
