//! Generated by Snowball 2.2.0 - https://snowballstem.org/
//!
//! 1:1 translation of the generated Dutch UTF-8 stemmer
//! `src/backend/snowball/libstemmer/stem_UTF_8_dutch.c` (header
//! `stem_UTF_8_dutch.h` merged in). The goto-driven control flow is mapped onto
//! Rust labeled blocks / early returns while preserving the cursor save/restore
//! backtracking idioms verbatim.

use crate::prelude::*;

use crate::snowball::api::{among, symbol, SIZE, SN_close_env, SN_create_env, SN_env};
use crate::snowball::utilities::{
    eq_s_b, find_among, find_among_b, in_grouping_U, out_grouping_b_U, out_grouping_U, skip_b_utf8,
    skip_utf8, slice_del, slice_from_s,
};

// ---------------------------------------------------------------------------
// among string literals (a_0)
// ---------------------------------------------------------------------------

static S_0_1: [symbol; 2] = [0xC3, 0xA1];
static S_0_2: [symbol; 2] = [0xC3, 0xA4];
static S_0_3: [symbol; 2] = [0xC3, 0xA9];
static S_0_4: [symbol; 2] = [0xC3, 0xAB];
static S_0_5: [symbol; 2] = [0xC3, 0xAD];
static S_0_6: [symbol; 2] = [0xC3, 0xAF];
static S_0_7: [symbol; 2] = [0xC3, 0xB3];
static S_0_8: [symbol; 2] = [0xC3, 0xB6];
static S_0_9: [symbol; 2] = [0xC3, 0xBA];
static S_0_10: [symbol; 2] = [0xC3, 0xBC];

static A_0: [among; 11] = [
    among { s_size: 0, s: core::ptr::null(), substring_i: -1, result: 6, function: None },
    among { s_size: 2, s: S_0_1.as_ptr(), substring_i: 0, result: 1, function: None },
    among { s_size: 2, s: S_0_2.as_ptr(), substring_i: 0, result: 1, function: None },
    among { s_size: 2, s: S_0_3.as_ptr(), substring_i: 0, result: 2, function: None },
    among { s_size: 2, s: S_0_4.as_ptr(), substring_i: 0, result: 2, function: None },
    among { s_size: 2, s: S_0_5.as_ptr(), substring_i: 0, result: 3, function: None },
    among { s_size: 2, s: S_0_6.as_ptr(), substring_i: 0, result: 3, function: None },
    among { s_size: 2, s: S_0_7.as_ptr(), substring_i: 0, result: 4, function: None },
    among { s_size: 2, s: S_0_8.as_ptr(), substring_i: 0, result: 4, function: None },
    among { s_size: 2, s: S_0_9.as_ptr(), substring_i: 0, result: 5, function: None },
    among { s_size: 2, s: S_0_10.as_ptr(), substring_i: 0, result: 5, function: None },
];

// ---------------------------------------------------------------------------
// among string literals (a_1)
// ---------------------------------------------------------------------------

static S_1_1: [symbol; 1] = [b'I'];
static S_1_2: [symbol; 1] = [b'Y'];

static A_1: [among; 3] = [
    among { s_size: 0, s: core::ptr::null(), substring_i: -1, result: 3, function: None },
    among { s_size: 1, s: S_1_1.as_ptr(), substring_i: 0, result: 2, function: None },
    among { s_size: 1, s: S_1_2.as_ptr(), substring_i: 0, result: 1, function: None },
];

// ---------------------------------------------------------------------------
// among string literals (a_2)
// ---------------------------------------------------------------------------

static S_2_0: [symbol; 2] = [b'd', b'd'];
static S_2_1: [symbol; 2] = [b'k', b'k'];
static S_2_2: [symbol; 2] = [b't', b't'];

static A_2: [among; 3] = [
    among { s_size: 2, s: S_2_0.as_ptr(), substring_i: -1, result: -1, function: None },
    among { s_size: 2, s: S_2_1.as_ptr(), substring_i: -1, result: -1, function: None },
    among { s_size: 2, s: S_2_2.as_ptr(), substring_i: -1, result: -1, function: None },
];

// ---------------------------------------------------------------------------
// among string literals (a_3)
// ---------------------------------------------------------------------------

static S_3_0: [symbol; 3] = [b'e', b'n', b'e'];
static S_3_1: [symbol; 2] = [b's', b'e'];
static S_3_2: [symbol; 2] = [b'e', b'n'];
static S_3_3: [symbol; 5] = [b'h', b'e', b'd', b'e', b'n'];
static S_3_4: [symbol; 1] = [b's'];

static A_3: [among; 5] = [
    among { s_size: 3, s: S_3_0.as_ptr(), substring_i: -1, result: 2, function: None },
    among { s_size: 2, s: S_3_1.as_ptr(), substring_i: -1, result: 3, function: None },
    among { s_size: 2, s: S_3_2.as_ptr(), substring_i: -1, result: 2, function: None },
    among { s_size: 5, s: S_3_3.as_ptr(), substring_i: 2, result: 1, function: None },
    among { s_size: 1, s: S_3_4.as_ptr(), substring_i: -1, result: 3, function: None },
];

// ---------------------------------------------------------------------------
// among string literals (a_4)
// ---------------------------------------------------------------------------

static S_4_0: [symbol; 3] = [b'e', b'n', b'd'];
static S_4_1: [symbol; 2] = [b'i', b'g'];
static S_4_2: [symbol; 3] = [b'i', b'n', b'g'];
static S_4_3: [symbol; 4] = [b'l', b'i', b'j', b'k'];
static S_4_4: [symbol; 4] = [b'b', b'a', b'a', b'r'];
static S_4_5: [symbol; 3] = [b'b', b'a', b'r'];

static A_4: [among; 6] = [
    among { s_size: 3, s: S_4_0.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 2, s: S_4_1.as_ptr(), substring_i: -1, result: 2, function: None },
    among { s_size: 3, s: S_4_2.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 4, s: S_4_3.as_ptr(), substring_i: -1, result: 3, function: None },
    among { s_size: 4, s: S_4_4.as_ptr(), substring_i: -1, result: 4, function: None },
    among { s_size: 3, s: S_4_5.as_ptr(), substring_i: -1, result: 5, function: None },
];

// ---------------------------------------------------------------------------
// among string literals (a_5)
// ---------------------------------------------------------------------------

static S_5_0: [symbol; 2] = [b'a', b'a'];
static S_5_1: [symbol; 2] = [b'e', b'e'];
static S_5_2: [symbol; 2] = [b'o', b'o'];
static S_5_3: [symbol; 2] = [b'u', b'u'];

static A_5: [among; 4] = [
    among { s_size: 2, s: S_5_0.as_ptr(), substring_i: -1, result: -1, function: None },
    among { s_size: 2, s: S_5_1.as_ptr(), substring_i: -1, result: -1, function: None },
    among { s_size: 2, s: S_5_2.as_ptr(), substring_i: -1, result: -1, function: None },
    among { s_size: 2, s: S_5_3.as_ptr(), substring_i: -1, result: -1, function: None },
];

// ---------------------------------------------------------------------------
// grouping tables
// ---------------------------------------------------------------------------

static G_V: [c_uchar; 17] = [17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128];

static G_V_I: [c_uchar; 20] = [
    1, 0, 0, 17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128,
];

static G_V_J: [c_uchar; 17] = [17, 67, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128];

// ---------------------------------------------------------------------------
// slice_from literals
// ---------------------------------------------------------------------------

static S_0: [symbol; 1] = [b'a'];
static S_1: [symbol; 1] = [b'e'];
static S_2: [symbol; 1] = [b'i'];
static S_3: [symbol; 1] = [b'o'];
static S_4: [symbol; 1] = [b'u'];
static S_5: [symbol; 1] = [b'Y'];
static S_6: [symbol; 1] = [b'I'];
static S_7: [symbol; 1] = [b'Y'];
static S_8: [symbol; 1] = [b'y'];
static S_9: [symbol; 1] = [b'i'];
static S_10: [symbol; 3] = [b'g', b'e', b'm'];
static S_11: [symbol; 4] = [b'h', b'e', b'i', b'd'];
static S_12: [symbol; 4] = [b'h', b'e', b'i', b'd'];
static S_13: [symbol; 2] = [b'e', b'n'];
static S_14: [symbol; 2] = [b'i', b'g'];

// ---------------------------------------------------------------------------
// helper functions
// ---------------------------------------------------------------------------

unsafe fn r_prelude(z: *mut SN_env) -> c_int {
    let mut among_var: c_int;
    {
        let c_test1: c_int = (*z).c;
        'pre: loop {
            let c2: c_int = (*z).c;
            (*z).bra = (*z).c;
            if (*z).c + 1 >= (*z).l
                || *(*z).p.offset(((*z).c + 1) as isize) as c_int >> 5 != 5
                || (340306450 >> (*(*z).p.offset(((*z).c + 1) as isize) as c_int & 0x1f)) & 1 == 0
            {
                among_var = 6;
            } else {
                among_var = find_among(z, A_0.as_ptr(), 11);
            }
            (*z).ket = (*z).c;
            match among_var {
                1 => {
                    let ret: c_int = slice_from_s(z, 1, S_0.as_ptr());
                    if ret < 0 {
                        return ret;
                    }
                }
                2 => {
                    let ret: c_int = slice_from_s(z, 1, S_1.as_ptr());
                    if ret < 0 {
                        return ret;
                    }
                }
                3 => {
                    let ret: c_int = slice_from_s(z, 1, S_2.as_ptr());
                    if ret < 0 {
                        return ret;
                    }
                }
                4 => {
                    let ret: c_int = slice_from_s(z, 1, S_3.as_ptr());
                    if ret < 0 {
                        return ret;
                    }
                }
                5 => {
                    let ret: c_int = slice_from_s(z, 1, S_4.as_ptr());
                    if ret < 0 {
                        return ret;
                    }
                }
                6 => 'lab0: {
                    let ret: c_int = skip_utf8((*z).p, (*z).c, (*z).l, 1);
                    if ret < 0 {
                        // goto lab0
                        (*z).c = c2;
                        break 'pre;
                    }
                    (*z).c = ret;
                    let _ = &mut among_var;
                    break 'lab0;
                }
                _ => {}
            }
            continue;
        }
        (*z).c = c_test1;
    }
    {
        let c3: c_int = (*z).c;
        'lab1: {
            (*z).bra = (*z).c;
            if (*z).c == (*z).l || *(*z).p.offset((*z).c as isize) as c_int != b'y' as c_int {
                (*z).c = c3;
                break 'lab1;
            }
            (*z).c += 1;
            (*z).ket = (*z).c;
            let ret: c_int = slice_from_s(z, 1, S_5.as_ptr());
            if ret < 0 {
                return ret;
            }
        }
    }
    loop {
        let c4: c_int = (*z).c;
        'lab2: {
            loop {
                let c5: c_int = (*z).c;
                'lab3: {
                    if in_grouping_U(z, G_V.as_ptr(), 97, 232, 0) != 0 {
                        break 'lab3;
                    }
                    (*z).bra = (*z).c;
                    {
                        let c6: c_int = (*z).c;
                        'lab5: {
                            if (*z).c == (*z).l
                                || *(*z).p.offset((*z).c as isize) as c_int != b'i' as c_int
                            {
                                break 'lab5;
                            }
                            (*z).c += 1;
                            (*z).ket = (*z).c;
                            if in_grouping_U(z, G_V.as_ptr(), 97, 232, 0) != 0 {
                                break 'lab5;
                            }
                            let ret: c_int = slice_from_s(z, 1, S_6.as_ptr());
                            if ret < 0 {
                                return ret;
                            }
                            // goto lab4
                            (*z).c = c5;
                            break 'lab3;
                        }
                        (*z).c = c6;
                        if (*z).c == (*z).l
                            || *(*z).p.offset((*z).c as isize) as c_int != b'y' as c_int
                        {
                            break 'lab3;
                        }
                        (*z).c += 1;
                        (*z).ket = (*z).c;
                        let ret: c_int = slice_from_s(z, 1, S_7.as_ptr());
                        if ret < 0 {
                            return ret;
                        }
                    }
                    // lab4:
                    (*z).c = c5;
                    break 'lab2;
                }
                // lab3:
                (*z).c = c5;
                {
                    let ret: c_int = skip_utf8((*z).p, (*z).c, (*z).l, 1);
                    if ret < 0 {
                        // goto lab2
                        (*z).c = c4;
                        return 1;
                    }
                    (*z).c = ret;
                }
            }
        }
        continue;
    }
}

unsafe fn r_mark_regions(z: *mut SN_env) -> c_int {
    *(*z).I.offset(2) = (*z).l;
    *(*z).I.offset(1) = (*z).l;
    {
        let c_test1: c_int = (*z).c;
        {
            let ret: c_int = skip_utf8((*z).p, (*z).c, (*z).l, 3);
            if ret < 0 {
                return 0;
            }
            (*z).c = ret;
        }
        *(*z).I.offset(0) = (*z).c;
        (*z).c = c_test1;
    }

    {
        let ret: c_int = out_grouping_U(z, G_V.as_ptr(), 97, 232, 1);
        if ret < 0 {
            return 0;
        }
        (*z).c += ret;
    }

    {
        let ret: c_int = in_grouping_U(z, G_V.as_ptr(), 97, 232, 1);
        if ret < 0 {
            return 0;
        }
        (*z).c += ret;
    }
    *(*z).I.offset(2) = (*z).c;

    'lab0: {
        if *(*z).I.offset(2) >= *(*z).I.offset(0) {
            break 'lab0;
        }
        *(*z).I.offset(2) = *(*z).I.offset(0);
    }

    {
        let ret: c_int = out_grouping_U(z, G_V.as_ptr(), 97, 232, 1);
        if ret < 0 {
            return 0;
        }
        (*z).c += ret;
    }

    {
        let ret: c_int = in_grouping_U(z, G_V.as_ptr(), 97, 232, 1);
        if ret < 0 {
            return 0;
        }
        (*z).c += ret;
    }
    *(*z).I.offset(1) = (*z).c;
    1
}

unsafe fn r_postlude(z: *mut SN_env) -> c_int {
    let mut among_var: c_int;
    loop {
        let c1: c_int = (*z).c;
        (*z).bra = (*z).c;
        if (*z).c >= (*z).l
            || (*(*z).p.offset(((*z).c + 0) as isize) as c_int != 73
                && *(*z).p.offset(((*z).c + 0) as isize) as c_int != 89)
        {
            among_var = 3;
        } else {
            among_var = find_among(z, A_1.as_ptr(), 3);
        }
        (*z).ket = (*z).c;
        match among_var {
            1 => {
                let ret: c_int = slice_from_s(z, 1, S_8.as_ptr());
                if ret < 0 {
                    return ret;
                }
            }
            2 => {
                let ret: c_int = slice_from_s(z, 1, S_9.as_ptr());
                if ret < 0 {
                    return ret;
                }
            }
            3 => 'lab0: {
                let ret: c_int = skip_utf8((*z).p, (*z).c, (*z).l, 1);
                if ret < 0 {
                    // goto lab0
                    (*z).c = c1;
                    return 1;
                }
                (*z).c = ret;
                let _ = &mut among_var;
                break 'lab0;
            }
            _ => {}
        }
        continue;
    }
}

unsafe fn r_R1(z: *mut SN_env) -> c_int {
    (*(*z).I.offset(2) <= (*z).c) as c_int
}

unsafe fn r_R2(z: *mut SN_env) -> c_int {
    (*(*z).I.offset(1) <= (*z).c) as c_int
}

unsafe fn r_undouble(z: *mut SN_env) -> c_int {
    {
        let m_test1: c_int = (*z).l - (*z).c;
        if (*z).c - 1 <= (*z).lb
            || *(*z).p.offset(((*z).c - 1) as isize) as c_int >> 5 != 3
            || (1050640 >> (*(*z).p.offset(((*z).c - 1) as isize) as c_int & 0x1f)) & 1 == 0
        {
            return 0;
        }
        if find_among_b(z, A_2.as_ptr(), 3) == 0 {
            return 0;
        }
        (*z).c = (*z).l - m_test1;
    }
    (*z).ket = (*z).c;
    {
        let ret: c_int = skip_b_utf8((*z).p, (*z).c, (*z).lb, 1);
        if ret < 0 {
            return 0;
        }
        (*z).c = ret;
    }
    (*z).bra = (*z).c;
    {
        let ret: c_int = slice_del(z);
        if ret < 0 {
            return ret;
        }
    }
    1
}

unsafe fn r_e_ending(z: *mut SN_env) -> c_int {
    *(*z).I.offset(3) = 0;
    (*z).ket = (*z).c;
    if (*z).c <= (*z).lb || *(*z).p.offset(((*z).c - 1) as isize) as c_int != b'e' as c_int {
        return 0;
    }
    (*z).c -= 1;
    (*z).bra = (*z).c;
    {
        let ret: c_int = r_R1(z);
        if ret <= 0 {
            return ret;
        }
    }
    {
        let m_test1: c_int = (*z).l - (*z).c;
        if out_grouping_b_U(z, G_V.as_ptr(), 97, 232, 0) != 0 {
            return 0;
        }
        (*z).c = (*z).l - m_test1;
    }
    {
        let ret: c_int = slice_del(z);
        if ret < 0 {
            return ret;
        }
    }
    *(*z).I.offset(3) = 1;
    {
        let ret: c_int = r_undouble(z);
        if ret <= 0 {
            return ret;
        }
    }
    1
}

unsafe fn r_en_ending(z: *mut SN_env) -> c_int {
    {
        let ret: c_int = r_R1(z);
        if ret <= 0 {
            return ret;
        }
    }
    {
        let m1: c_int = (*z).l - (*z).c;
        let _ = m1;
        if out_grouping_b_U(z, G_V.as_ptr(), 97, 232, 0) != 0 {
            return 0;
        }
        (*z).c = (*z).l - m1;
        {
            let m2: c_int = (*z).l - (*z).c;
            let _ = m2;
            'lab0: {
                if !(eq_s_b(z, 3, S_10.as_ptr()) != 0) {
                    break 'lab0;
                }
                return 0;
            }
            (*z).c = (*z).l - m2;
        }
    }
    {
        let ret: c_int = slice_del(z);
        if ret < 0 {
            return ret;
        }
    }
    {
        let ret: c_int = r_undouble(z);
        if ret <= 0 {
            return ret;
        }
    }
    1
}

unsafe fn r_standard_suffix(z: *mut SN_env) -> c_int {
    let mut among_var: c_int;
    {
        let m1: c_int = (*z).l - (*z).c;
        let _ = m1;
        'lab0: {
            (*z).ket = (*z).c;
            if (*z).c <= (*z).lb
                || *(*z).p.offset(((*z).c - 1) as isize) as c_int >> 5 != 3
                || (540704 >> (*(*z).p.offset(((*z).c - 1) as isize) as c_int & 0x1f)) & 1 == 0
            {
                break 'lab0;
            }
            among_var = find_among_b(z, A_3.as_ptr(), 5);
            if among_var == 0 {
                break 'lab0;
            }
            (*z).bra = (*z).c;
            match among_var {
                1 => {
                    {
                        let ret: c_int = r_R1(z);
                        if ret == 0 {
                            break 'lab0;
                        }
                        if ret < 0 {
                            return ret;
                        }
                    }
                    {
                        let ret: c_int = slice_from_s(z, 4, S_11.as_ptr());
                        if ret < 0 {
                            return ret;
                        }
                    }
                }
                2 => {
                    let ret: c_int = r_en_ending(z);
                    if ret == 0 {
                        break 'lab0;
                    }
                    if ret < 0 {
                        return ret;
                    }
                }
                3 => {
                    {
                        let ret: c_int = r_R1(z);
                        if ret == 0 {
                            break 'lab0;
                        }
                        if ret < 0 {
                            return ret;
                        }
                    }
                    if out_grouping_b_U(z, G_V_J.as_ptr(), 97, 232, 0) != 0 {
                        break 'lab0;
                    }
                    {
                        let ret: c_int = slice_del(z);
                        if ret < 0 {
                            return ret;
                        }
                    }
                }
                _ => {}
            }
        }
        (*z).c = (*z).l - m1;
    }
    {
        let m2: c_int = (*z).l - (*z).c;
        let _ = m2;
        {
            let ret: c_int = r_e_ending(z);
            if ret < 0 {
                return ret;
            }
        }
        (*z).c = (*z).l - m2;
    }
    {
        let m3: c_int = (*z).l - (*z).c;
        let _ = m3;
        'lab1: {
            (*z).ket = (*z).c;
            if !(eq_s_b(z, 4, S_12.as_ptr()) != 0) {
                break 'lab1;
            }
            (*z).bra = (*z).c;
            {
                let ret: c_int = r_R2(z);
                if ret == 0 {
                    break 'lab1;
                }
                if ret < 0 {
                    return ret;
                }
            }
            {
                let m4: c_int = (*z).l - (*z).c;
                let _ = m4;
                'lab2: {
                    if (*z).c <= (*z).lb
                        || *(*z).p.offset(((*z).c - 1) as isize) as c_int != b'c' as c_int
                    {
                        break 'lab2;
                    }
                    (*z).c -= 1;
                    // goto lab1
                    break 'lab1;
                }
                (*z).c = (*z).l - m4;
            }
            {
                let ret: c_int = slice_del(z);
                if ret < 0 {
                    return ret;
                }
            }
            (*z).ket = (*z).c;
            if !(eq_s_b(z, 2, S_13.as_ptr()) != 0) {
                break 'lab1;
            }
            (*z).bra = (*z).c;
            {
                let ret: c_int = r_en_ending(z);
                if ret == 0 {
                    break 'lab1;
                }
                if ret < 0 {
                    return ret;
                }
            }
        }
        (*z).c = (*z).l - m3;
    }
    {
        let m5: c_int = (*z).l - (*z).c;
        let _ = m5;
        'lab3: {
            (*z).ket = (*z).c;
            if (*z).c - 1 <= (*z).lb
                || *(*z).p.offset(((*z).c - 1) as isize) as c_int >> 5 != 3
                || (264336 >> (*(*z).p.offset(((*z).c - 1) as isize) as c_int & 0x1f)) & 1 == 0
            {
                break 'lab3;
            }
            among_var = find_among_b(z, A_4.as_ptr(), 6);
            if among_var == 0 {
                break 'lab3;
            }
            (*z).bra = (*z).c;
            match among_var {
                1 => {
                    {
                        let ret: c_int = r_R2(z);
                        if ret == 0 {
                            break 'lab3;
                        }
                        if ret < 0 {
                            return ret;
                        }
                    }
                    {
                        let ret: c_int = slice_del(z);
                        if ret < 0 {
                            return ret;
                        }
                    }
                    'lab4: {
                        {
                            let m6: c_int = (*z).l - (*z).c;
                            let _ = m6;
                            'lab5: {
                                (*z).ket = (*z).c;
                                if !(eq_s_b(z, 2, S_14.as_ptr()) != 0) {
                                    break 'lab5;
                                }
                                (*z).bra = (*z).c;
                                {
                                    let ret: c_int = r_R2(z);
                                    if ret == 0 {
                                        break 'lab5;
                                    }
                                    if ret < 0 {
                                        return ret;
                                    }
                                }
                                {
                                    let m7: c_int = (*z).l - (*z).c;
                                    let _ = m7;
                                    'lab6: {
                                        if (*z).c <= (*z).lb
                                            || *(*z).p.offset(((*z).c - 1) as isize) as c_int
                                                != b'e' as c_int
                                        {
                                            break 'lab6;
                                        }
                                        (*z).c -= 1;
                                        // goto lab5
                                        break 'lab5;
                                    }
                                    (*z).c = (*z).l - m7;
                                }
                                {
                                    let ret: c_int = slice_del(z);
                                    if ret < 0 {
                                        return ret;
                                    }
                                }
                                // goto lab4
                                break 'lab4;
                            }
                            (*z).c = (*z).l - m6;
                            {
                                let ret: c_int = r_undouble(z);
                                if ret == 0 {
                                    break 'lab3;
                                }
                                if ret < 0 {
                                    return ret;
                                }
                            }
                        }
                    }
                }
                2 => {
                    {
                        let ret: c_int = r_R2(z);
                        if ret == 0 {
                            break 'lab3;
                        }
                        if ret < 0 {
                            return ret;
                        }
                    }
                    {
                        let m8: c_int = (*z).l - (*z).c;
                        let _ = m8;
                        'lab7: {
                            if (*z).c <= (*z).lb
                                || *(*z).p.offset(((*z).c - 1) as isize) as c_int != b'e' as c_int
                            {
                                break 'lab7;
                            }
                            (*z).c -= 1;
                            // goto lab3
                            break 'lab3;
                        }
                        (*z).c = (*z).l - m8;
                    }
                    {
                        let ret: c_int = slice_del(z);
                        if ret < 0 {
                            return ret;
                        }
                    }
                }
                3 => {
                    {
                        let ret: c_int = r_R2(z);
                        if ret == 0 {
                            break 'lab3;
                        }
                        if ret < 0 {
                            return ret;
                        }
                    }
                    {
                        let ret: c_int = slice_del(z);
                        if ret < 0 {
                            return ret;
                        }
                    }
                    {
                        let ret: c_int = r_e_ending(z);
                        if ret == 0 {
                            break 'lab3;
                        }
                        if ret < 0 {
                            return ret;
                        }
                    }
                }
                4 => {
                    {
                        let ret: c_int = r_R2(z);
                        if ret == 0 {
                            break 'lab3;
                        }
                        if ret < 0 {
                            return ret;
                        }
                    }
                    {
                        let ret: c_int = slice_del(z);
                        if ret < 0 {
                            return ret;
                        }
                    }
                }
                5 => {
                    {
                        let ret: c_int = r_R2(z);
                        if ret == 0 {
                            break 'lab3;
                        }
                        if ret < 0 {
                            return ret;
                        }
                    }
                    if *(*z).I.offset(3) == 0 {
                        break 'lab3;
                    }
                    {
                        let ret: c_int = slice_del(z);
                        if ret < 0 {
                            return ret;
                        }
                    }
                }
                _ => {}
            }
        }
        (*z).c = (*z).l - m5;
    }
    {
        let m9: c_int = (*z).l - (*z).c;
        let _ = m9;
        'lab8: {
            if out_grouping_b_U(z, G_V_I.as_ptr(), 73, 232, 0) != 0 {
                break 'lab8;
            }
            {
                let m_test10: c_int = (*z).l - (*z).c;
                if (*z).c - 1 <= (*z).lb
                    || *(*z).p.offset(((*z).c - 1) as isize) as c_int >> 5 != 3
                    || (2129954 >> (*(*z).p.offset(((*z).c - 1) as isize) as c_int & 0x1f)) & 1 == 0
                {
                    break 'lab8;
                }
                if find_among_b(z, A_5.as_ptr(), 4) == 0 {
                    break 'lab8;
                }
                if out_grouping_b_U(z, G_V.as_ptr(), 97, 232, 0) != 0 {
                    break 'lab8;
                }
                (*z).c = (*z).l - m_test10;
            }
            (*z).ket = (*z).c;
            {
                let ret: c_int = skip_b_utf8((*z).p, (*z).c, (*z).lb, 1);
                if ret < 0 {
                    break 'lab8;
                }
                (*z).c = ret;
            }
            (*z).bra = (*z).c;
            {
                let ret: c_int = slice_del(z);
                if ret < 0 {
                    return ret;
                }
            }
        }
        (*z).c = (*z).l - m9;
    }
    1
}

#[no_mangle]
pub unsafe extern "C" fn dutch_UTF_8_stem(z: *mut SN_env) -> c_int {
    {
        let c1: c_int = (*z).c;
        {
            let ret: c_int = r_prelude(z);
            if ret < 0 {
                return ret;
            }
        }
        (*z).c = c1;
    }
    {
        let c2: c_int = (*z).c;
        {
            let ret: c_int = r_mark_regions(z);
            if ret < 0 {
                return ret;
            }
        }
        (*z).c = c2;
    }
    (*z).lb = (*z).c;
    (*z).c = (*z).l;

    {
        let ret: c_int = r_standard_suffix(z);
        if ret < 0 {
            return ret;
        }
    }
    (*z).c = (*z).lb;
    {
        let c3: c_int = (*z).c;
        {
            let ret: c_int = r_postlude(z);
            if ret < 0 {
                return ret;
            }
        }
        (*z).c = c3;
    }
    1
}

#[no_mangle]
pub unsafe extern "C" fn dutch_UTF_8_create_env() -> *mut SN_env {
    SN_create_env(0, 4)
}

#[no_mangle]
pub unsafe extern "C" fn dutch_UTF_8_close_env(z: *mut SN_env) {
    SN_close_env(z, 0);
}

// ---------------------------------------------------------------------------
// tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::snowball::api::SN_set_current;

    unsafe fn stem(word: &[u8]) -> Vec<symbol> {
        let z = dutch_UTF_8_create_env();
        SN_set_current(z, word.len() as c_int, word.as_ptr());
        let rc = dutch_UTF_8_stem(z);
        assert!(rc >= 0);
        let out = std::slice::from_raw_parts((*z).p, SIZE((*z).p) as usize).to_vec();
        dutch_UTF_8_close_env(z);
        out
    }

    #[test]
    fn short_root_unchanged() {
        unsafe {
            // A short root word with no removable suffix should pass through.
            assert_eq!(stem(b"de"), b"de".to_vec());
        }
    }

    #[test]
    fn idempotent() {
        unsafe {
            // Stemming a stemmed word yields the same result.
            let once = stem(b"lichamelijke");
            let twice = stem(&once);
            assert_eq!(once, twice);
            assert!(!once.is_empty());
        }
    }

    #[test]
    fn nonempty_and_ok() {
        unsafe {
            let out = stem(b"basaal");
            assert!(!out.is_empty());
        }
    }
}
