//! Generated by Snowball 2.2.0 - https://snowballstem.org/
//!
//! 1:1 Rust translation of
//! `src/backend/snowball/libstemmer/stem_UTF_8_finnish.c` merged with its
//! header `src/include/snowball/libstemmer/stem_UTF_8_finnish.h`.

use crate::prelude::*;
use crate::snowball::api::{symbol, SN_env, among, SIZE, SN_create_env, SN_close_env, SN_set_current};
use crate::snowball::utilities::{
    find_among_b, slice_from_s, slice_del, slice_to, skip_b_utf8,
    eq_s_b, eq_v_b, in_grouping_U, in_grouping_b_U, out_grouping_U,
};

// ---------------------------------------------------------------------------
// among string tables
// ---------------------------------------------------------------------------

static s_0_0: [symbol; 2] = [b'p', b'a'];
static s_0_1: [symbol; 3] = [b's', b't', b'i'];
static s_0_2: [symbol; 4] = [b'k', b'a', b'a', b'n'];
static s_0_3: [symbol; 3] = [b'h', b'a', b'n'];
static s_0_4: [symbol; 3] = [b'k', b'i', b'n'];
static s_0_5: [symbol; 4] = [b'h', 0xC3, 0xA4, b'n'];
static s_0_6: [symbol; 6] = [b'k', 0xC3, 0xA4, 0xC3, 0xA4, b'n'];
static s_0_7: [symbol; 2] = [b'k', b'o'];
static s_0_8: [symbol; 3] = [b'p', 0xC3, 0xA4];
static s_0_9: [symbol; 3] = [b'k', 0xC3, 0xB6];

static a_0: [among; 10] = [
    among { s_size: 2, s: s_0_0.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 3, s: s_0_1.as_ptr(), substring_i: -1, result: 2, function: None },
    among { s_size: 4, s: s_0_2.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 3, s: s_0_3.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 3, s: s_0_4.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 4, s: s_0_5.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 6, s: s_0_6.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 2, s: s_0_7.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 3, s: s_0_8.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 3, s: s_0_9.as_ptr(), substring_i: -1, result: 1, function: None },
];

static s_1_0: [symbol; 3] = [b'l', b'l', b'a'];
static s_1_1: [symbol; 2] = [b'n', b'a'];
static s_1_2: [symbol; 3] = [b's', b's', b'a'];
static s_1_3: [symbol; 2] = [b't', b'a'];
static s_1_4: [symbol; 3] = [b'l', b't', b'a'];
static s_1_5: [symbol; 3] = [b's', b't', b'a'];

static a_1: [among; 6] = [
    among { s_size: 3, s: s_1_0.as_ptr(), substring_i: -1, result: -1, function: None },
    among { s_size: 2, s: s_1_1.as_ptr(), substring_i: -1, result: -1, function: None },
    among { s_size: 3, s: s_1_2.as_ptr(), substring_i: -1, result: -1, function: None },
    among { s_size: 2, s: s_1_3.as_ptr(), substring_i: -1, result: -1, function: None },
    among { s_size: 3, s: s_1_4.as_ptr(), substring_i: 3, result: -1, function: None },
    among { s_size: 3, s: s_1_5.as_ptr(), substring_i: 3, result: -1, function: None },
];

static s_2_0: [symbol; 4] = [b'l', b'l', 0xC3, 0xA4];
static s_2_1: [symbol; 3] = [b'n', 0xC3, 0xA4];
static s_2_2: [symbol; 4] = [b's', b's', 0xC3, 0xA4];
static s_2_3: [symbol; 3] = [b't', 0xC3, 0xA4];
static s_2_4: [symbol; 4] = [b'l', b't', 0xC3, 0xA4];
static s_2_5: [symbol; 4] = [b's', b't', 0xC3, 0xA4];

static a_2: [among; 6] = [
    among { s_size: 4, s: s_2_0.as_ptr(), substring_i: -1, result: -1, function: None },
    among { s_size: 3, s: s_2_1.as_ptr(), substring_i: -1, result: -1, function: None },
    among { s_size: 4, s: s_2_2.as_ptr(), substring_i: -1, result: -1, function: None },
    among { s_size: 3, s: s_2_3.as_ptr(), substring_i: -1, result: -1, function: None },
    among { s_size: 4, s: s_2_4.as_ptr(), substring_i: 3, result: -1, function: None },
    among { s_size: 4, s: s_2_5.as_ptr(), substring_i: 3, result: -1, function: None },
];

static s_3_0: [symbol; 3] = [b'l', b'l', b'e'];
static s_3_1: [symbol; 3] = [b'i', b'n', b'e'];

static a_3: [among; 2] = [
    among { s_size: 3, s: s_3_0.as_ptr(), substring_i: -1, result: -1, function: None },
    among { s_size: 3, s: s_3_1.as_ptr(), substring_i: -1, result: -1, function: None },
];

static s_4_0: [symbol; 3] = [b'n', b's', b'a'];
static s_4_1: [symbol; 3] = [b'm', b'm', b'e'];
static s_4_2: [symbol; 3] = [b'n', b'n', b'e'];
static s_4_3: [symbol; 2] = [b'n', b'i'];
static s_4_4: [symbol; 2] = [b's', b'i'];
static s_4_5: [symbol; 2] = [b'a', b'n'];
static s_4_6: [symbol; 2] = [b'e', b'n'];
static s_4_7: [symbol; 3] = [0xC3, 0xA4, b'n'];
static s_4_8: [symbol; 4] = [b'n', b's', 0xC3, 0xA4];

static a_4: [among; 9] = [
    among { s_size: 3, s: s_4_0.as_ptr(), substring_i: -1, result: 3, function: None },
    among { s_size: 3, s: s_4_1.as_ptr(), substring_i: -1, result: 3, function: None },
    among { s_size: 3, s: s_4_2.as_ptr(), substring_i: -1, result: 3, function: None },
    among { s_size: 2, s: s_4_3.as_ptr(), substring_i: -1, result: 2, function: None },
    among { s_size: 2, s: s_4_4.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 2, s: s_4_5.as_ptr(), substring_i: -1, result: 4, function: None },
    among { s_size: 2, s: s_4_6.as_ptr(), substring_i: -1, result: 6, function: None },
    among { s_size: 3, s: s_4_7.as_ptr(), substring_i: -1, result: 5, function: None },
    among { s_size: 4, s: s_4_8.as_ptr(), substring_i: -1, result: 3, function: None },
];

static s_5_0: [symbol; 2] = [b'a', b'a'];
static s_5_1: [symbol; 2] = [b'e', b'e'];
static s_5_2: [symbol; 2] = [b'i', b'i'];
static s_5_3: [symbol; 2] = [b'o', b'o'];
static s_5_4: [symbol; 2] = [b'u', b'u'];
static s_5_5: [symbol; 4] = [0xC3, 0xA4, 0xC3, 0xA4];
static s_5_6: [symbol; 4] = [0xC3, 0xB6, 0xC3, 0xB6];

static a_5: [among; 7] = [
    among { s_size: 2, s: s_5_0.as_ptr(), substring_i: -1, result: -1, function: None },
    among { s_size: 2, s: s_5_1.as_ptr(), substring_i: -1, result: -1, function: None },
    among { s_size: 2, s: s_5_2.as_ptr(), substring_i: -1, result: -1, function: None },
    among { s_size: 2, s: s_5_3.as_ptr(), substring_i: -1, result: -1, function: None },
    among { s_size: 2, s: s_5_4.as_ptr(), substring_i: -1, result: -1, function: None },
    among { s_size: 4, s: s_5_5.as_ptr(), substring_i: -1, result: -1, function: None },
    among { s_size: 4, s: s_5_6.as_ptr(), substring_i: -1, result: -1, function: None },
];

static s_6_0: [symbol; 1] = [b'a'];
static s_6_1: [symbol; 3] = [b'l', b'l', b'a'];
static s_6_2: [symbol; 2] = [b'n', b'a'];
static s_6_3: [symbol; 3] = [b's', b's', b'a'];
static s_6_4: [symbol; 2] = [b't', b'a'];
static s_6_5: [symbol; 3] = [b'l', b't', b'a'];
static s_6_6: [symbol; 3] = [b's', b't', b'a'];
static s_6_7: [symbol; 3] = [b't', b't', b'a'];
static s_6_8: [symbol; 3] = [b'l', b'l', b'e'];
static s_6_9: [symbol; 3] = [b'i', b'n', b'e'];
static s_6_10: [symbol; 3] = [b'k', b's', b'i'];
static s_6_11: [symbol; 1] = [b'n'];
static s_6_12: [symbol; 3] = [b'h', b'a', b'n'];
static s_6_13: [symbol; 3] = [b'd', b'e', b'n'];
static s_6_14: [symbol; 4] = [b's', b'e', b'e', b'n'];
static s_6_15: [symbol; 3] = [b'h', b'e', b'n'];
static s_6_16: [symbol; 4] = [b't', b't', b'e', b'n'];
static s_6_17: [symbol; 3] = [b'h', b'i', b'n'];
static s_6_18: [symbol; 4] = [b's', b'i', b'i', b'n'];
static s_6_19: [symbol; 3] = [b'h', b'o', b'n'];
static s_6_20: [symbol; 4] = [b'h', 0xC3, 0xA4, b'n'];
static s_6_21: [symbol; 4] = [b'h', 0xC3, 0xB6, b'n'];
static s_6_22: [symbol; 2] = [0xC3, 0xA4];
static s_6_23: [symbol; 4] = [b'l', b'l', 0xC3, 0xA4];
static s_6_24: [symbol; 3] = [b'n', 0xC3, 0xA4];
static s_6_25: [symbol; 4] = [b's', b's', 0xC3, 0xA4];
static s_6_26: [symbol; 3] = [b't', 0xC3, 0xA4];
static s_6_27: [symbol; 4] = [b'l', b't', 0xC3, 0xA4];
static s_6_28: [symbol; 4] = [b's', b't', 0xC3, 0xA4];
static s_6_29: [symbol; 4] = [b't', b't', 0xC3, 0xA4];

static a_6: [among; 30] = [
    among { s_size: 1, s: s_6_0.as_ptr(), substring_i: -1, result: 8, function: None },
    among { s_size: 3, s: s_6_1.as_ptr(), substring_i: 0, result: -1, function: None },
    among { s_size: 2, s: s_6_2.as_ptr(), substring_i: 0, result: -1, function: None },
    among { s_size: 3, s: s_6_3.as_ptr(), substring_i: 0, result: -1, function: None },
    among { s_size: 2, s: s_6_4.as_ptr(), substring_i: 0, result: -1, function: None },
    among { s_size: 3, s: s_6_5.as_ptr(), substring_i: 4, result: -1, function: None },
    among { s_size: 3, s: s_6_6.as_ptr(), substring_i: 4, result: -1, function: None },
    among { s_size: 3, s: s_6_7.as_ptr(), substring_i: 4, result: 2, function: None },
    among { s_size: 3, s: s_6_8.as_ptr(), substring_i: -1, result: -1, function: None },
    among { s_size: 3, s: s_6_9.as_ptr(), substring_i: -1, result: -1, function: None },
    among { s_size: 3, s: s_6_10.as_ptr(), substring_i: -1, result: -1, function: None },
    among { s_size: 1, s: s_6_11.as_ptr(), substring_i: -1, result: 7, function: None },
    among { s_size: 3, s: s_6_12.as_ptr(), substring_i: 11, result: 1, function: None },
    among { s_size: 3, s: s_6_13.as_ptr(), substring_i: 11, result: -1, function: Some(r_VI) },
    among { s_size: 4, s: s_6_14.as_ptr(), substring_i: 11, result: -1, function: Some(r_LONG) },
    among { s_size: 3, s: s_6_15.as_ptr(), substring_i: 11, result: 2, function: None },
    among { s_size: 4, s: s_6_16.as_ptr(), substring_i: 11, result: -1, function: Some(r_VI) },
    among { s_size: 3, s: s_6_17.as_ptr(), substring_i: 11, result: 3, function: None },
    among { s_size: 4, s: s_6_18.as_ptr(), substring_i: 11, result: -1, function: Some(r_VI) },
    among { s_size: 3, s: s_6_19.as_ptr(), substring_i: 11, result: 4, function: None },
    among { s_size: 4, s: s_6_20.as_ptr(), substring_i: 11, result: 5, function: None },
    among { s_size: 4, s: s_6_21.as_ptr(), substring_i: 11, result: 6, function: None },
    among { s_size: 2, s: s_6_22.as_ptr(), substring_i: -1, result: 8, function: None },
    among { s_size: 4, s: s_6_23.as_ptr(), substring_i: 22, result: -1, function: None },
    among { s_size: 3, s: s_6_24.as_ptr(), substring_i: 22, result: -1, function: None },
    among { s_size: 4, s: s_6_25.as_ptr(), substring_i: 22, result: -1, function: None },
    among { s_size: 3, s: s_6_26.as_ptr(), substring_i: 22, result: -1, function: None },
    among { s_size: 4, s: s_6_27.as_ptr(), substring_i: 26, result: -1, function: None },
    among { s_size: 4, s: s_6_28.as_ptr(), substring_i: 26, result: -1, function: None },
    among { s_size: 4, s: s_6_29.as_ptr(), substring_i: 26, result: 2, function: None },
];

static s_7_0: [symbol; 3] = [b'e', b'j', b'a'];
static s_7_1: [symbol; 3] = [b'm', b'm', b'a'];
static s_7_2: [symbol; 4] = [b'i', b'm', b'm', b'a'];
static s_7_3: [symbol; 3] = [b'm', b'p', b'a'];
static s_7_4: [symbol; 4] = [b'i', b'm', b'p', b'a'];
static s_7_5: [symbol; 3] = [b'm', b'm', b'i'];
static s_7_6: [symbol; 4] = [b'i', b'm', b'm', b'i'];
static s_7_7: [symbol; 3] = [b'm', b'p', b'i'];
static s_7_8: [symbol; 4] = [b'i', b'm', b'p', b'i'];
static s_7_9: [symbol; 4] = [b'e', b'j', 0xC3, 0xA4];
static s_7_10: [symbol; 4] = [b'm', b'm', 0xC3, 0xA4];
static s_7_11: [symbol; 5] = [b'i', b'm', b'm', 0xC3, 0xA4];
static s_7_12: [symbol; 4] = [b'm', b'p', 0xC3, 0xA4];
static s_7_13: [symbol; 5] = [b'i', b'm', b'p', 0xC3, 0xA4];

static a_7: [among; 14] = [
    among { s_size: 3, s: s_7_0.as_ptr(), substring_i: -1, result: -1, function: None },
    among { s_size: 3, s: s_7_1.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 4, s: s_7_2.as_ptr(), substring_i: 1, result: -1, function: None },
    among { s_size: 3, s: s_7_3.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 4, s: s_7_4.as_ptr(), substring_i: 3, result: -1, function: None },
    among { s_size: 3, s: s_7_5.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 4, s: s_7_6.as_ptr(), substring_i: 5, result: -1, function: None },
    among { s_size: 3, s: s_7_7.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 4, s: s_7_8.as_ptr(), substring_i: 7, result: -1, function: None },
    among { s_size: 4, s: s_7_9.as_ptr(), substring_i: -1, result: -1, function: None },
    among { s_size: 4, s: s_7_10.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 5, s: s_7_11.as_ptr(), substring_i: 10, result: -1, function: None },
    among { s_size: 4, s: s_7_12.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 5, s: s_7_13.as_ptr(), substring_i: 12, result: -1, function: None },
];

static s_8_0: [symbol; 1] = [b'i'];
static s_8_1: [symbol; 1] = [b'j'];

static a_8: [among; 2] = [
    among { s_size: 1, s: s_8_0.as_ptr(), substring_i: -1, result: -1, function: None },
    among { s_size: 1, s: s_8_1.as_ptr(), substring_i: -1, result: -1, function: None },
];

static s_9_0: [symbol; 3] = [b'm', b'm', b'a'];
static s_9_1: [symbol; 4] = [b'i', b'm', b'm', b'a'];

static a_9: [among; 2] = [
    among { s_size: 3, s: s_9_0.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 4, s: s_9_1.as_ptr(), substring_i: 0, result: -1, function: None },
];

static G_AEI: [c_uchar; 17] = [17, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8];

static G_C: [c_uchar; 4] = [119, 223, 119, 1];

static G_V1: [c_uchar; 19] = [17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 32];

static G_V2: [c_uchar; 19] = [17, 65, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 32];

static G_particle_end: [c_uchar; 19] = [17, 97, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 32];

static s_0: [symbol; 3] = [b'k', b's', b'e'];
static s_1: [symbol; 3] = [b'k', b's', b'i'];
static s_2: [symbol; 2] = [0xC3, 0xA4];
static s_3: [symbol; 2] = [0xC3, 0xB6];
static s_4: [symbol; 2] = [b'i', b'e'];
static s_5: [symbol; 2] = [b'p', b'o'];
static s_6: [symbol; 2] = [b'p', b'o'];

// ---------------------------------------------------------------------------
// rules
// ---------------------------------------------------------------------------

unsafe extern "C" fn r_mark_regions(z: *mut SN_env) -> c_int {
    *(*z).I.offset(1) = (*z).l;
    *(*z).I.offset(0) = (*z).l;

    if out_grouping_U(z, G_V1.as_ptr(), 97, 246, 1) < 0 { return 0; }

    {
        let ret = in_grouping_U(z, G_V1.as_ptr(), 97, 246, 1);
        if ret < 0 { return 0; }
        (*z).c += ret;
    }
    *(*z).I.offset(1) = (*z).c;

    if out_grouping_U(z, G_V1.as_ptr(), 97, 246, 1) < 0 { return 0; }

    {
        let ret = in_grouping_U(z, G_V1.as_ptr(), 97, 246, 1);
        if ret < 0 { return 0; }
        (*z).c += ret;
    }
    *(*z).I.offset(0) = (*z).c;
    1
}

unsafe extern "C" fn r_R2(z: *mut SN_env) -> c_int {
    (*(*z).I.offset(0) <= (*z).c) as c_int
}

unsafe extern "C" fn r_particle_etc(z: *mut SN_env) -> c_int {
    let among_var: c_int;

    {
        let mlimit1: c_int;
        if (*z).c < *(*z).I.offset(1) { return 0; }
        mlimit1 = (*z).lb; (*z).lb = *(*z).I.offset(1);
        (*z).ket = (*z).c;
        among_var = find_among_b(z, a_0.as_ptr(), 10);
        if among_var == 0 { (*z).lb = mlimit1; return 0; }
        (*z).bra = (*z).c;
        (*z).lb = mlimit1;
    }
    match among_var {
        1 => {
            if in_grouping_b_U(z, G_particle_end.as_ptr(), 97, 246, 0) != 0 { return 0; }
        }
        2 => {
            let ret = r_R2(z);
            if ret <= 0 { return ret; }
        }
        _ => {}
    }
    {
        let ret = slice_del(z);
        if ret < 0 { return ret; }
    }
    1
}

unsafe extern "C" fn r_possessive(z: *mut SN_env) -> c_int {
    let among_var: c_int;

    {
        let mlimit1: c_int;
        if (*z).c < *(*z).I.offset(1) { return 0; }
        mlimit1 = (*z).lb; (*z).lb = *(*z).I.offset(1);
        (*z).ket = (*z).c;
        among_var = find_among_b(z, a_4.as_ptr(), 9);
        if among_var == 0 { (*z).lb = mlimit1; return 0; }
        (*z).bra = (*z).c;
        (*z).lb = mlimit1;
    }
    match among_var {
        1 => {
            let m2 = (*z).l - (*z).c;
            'lab0: {
                if (*z).c <= (*z).lb || *(*z).p.offset(((*z).c - 1) as isize) != b'k' { break 'lab0; }
                (*z).c -= 1;
                return 0;
            }
            (*z).c = (*z).l - m2;
            let ret = slice_del(z);
            if ret < 0 { return ret; }
        }
        2 => {
            {
                let ret = slice_del(z);
                if ret < 0 { return ret; }
            }
            (*z).ket = (*z).c;
            if eq_s_b(z, 3, s_0.as_ptr()) == 0 { return 0; }
            (*z).bra = (*z).c;
            {
                let ret = slice_from_s(z, 3, s_1.as_ptr());
                if ret < 0 { return ret; }
            }
        }
        3 => {
            let ret = slice_del(z);
            if ret < 0 { return ret; }
        }
        4 => {
            if (*z).c - 1 <= (*z).lb || *(*z).p.offset(((*z).c - 1) as isize) != 97 { return 0; }
            if find_among_b(z, a_1.as_ptr(), 6) == 0 { return 0; }
            let ret = slice_del(z);
            if ret < 0 { return ret; }
        }
        5 => {
            if (*z).c - 2 <= (*z).lb || *(*z).p.offset(((*z).c - 1) as isize) != 164 { return 0; }
            if find_among_b(z, a_2.as_ptr(), 6) == 0 { return 0; }
            let ret = slice_del(z);
            if ret < 0 { return ret; }
        }
        6 => {
            if (*z).c - 2 <= (*z).lb || *(*z).p.offset(((*z).c - 1) as isize) != 101 { return 0; }
            if find_among_b(z, a_3.as_ptr(), 2) == 0 { return 0; }
            let ret = slice_del(z);
            if ret < 0 { return ret; }
        }
        _ => {}
    }
    1
}

unsafe extern "C" fn r_LONG(z: *mut SN_env) -> c_int {
    if find_among_b(z, a_5.as_ptr(), 7) == 0 { return 0; }
    1
}

unsafe extern "C" fn r_VI(z: *mut SN_env) -> c_int {
    if (*z).c <= (*z).lb || *(*z).p.offset(((*z).c - 1) as isize) != b'i' { return 0; }
    (*z).c -= 1;
    if in_grouping_b_U(z, G_V2.as_ptr(), 97, 246, 0) != 0 { return 0; }
    1
}

unsafe extern "C" fn r_case_ending(z: *mut SN_env) -> c_int {
    let among_var: c_int;

    {
        let mlimit1: c_int;
        if (*z).c < *(*z).I.offset(1) { return 0; }
        mlimit1 = (*z).lb; (*z).lb = *(*z).I.offset(1);
        (*z).ket = (*z).c;
        among_var = find_among_b(z, a_6.as_ptr(), 30);
        if among_var == 0 { (*z).lb = mlimit1; return 0; }
        (*z).bra = (*z).c;
        (*z).lb = mlimit1;
    }
    match among_var {
        1 => {
            if (*z).c <= (*z).lb || *(*z).p.offset(((*z).c - 1) as isize) != b'a' { return 0; }
            (*z).c -= 1;
        }
        2 => {
            if (*z).c <= (*z).lb || *(*z).p.offset(((*z).c - 1) as isize) != b'e' { return 0; }
            (*z).c -= 1;
        }
        3 => {
            if (*z).c <= (*z).lb || *(*z).p.offset(((*z).c - 1) as isize) != b'i' { return 0; }
            (*z).c -= 1;
        }
        4 => {
            if (*z).c <= (*z).lb || *(*z).p.offset(((*z).c - 1) as isize) != b'o' { return 0; }
            (*z).c -= 1;
        }
        5 => {
            if eq_s_b(z, 2, s_2.as_ptr()) == 0 { return 0; }
        }
        6 => {
            if eq_s_b(z, 2, s_3.as_ptr()) == 0 { return 0; }
        }
        7 => {
            let m2 = (*z).l - (*z).c;
            'lab0: {
                let m3 = (*z).l - (*z).c;
                {
                    let m4 = (*z).l - (*z).c;
                    'lab1: {
                        'lab2: {
                            let ret = r_LONG(z);
                            if ret == 0 { break 'lab2; }
                            if ret < 0 { return ret; }
                            break 'lab1;
                        }
                        // lab2:
                        (*z).c = (*z).l - m4;
                        if eq_s_b(z, 2, s_4.as_ptr()) == 0 { (*z).c = (*z).l - m2; break 'lab0; }
                    }
                    // lab1:
                    (*z).c = (*z).l - m3;
                    let ret = skip_b_utf8((*z).p, (*z).c, (*z).lb, 1);
                    if ret < 0 { (*z).c = (*z).l - m2; break 'lab0; }
                    (*z).c = ret;
                }
                (*z).bra = (*z).c;
            }
            // lab0: ;
        }
        8 => {
            if in_grouping_b_U(z, G_V1.as_ptr(), 97, 246, 0) != 0 { return 0; }
            if in_grouping_b_U(z, G_C.as_ptr(), 98, 122, 0) != 0 { return 0; }
        }
        _ => {}
    }
    {
        let ret = slice_del(z);
        if ret < 0 { return ret; }
    }
    *(*z).I.offset(2) = 1;
    1
}

unsafe extern "C" fn r_other_endings(z: *mut SN_env) -> c_int {
    let among_var: c_int;

    {
        let mlimit1: c_int;
        if (*z).c < *(*z).I.offset(0) { return 0; }
        mlimit1 = (*z).lb; (*z).lb = *(*z).I.offset(0);
        (*z).ket = (*z).c;
        among_var = find_among_b(z, a_7.as_ptr(), 14);
        if among_var == 0 { (*z).lb = mlimit1; return 0; }
        (*z).bra = (*z).c;
        (*z).lb = mlimit1;
    }
    match among_var {
        1 => {
            let m2 = (*z).l - (*z).c;
            'lab0: {
                if eq_s_b(z, 2, s_5.as_ptr()) == 0 { break 'lab0; }
                return 0;
            }
            (*z).c = (*z).l - m2;
        }
        _ => {}
    }
    {
        let ret = slice_del(z);
        if ret < 0 { return ret; }
    }
    1
}

unsafe extern "C" fn r_i_plural(z: *mut SN_env) -> c_int {
    {
        let mlimit1: c_int;
        if (*z).c < *(*z).I.offset(1) { return 0; }
        mlimit1 = (*z).lb; (*z).lb = *(*z).I.offset(1);
        (*z).ket = (*z).c;
        if (*z).c <= (*z).lb
            || (*(*z).p.offset(((*z).c - 1) as isize) != 105
                && *(*z).p.offset(((*z).c - 1) as isize) != 106)
        {
            (*z).lb = mlimit1;
            return 0;
        }
        if find_among_b(z, a_8.as_ptr(), 2) == 0 { (*z).lb = mlimit1; return 0; }
        (*z).bra = (*z).c;
        (*z).lb = mlimit1;
    }
    {
        let ret = slice_del(z);
        if ret < 0 { return ret; }
    }
    1
}

unsafe extern "C" fn r_t_plural(z: *mut SN_env) -> c_int {
    let among_var: c_int;

    {
        let mlimit1: c_int;
        if (*z).c < *(*z).I.offset(1) { return 0; }
        mlimit1 = (*z).lb; (*z).lb = *(*z).I.offset(1);
        (*z).ket = (*z).c;
        if (*z).c <= (*z).lb || *(*z).p.offset(((*z).c - 1) as isize) != b't' { (*z).lb = mlimit1; return 0; }
        (*z).c -= 1;
        (*z).bra = (*z).c;
        {
            let m_test2 = (*z).l - (*z).c;
            if in_grouping_b_U(z, G_V1.as_ptr(), 97, 246, 0) != 0 { (*z).lb = mlimit1; return 0; }
            (*z).c = (*z).l - m_test2;
        }
        {
            let ret = slice_del(z);
            if ret < 0 { return ret; }
        }
        (*z).lb = mlimit1;
    }

    {
        let mlimit3: c_int;
        if (*z).c < *(*z).I.offset(0) { return 0; }
        mlimit3 = (*z).lb; (*z).lb = *(*z).I.offset(0);
        (*z).ket = (*z).c;
        if (*z).c - 2 <= (*z).lb || *(*z).p.offset(((*z).c - 1) as isize) != 97 { (*z).lb = mlimit3; return 0; }
        among_var = find_among_b(z, a_9.as_ptr(), 2);
        if among_var == 0 { (*z).lb = mlimit3; return 0; }
        (*z).bra = (*z).c;
        (*z).lb = mlimit3;
    }
    match among_var {
        1 => {
            let m4 = (*z).l - (*z).c;
            'lab0: {
                if eq_s_b(z, 2, s_6.as_ptr()) == 0 { break 'lab0; }
                return 0;
            }
            (*z).c = (*z).l - m4;
        }
        _ => {}
    }
    {
        let ret = slice_del(z);
        if ret < 0 { return ret; }
    }
    1
}

unsafe extern "C" fn r_tidy(z: *mut SN_env) -> c_int {
    {
        let mlimit1: c_int;
        if (*z).c < *(*z).I.offset(1) { return 0; }
        mlimit1 = (*z).lb; (*z).lb = *(*z).I.offset(1);
        {
            let m2 = (*z).l - (*z).c;
            'lab0: {
                let m3 = (*z).l - (*z).c;
                {
                    let ret = r_LONG(z);
                    if ret == 0 { break 'lab0; }
                    if ret < 0 { return ret; }
                }
                (*z).c = (*z).l - m3;
                (*z).ket = (*z).c;
                {
                    let ret = skip_b_utf8((*z).p, (*z).c, (*z).lb, 1);
                    if ret < 0 { break 'lab0; }
                    (*z).c = ret;
                }
                (*z).bra = (*z).c;
                {
                    let ret = slice_del(z);
                    if ret < 0 { return ret; }
                }
            }
            (*z).c = (*z).l - m2;
        }
        {
            let m4 = (*z).l - (*z).c;
            'lab1: {
                (*z).ket = (*z).c;
                if in_grouping_b_U(z, G_AEI.as_ptr(), 97, 228, 0) != 0 { break 'lab1; }
                (*z).bra = (*z).c;
                if in_grouping_b_U(z, G_C.as_ptr(), 98, 122, 0) != 0 { break 'lab1; }
                let ret = slice_del(z);
                if ret < 0 { return ret; }
            }
            (*z).c = (*z).l - m4;
        }
        {
            let m5 = (*z).l - (*z).c;
            'lab2: {
                (*z).ket = (*z).c;
                if (*z).c <= (*z).lb || *(*z).p.offset(((*z).c - 1) as isize) != b'j' { break 'lab2; }
                (*z).c -= 1;
                (*z).bra = (*z).c;
                'lab3: {
                    let m6 = (*z).l - (*z).c;
                    'lab4: {
                        if (*z).c <= (*z).lb || *(*z).p.offset(((*z).c - 1) as isize) != b'o' { break 'lab4; }
                        (*z).c -= 1;
                        break 'lab3;
                    }
                    // lab4:
                    (*z).c = (*z).l - m6;
                    if (*z).c <= (*z).lb || *(*z).p.offset(((*z).c - 1) as isize) != b'u' { break 'lab2; }
                    (*z).c -= 1;
                }
                let ret = slice_del(z);
                if ret < 0 { return ret; }
            }
            (*z).c = (*z).l - m5;
        }
        {
            let m7 = (*z).l - (*z).c;
            'lab5: {
                (*z).ket = (*z).c;
                if (*z).c <= (*z).lb || *(*z).p.offset(((*z).c - 1) as isize) != b'o' { break 'lab5; }
                (*z).c -= 1;
                (*z).bra = (*z).c;
                if (*z).c <= (*z).lb || *(*z).p.offset(((*z).c - 1) as isize) != b'j' { break 'lab5; }
                (*z).c -= 1;
                let ret = slice_del(z);
                if ret < 0 { return ret; }
            }
            (*z).c = (*z).l - m7;
        }
        (*z).lb = mlimit1;
    }

    if in_grouping_b_U(z, G_V1.as_ptr(), 97, 246, 1) < 0 { return 0; }
    (*z).ket = (*z).c;
    if in_grouping_b_U(z, G_C.as_ptr(), 98, 122, 0) != 0 { return 0; }
    (*z).bra = (*z).c;
    *(*z).S.offset(0) = slice_to(z, *(*z).S.offset(0));
    if (*(*z).S.offset(0)).is_null() { return -1; }
    if eq_v_b(z, *(*z).S.offset(0)) == 0 { return 0; }
    {
        let ret = slice_del(z);
        if ret < 0 { return ret; }
    }
    1
}

#[no_mangle]
pub unsafe extern "C" fn finnish_UTF_8_stem(z: *mut SN_env) -> c_int {
    {
        let c1 = (*z).c;
        {
            let ret = r_mark_regions(z);
            if ret < 0 { return ret; }
        }
        (*z).c = c1;
    }
    *(*z).I.offset(2) = 0;
    (*z).lb = (*z).c; (*z).c = (*z).l;

    {
        let m2 = (*z).l - (*z).c;
        {
            let ret = r_particle_etc(z);
            if ret < 0 { return ret; }
        }
        (*z).c = (*z).l - m2;
    }
    {
        let m3 = (*z).l - (*z).c;
        {
            let ret = r_possessive(z);
            if ret < 0 { return ret; }
        }
        (*z).c = (*z).l - m3;
    }
    {
        let m4 = (*z).l - (*z).c;
        {
            let ret = r_case_ending(z);
            if ret < 0 { return ret; }
        }
        (*z).c = (*z).l - m4;
    }
    {
        let m5 = (*z).l - (*z).c;
        {
            let ret = r_other_endings(z);
            if ret < 0 { return ret; }
        }
        (*z).c = (*z).l - m5;
    }

    'lab0: {
        'lab1: {
            if *(*z).I.offset(2) == 0 { break 'lab1; }
            {
                let m6 = (*z).l - (*z).c;
                {
                    let ret = r_i_plural(z);
                    if ret < 0 { return ret; }
                }
                (*z).c = (*z).l - m6;
            }
            break 'lab0;
        }
        // lab1:
        {
            let m7 = (*z).l - (*z).c;
            {
                let ret = r_t_plural(z);
                if ret < 0 { return ret; }
            }
            (*z).c = (*z).l - m7;
        }
    }
    // lab0:
    {
        let m8 = (*z).l - (*z).c;
        {
            let ret = r_tidy(z);
            if ret < 0 { return ret; }
        }
        (*z).c = (*z).l - m8;
    }
    (*z).c = (*z).lb;
    1
}

#[no_mangle]
pub unsafe extern "C" fn finnish_UTF_8_create_env() -> *mut SN_env {
    SN_create_env(1, 3)
}

#[no_mangle]
pub unsafe extern "C" fn finnish_UTF_8_close_env(z: *mut SN_env) {
    SN_close_env(z, 1)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    unsafe fn stem_word(w: &[u8]) -> Vec<u8> {
        let z = finnish_UTF_8_create_env();
        SN_set_current(z, w.len() as c_int, w.as_ptr());
        let rc = finnish_UTF_8_stem(z);
        assert!(rc >= 0);
        let out = std::slice::from_raw_parts((*z).p, SIZE((*z).p) as usize).to_vec();
        finnish_UTF_8_close_env(z);
        out
    }

    #[test]
    fn short_root_unchanged() {
        // A short consonant-cluster root has no endings to strip.
        let w = b"ja";
        unsafe {
            let out = stem_word(w);
            assert_eq!(out, w.to_vec());
        }
    }

    #[test]
    fn idempotence_and_nonempty() {
        // ASCII and Finnish-script (UTF-8 a-umlaut / o-umlaut) inputs.
        let words: [&[u8]; 4] = [
            b"talossa",
            b"kaupungeissa",
            &[b'p', b'a', b'i', 0xC3, 0xA4, b'n'],
            &[b'h', 0xC3, 0xA4, b'n'],
        ];
        unsafe {
            for w in words {
                let once = stem_word(w);
                assert!(!once.is_empty());
                let twice = stem_word(&once);
                assert_eq!(once, twice, "stem not idempotent");
            }
        }
    }
}
