// Generated by Snowball 2.2.0 - https://snowballstem.org/
// 1:1 Rust port of postgres/src/backend/snowball/libstemmer/stem_UTF_8_german.c
// (header stem_UTF_8_german.h merged: it only re-declares the 3 exported fns).

use crate::prelude::*;
use crate::snowball::api::{symbol, SN_env, among, SN_create_env, SN_close_env};
use crate::snowball::utilities::{
    find_among, find_among_b, slice_from_s, slice_del,
    eq_s_b, in_grouping_U, in_grouping_b_U, out_grouping_U, skip_utf8, skip_b_utf8,
};

static S_0_1: [symbol; 2] = [b'a', b'e'];
static S_0_2: [symbol; 2] = [b'o', b'e'];
static S_0_3: [symbol; 2] = [b'q', b'u'];
static S_0_4: [symbol; 2] = [b'u', b'e'];
static S_0_5: [symbol; 2] = [0xC3, 0x9F];

static A_0: [among; 6] = [
    among { s_size: 0, s: core::ptr::null(), substring_i: -1, result: 5, function: None },
    among { s_size: 2, s: S_0_1.as_ptr(), substring_i: 0, result: 2, function: None },
    among { s_size: 2, s: S_0_2.as_ptr(), substring_i: 0, result: 3, function: None },
    among { s_size: 2, s: S_0_3.as_ptr(), substring_i: 0, result: -1, function: None },
    among { s_size: 2, s: S_0_4.as_ptr(), substring_i: 0, result: 4, function: None },
    among { s_size: 2, s: S_0_5.as_ptr(), substring_i: 0, result: 1, function: None },
];

static S_1_1: [symbol; 1] = [b'U'];
static S_1_2: [symbol; 1] = [b'Y'];
static S_1_3: [symbol; 2] = [0xC3, 0xA4];
static S_1_4: [symbol; 2] = [0xC3, 0xB6];
static S_1_5: [symbol; 2] = [0xC3, 0xBC];

static A_1: [among; 6] = [
    among { s_size: 0, s: core::ptr::null(), substring_i: -1, result: 5, function: None },
    among { s_size: 1, s: S_1_1.as_ptr(), substring_i: 0, result: 2, function: None },
    among { s_size: 1, s: S_1_2.as_ptr(), substring_i: 0, result: 1, function: None },
    among { s_size: 2, s: S_1_3.as_ptr(), substring_i: 0, result: 3, function: None },
    among { s_size: 2, s: S_1_4.as_ptr(), substring_i: 0, result: 4, function: None },
    among { s_size: 2, s: S_1_5.as_ptr(), substring_i: 0, result: 2, function: None },
];

static S_2_0: [symbol; 1] = [b'e'];
static S_2_1: [symbol; 2] = [b'e', b'm'];
static S_2_2: [symbol; 2] = [b'e', b'n'];
static S_2_3: [symbol; 7] = [b'e', b'r', b'i', b'n', b'n', b'e', b'n'];
static S_2_4: [symbol; 4] = [b'e', b'r', b'i', b'n'];
static S_2_5: [symbol; 2] = [b'l', b'n'];
static S_2_6: [symbol; 3] = [b'e', b'r', b'n'];
static S_2_7: [symbol; 2] = [b'e', b'r'];
static S_2_8: [symbol; 1] = [b's'];
static S_2_9: [symbol; 2] = [b'e', b's'];
static S_2_10: [symbol; 3] = [b'l', b'n', b's'];

static A_2: [among; 11] = [
    among { s_size: 1, s: S_2_0.as_ptr(), substring_i: -1, result: 3, function: None },
    among { s_size: 2, s: S_2_1.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 2, s: S_2_2.as_ptr(), substring_i: -1, result: 3, function: None },
    among { s_size: 7, s: S_2_3.as_ptr(), substring_i: 2, result: 2, function: None },
    among { s_size: 4, s: S_2_4.as_ptr(), substring_i: -1, result: 2, function: None },
    among { s_size: 2, s: S_2_5.as_ptr(), substring_i: -1, result: 5, function: None },
    among { s_size: 3, s: S_2_6.as_ptr(), substring_i: -1, result: 2, function: None },
    among { s_size: 2, s: S_2_7.as_ptr(), substring_i: -1, result: 2, function: None },
    among { s_size: 1, s: S_2_8.as_ptr(), substring_i: -1, result: 4, function: None },
    among { s_size: 2, s: S_2_9.as_ptr(), substring_i: 8, result: 3, function: None },
    among { s_size: 3, s: S_2_10.as_ptr(), substring_i: 8, result: 5, function: None },
];

static S_3_0: [symbol; 2] = [b'e', b'n'];
static S_3_1: [symbol; 2] = [b'e', b'r'];
static S_3_2: [symbol; 2] = [b's', b't'];
static S_3_3: [symbol; 3] = [b'e', b's', b't'];

static A_3: [among; 4] = [
    among { s_size: 2, s: S_3_0.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 2, s: S_3_1.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 2, s: S_3_2.as_ptr(), substring_i: -1, result: 2, function: None },
    among { s_size: 3, s: S_3_3.as_ptr(), substring_i: 2, result: 1, function: None },
];

static S_4_0: [symbol; 2] = [b'i', b'g'];
static S_4_1: [symbol; 4] = [b'l', b'i', b'c', b'h'];

static A_4: [among; 2] = [
    among { s_size: 2, s: S_4_0.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 4, s: S_4_1.as_ptr(), substring_i: -1, result: 1, function: None },
];

static S_5_0: [symbol; 3] = [b'e', b'n', b'd'];
static S_5_1: [symbol; 2] = [b'i', b'g'];
static S_5_2: [symbol; 3] = [b'u', b'n', b'g'];
static S_5_3: [symbol; 4] = [b'l', b'i', b'c', b'h'];
static S_5_4: [symbol; 4] = [b'i', b's', b'c', b'h'];
static S_5_5: [symbol; 2] = [b'i', b'k'];
static S_5_6: [symbol; 4] = [b'h', b'e', b'i', b't'];
static S_5_7: [symbol; 4] = [b'k', b'e', b'i', b't'];

static A_5: [among; 8] = [
    among { s_size: 3, s: S_5_0.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 2, s: S_5_1.as_ptr(), substring_i: -1, result: 2, function: None },
    among { s_size: 3, s: S_5_2.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 4, s: S_5_3.as_ptr(), substring_i: -1, result: 3, function: None },
    among { s_size: 4, s: S_5_4.as_ptr(), substring_i: -1, result: 2, function: None },
    among { s_size: 2, s: S_5_5.as_ptr(), substring_i: -1, result: 2, function: None },
    among { s_size: 4, s: S_5_6.as_ptr(), substring_i: -1, result: 3, function: None },
    among { s_size: 4, s: S_5_7.as_ptr(), substring_i: -1, result: 4, function: None },
];

static G_V: [c_uchar; 20] = [17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 32, 8];

static G_S_ENDING: [c_uchar; 3] = [117, 30, 5];

static G_ST_ENDING: [c_uchar; 3] = [117, 30, 4];

static S_0: [symbol; 1] = [b'U'];
static S_1: [symbol; 1] = [b'Y'];
static S_2: [symbol; 2] = [b's', b's'];
static S_3: [symbol; 2] = [0xC3, 0xA4];
static S_4: [symbol; 2] = [0xC3, 0xB6];
static S_5: [symbol; 2] = [0xC3, 0xBC];
static S_6: [symbol; 1] = [b'y'];
static S_7: [symbol; 1] = [b'u'];
static S_8: [symbol; 1] = [b'a'];
static S_9: [symbol; 1] = [b'o'];
static S_10: [symbol; 4] = [b's', b'y', b's', b't'];
static S_11: [symbol; 3] = [b'n', b'i', b's'];
static S_12: [symbol; 1] = [b'l'];
static S_13: [symbol; 2] = [b'i', b'g'];
static S_14: [symbol; 2] = [b'e', b'r'];
static S_15: [symbol; 2] = [b'e', b'n'];

unsafe fn r_prelude(z: *mut SN_env) -> c_int {
    let mut among_var: c_int;
    {
        let c_test1 = (*z).c;
        'pre_outer: loop {
            let c2 = (*z).c;
            'lab0: {
                'pre_inner: loop {
                    let c3 = (*z).c;
                    'lab1: {
                        'lab2: {
                            if in_grouping_U(z, G_V.as_ptr(), 97, 252, 0) != 0 { break 'lab1; }
                            (*z).bra = (*z).c;
                            {
                                let c4 = (*z).c;
                                'lab3: {
                                    if (*z).c == (*z).l || *(*z).p.offset((*z).c as isize) != b'u' { break 'lab3; }
                                    (*z).c += 1;
                                    (*z).ket = (*z).c;
                                    if in_grouping_U(z, G_V.as_ptr(), 97, 252, 0) != 0 { break 'lab3; }
                                    {
                                        let ret = slice_from_s(z, 1, S_0.as_ptr());
                                        if ret < 0 { return ret; }
                                    }
                                    break 'lab2;
                                }
                                // lab3:
                                (*z).c = c4;
                                if (*z).c == (*z).l || *(*z).p.offset((*z).c as isize) != b'y' { break 'lab1; }
                                (*z).c += 1;
                                (*z).ket = (*z).c;
                                if in_grouping_U(z, G_V.as_ptr(), 97, 252, 0) != 0 { break 'lab1; }
                                {
                                    let ret = slice_from_s(z, 1, S_1.as_ptr());
                                    if ret < 0 { return ret; }
                                }
                            }
                        }
                        // lab2:
                        (*z).c = c3;
                        break 'pre_inner;
                    }
                    // lab1:
                    (*z).c = c3;
                    {
                        let ret = skip_utf8((*z).p, (*z).c, (*z).l, 1);
                        if ret < 0 { break 'lab0; }
                        (*z).c = ret;
                    }
                }
                continue 'pre_outer;
            }
            // lab0:
            (*z).c = c2;
            break;
        }
        (*z).c = c_test1;
    }
    'sfx: loop {
        let c5 = (*z).c;
        'lab4: {
            (*z).bra = (*z).c;
            among_var = find_among(z, A_0.as_ptr(), 6);
            (*z).ket = (*z).c;
            match among_var {
                1 => {
                    let ret = slice_from_s(z, 2, S_2.as_ptr());
                    if ret < 0 { return ret; }
                }
                2 => {
                    let ret = slice_from_s(z, 2, S_3.as_ptr());
                    if ret < 0 { return ret; }
                }
                3 => {
                    let ret = slice_from_s(z, 2, S_4.as_ptr());
                    if ret < 0 { return ret; }
                }
                4 => {
                    let ret = slice_from_s(z, 2, S_5.as_ptr());
                    if ret < 0 { return ret; }
                }
                5 => {
                    let ret = skip_utf8((*z).p, (*z).c, (*z).l, 1);
                    if ret < 0 { break 'lab4; }
                    (*z).c = ret;
                }
                _ => {}
            }
            continue 'sfx;
        }
        // lab4:
        (*z).c = c5;
        break;
    }
    return 1;
}

unsafe fn r_mark_regions(z: *mut SN_env) -> c_int {
    *(*z).I.offset(2) = (*z).l;
    *(*z).I.offset(1) = (*z).l;
    {
        let c_test1 = (*z).c;
        {
            let ret = skip_utf8((*z).p, (*z).c, (*z).l, 3);
            if ret < 0 { return 0; }
            (*z).c = ret;
        }
        *(*z).I.offset(0) = (*z).c;
        (*z).c = c_test1;
    }

    {
        let ret = out_grouping_U(z, G_V.as_ptr(), 97, 252, 1);
        if ret < 0 { return 0; }
        (*z).c += ret;
    }

    {
        let ret = in_grouping_U(z, G_V.as_ptr(), 97, 252, 1);
        if ret < 0 { return 0; }
        (*z).c += ret;
    }
    *(*z).I.offset(2) = (*z).c;

    'lab0: {
        if *(*z).I.offset(2) >= *(*z).I.offset(0) { break 'lab0; }
        *(*z).I.offset(2) = *(*z).I.offset(0);
    }

    {
        let ret = out_grouping_U(z, G_V.as_ptr(), 97, 252, 1);
        if ret < 0 { return 0; }
        (*z).c += ret;
    }

    {
        let ret = in_grouping_U(z, G_V.as_ptr(), 97, 252, 1);
        if ret < 0 { return 0; }
        (*z).c += ret;
    }
    *(*z).I.offset(1) = (*z).c;
    return 1;
}

unsafe fn r_postlude(z: *mut SN_env) -> c_int {
    let mut among_var: c_int;
    'post: loop {
        let c1 = (*z).c;
        'lab0: {
            (*z).bra = (*z).c;
            among_var = find_among(z, A_1.as_ptr(), 6);
            (*z).ket = (*z).c;
            match among_var {
                1 => {
                    let ret = slice_from_s(z, 1, S_6.as_ptr());
                    if ret < 0 { return ret; }
                }
                2 => {
                    let ret = slice_from_s(z, 1, S_7.as_ptr());
                    if ret < 0 { return ret; }
                }
                3 => {
                    let ret = slice_from_s(z, 1, S_8.as_ptr());
                    if ret < 0 { return ret; }
                }
                4 => {
                    let ret = slice_from_s(z, 1, S_9.as_ptr());
                    if ret < 0 { return ret; }
                }
                5 => {
                    let ret = skip_utf8((*z).p, (*z).c, (*z).l, 1);
                    if ret < 0 { break 'lab0; }
                    (*z).c = ret;
                }
                _ => {}
            }
            continue 'post;
        }
        // lab0:
        (*z).c = c1;
        break;
    }
    return 1;
}

unsafe fn r_R1(z: *mut SN_env) -> c_int {
    return (*(*z).I.offset(2) <= (*z).c) as c_int;
}

unsafe fn r_R2(z: *mut SN_env) -> c_int {
    return (*(*z).I.offset(1) <= (*z).c) as c_int;
}

unsafe fn r_standard_suffix(z: *mut SN_env) -> c_int {
    let mut among_var: c_int;
    {
        let m1 = (*z).l - (*z).c; let _ = m1;
        'lab0: {
            (*z).ket = (*z).c;
            if (*z).c <= (*z).lb
                || *(*z).p.offset(((*z).c - 1) as isize) >> 5 != 3
                || ((811040 >> (*(*z).p.offset(((*z).c - 1) as isize) & 0x1f)) & 1) == 0 { break 'lab0; }
            among_var = find_among_b(z, A_2.as_ptr(), 11);
            if among_var == 0 { break 'lab0; }
            (*z).bra = (*z).c;
            {
                let ret = r_R1(z);
                if ret == 0 { break 'lab0; }
                if ret < 0 { return ret; }
            }
            match among_var {
                1 => {
                    {
                        let m2 = (*z).l - (*z).c; let _ = m2;
                        'lab1: {
                            if eq_s_b(z, 4, S_10.as_ptr()) != 0 { break 'lab1; }
                            break 'lab0;
                        }
                        // lab1:
                        (*z).c = (*z).l - m2;
                    }
                    {
                        let ret = slice_del(z);
                        if ret < 0 { return ret; }
                    }
                }
                2 => {
                    let ret = slice_del(z);
                    if ret < 0 { return ret; }
                }
                3 => {
                    {
                        let ret = slice_del(z);
                        if ret < 0 { return ret; }
                    }
                    {
                        let m3 = (*z).l - (*z).c; let _ = m3;
                        'lab2: {
                            (*z).ket = (*z).c;
                            if (*z).c <= (*z).lb || *(*z).p.offset(((*z).c - 1) as isize) != b's' {
                                (*z).c = (*z).l - m3; break 'lab2;
                            }
                            (*z).c -= 1;
                            (*z).bra = (*z).c;
                            if eq_s_b(z, 3, S_11.as_ptr()) == 0 {
                                (*z).c = (*z).l - m3; break 'lab2;
                            }
                            {
                                let ret = slice_del(z);
                                if ret < 0 { return ret; }
                            }
                        }
                    }
                }
                4 => {
                    if in_grouping_b_U(z, G_S_ENDING.as_ptr(), 98, 116, 0) != 0 { break 'lab0; }
                    {
                        let ret = slice_del(z);
                        if ret < 0 { return ret; }
                    }
                }
                5 => {
                    let ret = slice_from_s(z, 1, S_12.as_ptr());
                    if ret < 0 { return ret; }
                }
                _ => {}
            }
        }
        // lab0:
        (*z).c = (*z).l - m1;
    }
    {
        let m4 = (*z).l - (*z).c; let _ = m4;
        'lab3: {
            (*z).ket = (*z).c;
            if (*z).c - 1 <= (*z).lb
                || *(*z).p.offset(((*z).c - 1) as isize) >> 5 != 3
                || ((1327104 >> (*(*z).p.offset(((*z).c - 1) as isize) & 0x1f)) & 1) == 0 { break 'lab3; }
            among_var = find_among_b(z, A_3.as_ptr(), 4);
            if among_var == 0 { break 'lab3; }
            (*z).bra = (*z).c;
            {
                let ret = r_R1(z);
                if ret == 0 { break 'lab3; }
                if ret < 0 { return ret; }
            }
            match among_var {
                1 => {
                    let ret = slice_del(z);
                    if ret < 0 { return ret; }
                }
                2 => {
                    if in_grouping_b_U(z, G_ST_ENDING.as_ptr(), 98, 116, 0) != 0 { break 'lab3; }
                    {
                        let ret = skip_b_utf8((*z).p, (*z).c, (*z).lb, 3);
                        if ret < 0 { break 'lab3; }
                        (*z).c = ret;
                    }
                    {
                        let ret = slice_del(z);
                        if ret < 0 { return ret; }
                    }
                }
                _ => {}
            }
        }
        // lab3:
        (*z).c = (*z).l - m4;
    }
    {
        let m5 = (*z).l - (*z).c; let _ = m5;
        'lab4: {
            (*z).ket = (*z).c;
            if (*z).c - 1 <= (*z).lb
                || *(*z).p.offset(((*z).c - 1) as isize) >> 5 != 3
                || ((1051024 >> (*(*z).p.offset(((*z).c - 1) as isize) & 0x1f)) & 1) == 0 { break 'lab4; }
            among_var = find_among_b(z, A_5.as_ptr(), 8);
            if among_var == 0 { break 'lab4; }
            (*z).bra = (*z).c;
            {
                let ret = r_R2(z);
                if ret == 0 { break 'lab4; }
                if ret < 0 { return ret; }
            }
            match among_var {
                1 => {
                    {
                        let ret = slice_del(z);
                        if ret < 0 { return ret; }
                    }
                    {
                        let m6 = (*z).l - (*z).c; let _ = m6;
                        'lab5: {
                            (*z).ket = (*z).c;
                            if eq_s_b(z, 2, S_13.as_ptr()) == 0 {
                                (*z).c = (*z).l - m6; break 'lab5;
                            }
                            (*z).bra = (*z).c;
                            {
                                let m7 = (*z).l - (*z).c; let _ = m7;
                                'lab6: {
                                    if (*z).c <= (*z).lb || *(*z).p.offset(((*z).c - 1) as isize) != b'e' { break 'lab6; }
                                    (*z).c -= 1;
                                    {
                                        (*z).c = (*z).l - m6; break 'lab5;
                                    }
                                }
                                // lab6:
                                (*z).c = (*z).l - m7;
                            }
                            {
                                let ret = r_R2(z);
                                if ret == 0 { (*z).c = (*z).l - m6; break 'lab5; }
                                if ret < 0 { return ret; }
                            }
                            {
                                let ret = slice_del(z);
                                if ret < 0 { return ret; }
                            }
                        }
                    }
                }
                2 => {
                    {
                        let m8 = (*z).l - (*z).c; let _ = m8;
                        'lab7: {
                            if (*z).c <= (*z).lb || *(*z).p.offset(((*z).c - 1) as isize) != b'e' { break 'lab7; }
                            (*z).c -= 1;
                            break 'lab4;
                        }
                        // lab7:
                        (*z).c = (*z).l - m8;
                    }
                    {
                        let ret = slice_del(z);
                        if ret < 0 { return ret; }
                    }
                }
                3 => {
                    {
                        let ret = slice_del(z);
                        if ret < 0 { return ret; }
                    }
                    {
                        let m9 = (*z).l - (*z).c; let _ = m9;
                        'lab8: {
                            (*z).ket = (*z).c;
                            {
                                let m10 = (*z).l - (*z).c; let _ = m10;
                                'lab9: {
                                    'lab10: {
                                        if eq_s_b(z, 2, S_14.as_ptr()) == 0 { break 'lab10; }
                                        break 'lab9;
                                    }
                                    // lab10:
                                    (*z).c = (*z).l - m10;
                                    if eq_s_b(z, 2, S_15.as_ptr()) == 0 {
                                        (*z).c = (*z).l - m9; break 'lab8;
                                    }
                                }
                            }
                            // lab9:
                            (*z).bra = (*z).c;
                            {
                                let ret = r_R1(z);
                                if ret == 0 { (*z).c = (*z).l - m9; break 'lab8; }
                                if ret < 0 { return ret; }
                            }
                            {
                                let ret = slice_del(z);
                                if ret < 0 { return ret; }
                            }
                        }
                    }
                }
                4 => {
                    {
                        let ret = slice_del(z);
                        if ret < 0 { return ret; }
                    }
                    {
                        let m11 = (*z).l - (*z).c; let _ = m11;
                        'lab11: {
                            (*z).ket = (*z).c;
                            if (*z).c - 1 <= (*z).lb
                                || (*(*z).p.offset(((*z).c - 1) as isize) != 103 && *(*z).p.offset(((*z).c - 1) as isize) != 104) {
                                (*z).c = (*z).l - m11; break 'lab11;
                            }
                            if find_among_b(z, A_4.as_ptr(), 2) == 0 {
                                (*z).c = (*z).l - m11; break 'lab11;
                            }
                            (*z).bra = (*z).c;
                            {
                                let ret = r_R2(z);
                                if ret == 0 { (*z).c = (*z).l - m11; break 'lab11; }
                                if ret < 0 { return ret; }
                            }
                            {
                                let ret = slice_del(z);
                                if ret < 0 { return ret; }
                            }
                        }
                    }
                }
                _ => {}
            }
        }
        // lab4:
        (*z).c = (*z).l - m5;
    }
    return 1;
}

#[no_mangle]
pub unsafe extern "C" fn german_UTF_8_stem(z: *mut SN_env) -> c_int {
    {
        let c1 = (*z).c;
        {
            let ret = r_prelude(z);
            if ret < 0 { return ret; }
        }
        (*z).c = c1;
    }
    {
        let c2 = (*z).c;
        {
            let ret = r_mark_regions(z);
            if ret < 0 { return ret; }
        }
        (*z).c = c2;
    }
    (*z).lb = (*z).c; (*z).c = (*z).l;

    {
        let ret = r_standard_suffix(z);
        if ret < 0 { return ret; }
    }
    (*z).c = (*z).lb;
    {
        let c3 = (*z).c;
        {
            let ret = r_postlude(z);
            if ret < 0 { return ret; }
        }
        (*z).c = c3;
    }
    return 1;
}

#[no_mangle]
pub unsafe extern "C" fn german_UTF_8_create_env() -> *mut SN_env {
    SN_create_env(0, 3)
}

#[no_mangle]
pub unsafe extern "C" fn german_UTF_8_close_env(z: *mut SN_env) {
    SN_close_env(z, 0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::snowball::api::{SN_set_current, SIZE};

    unsafe fn stem_word(word: &[u8]) -> Vec<symbol> {
        let z = german_UTF_8_create_env();
        SN_set_current(z, word.len() as c_int, word.as_ptr());
        let r = german_UTF_8_stem(z);
        assert!(r >= 0);
        let out = std::slice::from_raw_parts((*z).p, SIZE((*z).p) as usize).to_vec();
        german_UTF_8_close_env(z);
        out
    }

    #[test]
    fn short_root_unchanged() {
        unsafe {
            // A short root word with no suffixes to strip stays put.
            let w = b"tag";
            let out = stem_word(w);
            assert_eq!(out, w.to_vec());
        }
    }

    #[test]
    fn idempotent_and_nonempty() {
        unsafe {
            // "schoenheiten" -> stem; stemming the stem again yields the same.
            let word = b"schoenheiten";
            let once = stem_word(word);
            assert!(!once.is_empty());
            let twice = stem_word(&once);
            assert_eq!(once, twice);
        }
    }

    #[test]
    fn umlaut_word_idempotent() {
        unsafe {
            // "Baeumen" with real umlaut bytes (0xC3 0xA4 = ä) -> "baeumen".
            let word: &[u8] = b"b\xC3\xA4umen";
            let once = stem_word(word);
            assert!(!once.is_empty());
            let twice = stem_word(&once);
            assert_eq!(once, twice);
        }
    }
}
