//! Generated by Snowball 2.2.0 - https://snowballstem.org/
//!
//! 1:1 translation of
//! `postgres/src/backend/snowball/libstemmer/stem_UTF_8_nepali.c`
//! (merged with `stem_UTF_8_nepali.h`).

use crate::prelude::*;
use crate::snowball::api::{symbol, SN_env, among, SN_create_env, SN_close_env};
use crate::snowball::utilities::{find_among_b, slice_del, eq_s_b};

static S_0_0: [symbol; 6] = [0xE0, 0xA4, 0x95, 0xE0, 0xA5, 0x80];
static S_0_1: [symbol; 9] = [0xE0, 0xA4, 0xB2, 0xE0, 0xA4, 0xBE, 0xE0, 0xA4, 0x87];
static S_0_2: [symbol; 6] = [0xE0, 0xA4, 0xB2, 0xE0, 0xA5, 0x87];
static S_0_3: [symbol; 9] = [0xE0, 0xA4, 0xB2, 0xE0, 0xA4, 0xBE, 0xE0, 0xA4, 0x88];
static S_0_4: [symbol; 6] = [0xE0, 0xA4, 0x95, 0xE0, 0xA5, 0x88];
static S_0_5: [symbol; 12] = [0xE0, 0xA4, 0xB8, 0xE0, 0xA4, 0x81, 0xE0, 0xA4, 0x97, 0xE0, 0xA5, 0x88];
static S_0_6: [symbol; 6] = [0xE0, 0xA4, 0xAE, 0xE0, 0xA5, 0x88];
static S_0_7: [symbol; 6] = [0xE0, 0xA4, 0x95, 0xE0, 0xA5, 0x8B];
static S_0_8: [symbol; 9] = [0xE0, 0xA4, 0xB8, 0xE0, 0xA4, 0x81, 0xE0, 0xA4, 0x97];
static S_0_9: [symbol; 9] = [0xE0, 0xA4, 0xB8, 0xE0, 0xA4, 0x82, 0xE0, 0xA4, 0x97];
static S_0_10: [symbol; 18] = [0xE0, 0xA4, 0xAE, 0xE0, 0xA4, 0xBE, 0xE0, 0xA4, 0xB0, 0xE0, 0xA5, 0x8D, 0xE0, 0xA4, 0xAB, 0xE0, 0xA4, 0xA4];
static S_0_11: [symbol; 6] = [0xE0, 0xA4, 0xB0, 0xE0, 0xA4, 0xA4];
static S_0_12: [symbol; 6] = [0xE0, 0xA4, 0x95, 0xE0, 0xA4, 0xBE];
static S_0_13: [symbol; 6] = [0xE0, 0xA4, 0xAE, 0xE0, 0xA4, 0xBE];
static S_0_14: [symbol; 18] = [0xE0, 0xA4, 0xA6, 0xE0, 0xA5, 0x8D, 0xE0, 0xA4, 0xB5, 0xE0, 0xA4, 0xBE, 0xE0, 0xA4, 0xB0, 0xE0, 0xA4, 0xBE];
static S_0_15: [symbol; 6] = [0xE0, 0xA4, 0x95, 0xE0, 0xA4, 0xBF];
static S_0_16: [symbol; 9] = [0xE0, 0xA4, 0xAA, 0xE0, 0xA4, 0x9B, 0xE0, 0xA4, 0xBF];

static A_0: [among; 17] = [
    among { s_size: 6, s: S_0_0.as_ptr(), substring_i: -1, result: 2, function: None },
    among { s_size: 9, s: S_0_1.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 6, s: S_0_2.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 9, s: S_0_3.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 6, s: S_0_4.as_ptr(), substring_i: -1, result: 2, function: None },
    among { s_size: 12, s: S_0_5.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 6, s: S_0_6.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 6, s: S_0_7.as_ptr(), substring_i: -1, result: 2, function: None },
    among { s_size: 9, s: S_0_8.as_ptr(), substring_i: 7, result: 1, function: None },
    among { s_size: 12, s: S_0_9.as_ptr(), substring_i: 8, result: 1, function: None },
    among { s_size: 18, s: S_0_10.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 6, s: S_0_11.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 6, s: S_0_12.as_ptr(), substring_i: -1, result: 2, function: None },
    among { s_size: 6, s: S_0_13.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 18, s: S_0_14.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 6, s: S_0_15.as_ptr(), substring_i: -1, result: 2, function: None },
    among { s_size: 9, s: S_0_16.as_ptr(), substring_i: -1, result: 1, function: None },
];

static S_1_0: [symbol; 3] = [0xE0, 0xA4, 0x81];
static S_1_1: [symbol; 3] = [0xE0, 0xA4, 0x82];
static S_1_2: [symbol; 3] = [0xE0, 0xA5, 0x88];

static A_1: [among; 3] = [
    among { s_size: 3, s: S_1_0.as_ptr(), substring_i: -1, result: -1, function: None },
    among { s_size: 3, s: S_1_1.as_ptr(), substring_i: -1, result: -1, function: None },
    among { s_size: 3, s: S_1_2.as_ptr(), substring_i: -1, result: -1, function: None },
];

static S_2_0: [symbol; 3] = [0xE0, 0xA4, 0x81];
static S_2_1: [symbol; 3] = [0xE0, 0xA4, 0x82];
static S_2_2: [symbol; 3] = [0xE0, 0xA5, 0x88];

static A_2: [among; 3] = [
    among { s_size: 3, s: S_2_0.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 3, s: S_2_1.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 3, s: S_2_2.as_ptr(), substring_i: -1, result: 2, function: None },
];

static S_3_0: [symbol; 9] = [0xE0, 0xA5, 0x87, 0xE0, 0xA4, 0x95, 0xE0, 0xA5, 0x80];
static S_3_1: [symbol; 9] = [0xE0, 0xA4, 0x8F, 0xE0, 0xA4, 0x95, 0xE0, 0xA5, 0x80];
static S_3_2: [symbol; 12] = [0xE0, 0xA4, 0x87, 0xE0, 0xA4, 0x8F, 0xE0, 0xA4, 0x95, 0xE0, 0xA5, 0x80];
static S_3_3: [symbol; 12] = [0xE0, 0xA4, 0xBF, 0xE0, 0xA4, 0x8F, 0xE0, 0xA4, 0x95, 0xE0, 0xA5, 0x80];
static S_3_4: [symbol; 12] = [0xE0, 0xA4, 0xA6, 0xE0, 0xA5, 0x87, 0xE0, 0xA4, 0x96, 0xE0, 0xA5, 0x80];
static S_3_5: [symbol; 6] = [0xE0, 0xA4, 0xA5, 0xE0, 0xA5, 0x80];
static S_3_6: [symbol; 6] = [0xE0, 0xA4, 0xA6, 0xE0, 0xA5, 0x80];
static S_3_7: [symbol; 6] = [0xE0, 0xA4, 0x9B, 0xE0, 0xA5, 0x81];
static S_3_8: [symbol; 9] = [0xE0, 0xA5, 0x87, 0xE0, 0xA4, 0x9B, 0xE0, 0xA5, 0x81];
static S_3_9: [symbol; 12] = [0xE0, 0xA4, 0xA8, 0xE0, 0xA5, 0x87, 0xE0, 0xA4, 0x9B, 0xE0, 0xA5, 0x81];
static S_3_10: [symbol; 9] = [0xE0, 0xA4, 0x8F, 0xE0, 0xA4, 0x9B, 0xE0, 0xA5, 0x81];
static S_3_11: [symbol; 6] = [0xE0, 0xA4, 0xA8, 0xE0, 0xA5, 0x81];
static S_3_12: [symbol; 9] = [0xE0, 0xA4, 0xB9, 0xE0, 0xA4, 0xB0, 0xE0, 0xA5, 0x81];
static S_3_13: [symbol; 9] = [0xE0, 0xA4, 0xB9, 0xE0, 0xA4, 0xB0, 0xE0, 0xA5, 0x82];
static S_3_14: [symbol; 6] = [0xE0, 0xA4, 0x9B, 0xE0, 0xA5, 0x87];
static S_3_15: [symbol; 6] = [0xE0, 0xA4, 0xA5, 0xE0, 0xA5, 0x87];
static S_3_16: [symbol; 6] = [0xE0, 0xA4, 0xA8, 0xE0, 0xA5, 0x87];
static S_3_17: [symbol; 9] = [0xE0, 0xA5, 0x87, 0xE0, 0xA4, 0x95, 0xE0, 0xA5, 0x88];
static S_3_18: [symbol; 12] = [0xE0, 0xA4, 0xA8, 0xE0, 0xA5, 0x87, 0xE0, 0xA4, 0x95, 0xE0, 0xA5, 0x88];
static S_3_19: [symbol; 9] = [0xE0, 0xA4, 0x8F, 0xE0, 0xA4, 0x95, 0xE0, 0xA5, 0x88];
static S_3_20: [symbol; 6] = [0xE0, 0xA4, 0xA6, 0xE0, 0xA5, 0x88];
static S_3_21: [symbol; 9] = [0xE0, 0xA4, 0x87, 0xE0, 0xA4, 0xA6, 0xE0, 0xA5, 0x88];
static S_3_22: [symbol; 9] = [0xE0, 0xA4, 0xBF, 0xE0, 0xA4, 0xA6, 0xE0, 0xA5, 0x88];
static S_3_23: [symbol; 9] = [0xE0, 0xA5, 0x87, 0xE0, 0xA4, 0x95, 0xE0, 0xA5, 0x8B];
static S_3_24: [symbol; 12] = [0xE0, 0xA4, 0xA8, 0xE0, 0xA5, 0x87, 0xE0, 0xA4, 0x95, 0xE0, 0xA5, 0x8B];
static S_3_25: [symbol; 9] = [0xE0, 0xA4, 0x8F, 0xE0, 0xA4, 0x95, 0xE0, 0xA5, 0x8B];
static S_3_26: [symbol; 12] = [0xE0, 0xA4, 0x87, 0xE0, 0xA4, 0x8F, 0xE0, 0xA4, 0x95, 0xE0, 0xA5, 0x8B];
static S_3_27: [symbol; 12] = [0xE0, 0xA4, 0xBF, 0xE0, 0xA4, 0x8F, 0xE0, 0xA4, 0x95, 0xE0, 0xA5, 0x8B];
static S_3_28: [symbol; 6] = [0xE0, 0xA4, 0xA6, 0xE0, 0xA5, 0x8B];
static S_3_29: [symbol; 9] = [0xE0, 0xA4, 0x87, 0xE0, 0xA4, 0xA6, 0xE0, 0xA5, 0x8B];
static S_3_30: [symbol; 9] = [0xE0, 0xA4, 0xBF, 0xE0, 0xA4, 0xA6, 0xE0, 0xA5, 0x8B];
static S_3_31: [symbol; 6] = [0xE0, 0xA4, 0xAF, 0xE0, 0xA5, 0x8B];
static S_3_32: [symbol; 9] = [0xE0, 0xA4, 0x87, 0xE0, 0xA4, 0xAF, 0xE0, 0xA5, 0x8B];
static S_3_33: [symbol; 12] = [0xE0, 0xA4, 0xA5, 0xE0, 0xA5, 0x8D, 0xE0, 0xA4, 0xAF, 0xE0, 0xA5, 0x8B];
static S_3_34: [symbol; 9] = [0xE0, 0xA4, 0xAD, 0xE0, 0xA4, 0xAF, 0xE0, 0xA5, 0x8B];
static S_3_35: [symbol; 9] = [0xE0, 0xA4, 0xBF, 0xE0, 0xA4, 0xAF, 0xE0, 0xA5, 0x8B];
static S_3_36: [symbol; 12] = [0xE0, 0xA4, 0xA5, 0xE0, 0xA4, 0xBF, 0xE0, 0xA4, 0xAF, 0xE0, 0xA5, 0x8B];
static S_3_37: [symbol; 12] = [0xE0, 0xA4, 0xA6, 0xE0, 0xA4, 0xBF, 0xE0, 0xA4, 0xAF, 0xE0, 0xA5, 0x8B];
static S_3_38: [symbol; 6] = [0xE0, 0xA4, 0x9B, 0xE0, 0xA5, 0x8C];
static S_3_39: [symbol; 9] = [0xE0, 0xA4, 0x87, 0xE0, 0xA4, 0x9B, 0xE0, 0xA5, 0x8C];
static S_3_40: [symbol; 9] = [0xE0, 0xA5, 0x87, 0xE0, 0xA4, 0x9B, 0xE0, 0xA5, 0x8C];
static S_3_41: [symbol; 12] = [0xE0, 0xA4, 0xA8, 0xE0, 0xA5, 0x87, 0xE0, 0xA4, 0x9B, 0xE0, 0xA5, 0x8C];
static S_3_42: [symbol; 9] = [0xE0, 0xA4, 0x8F, 0xE0, 0xA4, 0x9B, 0xE0, 0xA5, 0x8C];
static S_3_43: [symbol; 9] = [0xE0, 0xA4, 0xBF, 0xE0, 0xA4, 0x9B, 0xE0, 0xA5, 0x8C];
static S_3_44: [symbol; 6] = [0xE0, 0xA4, 0xAF, 0xE0, 0xA5, 0x8C];
static S_3_45: [symbol; 12] = [0xE0, 0xA4, 0x9B, 0xE0, 0xA5, 0x8D, 0xE0, 0xA4, 0xAF, 0xE0, 0xA5, 0x8C];
static S_3_46: [symbol; 12] = [0xE0, 0xA4, 0xA5, 0xE0, 0xA5, 0x8D, 0xE0, 0xA4, 0xAF, 0xE0, 0xA5, 0x8C];
static S_3_47: [symbol; 12] = [0xE0, 0xA4, 0xA5, 0xE0, 0xA4, 0xBF, 0xE0, 0xA4, 0xAF, 0xE0, 0xA5, 0x8C];
static S_3_48: [symbol; 9] = [0xE0, 0xA4, 0x9B, 0xE0, 0xA4, 0xA8, 0xE0, 0xA5, 0x8D];
static S_3_49: [symbol; 12] = [0xE0, 0xA4, 0x87, 0xE0, 0xA4, 0x9B, 0xE0, 0xA4, 0xA8, 0xE0, 0xA5, 0x8D];
static S_3_50: [symbol; 12] = [0xE0, 0xA5, 0x87, 0xE0, 0xA4, 0x9B, 0xE0, 0xA4, 0xA8, 0xE0, 0xA5, 0x8D];
static S_3_51: [symbol; 15] = [0xE0, 0xA4, 0xA8, 0xE0, 0xA5, 0x87, 0xE0, 0xA4, 0x9B, 0xE0, 0xA4, 0xA8, 0xE0, 0xA5, 0x8D];
static S_3_52: [symbol; 12] = [0xE0, 0xA4, 0x8F, 0xE0, 0xA4, 0x9B, 0xE0, 0xA4, 0xA8, 0xE0, 0xA5, 0x8D];
static S_3_53: [symbol; 12] = [0xE0, 0xA4, 0xBF, 0xE0, 0xA4, 0x9B, 0xE0, 0xA4, 0xA8, 0xE0, 0xA5, 0x8D];
static S_3_54: [symbol; 12] = [0xE0, 0xA4, 0xB2, 0xE0, 0xA4, 0xBE, 0xE0, 0xA4, 0xA8, 0xE0, 0xA5, 0x8D];
static S_3_55: [symbol; 12] = [0xE0, 0xA4, 0x9B, 0xE0, 0xA4, 0xBF, 0xE0, 0xA4, 0xA8, 0xE0, 0xA5, 0x8D];
static S_3_56: [symbol; 12] = [0xE0, 0xA4, 0xA5, 0xE0, 0xA4, 0xBF, 0xE0, 0xA4, 0xA8, 0xE0, 0xA5, 0x8D];
static S_3_57: [symbol; 9] = [0xE0, 0xA4, 0xAA, 0xE0, 0xA4, 0xB0, 0xE0, 0xA5, 0x8D];
static S_3_58: [symbol; 9] = [0xE0, 0xA4, 0x87, 0xE0, 0xA4, 0xB8, 0xE0, 0xA5, 0x8D];
static S_3_59: [symbol; 15] = [0xE0, 0xA4, 0xA5, 0xE0, 0xA4, 0xBF, 0xE0, 0xA4, 0x87, 0xE0, 0xA4, 0xB8, 0xE0, 0xA5, 0x8D];
static S_3_60: [symbol; 12] = [0xE0, 0xA4, 0x9B, 0xE0, 0xA5, 0x87, 0xE0, 0xA4, 0xB8, 0xE0, 0xA5, 0x8D];
static S_3_61: [symbol; 12] = [0xE0, 0xA4, 0xB9, 0xE0, 0xA5, 0x8B, 0xE0, 0xA4, 0xB8, 0xE0, 0xA5, 0x8D];
static S_3_62: [symbol; 9] = [0xE0, 0xA4, 0x9B, 0xE0, 0xA4, 0xB8, 0xE0, 0xA5, 0x8D];
static S_3_63: [symbol; 12] = [0xE0, 0xA4, 0x87, 0xE0, 0xA4, 0x9B, 0xE0, 0xA4, 0xB8, 0xE0, 0xA5, 0x8D];
static S_3_64: [symbol; 12] = [0xE0, 0xA5, 0x87, 0xE0, 0xA4, 0x9B, 0xE0, 0xA4, 0xB8, 0xE0, 0xA5, 0x8D];
static S_3_65: [symbol; 15] = [0xE0, 0xA4, 0xA8, 0xE0, 0xA5, 0x87, 0xE0, 0xA4, 0x9B, 0xE0, 0xA4, 0xB8, 0xE0, 0xA5, 0x8D];
static S_3_66: [symbol; 12] = [0xE0, 0xA4, 0x8F, 0xE0, 0xA4, 0x9B, 0xE0, 0xA4, 0xB8, 0xE0, 0xA5, 0x8D];
static S_3_67: [symbol; 12] = [0xE0, 0xA4, 0xBF, 0xE0, 0xA4, 0x9B, 0xE0, 0xA4, 0xB8, 0xE0, 0xA5, 0x8D];
static S_3_68: [symbol; 9] = [0xE0, 0xA4, 0xBF, 0xE0, 0xA4, 0xB8, 0xE0, 0xA5, 0x8D];
static S_3_69: [symbol; 12] = [0xE0, 0xA4, 0xA5, 0xE0, 0xA4, 0xBF, 0xE0, 0xA4, 0xB8, 0xE0, 0xA5, 0x8D];
static S_3_70: [symbol; 9] = [0xE0, 0xA4, 0xA5, 0xE0, 0xA4, 0xBF, 0xE0, 0xA4, 0x8F];
static S_3_71: [symbol; 3] = [0xE0, 0xA4, 0x9B];
static S_3_72: [symbol; 6] = [0xE0, 0xA4, 0x87, 0xE0, 0xA4, 0x9B];
static S_3_73: [symbol; 6] = [0xE0, 0xA5, 0x87, 0xE0, 0xA4, 0x9B];
static S_3_74: [symbol; 9] = [0xE0, 0xA4, 0xA8, 0xE0, 0xA5, 0x87, 0xE0, 0xA4, 0x9B];
static S_3_75: [symbol; 15] = [0xE0, 0xA4, 0xB9, 0xE0, 0xA5, 0x81, 0xE0, 0xA4, 0xA8, 0xE0, 0xA5, 0x87, 0xE0, 0xA4, 0x9B];
static S_3_76: [symbol; 15] = [0xE0, 0xA4, 0xB9, 0xE0, 0xA5, 0x81, 0xE0, 0xA4, 0xA8, 0xE0, 0xA5, 0x8D, 0xE0, 0xA4, 0x9B];
static S_3_77: [symbol; 12] = [0xE0, 0xA4, 0x87, 0xE0, 0xA4, 0xA8, 0xE0, 0xA5, 0x8D, 0xE0, 0xA4, 0x9B];
static S_3_78: [symbol; 12] = [0xE0, 0xA4, 0xBF, 0xE0, 0xA4, 0xA8, 0xE0, 0xA5, 0x8D, 0xE0, 0xA4, 0x9B];
static S_3_79: [symbol; 6] = [0xE0, 0xA4, 0x8F, 0xE0, 0xA4, 0x9B];
static S_3_80: [symbol; 6] = [0xE0, 0xA4, 0xBF, 0xE0, 0xA4, 0x9B];
static S_3_81: [symbol; 9] = [0xE0, 0xA5, 0x87, 0xE0, 0xA4, 0x95, 0xE0, 0xA4, 0xBE];
static S_3_82: [symbol; 12] = [0xE0, 0xA4, 0xA8, 0xE0, 0xA5, 0x87, 0xE0, 0xA4, 0x95, 0xE0, 0xA4, 0xBE];
static S_3_83: [symbol; 9] = [0xE0, 0xA4, 0x8F, 0xE0, 0xA4, 0x95, 0xE0, 0xA4, 0xBE];
static S_3_84: [symbol; 12] = [0xE0, 0xA4, 0x87, 0xE0, 0xA4, 0x8F, 0xE0, 0xA4, 0x95, 0xE0, 0xA4, 0xBE];
static S_3_85: [symbol; 12] = [0xE0, 0xA4, 0xBF, 0xE0, 0xA4, 0x8F, 0xE0, 0xA4, 0x95, 0xE0, 0xA4, 0xBE];
static S_3_86: [symbol; 6] = [0xE0, 0xA4, 0xA6, 0xE0, 0xA4, 0xBE];
static S_3_87: [symbol; 9] = [0xE0, 0xA4, 0x87, 0xE0, 0xA4, 0xA6, 0xE0, 0xA4, 0xBE];
static S_3_88: [symbol; 9] = [0xE0, 0xA4, 0xBF, 0xE0, 0xA4, 0xA6, 0xE0, 0xA4, 0xBE];
static S_3_89: [symbol; 12] = [0xE0, 0xA4, 0xA6, 0xE0, 0xA5, 0x87, 0xE0, 0xA4, 0x96, 0xE0, 0xA4, 0xBF];
static S_3_90: [symbol; 12] = [0xE0, 0xA4, 0xAE, 0xE0, 0xA4, 0xBE, 0xE0, 0xA4, 0xA5, 0xE0, 0xA4, 0xBF];

static A_3: [among; 91] = [
    among { s_size: 9, s: S_3_0.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 9, s: S_3_1.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 12, s: S_3_2.as_ptr(), substring_i: 1, result: 1, function: None },
    among { s_size: 12, s: S_3_3.as_ptr(), substring_i: 1, result: 1, function: None },
    among { s_size: 12, s: S_3_4.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 6, s: S_3_5.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 6, s: S_3_6.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 6, s: S_3_7.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 9, s: S_3_8.as_ptr(), substring_i: 7, result: 1, function: None },
    among { s_size: 12, s: S_3_9.as_ptr(), substring_i: 8, result: 1, function: None },
    among { s_size: 9, s: S_3_10.as_ptr(), substring_i: 7, result: 1, function: None },
    among { s_size: 6, s: S_3_11.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 9, s: S_3_12.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 9, s: S_3_13.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 6, s: S_3_14.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 6, s: S_3_15.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 6, s: S_3_16.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 9, s: S_3_17.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 12, s: S_3_18.as_ptr(), substring_i: 17, result: 1, function: None },
    among { s_size: 9, s: S_3_19.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 6, s: S_3_20.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 9, s: S_3_21.as_ptr(), substring_i: 20, result: 1, function: None },
    among { s_size: 9, s: S_3_22.as_ptr(), substring_i: 20, result: 1, function: None },
    among { s_size: 9, s: S_3_23.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 12, s: S_3_24.as_ptr(), substring_i: 23, result: 1, function: None },
    among { s_size: 9, s: S_3_25.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 12, s: S_3_26.as_ptr(), substring_i: 25, result: 1, function: None },
    among { s_size: 12, s: S_3_27.as_ptr(), substring_i: 25, result: 1, function: None },
    among { s_size: 6, s: S_3_28.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 9, s: S_3_29.as_ptr(), substring_i: 28, result: 1, function: None },
    among { s_size: 9, s: S_3_30.as_ptr(), substring_i: 28, result: 1, function: None },
    among { s_size: 6, s: S_3_31.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 9, s: S_3_32.as_ptr(), substring_i: 31, result: 1, function: None },
    among { s_size: 12, s: S_3_33.as_ptr(), substring_i: 31, result: 1, function: None },
    among { s_size: 9, s: S_3_34.as_ptr(), substring_i: 31, result: 1, function: None },
    among { s_size: 9, s: S_3_35.as_ptr(), substring_i: 31, result: 1, function: None },
    among { s_size: 12, s: S_3_36.as_ptr(), substring_i: 35, result: 1, function: None },
    among { s_size: 12, s: S_3_37.as_ptr(), substring_i: 35, result: 1, function: None },
    among { s_size: 6, s: S_3_38.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 9, s: S_3_39.as_ptr(), substring_i: 38, result: 1, function: None },
    among { s_size: 9, s: S_3_40.as_ptr(), substring_i: 38, result: 1, function: None },
    among { s_size: 12, s: S_3_41.as_ptr(), substring_i: 40, result: 1, function: None },
    among { s_size: 9, s: S_3_42.as_ptr(), substring_i: 38, result: 1, function: None },
    among { s_size: 9, s: S_3_43.as_ptr(), substring_i: 38, result: 1, function: None },
    among { s_size: 6, s: S_3_44.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 12, s: S_3_45.as_ptr(), substring_i: 44, result: 1, function: None },
    among { s_size: 12, s: S_3_46.as_ptr(), substring_i: 44, result: 1, function: None },
    among { s_size: 12, s: S_3_47.as_ptr(), substring_i: 44, result: 1, function: None },
    among { s_size: 9, s: S_3_48.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 12, s: S_3_49.as_ptr(), substring_i: 48, result: 1, function: None },
    among { s_size: 12, s: S_3_50.as_ptr(), substring_i: 48, result: 1, function: None },
    among { s_size: 15, s: S_3_51.as_ptr(), substring_i: 50, result: 1, function: None },
    among { s_size: 12, s: S_3_52.as_ptr(), substring_i: 48, result: 1, function: None },
    among { s_size: 12, s: S_3_53.as_ptr(), substring_i: 48, result: 1, function: None },
    among { s_size: 12, s: S_3_54.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 12, s: S_3_55.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 12, s: S_3_56.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 9, s: S_3_57.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 9, s: S_3_58.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 15, s: S_3_59.as_ptr(), substring_i: 58, result: 1, function: None },
    among { s_size: 12, s: S_3_60.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 12, s: S_3_61.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 9, s: S_3_62.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 12, s: S_3_63.as_ptr(), substring_i: 62, result: 1, function: None },
    among { s_size: 12, s: S_3_64.as_ptr(), substring_i: 62, result: 1, function: None },
    among { s_size: 15, s: S_3_65.as_ptr(), substring_i: 64, result: 1, function: None },
    among { s_size: 12, s: S_3_66.as_ptr(), substring_i: 62, result: 1, function: None },
    among { s_size: 12, s: S_3_67.as_ptr(), substring_i: 62, result: 1, function: None },
    among { s_size: 9, s: S_3_68.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 12, s: S_3_69.as_ptr(), substring_i: 68, result: 1, function: None },
    among { s_size: 9, s: S_3_70.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 3, s: S_3_71.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 6, s: S_3_72.as_ptr(), substring_i: 71, result: 1, function: None },
    among { s_size: 6, s: S_3_73.as_ptr(), substring_i: 71, result: 1, function: None },
    among { s_size: 9, s: S_3_74.as_ptr(), substring_i: 73, result: 1, function: None },
    among { s_size: 15, s: S_3_75.as_ptr(), substring_i: 74, result: 1, function: None },
    among { s_size: 15, s: S_3_76.as_ptr(), substring_i: 71, result: 1, function: None },
    among { s_size: 12, s: S_3_77.as_ptr(), substring_i: 71, result: 1, function: None },
    among { s_size: 12, s: S_3_78.as_ptr(), substring_i: 71, result: 1, function: None },
    among { s_size: 6, s: S_3_79.as_ptr(), substring_i: 71, result: 1, function: None },
    among { s_size: 6, s: S_3_80.as_ptr(), substring_i: 71, result: 1, function: None },
    among { s_size: 9, s: S_3_81.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 12, s: S_3_82.as_ptr(), substring_i: 81, result: 1, function: None },
    among { s_size: 9, s: S_3_83.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 12, s: S_3_84.as_ptr(), substring_i: 83, result: 1, function: None },
    among { s_size: 12, s: S_3_85.as_ptr(), substring_i: 83, result: 1, function: None },
    among { s_size: 6, s: S_3_86.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 9, s: S_3_87.as_ptr(), substring_i: 86, result: 1, function: None },
    among { s_size: 9, s: S_3_88.as_ptr(), substring_i: 86, result: 1, function: None },
    among { s_size: 12, s: S_3_89.as_ptr(), substring_i: -1, result: 1, function: None },
    among { s_size: 12, s: S_3_90.as_ptr(), substring_i: -1, result: 1, function: None },
];

static S_0: [symbol; 3] = [0xE0, 0xA4, 0x8F];
static S_1: [symbol; 3] = [0xE0, 0xA5, 0x87];
static S_2: [symbol; 6] = [0xE0, 0xA4, 0xAF, 0xE0, 0xA5, 0x8C];
static S_3: [symbol; 6] = [0xE0, 0xA4, 0x9B, 0xE0, 0xA5, 0x8C];
static S_4: [symbol; 6] = [0xE0, 0xA4, 0xA8, 0xE0, 0xA5, 0x8C];
static S_5: [symbol; 6] = [0xE0, 0xA4, 0xA5, 0xE0, 0xA5, 0x87];
static S_6: [symbol; 9] = [0xE0, 0xA4, 0xA4, 0xE0, 0xA5, 0x8D, 0xE0, 0xA4, 0xB0];

unsafe fn r_remove_category_1(z: *mut SN_env) -> c_int {
    let among_var: c_int;
    (*z).ket = (*z).c;
    among_var = find_among_b(z, A_0.as_ptr(), 17);
    if among_var == 0 { return 0; }
    (*z).bra = (*z).c;
    match among_var {
        1 => {
            let ret = slice_del(z);
            if ret < 0 { return ret; }
        }
        2 => {
            'lab0: {
                let m1 = (*z).l - (*z).c; let _ = m1;
                'lab1: {
                    let m2 = (*z).l - (*z).c; let _ = m2;
                    'lab2: {
                        'lab3: {
                            if !(eq_s_b(z, 3, S_0.as_ptr()) != 0) { break 'lab3; }
                            break 'lab2;
                        }
                        // lab3:
                        (*z).c = (*z).l - m2;
                        if !(eq_s_b(z, 3, S_1.as_ptr()) != 0) { break 'lab1; }
                    }
                    // lab2:
                    break 'lab0;
                }
                // lab1:
                (*z).c = (*z).l - m1;
                let ret = slice_del(z);
                if ret < 0 { return ret; }
            }
            // lab0:
        }
        _ => {}
    }
    1
}

unsafe fn r_check_category_2(z: *mut SN_env) -> c_int {
    (*z).ket = (*z).c;
    if (*z).c - 2 <= (*z).lb
        || (*(*z).p.offset(((*z).c - 1) as isize) as c_int) >> 5 != 4
        || ((262 >> (*(*z).p.offset(((*z).c - 1) as isize) as c_int & 0x1f)) & 1) == 0
    {
        return 0;
    }
    if find_among_b(z, A_1.as_ptr(), 3) == 0 { return 0; }
    (*z).bra = (*z).c;
    1
}

unsafe fn r_remove_category_2(z: *mut SN_env) -> c_int {
    let among_var: c_int;
    (*z).ket = (*z).c;
    if (*z).c - 2 <= (*z).lb
        || (*(*z).p.offset(((*z).c - 1) as isize) as c_int) >> 5 != 4
        || ((262 >> (*(*z).p.offset(((*z).c - 1) as isize) as c_int & 0x1f)) & 1) == 0
    {
        return 0;
    }
    among_var = find_among_b(z, A_2.as_ptr(), 3);
    if among_var == 0 { return 0; }
    (*z).bra = (*z).c;
    match among_var {
        1 => {
            'lab0: {
                let m1 = (*z).l - (*z).c; let _ = m1;
                'lab1: {
                    if !(eq_s_b(z, 6, S_2.as_ptr()) != 0) { break 'lab1; }
                    break 'lab0;
                }
                // lab1:
                (*z).c = (*z).l - m1;
                'lab2: {
                    if !(eq_s_b(z, 6, S_3.as_ptr()) != 0) { break 'lab2; }
                    break 'lab0;
                }
                // lab2:
                (*z).c = (*z).l - m1;
                'lab3: {
                    if !(eq_s_b(z, 6, S_4.as_ptr()) != 0) { break 'lab3; }
                    break 'lab0;
                }
                // lab3:
                (*z).c = (*z).l - m1;
                if !(eq_s_b(z, 6, S_5.as_ptr()) != 0) { return 0; }
            }
            // lab0:
            let ret = slice_del(z);
            if ret < 0 { return ret; }
        }
        2 => {
            if !(eq_s_b(z, 9, S_6.as_ptr()) != 0) { return 0; }
            let ret = slice_del(z);
            if ret < 0 { return ret; }
        }
        _ => {}
    }
    1
}

unsafe fn r_remove_category_3(z: *mut SN_env) -> c_int {
    (*z).ket = (*z).c;
    if find_among_b(z, A_3.as_ptr(), 91) == 0 { return 0; }
    (*z).bra = (*z).c;
    let ret = slice_del(z);
    if ret < 0 { return ret; }
    1
}

#[no_mangle]
pub unsafe extern "C" fn nepali_UTF_8_stem(z: *mut SN_env) -> c_int {
    (*z).lb = (*z).c; (*z).c = (*z).l;

    {
        let m1 = (*z).l - (*z).c; let _ = m1;
        let ret = r_remove_category_1(z);
        if ret < 0 { return ret; }
        (*z).c = (*z).l - m1;
    }
    {
        let m2 = (*z).l - (*z).c; let _ = m2;
        'mark: loop {
            let m3 = (*z).l - (*z).c; let _ = m3;
            {
                let m4 = (*z).l - (*z).c; let _ = m4;
                'lab2: {
                    let m5 = (*z).l - (*z).c; let _ = m5;
                    let ret = r_check_category_2(z);
                    if ret == 0 { break 'lab2; }
                    if ret < 0 { return ret; }
                    (*z).c = (*z).l - m5;
                    let ret = r_remove_category_2(z);
                    if ret == 0 { break 'lab2; }
                    if ret < 0 { return ret; }
                }
                // lab2:
                (*z).c = (*z).l - m4;
            }
            'lab1: {
                let ret = r_remove_category_3(z);
                if ret == 0 { break 'lab1; }
                if ret < 0 { return ret; }
                continue 'mark;
            }
            // lab1:
            (*z).c = (*z).l - m3;
            break;
        }
        (*z).c = (*z).l - m2;
    }
    (*z).c = (*z).lb;
    1
}

#[no_mangle]
pub unsafe extern "C" fn nepali_UTF_8_create_env() -> *mut SN_env {
    SN_create_env(0, 0)
}

#[no_mangle]
pub unsafe extern "C" fn nepali_UTF_8_close_env(z: *mut SN_env) {
    SN_close_env(z, 0);
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::snowball::api::{SIZE, SN_set_current};

    unsafe fn stem(word: &[u8]) -> Vec<u8> {
        let z = nepali_UTF_8_create_env();
        SN_set_current(z, word.len() as c_int, word.as_ptr());
        let rc = nepali_UTF_8_stem(z);
        assert!(rc >= 0);
        let out = std::slice::from_raw_parts((*z).p, SIZE((*z).p) as usize).to_vec();
        nepali_UTF_8_close_env(z);
        out
    }

    // Short root word (Devanagari "ghar" = house) should pass through unchanged:
    // no suffix in any category matches.
    #[test]
    fn short_root_unchanged() {
        let word: &[u8] = b"\xE0\xA4\x98\xE0\xA4\xB0"; // U+0918 U+0930
        unsafe {
            let out = stem(word);
            assert_eq!(out, word.to_vec());
            assert!(!out.is_empty());
        }
    }

    // Idempotence: stem(stem(w)) == stem(w) on a longer inflected word.
    // "ramako" = ram + genitive suffix ko (U+0915 U+094B).
    #[test]
    fn idempotent() {
        let word: &[u8] = b"\xE0\xA4\xB0\xE0\xA4\xBE\xE0\xA4\xAE\xE0\xA4\x95\xE0\xA5\x8B";
        unsafe {
            let once = stem(word);
            assert!(!once.is_empty());
            let twice = stem(&once);
            assert_eq!(once, twice);
        }
    }
}
