//! src/backend/backup/basebackup_incremental.c
//!
//! code for incremental backup support
//!
//! This code isn't actually in charge of taking an incremental backup;
//! the actual construction of the incremental backup happens in
//! basebackup.c. Here, we're concerned with providing the necessary
//! supports for that operation. In particular, we need to parse the
//! backup manifest supplied by the user taking the incremental backup
//! and extract the required information from it.
//!
//! Portions Copyright (c) 2010-2025, PostgreSQL Global Development Group
//!
//! IDENTIFICATION
//!   src/backend/backup/basebackup_incremental.c
//!
//! API for incremental backup support (basebackup_incremental.h)
//!   src/include/backup/basebackup_incremental.h

use crate::prelude::*;

use std::ffi::{c_char, c_int, c_void};

use crate::c::{uint32, uint64, uint8, Size};
use crate::postgres_ext::Oid;
use crate::storage::block::BlockNumber;
use crate::access::transam::xlogdefs::XLogRecPtr;
use crate::nodes::pg_list::{List, ListCell};
use crate::{foreach, current_cell};

// ---------------------------------------------------------------------------
// Constants from basebackup_incremental.h
// ---------------------------------------------------------------------------

pub const INCREMENTAL_MAGIC: u32 = 0xd3ae1f0d;

#[repr(C)]
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum FileBackupMethod {
    BACK_UP_FILE_FULLY,
    BACK_UP_FILE_INCREMENTALLY,
}
pub use FileBackupMethod::*;

const BLOCKS_PER_READ: usize = 512;

/*
 * We expect to find the last lines of the manifest, including the checksum,
 * in the last MIN_CHUNK bytes of the manifest. We trigger an incremental
 * parse step if we are about to overflow MAX_CHUNK bytes.
 */
const MIN_CHUNK: usize = 1024;
const MAX_CHUNK: usize = 128 * 1024;

// ---------------------------------------------------------------------------
// Stub types for dependencies not yet ported.
// ---------------------------------------------------------------------------

pub type TimeLineID = uint32;
pub type RelFileNumber = Oid;
pub type ForkNumber = c_int;
pub type pg_checksum_type = c_int;
pub type MemoryContext = *mut c_void;
pub type StringInfo = *mut StringInfoData;

#[repr(C)]
pub struct StringInfoData {
    pub data: *mut c_char,
    pub len: c_int,
    pub maxlen: c_int,
    pub cursor: c_int,
}

#[repr(C)]
pub struct RelFileLocator {
    pub spcOid: Oid,
    pub dbOid: Oid,
    pub relNumber: RelFileNumber,
}

#[repr(C)]
pub struct RelPathStr {
    pub str: [c_char; 1],
}

#[repr(C)]
pub struct BackupState {
    pub starttli: TimeLineID,
    pub startpoint: XLogRecPtr,
    pub istartpoint: XLogRecPtr,
    pub istarttli: TimeLineID,
}

#[repr(C)]
pub struct TimeLineHistoryEntry {
    pub tli: TimeLineID,
    pub begin: XLogRecPtr,
    pub end: XLogRecPtr,
}

pub enum BlockRefTable {}
pub enum BlockRefTableEntry {}
pub enum BlockRefTableReader {}
pub enum JsonManifestParseIncrementalState {}

#[repr(C)]
pub struct JsonManifestParseContext {
    pub private_data: *mut c_void,
    pub version_cb: Option<unsafe extern "C" fn(*mut JsonManifestParseContext, c_int)>,
    pub system_identifier_cb: Option<unsafe extern "C" fn(*mut JsonManifestParseContext, uint64)>,
    pub per_file_cb: Option<
        unsafe extern "C" fn(
            *mut JsonManifestParseContext,
            *const c_char,
            uint64,
            pg_checksum_type,
            c_int,
            *mut uint8,
        ),
    >,
    pub per_wal_range_cb: Option<
        unsafe extern "C" fn(
            *mut JsonManifestParseContext,
            TimeLineID,
            XLogRecPtr,
            XLogRecPtr,
        ),
    >,
    pub error_cb: Option<unsafe extern "C" fn(*mut JsonManifestParseContext, *const c_char)>,
}

/* File handle type used by the WAL summary I/O routines. */
pub type File = c_int;

#[repr(C)]
pub struct WalSummaryFile {
    pub _dummy: c_int,
}

#[repr(C)]
pub struct WalSummaryIO {
    pub file: File,
    pub filepos: i64,
}

// ---------------------------------------------------------------------------
// Details extracted from the WAL ranges present in the supplied backup manifest.
// ---------------------------------------------------------------------------

#[repr(C)]
struct backup_wal_range {
    tli: TimeLineID,
    start_lsn: XLogRecPtr,
    end_lsn: XLogRecPtr,
}

/*
 * Details extracted from the file list present in the supplied backup manifest.
 */
#[repr(C)]
struct backup_file_entry {
    status: uint32,
    path: *const c_char,
    size: uint64,
}

/*
 * simplehash-based hash table mapping file path -> backup_file_entry.
 * (Generated by lib/simplehash.h with SH_PREFIX = backup_file.)
 */
#[repr(C)]
pub struct backup_file_hash {
    pub ctx: MemoryContext,
    _opaque: [u8; 0],
}

pub struct IncrementalBackupInfo {
    /* Memory context for this object and its subsidiary objects. */
    mcxt: MemoryContext,

    /* Temporary buffer for storing the manifest while parsing it. */
    buf: StringInfoData,

    /* WAL ranges extracted from the backup manifest. */
    manifest_wal_ranges: *mut List,

    /*
     * Files extracted from the backup manifest.
     *
     * We don't really need this information, because we use WAL summaries to
     * figure out what's changed. It would be unsafe to just rely on the list
     * of files that existed before, because it's possible for a file to be
     * removed and a new one created with the same name and different
     * contents. In such cases, the whole file must still be sent. We can tell
     * from the WAL summaries whether that happened, but not from the file
     * list.
     *
     * Nonetheless, this data is useful for sanity checking. If a file that we
     * think we shouldn't need to send is not present in the manifest for the
     * prior backup, something has gone terribly wrong. We retain the file
     * names and sizes, but not the checksums or last modified times, for
     * which we have no use.
     *
     * One significant downside of storing this data is that it consumes
     * memory. If that turns out to be a problem, we might have to decide not
     * to retain this information, or to make it optional.
     */
    manifest_files: *mut backup_file_hash,

    /*
     * Block-reference table for the incremental backup.
     *
     * It's possible that storing the entire block-reference table in memory
     * will be a problem for some users. The in-memory format that we're using
     * here is pretty efficient, converging to little more than 1 bit per
     * block for relation forks with large numbers of modified blocks. It's
     * possible, however, that if you try to perform an incremental backup of
     * a database with a sufficiently large number of relations on a
     * sufficiently small machine, you could run out of memory here. If that
     * turns out to be a problem in practice, we'll need to be more clever.
     */
    brtab: *mut BlockRefTable,

    /*
     * State object for incremental JSON parsing
     */
    inc_state: *mut JsonManifestParseIncrementalState,
}

// ---------------------------------------------------------------------------
// Local stubs for unported helper functions and constants.
// ---------------------------------------------------------------------------

const InvalidXLogRecPtr: XLogRecPtr = 0;
const NIL: *mut List = std::ptr::null_mut();

// BLCKSZ / RELSEG_SIZE come from pg_config.h
const BLCKSZ: usize = 8192;
const RELSEG_SIZE: u32 = 131072;

// Fork numbers from common/relpath.h
const MAIN_FORKNUM: ForkNumber = 0;
const FSM_FORKNUM: ForkNumber = 1;

// Invalid proc number from storage/procnumber.h
const INVALID_PROC_NUMBER: c_int = -1;

#[inline]
unsafe fn OidIsValid(oid: Oid) -> bool {
    oid != crate::postgres_ext::InvalidOid
}

#[inline]
unsafe fn RelFileNumberIsValid(relnumber: RelFileNumber) -> bool {
    relnumber != crate::postgres_ext::InvalidOid
}

#[inline]
unsafe fn BlockNumberIsValid(blockNumber: BlockNumber) -> bool {
    blockNumber != crate::storage::block::InvalidBlockNumber
}

#[inline]
unsafe fn XLogRecPtrIsInvalid(r: XLogRecPtr) -> bool {
    r == 0
}

unsafe fn list_length(list: *const List) -> c_int {
    unimplemented!() // TODO: nodes/list.c
}

unsafe fn list_nth(list: *const List, n: c_int) -> *mut c_void {
    unimplemented!() // TODO: nodes/list.c
}

unsafe fn lappend(list: *mut List, datum: *mut c_void) -> *mut List {
    unimplemented!() // TODO: nodes/list.c
}

unsafe fn list_concat(list1: *mut List, list2: *const List) -> *mut List {
    unimplemented!() // TODO: nodes/list.c
}

unsafe fn lfirst(lc: *const ListCell) -> *mut c_void {
    unimplemented!() // TODO: nodes/pg_list.h
}

unsafe fn initStringInfo(str: StringInfo) {
    unimplemented!() // TODO: lib/stringinfo.c
}

unsafe fn appendBinaryStringInfo(str: StringInfo, data: *const c_char, datalen: c_int) {
    unimplemented!() // TODO: lib/stringinfo.c
}

unsafe fn appendStringInfoVA(str: StringInfo, fmt: *const c_char, args: *mut c_void) -> c_int {
    unimplemented!() // TODO: lib/stringinfo.c
}

unsafe fn enlargeStringInfo(str: StringInfo, needed: c_int) {
    unimplemented!() // TODO: lib/stringinfo.c
}

unsafe fn backup_file_create(
    ctx: MemoryContext,
    nelements: uint32,
    private_data: *mut c_void,
) -> *mut backup_file_hash {
    unimplemented!() // TODO: lib/simplehash.h
}

unsafe fn backup_file_lookup(
    tb: *mut backup_file_hash,
    key: *const c_char,
) -> *mut backup_file_entry {
    unimplemented!() // TODO: lib/simplehash.h
}

unsafe fn backup_file_insert(
    tb: *mut backup_file_hash,
    key: *const c_char,
    found: *mut bool,
) -> *mut backup_file_entry {
    unimplemented!() // TODO: lib/simplehash.h
}

unsafe fn json_parse_manifest_incremental_init(
    context: *mut JsonManifestParseContext,
) -> *mut JsonManifestParseIncrementalState {
    unimplemented!() // TODO: common/parse_manifest.c
}

unsafe fn json_parse_manifest_incremental_chunk(
    incstate: *mut JsonManifestParseIncrementalState,
    chunk: *const c_char,
    size: c_int,
    is_last: bool,
) {
    unimplemented!() // TODO: common/parse_manifest.c
}

unsafe fn json_parse_manifest_incremental_shutdown(
    incstate: *mut JsonManifestParseIncrementalState,
) {
    unimplemented!() // TODO: common/parse_manifest.c
}

unsafe fn readTimeLineHistory(targetTLI: TimeLineID) -> *mut List {
    unimplemented!() // TODO: access/timeline.c
}

unsafe fn WaitForWalSummarization(lsn: XLogRecPtr) {
    unimplemented!() // TODO: postmaster/walsummarizer.c
}

unsafe fn GetSystemIdentifier() -> uint64 {
    unimplemented!() // TODO: access/xlog.c
}

unsafe fn GetWalSummaries(tli: TimeLineID, start_lsn: XLogRecPtr, end_lsn: XLogRecPtr) -> *mut List {
    unimplemented!() // TODO: backup/walsummary.c
}

unsafe fn FilterWalSummaries(
    wslist: *mut List,
    tli: TimeLineID,
    start_lsn: XLogRecPtr,
    end_lsn: XLogRecPtr,
) -> *mut List {
    unimplemented!() // TODO: backup/walsummary.c
}

unsafe fn WalSummariesAreComplete(
    wslist: *mut List,
    start_lsn: XLogRecPtr,
    end_lsn: XLogRecPtr,
    missing_lsn: *mut XLogRecPtr,
) -> bool {
    unimplemented!() // TODO: backup/walsummary.c
}

unsafe fn OpenWalSummaryFile(ws: *mut WalSummaryFile, missing_ok: bool) -> File {
    unimplemented!() // TODO: backup/walsummary.c
}

unsafe fn ReadWalSummary(
    wsio: *mut c_void,
    data: *mut c_void,
    length: c_int,
) -> c_int {
    unimplemented!() // TODO: backup/walsummary.c
}

unsafe fn ReportWalSummaryError(callback_arg: *mut c_void, fmt: *const c_char) {
    unimplemented!() // TODO: backup/walsummary.c
}

unsafe fn FilePathName(file: File) -> *mut c_char {
    unimplemented!() // TODO: storage/file/fd.c
}

unsafe fn FileClose(file: File) {
    unimplemented!() // TODO: storage/file/fd.c
}

unsafe fn CreateEmptyBlockRefTable() -> *mut BlockRefTable {
    unimplemented!() // TODO: common/blkreftable.c
}

unsafe fn BlockRefTableSetLimitBlock(
    brtab: *mut BlockRefTable,
    rlocator: *const RelFileLocator,
    forknum: ForkNumber,
    limit_block: BlockNumber,
) {
    unimplemented!() // TODO: common/blkreftable.c
}

unsafe fn BlockRefTableMarkBlockModified(
    brtab: *mut BlockRefTable,
    rlocator: *const RelFileLocator,
    forknum: ForkNumber,
    blknum: BlockNumber,
) {
    unimplemented!() // TODO: common/blkreftable.c
}

unsafe fn BlockRefTableGetEntry(
    brtab: *mut BlockRefTable,
    rlocator: *const RelFileLocator,
    forknum: ForkNumber,
    limit_block: *mut BlockNumber,
) -> *mut BlockRefTableEntry {
    unimplemented!() // TODO: common/blkreftable.c
}

unsafe fn BlockRefTableEntryGetBlocks(
    entry: *mut BlockRefTableEntry,
    start_blkno: BlockNumber,
    stop_blkno: BlockNumber,
    blocks: *mut BlockNumber,
    nblocks: c_int,
) -> c_int {
    unimplemented!() // TODO: common/blkreftable.c
}

unsafe fn CreateBlockRefTableReader(
    read_callback: unsafe fn(*mut c_void, *mut c_void, c_int) -> c_int,
    read_callback_arg: *mut c_void,
    error_filename: *mut c_char,
    error_callback: unsafe fn(*mut c_void, *const c_char),
    error_callback_arg: *mut c_void,
) -> *mut BlockRefTableReader {
    unimplemented!() // TODO: common/blkreftable.c
}

unsafe fn BlockRefTableReaderNextRelation(
    reader: *mut BlockRefTableReader,
    rlocator: *mut RelFileLocator,
    forknum: *mut ForkNumber,
    limit_block: *mut BlockNumber,
) -> bool {
    unimplemented!() // TODO: common/blkreftable.c
}

unsafe fn BlockRefTableReaderGetBlocks(
    reader: *mut BlockRefTableReader,
    blocks: *mut BlockNumber,
    nblocks: c_int,
) -> c_uint {
    unimplemented!() // TODO: common/blkreftable.c
}

unsafe fn DestroyBlockRefTableReader(reader: *mut BlockRefTableReader) {
    unimplemented!() // TODO: common/blkreftable.c
}

unsafe fn GetRelationPath(
    dbOid: Oid,
    spcOid: Oid,
    relNumber: RelFileNumber,
    procNumber: c_int,
    forknum: ForkNumber,
) -> RelPathStr {
    unimplemented!() // TODO: common/relpath.c
}

unsafe fn MemoryContextStrdup(context: MemoryContext, string: *const c_char) -> *mut c_char {
    unimplemented!() // TODO: utils/mmgr/mcxt.c
}

unsafe fn hash_bytes(k: *const c_uchar, keylen: c_int) -> uint32 {
    unimplemented!() // TODO: common/hashfn.c
}

#[inline]
unsafe fn pg_cmp_u32(a: uint32, b: uint32) -> c_int {
    /* common/int.h */
    (a > b) as c_int - (a < b) as c_int
}

use std::ffi::{c_uchar, c_uint};

extern "C" {
    fn strlen(s: *const c_char) -> usize;
    fn strcmp(a: *const c_char, b: *const c_char) -> c_int;
    fn strrchr(s: *const c_char, c: c_int) -> *mut c_char;
    fn memmove(dest: *mut c_void, src: *const c_void, n: usize) -> *mut c_void;
    fn qsort(
        base: *mut c_void,
        nmemb: usize,
        size: usize,
        compar: unsafe extern "C" fn(*const c_void, *const c_void) -> c_int,
    );
    fn psprintf(fmt: *const c_char, ...) -> *mut c_char;
}

// ---------------------------------------------------------------------------
// Functions
// ---------------------------------------------------------------------------

/*
 * Create a new object for storing information extracted from the manifest
 * supplied when creating an incremental backup.
 */
pub unsafe fn CreateIncrementalBackupInfo(mcxt: MemoryContext) -> *mut IncrementalBackupInfo {
    let ib: *mut IncrementalBackupInfo;
    let oldcontext: MemoryContext;
    let context: *mut JsonManifestParseContext;

    oldcontext = MemoryContextSwitchTo(mcxt as crate::utils::palloc::MemoryContext) as MemoryContext;

    ib = palloc0(std::mem::size_of::<IncrementalBackupInfo>()) as *mut IncrementalBackupInfo;
    (*ib).mcxt = mcxt;
    initStringInfo(&mut (*ib).buf);

    /*
     * It's hard to guess how many files a "typical" installation will have in
     * the data directory, but a fresh initdb creates almost 1000 files as of
     * this writing, so it seems to make sense for our estimate to
     * substantially higher.
     */
    (*ib).manifest_files = backup_file_create(mcxt, 10000, std::ptr::null_mut());

    context =
        palloc0(std::mem::size_of::<JsonManifestParseContext>()) as *mut JsonManifestParseContext;
    /* Parse the manifest. */
    (*context).private_data = ib as *mut c_void;
    (*context).version_cb = Some(manifest_process_version);
    (*context).system_identifier_cb = Some(manifest_process_system_identifier);
    (*context).per_file_cb = Some(manifest_process_file);
    (*context).per_wal_range_cb = Some(manifest_process_wal_range);
    (*context).error_cb = Some(manifest_report_error);

    (*ib).inc_state = json_parse_manifest_incremental_init(context);

    MemoryContextSwitchTo(oldcontext as crate::utils::palloc::MemoryContext);

    ib
}

/*
 * Before taking an incremental backup, the caller must supply the backup
 * manifest from a prior backup. Each chunk of manifest data received
 * from the client should be passed to this function.
 */
pub unsafe fn AppendIncrementalManifestData(
    ib: *mut IncrementalBackupInfo,
    data: *const c_char,
    len: c_int,
) {
    let oldcontext: MemoryContext;

    /* Switch to our memory context. */
    oldcontext =
        MemoryContextSwitchTo((*ib).mcxt as crate::utils::palloc::MemoryContext) as MemoryContext;

    if (*ib).buf.len > MIN_CHUNK as c_int && (*ib).buf.len + len > MAX_CHUNK as c_int {
        /*
         * time for an incremental parse. We'll do all but the last MIN_CHUNK
         * so that we have enough left for the final piece.
         */
        json_parse_manifest_incremental_chunk(
            (*ib).inc_state,
            (*ib).buf.data,
            (*ib).buf.len - MIN_CHUNK as c_int,
            false,
        );
        /* now remove what we just parsed  */
        memmove(
            (*ib).buf.data as *mut c_void,
            (*ib).buf.data.add(((*ib).buf.len - MIN_CHUNK as c_int) as usize) as *const c_void,
            MIN_CHUNK + 1,
        );
        (*ib).buf.len = MIN_CHUNK as c_int;
    }

    appendBinaryStringInfo(&mut (*ib).buf, data, len);

    /* Switch back to previous memory context. */
    MemoryContextSwitchTo(oldcontext as crate::utils::palloc::MemoryContext);
}

/*
 * Finalize an IncrementalBackupInfo object after all manifest data has
 * been supplied via calls to AppendIncrementalManifestData.
 */
pub unsafe fn FinalizeIncrementalManifest(ib: *mut IncrementalBackupInfo) {
    let oldcontext: MemoryContext;

    /* Switch to our memory context. */
    oldcontext =
        MemoryContextSwitchTo((*ib).mcxt as crate::utils::palloc::MemoryContext) as MemoryContext;

    /* Parse the last chunk of the manifest */
    json_parse_manifest_incremental_chunk((*ib).inc_state, (*ib).buf.data, (*ib).buf.len, true);

    /* Done with the buffer, so release memory. */
    pfree((*ib).buf.data as *mut c_void);
    (*ib).buf.data = std::ptr::null_mut();

    /* Done with inc_state, so release that memory too */
    json_parse_manifest_incremental_shutdown((*ib).inc_state);

    /* Switch back to previous memory context. */
    MemoryContextSwitchTo(oldcontext as crate::utils::palloc::MemoryContext);
}

/*
 * Prepare to take an incremental backup.
 *
 * Before this function is called, AppendIncrementalManifestData and
 * FinalizeIncrementalManifest should have already been called to pass all
 * the manifest data to this object.
 *
 * This function performs sanity checks on the data extracted from the
 * manifest and figures out for which WAL ranges we need summaries, and
 * whether those summaries are available. Then, it reads and combines the
 * data from those summary files. It also updates the backup_state with the
 * reference TLI and LSN for the prior backup.
 */
pub unsafe fn PrepareForIncrementalBackup(
    ib: *mut IncrementalBackupInfo,
    backup_state: *mut BackupState,
) {
    let oldcontext: MemoryContext;
    let expectedTLEs: *mut List;
    let all_wslist: *mut List;
    let mut required_wslist: *mut List = NIL;
    let tlep: *mut *mut TimeLineHistoryEntry;
    let num_wal_ranges: c_int;
    let mut i: c_int;
    let mut found_backup_start_tli: bool = false;
    let mut earliest_wal_range_tli: TimeLineID = 0;
    let mut earliest_wal_range_start_lsn: XLogRecPtr = InvalidXLogRecPtr;
    let mut latest_wal_range_tli: TimeLineID = 0;

    Assert!((*ib).buf.data.is_null());

    /* Switch to our memory context. */
    oldcontext =
        MemoryContextSwitchTo((*ib).mcxt as crate::utils::palloc::MemoryContext) as MemoryContext;

    /*
     * A valid backup manifest must always contain at least one WAL range
     * (usually exactly one, unless the backup spanned a timeline switch).
     */
    num_wal_ranges = list_length((*ib).manifest_wal_ranges);
    if num_wal_ranges == 0 {
        ereport!(ERROR, "manifest contains no required WAL ranges");
        unreachable!();
    }

    /*
     * Match up the TLIs that appear in the WAL ranges of the backup manifest
     * with those that appear in this server's timeline history. We expect
     * every backup_wal_range to match to a TimeLineHistoryEntry; if it does
     * not, that's an error.
     *
     * This loop also decides which of the WAL ranges is the manifest is most
     * ancient and which one is the newest, according to the timeline history
     * of this server, and stores TLIs of those WAL ranges into
     * earliest_wal_range_tli and latest_wal_range_tli. It also updates
     * earliest_wal_range_start_lsn to the start LSN of the WAL range for
     * earliest_wal_range_tli.
     *
     * Note that the return value of readTimeLineHistory puts the latest
     * timeline at the beginning of the list, not the end. Hence, the earliest
     * TLI is the one that occurs nearest the end of the list returned by
     * readTimeLineHistory, and the latest TLI is the one that occurs closest
     * to the beginning.
     */
    expectedTLEs = readTimeLineHistory((*backup_state).starttli);
    tlep = palloc0(num_wal_ranges as usize * std::mem::size_of::<*mut TimeLineHistoryEntry>())
        as *mut *mut TimeLineHistoryEntry;
    i = 0;
    while i < num_wal_ranges {
        let range = list_nth((*ib).manifest_wal_ranges, i) as *mut backup_wal_range;
        let mut saw_earliest_wal_range_tli: bool = false;
        let mut saw_latest_wal_range_tli: bool = false;

        /* Search this server's history for this WAL range's TLI. */
        foreach!(lc, expectedTLEs, {
            let tle = lfirst(current_cell!(lc)) as *mut TimeLineHistoryEntry;

            if (*tle).tli == (*range).tli {
                *tlep.add(i as usize) = tle;
                break;
            }

            if (*tle).tli == earliest_wal_range_tli {
                saw_earliest_wal_range_tli = true;
            }
            if (*tle).tli == latest_wal_range_tli {
                saw_latest_wal_range_tli = true;
            }
        });

        /*
         * An incremental backup can only be taken relative to a backup that
         * represents a previous state of this server. If the backup requires
         * WAL from a timeline that's not in our history, that definitely
         * isn't the case.
         */
        if (*tlep.add(i as usize)).is_null() {
            elog!(
                ERROR,
                "timeline {} found in manifest, but not in this server's history",
                (*range).tli
            );
            unreachable!();
        }

        /*
         * If we found this TLI in the server's history before encountering
         * the latest TLI seen so far in the server's history, then this TLI
         * is the latest one seen so far.
         *
         * If on the other hand we saw the earliest TLI seen so far before
         * finding this TLI, this TLI is earlier than the earliest one seen so
         * far. And if this is the first TLI for which we've searched, it's
         * also the earliest one seen so far.
         *
         * On the first loop iteration, both things should necessarily be
         * true.
         */
        if !saw_latest_wal_range_tli {
            latest_wal_range_tli = (*range).tli;
        }
        if earliest_wal_range_tli == 0 || saw_earliest_wal_range_tli {
            earliest_wal_range_tli = (*range).tli;
            earliest_wal_range_start_lsn = (*range).start_lsn;
        }

        i += 1;
    }

    /*
     * Propagate information about the prior backup into the backup_label that
     * will be generated for this backup.
     */
    (*backup_state).istartpoint = earliest_wal_range_start_lsn;
    (*backup_state).istarttli = earliest_wal_range_tli;

    /*
     * Sanity check start and end LSNs for the WAL ranges in the manifest.
     *
     * Commonly, there won't be any timeline switches during the prior backup
     * at all, but if there are, they should happen at the same LSNs that this
     * server switched timelines.
     *
     * Whether there are any timeline switches during the prior backup or not,
     * the prior backup shouldn't require any WAL from a timeline prior to the
     * start of that timeline. It also shouldn't require any WAL from later
     * than the start of this backup.
     *
     * If any of these sanity checks fail, one possible explanation is that
     * the user has generated WAL on the same timeline with the same LSNs more
     * than once. For instance, if two standbys running on timeline 1 were
     * both promoted and (due to a broken archiving setup) both selected new
     * timeline ID 2, then it's possible that one of these checks might trip.
     *
     * Note that there are lots of ways for the user to do something very bad
     * without tripping any of these checks, and they are not intended to be
     * comprehensive. It's pretty hard to see how we could be certain of
     * anything here. However, if there's a problem staring us right in the
     * face, it's best to report it, so we do.
     */
    i = 0;
    while i < num_wal_ranges {
        let range = list_nth((*ib).manifest_wal_ranges, i) as *mut backup_wal_range;

        if (*range).tli == earliest_wal_range_tli {
            if (*range).start_lsn < (**tlep.add(i as usize)).begin {
                elog!(
                    ERROR,
                    "manifest requires WAL from initial timeline {} starting at {:X}/{:X}, but that timeline begins at {:X}/{:X}",
                    (*range).tli,
                    ((*range).start_lsn >> 32) as u32,
                    (*range).start_lsn as u32,
                    ((**tlep.add(i as usize)).begin >> 32) as u32,
                    (**tlep.add(i as usize)).begin as u32
                );
                unreachable!();
            }
        } else if (*range).start_lsn != (**tlep.add(i as usize)).begin {
            elog!(
                ERROR,
                "manifest requires WAL from continuation timeline {} starting at {:X}/{:X}, but that timeline begins at {:X}/{:X}",
                (*range).tli,
                ((*range).start_lsn >> 32) as u32,
                (*range).start_lsn as u32,
                ((**tlep.add(i as usize)).begin >> 32) as u32,
                (**tlep.add(i as usize)).begin as u32
            );
            unreachable!();
        }

        if (*range).tli == latest_wal_range_tli {
            if (*range).end_lsn > (*backup_state).startpoint {
                elog!(
                    ERROR,
                    "manifest requires WAL from final timeline {} ending at {:X}/{:X}, but this backup starts at {:X}/{:X}",
                    (*range).tli,
                    ((*range).end_lsn >> 32) as u32,
                    (*range).end_lsn as u32,
                    ((*backup_state).startpoint >> 32) as u32,
                    (*backup_state).startpoint as u32
                );
                unreachable!();
            }
        } else if (*range).end_lsn != (**tlep.add(i as usize)).end {
            elog!(
                ERROR,
                "manifest requires WAL from non-final timeline {} ending at {:X}/{:X}, but this server switched timelines at {:X}/{:X}",
                (*range).tli,
                ((*range).end_lsn >> 32) as u32,
                (*range).end_lsn as u32,
                ((**tlep.add(i as usize)).end >> 32) as u32,
                (**tlep.add(i as usize)).end as u32
            );
            unreachable!();
        }

        i += 1;
    }

    /*
     * Wait for WAL summarization to catch up to the backup start LSN. This
     * will throw an error if the WAL summarizer appears to be stuck. If WAL
     * summarization gets disabled while we're waiting, this will return
     * immediately, and we'll error out further down if the WAL summaries are
     * incomplete.
     */
    WaitForWalSummarization((*backup_state).startpoint);

    /*
     * Retrieve a list of all WAL summaries on any timeline that overlap with
     * the LSN range of interest. We could instead call GetWalSummaries() once
     * per timeline in the loop that follows, but that would involve reading
     * the directory multiple times. It should be mildly faster - and perhaps
     * a bit safer - to do it just once.
     */
    all_wslist = GetWalSummaries(0, earliest_wal_range_start_lsn, (*backup_state).startpoint);

    /*
     * We need WAL summaries for everything that happened during the prior
     * backup and everything that happened afterward up until the point where
     * the current backup started.
     */
    foreach!(lc, expectedTLEs, {
        let tle = lfirst(current_cell!(lc)) as *mut TimeLineHistoryEntry;
        let mut tli_start_lsn: XLogRecPtr = (*tle).begin;
        let mut tli_end_lsn: XLogRecPtr = (*tle).end;
        let mut tli_missing_lsn: XLogRecPtr = InvalidXLogRecPtr;
        let tli_wslist: *mut List;

        /*
         * Working through the history of this server from the current
         * timeline backwards, we skip everything until we find the timeline
         * where this backup started. Most of the time, this means we won't
         * skip anything at all, as it's unlikely that the timeline has
         * changed since the beginning of the backup moments ago.
         */
        if (*tle).tli == (*backup_state).starttli {
            found_backup_start_tli = true;
            tli_end_lsn = (*backup_state).startpoint;
        } else if !found_backup_start_tli {
            continue;
        }

        /*
         * Find the summaries that overlap the LSN range of interest for this
         * timeline. If this is the earliest timeline involved, the range of
         * interest begins with the start LSN of the prior backup; otherwise,
         * it begins at the LSN at which this timeline came into existence. If
         * this is the latest TLI involved, the range of interest ends at the
         * start LSN of the current backup; otherwise, it ends at the point
         * where we switched from this timeline to the next one.
         */
        if (*tle).tli == earliest_wal_range_tli {
            tli_start_lsn = earliest_wal_range_start_lsn;
        }
        tli_wslist = FilterWalSummaries(all_wslist, (*tle).tli, tli_start_lsn, tli_end_lsn);

        /*
         * There is no guarantee that the WAL summaries we found cover the
         * entire range of LSNs for which summaries are required, or indeed
         * that we found any WAL summaries at all. Check whether we have a
         * problem of that sort.
         */
        if !WalSummariesAreComplete(tli_wslist, tli_start_lsn, tli_end_lsn, &mut tli_missing_lsn) {
            if XLogRecPtrIsInvalid(tli_missing_lsn) {
                elog!(
                    ERROR,
                    "WAL summaries are required on timeline {} from {:X}/{:X} to {:X}/{:X}, but no summaries for that timeline and LSN range exist",
                    (*tle).tli,
                    (tli_start_lsn >> 32) as u32,
                    tli_start_lsn as u32,
                    (tli_end_lsn >> 32) as u32,
                    tli_end_lsn as u32
                );
                unreachable!();
            } else {
                elog!(
                    ERROR,
                    "WAL summaries are required on timeline {} from {:X}/{:X} to {:X}/{:X}, but the summaries for that timeline and LSN range are incomplete",
                    (*tle).tli,
                    (tli_start_lsn >> 32) as u32,
                    tli_start_lsn as u32,
                    (tli_end_lsn >> 32) as u32,
                    tli_end_lsn as u32
                );
                unreachable!();
            }
        }

        /*
         * Remember that we need to read these summaries.
         *
         * Technically, it's possible that this could read more files than
         * required, since tli_wslist in theory could contain redundant
         * summaries. For instance, if we have a summary from 0/10000000 to
         * 0/20000000 and also one from 0/00000000 to 0/30000000, then the
         * latter subsumes the former and the former could be ignored.
         *
         * We ignore this possibility because the WAL summarizer only tries to
         * generate summaries that do not overlap. If somehow they exist,
         * we'll do a bit of extra work but the results should still be
         * correct.
         */
        required_wslist = list_concat(required_wslist, tli_wslist);

        /*
         * Timelines earlier than the one in which the prior backup began are
         * not relevant.
         */
        if (*tle).tli == earliest_wal_range_tli {
            break;
        }
    });

    /*
     * Read all of the required block reference table files and merge all of
     * the data into a single in-memory block reference table.
     *
     * See the comments for struct IncrementalBackupInfo for some thoughts on
     * memory usage.
     */
    (*ib).brtab = CreateEmptyBlockRefTable();
    foreach!(lc, required_wslist, {
        let ws = lfirst(current_cell!(lc)) as *mut WalSummaryFile;
        let mut wsio: WalSummaryIO = std::mem::zeroed();
        let reader: *mut BlockRefTableReader;
        let mut rlocator: RelFileLocator = std::mem::zeroed();
        let mut forknum: ForkNumber = 0;
        let mut limit_block: BlockNumber = 0;
        let mut blocks: [BlockNumber; BLOCKS_PER_READ] = [0; BLOCKS_PER_READ];

        wsio.file = OpenWalSummaryFile(ws, false);
        wsio.filepos = 0;
        elog!(
            DEBUG1,
            "reading WAL summary file \"{}\"",
            cstr_to_display(FilePathName(wsio.file))
        );
        reader = CreateBlockRefTableReader(
            ReadWalSummary,
            &mut wsio as *mut WalSummaryIO as *mut c_void,
            FilePathName(wsio.file),
            ReportWalSummaryError,
            std::ptr::null_mut(),
        );
        while BlockRefTableReaderNextRelation(reader, &mut rlocator, &mut forknum, &mut limit_block)
        {
            BlockRefTableSetLimitBlock(
                (*ib).brtab,
                &rlocator,
                forknum,
                limit_block,
            );

            loop {
                let nblocks: c_uint;

                nblocks = BlockRefTableReaderGetBlocks(
                    reader,
                    blocks.as_mut_ptr(),
                    BLOCKS_PER_READ as c_int,
                );
                if nblocks == 0 {
                    break;
                }

                let mut j: c_uint = 0;
                while j < nblocks {
                    BlockRefTableMarkBlockModified(
                        (*ib).brtab,
                        &rlocator,
                        forknum,
                        blocks[j as usize],
                    );
                    j += 1;
                }
            }
        }
        DestroyBlockRefTableReader(reader);
        FileClose(wsio.file);
    });

    /* Switch back to previous memory context. */
    MemoryContextSwitchTo(oldcontext as crate::utils::palloc::MemoryContext);
}

/*
 * Get the pathname that should be used when a file is sent incrementally.
 *
 * The result is a palloc'd string.
 */
pub unsafe fn GetIncrementalFilePath(
    dboid: Oid,
    spcoid: Oid,
    relfilenumber: RelFileNumber,
    forknum: ForkNumber,
    segno: c_uint,
) -> *mut c_char {
    let mut path: RelPathStr;
    let lastslash: *mut c_char;
    let ipath: *mut c_char;

    path = GetRelationPath(dboid, spcoid, relfilenumber, INVALID_PROC_NUMBER, forknum);

    let path_str = path.str.as_mut_ptr();
    lastslash = strrchr(path_str, '/' as c_int);
    Assert!(!lastslash.is_null());
    *lastslash = 0;

    if segno > 0 {
        ipath = psprintf(
            c"%s/INCREMENTAL.%s.%u".as_ptr(),
            path_str,
            lastslash.add(1),
            segno,
        );
    } else {
        ipath = psprintf(c"%s/INCREMENTAL.%s".as_ptr(), path_str, lastslash.add(1));
    }

    ipath
}

/*
 * How should we back up a particular file as part of an incremental backup?
 *
 * If the return value is BACK_UP_FILE_FULLY, caller should back up the whole
 * file just as if this were not an incremental backup.  The contents of the
 * relative_block_numbers array are unspecified in this case.
 *
 * If the return value is BACK_UP_FILE_INCREMENTALLY, caller should include
 * an incremental file in the backup instead of the entire file. On return,
 * *num_blocks_required will be set to the number of blocks that need to be
 * sent, and the actual block numbers will have been stored in
 * relative_block_numbers, which should be an array of at least RELSEG_SIZE.
 * In addition, *truncation_block_length will be set to the value that should
 * be included in the incremental file.
 */
pub unsafe fn GetFileBackupMethod(
    ib: *mut IncrementalBackupInfo,
    path: *const c_char,
    dboid: Oid,
    spcoid: Oid,
    relfilenumber: RelFileNumber,
    forknum: ForkNumber,
    segno: c_uint,
    size: Size,
    num_blocks_required: *mut c_uint,
    relative_block_numbers: *mut BlockNumber,
    truncation_block_length: *mut c_uint,
) -> FileBackupMethod {
    let limit_block: BlockNumber;
    let start_blkno: BlockNumber;
    let stop_blkno: BlockNumber;
    let mut rlocator: RelFileLocator = std::mem::zeroed();
    let brtentry: *mut BlockRefTableEntry;
    let mut i: c_uint;
    let nblocks: c_uint;

    /* Should only be called after PrepareForIncrementalBackup. */
    Assert!((*ib).buf.data.is_null());

    /*
     * dboid could be InvalidOid if shared rel, but spcoid and relfilenumber
     * should have legal values.
     */
    Assert!(OidIsValid(spcoid));
    Assert!(RelFileNumberIsValid(relfilenumber));

    /*
     * If the file size is too large or not a multiple of BLCKSZ, then
     * something weird is happening, so give up and send the whole file.
     */
    if (size % BLCKSZ) != 0 || (size / BLCKSZ) as u32 > RELSEG_SIZE {
        return BACK_UP_FILE_FULLY;
    }

    /*
     * The free-space map fork is not properly WAL-logged, so we need to
     * backup the entire file every time.
     */
    if forknum == FSM_FORKNUM {
        return BACK_UP_FILE_FULLY;
    }

    /*
     * If this file was not part of the prior backup, back it up fully.
     *
     * If this file was created after the prior backup and before the start of
     * the current backup, then the WAL summary information will tell us to
     * back up the whole file. However, if this file was created after the
     * start of the current backup, then the WAL summary won't know anything
     * about it. Without this logic, we would erroneously conclude that it was
     * OK to send it incrementally.
     *
     * Note that the file could have existed at the time of the prior backup,
     * gotten deleted, and then a new file with the same name could have been
     * created.  In that case, this logic won't prevent the file from being
     * backed up incrementally. But, if the deletion happened before the start
     * of the current backup, the limit block will be 0, inducing a full
     * backup. If the deletion happened after the start of the current backup,
     * reconstruction will erroneously combine blocks from the current
     * lifespan of the file with blocks from the previous lifespan -- but in
     * this type of case, WAL replay to reach backup consistency should remove
     * and recreate the file anyway, so the initial bogus contents should not
     * matter.
     */
    if backup_file_lookup((*ib).manifest_files, path).is_null() {
        let ipath: *mut c_char;

        ipath = GetIncrementalFilePath(dboid, spcoid, relfilenumber, forknum, segno);
        if backup_file_lookup((*ib).manifest_files, ipath).is_null() {
            return BACK_UP_FILE_FULLY;
        }
    }

    /*
     * Look up the special block reference table entry for the database as a
     * whole.
     */
    rlocator.spcOid = spcoid;
    rlocator.dbOid = dboid;
    rlocator.relNumber = Oid::from(0u32);
    let mut limit_block_db: BlockNumber = 0;
    if !BlockRefTableGetEntry((*ib).brtab, &rlocator, MAIN_FORKNUM, &mut limit_block_db).is_null() {
        /*
         * According to the WAL summary, this database OID/tablespace OID
         * pairing has been created since the previous backup. So, everything
         * in it must be backed up fully.
         */
        return BACK_UP_FILE_FULLY;
    }

    /* Look up the block reference table entry for this relfilenode. */
    rlocator.relNumber = relfilenumber;
    let mut limit_block_v: BlockNumber = 0;
    brtentry = BlockRefTableGetEntry((*ib).brtab, &rlocator, forknum, &mut limit_block_v);
    limit_block = limit_block_v;

    /*
     * If there is no entry, then there have been no WAL-logged changes to the
     * relation since the predecessor backup was taken, so we can back it up
     * incrementally and need not include any modified blocks.
     *
     * However, if the file is zero-length, we should do a full backup,
     * because an incremental file is always more than zero length, and it's
     * silly to take an incremental backup when a full backup would be
     * smaller.
     */
    if brtentry.is_null() {
        if size == 0 {
            return BACK_UP_FILE_FULLY;
        }
        *num_blocks_required = 0;
        *truncation_block_length = (size / BLCKSZ) as c_uint;
        return BACK_UP_FILE_INCREMENTALLY;
    }

    /*
     * If the limit_block is less than or equal to the point where this
     * segment starts, send the whole file.
     */
    if limit_block <= segno * RELSEG_SIZE {
        return BACK_UP_FILE_FULLY;
    }

    /*
     * Get relevant entries from the block reference table entry.
     *
     * We shouldn't overflow computing the start or stop block numbers, but if
     * it manages to happen somehow, detect it and throw an error.
     */
    start_blkno = segno * RELSEG_SIZE;
    stop_blkno = start_blkno + (size / BLCKSZ) as u32;
    if start_blkno / RELSEG_SIZE != segno || stop_blkno < start_blkno {
        elog!(
            ERROR,
            "overflow computing block number bounds for segment {} with size {}",
            segno,
            size
        );
        unreachable!();
    }

    /*
     * This will write *absolute* block numbers into the output array, but
     * we'll transpose them below.
     */
    nblocks = BlockRefTableEntryGetBlocks(
        brtentry,
        start_blkno,
        stop_blkno,
        relative_block_numbers,
        RELSEG_SIZE as c_int,
    ) as c_uint;
    Assert!(nblocks <= RELSEG_SIZE);

    /*
     * If we're going to have to send nearly all of the blocks, then just send
     * the whole file, because that won't require much extra storage or
     * transfer and will speed up and simplify backup restoration. It's not
     * clear what threshold is most appropriate here and perhaps it ought to
     * be configurable, but for now we're just going to say that if we'd need
     * to send 90% of the blocks anyway, give up and send the whole file.
     *
     * NB: If you change the threshold here, at least make sure to back up the
     * file fully when every single block must be sent, because there's
     * nothing good about sending an incremental file in that case.
     */
    if (nblocks as f64) * (BLCKSZ as f64) > (size as f64) * 0.9 {
        return BACK_UP_FILE_FULLY;
    }

    /*
     * Looks like we can send an incremental file, so sort the block numbers
     * and then transpose them from absolute block numbers to relative block
     * numbers if necessary.
     *
     * NB: If the block reference table was using the bitmap representation
     * for a given chunk, the block numbers in that chunk will already be
     * sorted, but when the array-of-offsets representation is used, we can
     * receive block numbers here out of order.
     */
    qsort(
        relative_block_numbers as *mut c_void,
        nblocks as usize,
        std::mem::size_of::<BlockNumber>(),
        compare_block_numbers,
    );
    if start_blkno != 0 {
        i = 0;
        while i < nblocks {
            *relative_block_numbers.add(i as usize) -= start_blkno;
            i += 1;
        }
    }
    *num_blocks_required = nblocks;

    /*
     * The truncation block length is the minimum length of the reconstructed
     * file. Any block numbers below this threshold that are not present in
     * the backup need to be fetched from the prior backup. At or above this
     * threshold, blocks should only be included in the result if they are
     * present in the backup. (This may require inserting zero blocks if the
     * blocks included in the backup are non-consecutive.)
     */
    *truncation_block_length = (size / BLCKSZ) as c_uint;
    if BlockNumberIsValid(limit_block) {
        let relative_limit: c_uint = limit_block - segno * RELSEG_SIZE;

        /*
         * We can't set a truncation_block_length in excess of the limit block
         * number (relativized to the current segment). To do so would be to
         * treat blocks from older backups as valid current contents even if
         * they were subsequently truncated away.
         */
        if *truncation_block_length < relative_limit {
            *truncation_block_length = relative_limit;
        }

        /*
         * We also can't set a truncation_block_length in excess of the
         * segment size, since the reconstructed file can't be larger than
         * that.
         */
        if *truncation_block_length > RELSEG_SIZE {
            *truncation_block_length = RELSEG_SIZE;
        }
    }

    /* Send it incrementally. */
    BACK_UP_FILE_INCREMENTALLY
}

/*
 * Compute the size for a header of an incremental file containing a given
 * number of blocks. The header is rounded to a multiple of BLCKSZ, but
 * only if the file will store some block data.
 */
pub unsafe fn GetIncrementalHeaderSize(num_blocks_required: c_uint) -> Size {
    let mut result: Size;

    /* Make sure we're not going to overflow. */
    Assert!(num_blocks_required <= RELSEG_SIZE);

    /*
     * Three four byte quantities (magic number, truncation block length,
     * block count) followed by block numbers.
     */
    result = 3 * std::mem::size_of::<uint32>()
        + (std::mem::size_of::<BlockNumber>() * num_blocks_required as usize);

    /*
     * Round the header size to a multiple of BLCKSZ - when not a multiple of
     * BLCKSZ, add the missing fraction of a block. But do this only if the
     * file will store data for some blocks, otherwise keep it small.
     */
    if (num_blocks_required > 0) && (result % BLCKSZ != 0) {
        result += BLCKSZ - (result % BLCKSZ);
    }

    result
}

/*
 * Compute the size for an incremental file containing a given number of blocks.
 */
pub unsafe fn GetIncrementalFileSize(num_blocks_required: c_uint) -> Size {
    let mut result: Size;

    /* Make sure we're not going to overflow. */
    Assert!(num_blocks_required <= RELSEG_SIZE);

    /*
     * Header with three four byte quantities (magic number, truncation block
     * length, block count) followed by block numbers, rounded to a multiple
     * of BLCKSZ (for files with block data), followed by block contents.
     */
    result = GetIncrementalHeaderSize(num_blocks_required);
    result += BLCKSZ * num_blocks_required as usize;

    result
}

/*
 * Helper function for filemap hash table.
 */
unsafe fn hash_string_pointer(s: *const c_char) -> uint32 {
    let ss = s as *mut c_uchar;

    hash_bytes(ss, strlen(s) as c_int)
}

/*
 * This callback to validate the manifest version for incremental backup.
 */
unsafe extern "C" fn manifest_process_version(
    context: *mut JsonManifestParseContext,
    manifest_version: c_int,
) {
    /* Incremental backups don't work with manifest version 1 */
    if manifest_version == 1 {
        ((*context).error_cb).unwrap()(
            context,
            c"backup manifest version 1 does not support incremental backup".as_ptr(),
        );
    }
}

/*
 * This callback to validate the manifest system identifier against the current
 * database server.
 */
unsafe extern "C" fn manifest_process_system_identifier(
    context: *mut JsonManifestParseContext,
    manifest_system_identifier: uint64,
) {
    let system_identifier: uint64;

    /* Get system identifier of current system */
    system_identifier = GetSystemIdentifier();

    if manifest_system_identifier != system_identifier {
        ((*context).error_cb).unwrap()(
            context,
            c"system identifier in backup manifest is %llu, but database system identifier is %llu"
                .as_ptr(),
        );
    }
}

/*
 * This callback is invoked for each file mentioned in the backup manifest.
 *
 * We store the path to each file and the size of each file for sanity-checking
 * purposes. For further details, see comments for IncrementalBackupInfo.
 */
unsafe extern "C" fn manifest_process_file(
    context: *mut JsonManifestParseContext,
    pathname: *const c_char,
    size: uint64,
    _checksum_type: pg_checksum_type,
    _checksum_length: c_int,
    _checksum_payload: *mut uint8,
) {
    let ib = (*context).private_data as *mut IncrementalBackupInfo;
    let entry: *mut backup_file_entry;
    let mut found: bool = false;

    entry = backup_file_insert((*ib).manifest_files, pathname, &mut found);
    if !found {
        (*entry).path = MemoryContextStrdup((*(*ib).manifest_files).ctx, pathname);
        (*entry).size = size;
    }
}

/*
 * This callback is invoked for each WAL range mentioned in the backup
 * manifest.
 *
 * We're just interested in learning the oldest LSN and the corresponding TLI
 * that appear in any WAL range.
 */
unsafe extern "C" fn manifest_process_wal_range(
    context: *mut JsonManifestParseContext,
    tli: TimeLineID,
    start_lsn: XLogRecPtr,
    end_lsn: XLogRecPtr,
) {
    let ib = (*context).private_data as *mut IncrementalBackupInfo;
    let range = palloc(std::mem::size_of::<backup_wal_range>()) as *mut backup_wal_range;

    (*range).tli = tli;
    (*range).start_lsn = start_lsn;
    (*range).end_lsn = end_lsn;
    (*ib).manifest_wal_ranges = lappend((*ib).manifest_wal_ranges, range as *mut c_void);
}

/*
 * This callback is invoked if an error occurs while parsing the backup
 * manifest.
 */
unsafe extern "C" fn manifest_report_error(
    _context: *mut JsonManifestParseContext,
    fmt: *const c_char,
) {
    // Variadic error callback; Rust can't define C-variadic bodies, so report
    // the format string directly. TODO: thread the varargs once supported.
    elog!(ERROR, "{}", std::ffi::CStr::from_ptr(fmt).to_string_lossy());
}

/*
 * Quicksort comparator for block numbers.
 */
unsafe extern "C" fn compare_block_numbers(a: *const c_void, b: *const c_void) -> c_int {
    let aa: BlockNumber = *(a as *const BlockNumber);
    let bb: BlockNumber = *(b as *const BlockNumber);

    pg_cmp_u32(aa, bb)
}

/*
 * Helper to render a NUL-terminated C string for elog! formatting.
 */
unsafe fn cstr_to_display(s: *const c_char) -> std::borrow::Cow<'static, str> {
    if s.is_null() {
        return std::borrow::Cow::Borrowed("(null)");
    }
    std::ffi::CStr::from_ptr(s).to_string_lossy()
}
