//! src/backend/utils/cache/relfilenumbermap.c - relfilenumber to oid mapping cache.

use crate::prelude::*;
use crate::access::attnum::AttrNumber;

use std::ffi::{c_char, c_int, c_void};

use crate::access::common::scankey::ScanKeyData;
use crate::access::htup_details::{GETSTRUCT, HeapTuple, HeapTupleIsValid};
use crate::access::relscan::SysScanDescData;
use crate::access::stratnum::BTEqualStrategyNumber;
use crate::access::table::table::{table_close, table_open};
use crate::catalog::catalog_oids::RelationRelationId;
use crate::catalog::pg_class::{Form_pg_class, RELPERSISTENCE_TEMP};
use crate::catalog::pg_known_oids::GLOBALTABLESPACE_OID;
use crate::miscadmin::MyDatabaseTableSpace;
use crate::storage::lockdefs::AccessShareLock;
use crate::utils::fmgr::{FmgrInfo, fmgr_info_cxt};
use crate::utils::hash::dynahash::{
    HASHCTL, HASH_BLOBS, HASH_CONTEXT, HASH_ELEM, HASH_SEQ_STATUS, HTAB,
    HASHACTION::{HASH_ENTER, HASH_FIND, HASH_REMOVE},
    hash_create, hash_search, hash_seq_init, hash_seq_search,
};
use crate::utils::mmgr::mcxt::CacheMemoryContext;
use crate::utils::mmgr::memnodes::MemoryContext;
use crate::utils::rel::Relation;

/* RelFileNumber, matching other ports - relpath.rs defines it as Oid */
use crate::common::relpath::RelFileNumber;

/*
 * Constants not yet generated by catalog tooling.
 */
/* F_OIDEQ: pg_proc OID of "oideq" (fmgroids.h) */
const F_OIDEQ: Oid = 184;
/* attribute numbers in pg_class (1-based) */
const Anum_pg_class_reltablespace: AttrNumber = 16;
const Anum_pg_class_relfilenode: AttrNumber = 15;
/* DECLARE_INDEX(pg_class_tblspc_relfilenode_index, 3455, ClassTblspcRelfilenodeIndexId, ...) */
const ClassTblspcRelfilenodeIndexId: Oid = 3455;

/* Hash table for information about each relfilenumber <-> oid pair */
static mut RelfilenumberMapHash: *mut HTAB = core::ptr::null_mut();

/* an all-zero FmgrInfo for const static initialization */
const EMPTY_FMGRINFO: FmgrInfo = FmgrInfo {
    fn_addr: None,
    fn_oid: 0,
    fn_nargs: 0,
    fn_strict: false,
    fn_retset: false,
    fn_stats: 0,
    fn_extra: core::ptr::null_mut(),
    fn_mcxt: core::ptr::null_mut(),
    fn_expr: core::ptr::null_mut(),
};

const EMPTY_SKEY: ScanKeyData = ScanKeyData {
    sk_flags: 0,
    sk_attno: 0,
    sk_strategy: 0,
    sk_subtype: 0,
    sk_collation: 0,
    sk_func: EMPTY_FMGRINFO,
    sk_argument: 0,
};

/* built first time through in InitializeRelfilenumberMap */
static mut relfilenumber_skey: [ScanKeyData; 2] = [EMPTY_SKEY, EMPTY_SKEY];

#[repr(C)]
#[derive(Clone, Copy)]
struct RelfilenumberMapKey {
    reltablespace: Oid,
    relfilenumber: RelFileNumber,
}

#[repr(C)]
struct RelfilenumberMapEntry {
    key: RelfilenumberMapKey, /* lookup key - must be first */
    relid: Oid,               /* pg_class.oid */
}

/*
 * RelfilenumberMapInvalidateCallback
 *		Flush mapping entries when pg_class is updated in a relevant fashion.
 */
unsafe extern "C" fn RelfilenumberMapInvalidateCallback(_arg: Datum, relid: Oid) {
    let mut status: HASH_SEQ_STATUS = core::mem::zeroed();

    /* callback only gets registered after creating the hash */
    Assert!(!RelfilenumberMapHash.is_null());

    hash_seq_init(&mut status, RelfilenumberMapHash);
    loop {
        let entry = hash_seq_search(&mut status) as *mut RelfilenumberMapEntry;
        if entry.is_null() {
            break;
        }

        /*
         * If relid is InvalidOid, signaling a complete reset, we must remove
         * all entries, otherwise just remove the specific relation's entry.
         * Always remove negative cache entries.
         */
        if relid == InvalidOid                  /* complete reset */
            || (*entry).relid == InvalidOid     /* negative cache entry */
            || (*entry).relid == relid
        /* individual flushed relation */
        {
            if hash_search(
                RelfilenumberMapHash,
                &(*entry).key as *const RelfilenumberMapKey as *const c_void,
                HASH_REMOVE,
                core::ptr::null_mut(),
            )
            .is_null()
            {
                elog!(ERROR, "hash table corrupted");
            }
        }
    }
}

/*
 * InitializeRelfilenumberMap
 *		Initialize cache, either on first use or after a reset.
 */
unsafe fn InitializeRelfilenumberMap() {
    let mut ctl: HASHCTL = core::mem::zeroed();

    /* Make sure we've initialized CacheMemoryContext. */
    if CacheMemoryContext.is_null() {
        CreateCacheMemoryContext();
    }

    /* build skey */
    MemSet(
        core::ptr::addr_of_mut!(relfilenumber_skey) as *mut c_void,
        0,
        core::mem::size_of_val(&relfilenumber_skey),
    );

    for i in 0..2 {
        fmgr_info_cxt(
            F_OIDEQ,
            &mut relfilenumber_skey[i].sk_func,
            CacheMemoryContext as *mut _,
        );
        relfilenumber_skey[i].sk_strategy = BTEqualStrategyNumber;
        relfilenumber_skey[i].sk_subtype = InvalidOid;
        relfilenumber_skey[i].sk_collation = InvalidOid;
    }

    relfilenumber_skey[0].sk_attno = Anum_pg_class_reltablespace;
    relfilenumber_skey[1].sk_attno = Anum_pg_class_relfilenode;

    /*
     * Only create the RelfilenumberMapHash now, so we don't end up partially
     * initialized when fmgr_info_cxt() above ERRORs out with an out of memory
     * error.
     */
    ctl.keysize = core::mem::size_of::<RelfilenumberMapKey>();
    ctl.entrysize = core::mem::size_of::<RelfilenumberMapEntry>();
    ctl.hcxt = CacheMemoryContext as *mut _;

    RelfilenumberMapHash = hash_create(
        c"RelfilenumberMap cache".as_ptr(),
        64,
        &ctl,
        HASH_ELEM | HASH_BLOBS | HASH_CONTEXT,
    );

    /* Watch for invalidation events. */
    CacheRegisterRelcacheCallback(RelfilenumberMapInvalidateCallback, 0 as Datum);
}

/*
 * Map a relation's (tablespace, relfilenumber) to a relation's oid and cache
 * the result.
 *
 * A temporary relation may share its relfilenumber with a permanent relation
 * or temporary relations created in other backends.  Being able to uniquely
 * identify a temporary relation would require a backend's proc number, which
 * we do not know about.  Hence, this function ignores this case.
 *
 * Returns InvalidOid if no relation matching the criteria could be found.
 */
pub unsafe fn RelidByRelfilenumber(
    mut reltablespace: Oid,
    relfilenumber: RelFileNumber,
) -> Oid {
    let mut key: RelfilenumberMapKey = core::mem::zeroed();
    let mut entry: *mut RelfilenumberMapEntry;
    let mut found: bool = false;
    let scandesc: *mut SysScanDescData;
    let relation: Relation;
    let mut ntp: HeapTuple;
    let mut relid: Oid;

    if RelfilenumberMapHash.is_null() {
        InitializeRelfilenumberMap();
    }

    /* pg_class will show 0 when the value is actually MyDatabaseTableSpace */
    if reltablespace == MyDatabaseTableSpace {
        reltablespace = 0;
    }

    MemSet(
        &mut key as *mut RelfilenumberMapKey as *mut c_void,
        0,
        core::mem::size_of::<RelfilenumberMapKey>(),
    );
    key.reltablespace = reltablespace;
    key.relfilenumber = relfilenumber;

    /*
     * Check cache and return entry if one is found. Even if no target
     * relation can be found later on we store the negative match and return a
     * InvalidOid from cache. That's not really necessary for performance
     * since querying invalid values isn't supposed to be a frequent thing,
     * but it's basically free.
     */
    entry = hash_search(
        RelfilenumberMapHash,
        &key as *const RelfilenumberMapKey as *const c_void,
        HASH_FIND,
        &mut found,
    ) as *mut RelfilenumberMapEntry;

    if found {
        return (*entry).relid;
    }

    /* ok, no previous cache entry, do it the hard way */

    /* initialize empty/negative cache entry before doing the actual lookups */
    relid = InvalidOid;

    if reltablespace == GLOBALTABLESPACE_OID {
        /*
         * Ok, shared table, check relmapper.
         */
        relid = RelationMapFilenumberToOid(relfilenumber, true);
    } else {
        let mut skey: [ScanKeyData; 2] = core::mem::zeroed();

        /*
         * Not a shared table, could either be a plain relation or a
         * non-shared, nailed one, like e.g. pg_class.
         */

        /* check for plain relations by looking in pg_class */
        relation = table_open(RelationRelationId, AccessShareLock);

        /* copy scankey to local copy and set scan arguments */
        core::ptr::copy_nonoverlapping(
            core::ptr::addr_of!(relfilenumber_skey) as *const ScanKeyData,
            skey.as_mut_ptr(),
            2,
        );
        skey[0].sk_argument = ObjectIdGetDatum(reltablespace);
        skey[1].sk_argument = ObjectIdGetDatum(relfilenumber);

        scandesc = systable_beginscan(
            relation,
            ClassTblspcRelfilenodeIndexId,
            true,
            core::ptr::null_mut(),
            2,
            skey.as_mut_ptr(),
        );

        found = false;

        loop {
            ntp = systable_getnext(scandesc);
            if !HeapTupleIsValid(ntp) {
                break;
            }

            let classform = GETSTRUCT(ntp) as Form_pg_class;

            if (*classform).relpersistence == RELPERSISTENCE_TEMP {
                continue;
            }

            if found {
                elog!(
                    ERROR,
                    "unexpected duplicate for tablespace {}, relfilenumber {}",
                    reltablespace,
                    relfilenumber
                );
            }
            found = true;

            Assert!((*classform).reltablespace == reltablespace);
            Assert!((*classform).relfilenode == relfilenumber);
            relid = (*classform).oid;
        }

        systable_endscan(scandesc);
        table_close(relation, AccessShareLock);

        /* check for tables that are mapped but not shared */
        if !found {
            relid = RelationMapFilenumberToOid(relfilenumber, false);
        }
    }

    /*
     * Only enter entry into cache now, our opening of pg_class could have
     * caused cache invalidations to be executed which would have deleted a
     * new entry if we had entered it above.
     */
    entry = hash_search(
        RelfilenumberMapHash,
        &key as *const RelfilenumberMapKey as *const c_void,
        HASH_ENTER,
        &mut found,
    ) as *mut RelfilenumberMapEntry;
    if found {
        elog!(ERROR, "corrupted hashtable");
    }
    (*entry).relid = relid;

    relid
}

/* ---- Stubs for not-yet-ported dependencies ---- */

// TODO: not ported - utils/cache/inval.c
type RelcacheCallbackFunction = unsafe extern "C" fn(arg: Datum, relid: Oid);
unsafe fn CacheRegisterRelcacheCallback(_func: RelcacheCallbackFunction, _arg: Datum) {
    unimplemented!()
}

// TODO: not ported - utils/mmgr/mcxt.c (CreateCacheMemoryContext)
unsafe fn CreateCacheMemoryContext() {
    unimplemented!()
}

// TODO: not ported - utils/cache/relmapper.c
unsafe fn RelationMapFilenumberToOid(_filenumber: RelFileNumber, _shared: bool) -> Oid {
    unimplemented!()
}

// TODO: not ported - access/index/genam.c
unsafe fn systable_beginscan(
    _heapRelation: Relation,
    _indexId: Oid,
    _indexOK: bool,
    _snapshot: *mut c_void,
    _nkeys: c_int,
    _key: *mut ScanKeyData,
) -> *mut SysScanDescData {
    unimplemented!()
}

// TODO: not ported - access/index/genam.c
unsafe fn systable_getnext(_sysscan: *mut SysScanDescData) -> HeapTuple {
    unimplemented!()
}

// TODO: not ported - access/index/genam.c
unsafe fn systable_endscan(_sysscan: *mut SysScanDescData) {
    unimplemented!()
}
