//! src/backend/utils/cache/syscache.c
//!
//! System cache management routines
//!
//! Portions Copyright (c) 1996-2025, PostgreSQL Global Development Group
//! Portions Copyright (c) 1994, Regents of the University of California
//!
//! NOTES
//!   These routines allow the parser/planner/executor to perform
//!   rapid lookups on the contents of the system catalogs.
//!
//!   see utils/syscache.h for a list of the cache IDs
//!
//! Companion header src/include/utils/syscache.h is merged below.

use crate::prelude::*;

use crate::access::attnum::AttrNumber;
use crate::access::htup_details::{HeapTuple, HeapTupleIsValid, GETSTRUCT};
use crate::catalog::pg_attribute::Form_pg_attribute;
use crate::common::int::pg_cmp_u32;
use crate::lib::qunique::qunique;
use crate::miscadmin::MyDatabaseId;
use crate::storage::block::BlockNumber;
use crate::storage::itemptr::{
    ItemPointerData, ItemPointerEquals, ItemPointerGetBlockNumber, ItemPointerGetOffsetNumber,
    ItemPointerIsValid, ItemPointerSetInvalid,
};

/* ---------------------------------------------------------------------------
 *
 * syscache.h declarations
 *
 * src/include/utils/syscache.h
 *
 * See also lsyscache.h, which provides convenience routines for
 * common cache-lookup operations.
 *
 * The use of the macros below rather than direct calls to the corresponding
 * functions is encouraged, as it insulates the caller from changes in the
 * maximum number of keys.
 *
 *   SearchSysCacheCopy1..4(cacheId, key1..4) ==
 *       SearchSysCacheCopy(cacheId, key1, [key2|0], [key3|0], [key4|0])
 *   SearchSysCacheExists1..4(cacheId, key1..4) ==
 *       SearchSysCacheExists(cacheId, key1, [key2|0], [key3|0], [key4|0])
 *   GetSysCacheOid1..4(cacheId, oidcol, key1..4) ==
 *       GetSysCacheOid(cacheId, oidcol, key1, [key2|0], [key3|0], [key4|0])
 *   GetSysCacheHashValue1..4(cacheId, key1..4) ==
 *       GetSysCacheHashValue(cacheId, key1, [key2|0], [key3|0], [key4|0])
 *   SearchSysCacheList1..3(cacheId, key1..3) ==
 *       SearchSysCacheList(cacheId, n, key1, [key2|0], [key3|0])
 *   ReleaseSysCacheList(x) == ReleaseCatCacheList(x)
 *
 * (These convenience wrappers are macros in C; callers in the Rust port should
 * use the underlying functions directly, supplying explicit 0 keys.)
 * ---------------------------------------------------------------------------
 */

/*
 * The SysCacheIdentifier enumeration and the SysCacheSize constant are
 * generated by genbki into catalog/syscache_ids.h from MAKE_SYSCACHE
 * declarations.  That generated header is not yet available in the port; the
 * cache-ID constants referenced elsewhere (ATTNAME, ATTNUM, ...) are declared
 * locally where needed.  SysCacheSize is the count of those identifiers.
 */
pub const SysCacheSize: c_int = 0; // TODO: catalog/syscache_ids.h (generated)

/* Cache ID constants (generated by genbki; stubbed here) */
pub const CLAOID: c_int = 7;        /* pg_opclass by oid */
pub const CLAAMNAMENSP: c_int = 6;  /* pg_opclass by (opcmethod, opcname, opcnamespace) */
pub const INDEXRELID: c_int = 35;   /* pg_index by indexrelid */

/*
 *		struct cachedesc: information defining a single syscache
 */
#[repr(C)]
pub struct cachedesc {
    pub reloid: Oid,    /* OID of the relation being cached */
    pub indoid: Oid,    /* OID of index relation for this cache */
    pub nkeys: c_int,   /* # of keys needed for cache lookup */
    pub key: [c_int; 4], /* attribute numbers of key attrs */
    pub nbuckets: c_int, /* number of hash buckets for this cache */
}

/*
 * The cacheinfo[] array is generated by genbki into catalog/syscache_info.h
 * from MAKE_SYSCACHE declarations.  That generated header is not yet available
 * in the port, so the table is empty.
 */
pub static cacheinfo: [cachedesc; SysCacheSize as usize] = []; // TODO: catalog/syscache_info.h (generated)

static mut SysCache: [*mut CatCache; SysCacheSize as usize] = [];

static mut CacheInitialized: bool = false;

/* Sorted array of OIDs of tables that have caches on them */
static mut SysCacheRelationOid: [Oid; SysCacheSize as usize] = [];
static mut SysCacheRelationOidSize: c_int = 0;

/* Sorted array of OIDs of tables and indexes used by caches */
static mut SysCacheSupportingRelOid: [Oid; (SysCacheSize * 2) as usize] = [];
static mut SysCacheSupportingRelOidSize: c_int = 0;

/*
 * InitCatalogCache - initialize the caches
 *
 * Note that no database access is done here; we only allocate memory
 * and initialize the cache structure.  Interrogation of the database
 * to complete initialization of a cache happens upon first use
 * of that cache.
 */
pub unsafe fn InitCatalogCache() {
    let mut cacheId: c_int;

    Assert!(!CacheInitialized);

    SysCacheRelationOidSize = 0;
    SysCacheSupportingRelOidSize = 0;

    cacheId = 0;
    while cacheId < SysCacheSize {
        /*
         * Assert that every enumeration value defined in syscache.h has been
         * populated in the cacheinfo array.
         */
        Assert!(OidIsValid(cacheinfo[cacheId as usize].reloid));
        Assert!(OidIsValid(cacheinfo[cacheId as usize].indoid));
        /* .nbuckets and .key[] are checked by InitCatCache() */

        SysCache[cacheId as usize] = InitCatCache(
            cacheId,
            cacheinfo[cacheId as usize].reloid,
            cacheinfo[cacheId as usize].indoid,
            cacheinfo[cacheId as usize].nkeys,
            cacheinfo[cacheId as usize].key.as_ptr(),
            cacheinfo[cacheId as usize].nbuckets,
        );
        if !PointerIsValid(SysCache[cacheId as usize]) {
            elog!(
                ERROR,
                "could not initialize cache {} ({})",
                cacheinfo[cacheId as usize].reloid,
                cacheId
            );
        }
        /* Accumulate data for OID lists, too */
        SysCacheRelationOid[SysCacheRelationOidSize as usize] = cacheinfo[cacheId as usize].reloid;
        SysCacheRelationOidSize += 1;
        SysCacheSupportingRelOid[SysCacheSupportingRelOidSize as usize] =
            cacheinfo[cacheId as usize].reloid;
        SysCacheSupportingRelOidSize += 1;
        SysCacheSupportingRelOid[SysCacheSupportingRelOidSize as usize] =
            cacheinfo[cacheId as usize].indoid;
        SysCacheSupportingRelOidSize += 1;
        /* see comments for RelationInvalidatesSnapshotsOnly */
        Assert!(!RelationInvalidatesSnapshotsOnly(
            cacheinfo[cacheId as usize].reloid
        ));

        cacheId += 1;
    }

    Assert!(SysCacheRelationOidSize as usize <= lengthof!(SysCacheRelationOid));
    Assert!(SysCacheSupportingRelOidSize as usize <= lengthof!(SysCacheSupportingRelOid));

    /* Sort and de-dup OID arrays, so we can use binary search. */
    qsort(
        SysCacheRelationOid.as_mut_ptr() as *mut c_void,
        SysCacheRelationOidSize as Size,
        core::mem::size_of::<Oid>(),
        oid_compare,
    );
    SysCacheRelationOidSize = qunique(
        SysCacheRelationOid.as_mut_ptr() as *mut c_void,
        SysCacheRelationOidSize as Size,
        core::mem::size_of::<Oid>(),
        oid_compare_rs,
    ) as c_int;

    qsort(
        SysCacheSupportingRelOid.as_mut_ptr() as *mut c_void,
        SysCacheSupportingRelOidSize as Size,
        core::mem::size_of::<Oid>(),
        oid_compare,
    );
    SysCacheSupportingRelOidSize = qunique(
        SysCacheSupportingRelOid.as_mut_ptr() as *mut c_void,
        SysCacheSupportingRelOidSize as Size,
        core::mem::size_of::<Oid>(),
        oid_compare_rs,
    ) as c_int;

    CacheInitialized = true;
}

/*
 * InitCatalogCachePhase2 - finish initializing the caches
 *
 * Finish initializing all the caches, including necessary database
 * access.
 *
 * This is *not* essential; normally we allow syscaches to be initialized
 * on first use.  However, it is useful as a mechanism to preload the
 * relcache with entries for the most-commonly-used system catalogs.
 * Therefore, we invoke this routine when we need to write a new relcache
 * init file.
 */
pub unsafe fn InitCatalogCachePhase2() {
    let mut cacheId: c_int;

    Assert!(CacheInitialized);

    cacheId = 0;
    while cacheId < SysCacheSize {
        InitCatCachePhase2(SysCache[cacheId as usize], true);
        cacheId += 1;
    }
}

/*
 * SearchSysCache
 *
 *	A layer on top of SearchCatCache that does the initialization and
 *	key-setting for you.
 *
 *	Returns the cache copy of the tuple if one is found, NULL if not.
 *	The tuple is the 'cache' copy and must NOT be modified!
 *
 *	When the caller is done using the tuple, call ReleaseSysCache()
 *	to release the reference count grabbed by SearchSysCache().  If this
 *	is not done, the tuple will remain locked in cache until end of
 *	transaction, which is tolerable but not desirable.
 *
 *	CAUTION: The tuple that is returned must NOT be freed by the caller!
 */
pub unsafe fn SearchSysCache(
    cacheId: c_int,
    key1: Datum,
    key2: Datum,
    key3: Datum,
    key4: Datum,
) -> HeapTuple {
    Assert!(
        cacheId >= 0 && cacheId < SysCacheSize && PointerIsValid(SysCache[cacheId as usize])
    );

    SearchCatCache(SysCache[cacheId as usize], key1, key2, key3, key4)
}

pub unsafe fn SearchSysCache1(cacheId: c_int, key1: Datum) -> HeapTuple {
    Assert!(
        cacheId >= 0 && cacheId < SysCacheSize && PointerIsValid(SysCache[cacheId as usize])
    );
    Assert!((*SysCache[cacheId as usize]).cc_nkeys == 1);

    SearchCatCache1(SysCache[cacheId as usize], key1)
}

pub unsafe fn SearchSysCache2(cacheId: c_int, key1: Datum, key2: Datum) -> HeapTuple {
    Assert!(
        cacheId >= 0 && cacheId < SysCacheSize && PointerIsValid(SysCache[cacheId as usize])
    );
    Assert!((*SysCache[cacheId as usize]).cc_nkeys == 2);

    SearchCatCache2(SysCache[cacheId as usize], key1, key2)
}

pub unsafe fn SearchSysCache3(cacheId: c_int, key1: Datum, key2: Datum, key3: Datum) -> HeapTuple {
    Assert!(
        cacheId >= 0 && cacheId < SysCacheSize && PointerIsValid(SysCache[cacheId as usize])
    );
    Assert!((*SysCache[cacheId as usize]).cc_nkeys == 3);

    SearchCatCache3(SysCache[cacheId as usize], key1, key2, key3)
}

pub unsafe fn SearchSysCache4(
    cacheId: c_int,
    key1: Datum,
    key2: Datum,
    key3: Datum,
    key4: Datum,
) -> HeapTuple {
    Assert!(
        cacheId >= 0 && cacheId < SysCacheSize && PointerIsValid(SysCache[cacheId as usize])
    );
    Assert!((*SysCache[cacheId as usize]).cc_nkeys == 4);

    SearchCatCache4(SysCache[cacheId as usize], key1, key2, key3, key4)
}

/*
 * ReleaseSysCache
 *		Release previously grabbed reference count on a tuple
 */
pub unsafe fn ReleaseSysCache(tuple: HeapTuple) {
    ReleaseCatCache(tuple);
}

/*
 * SearchSysCacheLocked1
 *
 * Combine SearchSysCache1() with acquiring a LOCKTAG_TUPLE at mode
 * InplaceUpdateTupleLock.  This is a tool for complying with the
 * README.tuplock section "Locking to write inplace-updated tables".  After
 * the caller's heap_update(), it should UnlockTuple(InplaceUpdateTupleLock)
 * and ReleaseSysCache().
 *
 * The returned tuple may be the subject of an uncommitted update, so this
 * doesn't prevent the "tuple concurrently updated" error.
 */
pub unsafe fn SearchSysCacheLocked1(cacheId: c_int, key1: Datum) -> HeapTuple {
    let cache: *mut CatCache = SysCache[cacheId as usize];
    let mut tid: ItemPointerData = core::mem::zeroed();
    let mut tag: LOCKTAG = core::mem::zeroed();

    /*----------
     * Since inplace updates may happen just before our LockTuple(), we must
     * return content acquired after LockTuple() of the TID we return.  If we
     * just fetched twice instead of looping, the following sequence would
     * defeat our locking:
     *
     * GRANT:   SearchSysCache1() = TID (1,5)
     * GRANT:   LockTuple(pg_class, (1,5))
     * [no more inplace update of (1,5) until we release the lock]
     * CLUSTER: SearchSysCache1() = TID (1,5)
     * CLUSTER: heap_update() = TID (1,8)
     * CLUSTER: COMMIT
     * GRANT:   SearchSysCache1() = TID (1,8)
     * GRANT:   return (1,8) from SearchSysCacheLocked1()
     * VACUUM:  SearchSysCache1() = TID (1,8)
     * VACUUM:  LockTuple(pg_class, (1,8))  # two TIDs now locked for one rel
     * VACUUM:  inplace update
     * GRANT:   heap_update() = (1,9)  # lose inplace update
     *
     * In the happy case, this takes two fetches, one to determine the TID to
     * lock and another to get the content and confirm the TID didn't change.
     *
     * This is valid even if the row gets updated to a new TID, the old TID
     * becomes LP_UNUSED, and the row gets updated back to its old TID.  We'd
     * still hold the right LOCKTAG_TUPLE and a copy of the row captured after
     * the LOCKTAG_TUPLE.
     */
    ItemPointerSetInvalid(&mut tid);
    loop {
        let tuple: HeapTuple;
        let lockmode: LOCKMODE = InplaceUpdateTupleLock;

        tuple = SearchSysCache1(cacheId, key1);
        if ItemPointerIsValid(&tid) {
            if !HeapTupleIsValid(tuple) {
                LockRelease(&mut tag, lockmode, false);
                return tuple;
            }
            if ItemPointerEquals(&raw const tid as *mut _, &raw const (*tuple).t_self as *mut _) {
                return tuple;
            }
            LockRelease(&mut tag, lockmode, false);
        } else if !HeapTupleIsValid(tuple) {
            return tuple;
        }

        tid = (*tuple).t_self;
        ReleaseSysCache(tuple);

        /*
         * Do like LockTuple(rel, &tid, lockmode).  While cc_relisshared won't
         * change from one iteration to another, it may have been a temporary
         * "false" until our first SearchSysCache1().
         */
        SET_LOCKTAG_TUPLE(
            &mut tag,
            if (*cache).cc_relisshared {
                InvalidOid
            } else {
                MyDatabaseId
            },
            (*cache).cc_reloid,
            ItemPointerGetBlockNumber(&tid),
            ItemPointerGetOffsetNumber(&tid),
        );
        LockAcquire(&mut tag, lockmode, false, false);

        /*
         * If an inplace update just finished, ensure we process the syscache
         * inval.
         *
         * If a heap_update() call just released its LOCKTAG_TUPLE, we'll
         * probably find the old tuple and reach "tuple concurrently updated".
         * If that heap_update() aborts, our LOCKTAG_TUPLE blocks inplace
         * updates while our caller works.
         */
        AcceptInvalidationMessages();
    }
}

/*
 * SearchSysCacheCopy
 *
 * A convenience routine that does SearchSysCache and (if successful)
 * returns a modifiable copy of the syscache entry.  The original
 * syscache entry is released before returning.  The caller should
 * heap_freetuple() the result when done with it.
 */
pub unsafe fn SearchSysCacheCopy(
    cacheId: c_int,
    key1: Datum,
    key2: Datum,
    key3: Datum,
    key4: Datum,
) -> HeapTuple {
    let tuple: HeapTuple;
    let newtuple: HeapTuple;

    tuple = SearchSysCache(cacheId, key1, key2, key3, key4);
    if !HeapTupleIsValid(tuple) {
        return tuple;
    }
    newtuple = heap_copytuple(tuple);
    ReleaseSysCache(tuple);
    newtuple
}

/*
 * SearchSysCacheLockedCopy1
 *
 * Meld SearchSysCacheLocked1 with SearchSysCacheCopy().  After the
 * caller's heap_update(), it should UnlockTuple(InplaceUpdateTupleLock) and
 * heap_freetuple().
 */
pub unsafe fn SearchSysCacheLockedCopy1(cacheId: c_int, key1: Datum) -> HeapTuple {
    let tuple: HeapTuple;
    let newtuple: HeapTuple;

    tuple = SearchSysCacheLocked1(cacheId, key1);
    if !HeapTupleIsValid(tuple) {
        return tuple;
    }
    newtuple = heap_copytuple(tuple);
    ReleaseSysCache(tuple);
    newtuple
}

/*
 * SearchSysCacheExists
 *
 * A convenience routine that just probes to see if a tuple can be found.
 * No lock is retained on the syscache entry.
 */
pub unsafe fn SearchSysCacheExists(
    cacheId: c_int,
    key1: Datum,
    key2: Datum,
    key3: Datum,
    key4: Datum,
) -> bool {
    let tuple: HeapTuple;

    tuple = SearchSysCache(cacheId, key1, key2, key3, key4);
    if !HeapTupleIsValid(tuple) {
        return false;
    }
    ReleaseSysCache(tuple);
    true
}

/*
 * GetSysCacheOid
 *
 * A convenience routine that does SearchSysCache and returns the OID in the
 * oidcol column of the found tuple, or InvalidOid if no tuple could be found.
 * No lock is retained on the syscache entry.
 */
pub unsafe fn GetSysCacheOid(
    cacheId: c_int,
    oidcol: AttrNumber,
    key1: Datum,
    key2: Datum,
    key3: Datum,
    key4: Datum,
) -> Oid {
    let tuple: HeapTuple;
    let mut isNull: bool = false;
    let result: Oid;

    tuple = SearchSysCache(cacheId, key1, key2, key3, key4);
    if !HeapTupleIsValid(tuple) {
        return InvalidOid;
    }
    result = DatumGetObjectId(heap_getattr(
        tuple,
        oidcol,
        (*SysCache[cacheId as usize]).cc_tupdesc,
        &mut isNull,
    ));
    Assert!(!isNull); /* columns used as oids should never be NULL */
    ReleaseSysCache(tuple);
    result
}

/*
 * SearchSysCacheAttName
 *
 * This routine is equivalent to SearchSysCache on the ATTNAME cache,
 * except that it will return NULL if the found attribute is marked
 * attisdropped.  This is convenient for callers that want to act as
 * though dropped attributes don't exist.
 */
pub unsafe fn SearchSysCacheAttName(relid: Oid, attname: *const c_char) -> HeapTuple {
    let tuple: HeapTuple;

    tuple = SearchSysCache2(
        ATTNAME,
        ObjectIdGetDatum(relid),
        CStringGetDatum(attname),
    );
    if !HeapTupleIsValid(tuple) {
        return null_mut();
    }
    if (*(GETSTRUCT(tuple) as Form_pg_attribute)).attisdropped {
        ReleaseSysCache(tuple);
        return null_mut();
    }
    tuple
}

/*
 * SearchSysCacheCopyAttName
 *
 * As above, an attisdropped-aware version of SearchSysCacheCopy.
 */
pub unsafe fn SearchSysCacheCopyAttName(relid: Oid, attname: *const c_char) -> HeapTuple {
    let tuple: HeapTuple;
    let newtuple: HeapTuple;

    tuple = SearchSysCacheAttName(relid, attname);
    if !HeapTupleIsValid(tuple) {
        return tuple;
    }
    newtuple = heap_copytuple(tuple);
    ReleaseSysCache(tuple);
    newtuple
}

/*
 * SearchSysCacheExistsAttName
 *
 * As above, an attisdropped-aware version of SearchSysCacheExists.
 */
pub unsafe fn SearchSysCacheExistsAttName(relid: Oid, attname: *const c_char) -> bool {
    let tuple: HeapTuple;

    tuple = SearchSysCacheAttName(relid, attname);
    if !HeapTupleIsValid(tuple) {
        return false;
    }
    ReleaseSysCache(tuple);
    true
}

/*
 * SearchSysCacheAttNum
 *
 * This routine is equivalent to SearchSysCache on the ATTNUM cache,
 * except that it will return NULL if the found attribute is marked
 * attisdropped.  This is convenient for callers that want to act as
 * though dropped attributes don't exist.
 */
pub unsafe fn SearchSysCacheAttNum(relid: Oid, attnum: int16) -> HeapTuple {
    let tuple: HeapTuple;

    tuple = SearchSysCache2(ATTNUM, ObjectIdGetDatum(relid), Int16GetDatum(attnum));
    if !HeapTupleIsValid(tuple) {
        return null_mut();
    }
    if (*(GETSTRUCT(tuple) as Form_pg_attribute)).attisdropped {
        ReleaseSysCache(tuple);
        return null_mut();
    }
    tuple
}

/*
 * SearchSysCacheCopyAttNum
 *
 * As above, an attisdropped-aware version of SearchSysCacheCopy.
 */
pub unsafe fn SearchSysCacheCopyAttNum(relid: Oid, attnum: int16) -> HeapTuple {
    let tuple: HeapTuple;
    let newtuple: HeapTuple;

    tuple = SearchSysCacheAttNum(relid, attnum);
    if !HeapTupleIsValid(tuple) {
        return null_mut();
    }
    newtuple = heap_copytuple(tuple);
    ReleaseSysCache(tuple);
    newtuple
}

/*
 * SysCacheGetAttr
 *
 *		Given a tuple previously fetched by SearchSysCache(),
 *		extract a specific attribute.
 *
 * This is equivalent to using heap_getattr() on a tuple fetched
 * from a non-cached relation.  Usually, this is only used for attributes
 * that could be NULL or variable length; the fixed-size attributes in
 * a system table are accessed just by mapping the tuple onto the C struct
 * declarations from include/catalog/.
 *
 * As with heap_getattr(), if the attribute is of a pass-by-reference type
 * then a pointer into the tuple data area is returned --- the caller must
 * not modify or pfree the datum!
 *
 * Note: it is legal to use SysCacheGetAttr() with a cacheId referencing
 * a different cache for the same catalog the tuple was fetched from.
 */
pub unsafe fn SysCacheGetAttr(
    cacheId: c_int,
    tup: HeapTuple,
    attributeNumber: AttrNumber,
    isNull: *mut bool,
) -> Datum {
    /*
     * We just need to get the TupleDesc out of the cache entry, and then we
     * can apply heap_getattr().  Normally the cache control data is already
     * valid (because the caller recently fetched the tuple via this same
     * cache), but there are cases where we have to initialize the cache here.
     */
    if cacheId < 0 || cacheId >= SysCacheSize || !PointerIsValid(SysCache[cacheId as usize]) {
        elog!(ERROR, "invalid cache ID: {}", cacheId);
    }
    if !PointerIsValid((*SysCache[cacheId as usize]).cc_tupdesc) {
        InitCatCachePhase2(SysCache[cacheId as usize], false);
        Assert!(PointerIsValid((*SysCache[cacheId as usize]).cc_tupdesc));
    }

    heap_getattr(
        tup,
        attributeNumber,
        (*SysCache[cacheId as usize]).cc_tupdesc,
        isNull,
    )
}

/*
 * SysCacheGetAttrNotNull
 *
 * As above, a version of SysCacheGetAttr which knows that the attr cannot
 * be NULL.
 */
pub unsafe fn SysCacheGetAttrNotNull(
    cacheId: c_int,
    tup: HeapTuple,
    attributeNumber: AttrNumber,
) -> Datum {
    let mut isnull: bool = false;
    let attr: Datum;

    attr = SysCacheGetAttr(cacheId, tup, attributeNumber, &mut isnull);

    if isnull {
        elog!(
            ERROR,
            "unexpected null value in cached tuple for catalog {} column {}",
            CStr_to_display(get_rel_name(cacheinfo[cacheId as usize].reloid)),
            CStr_to_display(NameStr(
                &mut (*TupleDescAttr(
                    (*SysCache[cacheId as usize]).cc_tupdesc,
                    (attributeNumber - 1) as c_int,
                ))
                .attname
            ))
        );
    }

    attr
}

/*
 * GetSysCacheHashValue
 *
 * Get the hash value that would be used for a tuple in the specified cache
 * with the given search keys.
 *
 * The reason for exposing this as part of the API is that the hash value is
 * exposed in cache invalidation operations, so there are places outside the
 * catcache code that need to be able to compute the hash values.
 */
pub unsafe fn GetSysCacheHashValue(
    cacheId: c_int,
    key1: Datum,
    key2: Datum,
    key3: Datum,
    key4: Datum,
) -> uint32 {
    if cacheId < 0 || cacheId >= SysCacheSize || !PointerIsValid(SysCache[cacheId as usize]) {
        elog!(ERROR, "invalid cache ID: {}", cacheId);
    }

    GetCatCacheHashValue(SysCache[cacheId as usize], key1, key2, key3, key4)
}

/*
 * List-search interface
 */
pub unsafe fn SearchSysCacheList(
    cacheId: c_int,
    nkeys: c_int,
    key1: Datum,
    key2: Datum,
    key3: Datum,
) -> *mut catclist {
    if cacheId < 0 || cacheId >= SysCacheSize || !PointerIsValid(SysCache[cacheId as usize]) {
        elog!(ERROR, "invalid cache ID: {}", cacheId);
    }

    SearchCatCacheList(SysCache[cacheId as usize], nkeys, key1, key2, key3)
}

/*
 * SysCacheInvalidate
 *
 *	Invalidate entries in the specified cache, given a hash value.
 *	See CatCacheInvalidate() for more info.
 *
 *	This routine is only quasi-public: it should only be used by inval.c.
 */
pub unsafe fn SysCacheInvalidate(cacheId: c_int, hashValue: uint32) {
    if cacheId < 0 || cacheId >= SysCacheSize {
        elog!(ERROR, "invalid cache ID: {}", cacheId);
    }

    /* if this cache isn't initialized yet, no need to do anything */
    if !PointerIsValid(SysCache[cacheId as usize]) {
        return;
    }

    CatCacheInvalidate(SysCache[cacheId as usize], hashValue);
}

/*
 * Certain relations that do not have system caches send snapshot invalidation
 * messages in lieu of catcache messages.  This is for the benefit of
 * GetCatalogSnapshot(), which can then reuse its existing MVCC snapshot
 * for scanning one of those catalogs, rather than taking a new one, if no
 * invalidation has been received.
 *
 * Relations that have syscaches need not (and must not) be listed here.  The
 * catcache invalidation messages will also flush the snapshot.  If you add a
 * syscache for one of these relations, remove it from this list.
 */
pub unsafe fn RelationInvalidatesSnapshotsOnly(relid: Oid) -> bool {
    match relid {
        DbRoleSettingRelationId
        | DependRelationId
        | SharedDependRelationId
        | DescriptionRelationId
        | SharedDescriptionRelationId
        | SecLabelRelationId
        | SharedSecLabelRelationId => return true,
        _ => {}
    }

    false
}

/*
 * Test whether a relation has a system cache.
 */
pub unsafe fn RelationHasSysCache(relid: Oid) -> bool {
    let mut low: c_int = 0;
    let mut high: c_int = SysCacheRelationOidSize - 1;

    while low <= high {
        let middle: c_int = low + (high - low) / 2;

        if SysCacheRelationOid[middle as usize] == relid {
            return true;
        }
        if SysCacheRelationOid[middle as usize] < relid {
            low = middle + 1;
        } else {
            high = middle - 1;
        }
    }

    false
}

/*
 * Test whether a relation supports a system cache, ie it is either a
 * cached table or the index used for a cache.
 */
pub unsafe fn RelationSupportsSysCache(relid: Oid) -> bool {
    let mut low: c_int = 0;
    let mut high: c_int = SysCacheSupportingRelOidSize - 1;

    while low <= high {
        let middle: c_int = low + (high - low) / 2;

        if SysCacheSupportingRelOid[middle as usize] == relid {
            return true;
        }
        if SysCacheSupportingRelOid[middle as usize] < relid {
            low = middle + 1;
        } else {
            high = middle - 1;
        }
    }

    false
}

/*
 * OID comparator for qsort
 */
unsafe extern "C" fn oid_compare(a: *const c_void, b: *const c_void) -> c_int {
    let oa: Oid = *(a as *const Oid);
    let ob: Oid = *(b as *const Oid);

    pg_cmp_u32(oa, ob)
}

/*
 * Rust-ABI shim over oid_compare for qunique(), whose comparator type is a
 * plain `unsafe fn` (not `extern "C"`).  The libc qsort() above takes the
 * `extern "C"` form directly.
 */
unsafe fn oid_compare_rs(a: *const c_void, b: *const c_void) -> c_int {
    oid_compare(a, b)
}

/* ----------------------------------------------------------------
 *		Local stubs for dependencies not yet ported
 * ----------------------------------------------------------------
 */

/* utils/catcache.h: the catcache machinery (not yet ported). */
#[repr(C)]
pub struct CatCache {
    pub cc_nkeys: c_int,
    pub cc_tupdesc: *mut c_void, /* TupleDesc */
    pub cc_reloid: Oid,
    pub cc_relisshared: bool,
}

#[repr(C)]
pub struct catclist {
    _private: [u8; 0],
}

unsafe fn InitCatCache(
    _id: c_int,
    _reloid: Oid,
    _indexoid: Oid,
    _nkeys: c_int,
    _key: *const c_int,
    _nbuckets: c_int,
) -> *mut CatCache {
    unimplemented!() // TODO: utils/cache/catcache.c
}

unsafe fn InitCatCachePhase2(_cache: *mut CatCache, _touch_index: bool) {
    unimplemented!() // TODO: utils/cache/catcache.c
}

unsafe fn SearchCatCache(
    _cache: *mut CatCache,
    _v1: Datum,
    _v2: Datum,
    _v3: Datum,
    _v4: Datum,
) -> HeapTuple {
    unimplemented!() // TODO: utils/cache/catcache.c
}

unsafe fn SearchCatCache1(_cache: *mut CatCache, _v1: Datum) -> HeapTuple {
    unimplemented!() // TODO: utils/cache/catcache.c
}

unsafe fn SearchCatCache2(_cache: *mut CatCache, _v1: Datum, _v2: Datum) -> HeapTuple {
    unimplemented!() // TODO: utils/cache/catcache.c
}

unsafe fn SearchCatCache3(_cache: *mut CatCache, _v1: Datum, _v2: Datum, _v3: Datum) -> HeapTuple {
    unimplemented!() // TODO: utils/cache/catcache.c
}

unsafe fn SearchCatCache4(
    _cache: *mut CatCache,
    _v1: Datum,
    _v2: Datum,
    _v3: Datum,
    _v4: Datum,
) -> HeapTuple {
    unimplemented!() // TODO: utils/cache/catcache.c
}

unsafe fn ReleaseCatCache(_tuple: HeapTuple) {
    unimplemented!() // TODO: utils/cache/catcache.c
}

unsafe fn GetCatCacheHashValue(
    _cache: *mut CatCache,
    _v1: Datum,
    _v2: Datum,
    _v3: Datum,
    _v4: Datum,
) -> uint32 {
    unimplemented!() // TODO: utils/cache/catcache.c
}

unsafe fn SearchCatCacheList(
    _cache: *mut CatCache,
    _nkeys: c_int,
    _v1: Datum,
    _v2: Datum,
    _v3: Datum,
) -> *mut catclist {
    unimplemented!() // TODO: utils/cache/catcache.c
}

unsafe fn CatCacheInvalidate(_cache: *mut CatCache, _hashValue: uint32) {
    unimplemented!() // TODO: utils/cache/catcache.c
}

/* access/htup_details.h / access/heaptuple.c */
unsafe fn heap_copytuple(_tuple: HeapTuple) -> HeapTuple {
    unimplemented!() // TODO: access/common/heaptuple.c
}

unsafe fn heap_getattr(
    _tup: HeapTuple,
    _attnum: AttrNumber,
    _tupleDesc: *mut c_void,
    _isnull: *mut bool,
) -> Datum {
    unimplemented!() // TODO: access/htup_details.h
}

/* access/tupdesc.h */
unsafe fn TupleDescAttr(_tupdesc: *mut c_void, _i: c_int) -> *mut FormData_pg_attribute_stub {
    unimplemented!() // TODO: access/tupdesc.h
}

#[repr(C)]
pub struct FormData_pg_attribute_stub {
    pub attname: NameData_stub,
}

#[repr(C)]
pub struct NameData_stub {
    pub data: [c_char; 64],
}

unsafe fn NameStr(name: *mut NameData_stub) -> *const c_char {
    (*name).data.as_ptr() // c.h: NameStr(name) == ((name).data)
}

/* utils/lsyscache.h */
unsafe fn get_rel_name(_relid: Oid) -> *const c_char {
    unimplemented!() // TODO: utils/cache/lsyscache.c
}

/* utils/inval.h */
unsafe fn AcceptInvalidationMessages() {
    unimplemented!() // TODO: utils/cache/inval.c
}

/* storage/lock.h + storage/lmgr.h (lock manager not yet ported). */
pub type LOCKMODE = c_int;

#[repr(C)]
pub struct LOCKTAG {
    _private: [u8; 16],
}

const InplaceUpdateTupleLock: LOCKMODE = 8; /* storage/lockdefs.h: == ExclusiveLock */

unsafe fn SET_LOCKTAG_TUPLE(
    _tag: *mut LOCKTAG,
    _dboid: Oid,
    _reloid: Oid,
    _blocknum: BlockNumber,
    _offnum: u16,
) {
    unimplemented!() // TODO: storage/lock.h
}

unsafe fn LockAcquire(
    _locktag: *mut LOCKTAG,
    _lockmode: LOCKMODE,
    _sessionLock: bool,
    _dontWait: bool,
) -> c_int {
    unimplemented!() // TODO: storage/lmgr/lock.c
}

unsafe fn LockRelease(_locktag: *mut LOCKTAG, _lockmode: LOCKMODE, _sessionLock: bool) -> bool {
    unimplemented!() // TODO: storage/lmgr/lock.c
}

/* catalog relation OID constants (catalog/pg_*_d.h, generated). */
const DbRoleSettingRelationId: Oid = 2964; // TODO: catalog/pg_db_role_setting_d.h
const DependRelationId: Oid = 2608; // TODO: catalog/pg_depend_d.h
const SharedDependRelationId: Oid = 1214; // TODO: catalog/pg_shdepend_d.h
const DescriptionRelationId: Oid = 2609; // TODO: catalog/pg_description_d.h
const SharedDescriptionRelationId: Oid = 2396; // TODO: catalog/pg_shdescription_d.h
const SecLabelRelationId: Oid = 3596; // TODO: catalog/pg_seclabel_d.h
const SharedSecLabelRelationId: Oid = 3592; // TODO: catalog/pg_shseclabel_d.h

/* syscache identifiers used by name in this file (catalog/syscache_ids.h, generated). */
const ATTNAME: c_int = 0; // TODO: catalog/syscache_ids.h
const ATTNUM: c_int = 0; // TODO: catalog/syscache_ids.h

/* port: qsort (stdlib) */
extern "C" {
    fn qsort(
        base: *mut c_void,
        nmemb: Size,
        size: usize,
        compar: unsafe extern "C" fn(*const c_void, *const c_void) -> c_int,
    );
}

/*
 * Helper to render a NUL-terminated C string in an elog! format argument.
 * (In C the %s conversion does this directly; here we wrap the raw pointer.)
 */
unsafe fn CStr_to_display(s: *const c_char) -> &'static str {
    if s.is_null() {
        return "(null)";
    }
    core::ffi::CStr::from_ptr(s).to_str().unwrap_or("(invalid)")
}
