//! GENERATED by /tmp/gen_syscache.py from postgres/src/include/catalog/
//! syscache_ids.h + syscache_info.h + *_d.h. Do not edit by hand.
#![allow(non_upper_case_globals)]
use std::ffi::c_int;
use crate::postgres_ext::Oid;
use crate::utils::cache::syscache::cachedesc;

pub const AGGFNOID: c_int = 0;
pub const AMNAME: c_int = 1;
pub const AMOID: c_int = 2;
pub const AMOPOPID: c_int = 3;
pub const AMOPSTRATEGY: c_int = 4;
pub const AMPROCNUM: c_int = 5;
pub const ATTNAME: c_int = 6;
pub const ATTNUM: c_int = 7;
pub const AUTHMEMMEMROLE: c_int = 8;
pub const AUTHMEMROLEMEM: c_int = 9;
pub const AUTHNAME: c_int = 10;
pub const AUTHOID: c_int = 11;
pub const CASTSOURCETARGET: c_int = 12;
pub const CLAAMNAMENSP: c_int = 13;
pub const CLAOID: c_int = 14;
pub const COLLNAMEENCNSP: c_int = 15;
pub const COLLOID: c_int = 16;
pub const CONDEFAULT: c_int = 17;
pub const CONNAMENSP: c_int = 18;
pub const CONSTROID: c_int = 19;
pub const CONVOID: c_int = 20;
pub const DATABASEOID: c_int = 21;
pub const DEFACLROLENSPOBJ: c_int = 22;
pub const ENUMOID: c_int = 23;
pub const ENUMTYPOIDNAME: c_int = 24;
pub const EVENTTRIGGERNAME: c_int = 25;
pub const EVENTTRIGGEROID: c_int = 26;
pub const EXTENSIONNAME: c_int = 27;
pub const EXTENSIONOID: c_int = 28;
pub const FOREIGNDATAWRAPPERNAME: c_int = 29;
pub const FOREIGNDATAWRAPPEROID: c_int = 30;
pub const FOREIGNSERVERNAME: c_int = 31;
pub const FOREIGNSERVEROID: c_int = 32;
pub const FOREIGNTABLEREL: c_int = 33;
pub const INDEXRELID: c_int = 34;
pub const LANGNAME: c_int = 35;
pub const LANGOID: c_int = 36;
pub const NAMESPACENAME: c_int = 37;
pub const NAMESPACEOID: c_int = 38;
pub const OPERNAMENSP: c_int = 39;
pub const OPEROID: c_int = 40;
pub const OPFAMILYAMNAMENSP: c_int = 41;
pub const OPFAMILYOID: c_int = 42;
pub const PARAMETERACLNAME: c_int = 43;
pub const PARAMETERACLOID: c_int = 44;
pub const PARTRELID: c_int = 45;
pub const PROCNAMEARGSNSP: c_int = 46;
pub const PROCOID: c_int = 47;
pub const PUBLICATIONNAME: c_int = 48;
pub const PUBLICATIONNAMESPACE: c_int = 49;
pub const PUBLICATIONNAMESPACEMAP: c_int = 50;
pub const PUBLICATIONOID: c_int = 51;
pub const PUBLICATIONREL: c_int = 52;
pub const PUBLICATIONRELMAP: c_int = 53;
pub const RANGEMULTIRANGE: c_int = 54;
pub const RANGETYPE: c_int = 55;
pub const RELNAMENSP: c_int = 56;
pub const RELOID: c_int = 57;
pub const REPLORIGIDENT: c_int = 58;
pub const REPLORIGNAME: c_int = 59;
pub const RULERELNAME: c_int = 60;
pub const SEQRELID: c_int = 61;
pub const STATEXTDATASTXOID: c_int = 62;
pub const STATEXTNAMENSP: c_int = 63;
pub const STATEXTOID: c_int = 64;
pub const STATRELATTINH: c_int = 65;
pub const SUBSCRIPTIONNAME: c_int = 66;
pub const SUBSCRIPTIONOID: c_int = 67;
pub const SUBSCRIPTIONRELMAP: c_int = 68;
pub const TABLESPACEOID: c_int = 69;
pub const TRFOID: c_int = 70;
pub const TRFTYPELANG: c_int = 71;
pub const TSCONFIGMAP: c_int = 72;
pub const TSCONFIGNAMENSP: c_int = 73;
pub const TSCONFIGOID: c_int = 74;
pub const TSDICTNAMENSP: c_int = 75;
pub const TSDICTOID: c_int = 76;
pub const TSPARSERNAMENSP: c_int = 77;
pub const TSPARSEROID: c_int = 78;
pub const TSTEMPLATENAMENSP: c_int = 79;
pub const TSTEMPLATEOID: c_int = 80;
pub const TYPENAMENSP: c_int = 81;
pub const TYPEOID: c_int = 82;
pub const USERMAPPINGOID: c_int = 83;
pub const USERMAPPINGUSERSERVER: c_int = 84;

pub const SysCacheSize: c_int = 85;

pub static cacheinfo: [cachedesc; 85] = [
    cachedesc { reloid: 2600 as Oid, indoid: 2650 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 16 }, // AGGFNOID
    cachedesc { reloid: 2601 as Oid, indoid: 2651 as Oid, nkeys: 1, key: [2, 0, 0, 0], nbuckets: 4 }, // AMNAME
    cachedesc { reloid: 2601 as Oid, indoid: 2652 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 4 }, // AMOID
    cachedesc { reloid: 2602 as Oid, indoid: 2654 as Oid, nkeys: 3, key: [7, 6, 2, 0], nbuckets: 64 }, // AMOPOPID
    cachedesc { reloid: 2602 as Oid, indoid: 2653 as Oid, nkeys: 4, key: [2, 3, 4, 5], nbuckets: 64 }, // AMOPSTRATEGY
    cachedesc { reloid: 2603 as Oid, indoid: 2655 as Oid, nkeys: 4, key: [2, 3, 4, 5], nbuckets: 16 }, // AMPROCNUM
    cachedesc { reloid: 1249 as Oid, indoid: 2658 as Oid, nkeys: 2, key: [1, 2, 0, 0], nbuckets: 32 }, // ATTNAME
    cachedesc { reloid: 1249 as Oid, indoid: 2659 as Oid, nkeys: 2, key: [1, 5, 0, 0], nbuckets: 128 }, // ATTNUM
    cachedesc { reloid: 1261 as Oid, indoid: 2695 as Oid, nkeys: 3, key: [3, 2, 4, 0], nbuckets: 8 }, // AUTHMEMMEMROLE
    cachedesc { reloid: 1261 as Oid, indoid: 2694 as Oid, nkeys: 3, key: [2, 3, 4, 0], nbuckets: 8 }, // AUTHMEMROLEMEM
    cachedesc { reloid: 1260 as Oid, indoid: 2676 as Oid, nkeys: 1, key: [2, 0, 0, 0], nbuckets: 8 }, // AUTHNAME
    cachedesc { reloid: 1260 as Oid, indoid: 2677 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 8 }, // AUTHOID
    cachedesc { reloid: 2605 as Oid, indoid: 2661 as Oid, nkeys: 2, key: [2, 3, 0, 0], nbuckets: 256 }, // CASTSOURCETARGET
    cachedesc { reloid: 2616 as Oid, indoid: 2686 as Oid, nkeys: 3, key: [2, 3, 4, 0], nbuckets: 8 }, // CLAAMNAMENSP
    cachedesc { reloid: 2616 as Oid, indoid: 2687 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 8 }, // CLAOID
    cachedesc { reloid: 3456 as Oid, indoid: 3164 as Oid, nkeys: 3, key: [2, 7, 3, 0], nbuckets: 8 }, // COLLNAMEENCNSP
    cachedesc { reloid: 3456 as Oid, indoid: 3085 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 8 }, // COLLOID
    cachedesc { reloid: 2607 as Oid, indoid: 2668 as Oid, nkeys: 4, key: [3, 5, 6, 1], nbuckets: 8 }, // CONDEFAULT
    cachedesc { reloid: 2607 as Oid, indoid: 2669 as Oid, nkeys: 2, key: [2, 3, 0, 0], nbuckets: 8 }, // CONNAMENSP
    cachedesc { reloid: 2606 as Oid, indoid: 2667 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 16 }, // CONSTROID
    cachedesc { reloid: 2607 as Oid, indoid: 2670 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 8 }, // CONVOID
    cachedesc { reloid: 1262 as Oid, indoid: 2672 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 4 }, // DATABASEOID
    cachedesc { reloid: 826 as Oid, indoid: 827 as Oid, nkeys: 3, key: [2, 3, 4, 0], nbuckets: 8 }, // DEFACLROLENSPOBJ
    cachedesc { reloid: 3501 as Oid, indoid: 3502 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 8 }, // ENUMOID
    cachedesc { reloid: 3501 as Oid, indoid: 3503 as Oid, nkeys: 2, key: [2, 4, 0, 0], nbuckets: 8 }, // ENUMTYPOIDNAME
    cachedesc { reloid: 3466 as Oid, indoid: 3467 as Oid, nkeys: 1, key: [2, 0, 0, 0], nbuckets: 8 }, // EVENTTRIGGERNAME
    cachedesc { reloid: 3466 as Oid, indoid: 3468 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 8 }, // EVENTTRIGGEROID
    cachedesc { reloid: 3079 as Oid, indoid: 3081 as Oid, nkeys: 1, key: [2, 0, 0, 0], nbuckets: 2 }, // EXTENSIONNAME
    cachedesc { reloid: 3079 as Oid, indoid: 3080 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 2 }, // EXTENSIONOID
    cachedesc { reloid: 2328 as Oid, indoid: 548 as Oid, nkeys: 1, key: [2, 0, 0, 0], nbuckets: 2 }, // FOREIGNDATAWRAPPERNAME
    cachedesc { reloid: 2328 as Oid, indoid: 112 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 2 }, // FOREIGNDATAWRAPPEROID
    cachedesc { reloid: 1417 as Oid, indoid: 549 as Oid, nkeys: 1, key: [2, 0, 0, 0], nbuckets: 2 }, // FOREIGNSERVERNAME
    cachedesc { reloid: 1417 as Oid, indoid: 113 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 2 }, // FOREIGNSERVEROID
    cachedesc { reloid: 3118 as Oid, indoid: 3119 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 4 }, // FOREIGNTABLEREL
    cachedesc { reloid: 2610 as Oid, indoid: 2679 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 64 }, // INDEXRELID
    cachedesc { reloid: 2612 as Oid, indoid: 2681 as Oid, nkeys: 1, key: [2, 0, 0, 0], nbuckets: 4 }, // LANGNAME
    cachedesc { reloid: 2612 as Oid, indoid: 2682 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 4 }, // LANGOID
    cachedesc { reloid: 2615 as Oid, indoid: 2684 as Oid, nkeys: 1, key: [2, 0, 0, 0], nbuckets: 4 }, // NAMESPACENAME
    cachedesc { reloid: 2615 as Oid, indoid: 2685 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 16 }, // NAMESPACEOID
    cachedesc { reloid: 2617 as Oid, indoid: 2689 as Oid, nkeys: 4, key: [2, 8, 9, 3], nbuckets: 256 }, // OPERNAMENSP
    cachedesc { reloid: 2617 as Oid, indoid: 2688 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 32 }, // OPEROID
    cachedesc { reloid: 2753 as Oid, indoid: 2754 as Oid, nkeys: 3, key: [2, 3, 4, 0], nbuckets: 8 }, // OPFAMILYAMNAMENSP
    cachedesc { reloid: 2753 as Oid, indoid: 2755 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 8 }, // OPFAMILYOID
    cachedesc { reloid: 6243 as Oid, indoid: 6246 as Oid, nkeys: 1, key: [2, 0, 0, 0], nbuckets: 4 }, // PARAMETERACLNAME
    cachedesc { reloid: 6243 as Oid, indoid: 6247 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 4 }, // PARAMETERACLOID
    cachedesc { reloid: 3350 as Oid, indoid: 3351 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 32 }, // PARTRELID
    cachedesc { reloid: 1255 as Oid, indoid: 2691 as Oid, nkeys: 3, key: [2, 20, 3, 0], nbuckets: 128 }, // PROCNAMEARGSNSP
    cachedesc { reloid: 1255 as Oid, indoid: 2690 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 128 }, // PROCOID
    cachedesc { reloid: 6104 as Oid, indoid: 6111 as Oid, nkeys: 1, key: [2, 0, 0, 0], nbuckets: 8 }, // PUBLICATIONNAME
    cachedesc { reloid: 6237 as Oid, indoid: 6238 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 64 }, // PUBLICATIONNAMESPACE
    cachedesc { reloid: 6237 as Oid, indoid: 6239 as Oid, nkeys: 2, key: [3, 2, 0, 0], nbuckets: 64 }, // PUBLICATIONNAMESPACEMAP
    cachedesc { reloid: 6104 as Oid, indoid: 6110 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 8 }, // PUBLICATIONOID
    cachedesc { reloid: 6106 as Oid, indoid: 6112 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 64 }, // PUBLICATIONREL
    cachedesc { reloid: 6106 as Oid, indoid: 6113 as Oid, nkeys: 2, key: [3, 2, 0, 0], nbuckets: 64 }, // PUBLICATIONRELMAP
    cachedesc { reloid: 3541 as Oid, indoid: 2228 as Oid, nkeys: 1, key: [3, 0, 0, 0], nbuckets: 4 }, // RANGEMULTIRANGE
    cachedesc { reloid: 3541 as Oid, indoid: 3542 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 4 }, // RANGETYPE
    cachedesc { reloid: 1259 as Oid, indoid: 2663 as Oid, nkeys: 2, key: [2, 3, 0, 0], nbuckets: 128 }, // RELNAMENSP
    cachedesc { reloid: 1259 as Oid, indoid: 2662 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 128 }, // RELOID
    cachedesc { reloid: 6000 as Oid, indoid: 6001 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 16 }, // REPLORIGIDENT
    cachedesc { reloid: 6000 as Oid, indoid: 6002 as Oid, nkeys: 1, key: [2, 0, 0, 0], nbuckets: 16 }, // REPLORIGNAME
    cachedesc { reloid: 2618 as Oid, indoid: 2693 as Oid, nkeys: 2, key: [3, 2, 0, 0], nbuckets: 8 }, // RULERELNAME
    cachedesc { reloid: 2224 as Oid, indoid: 5002 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 32 }, // SEQRELID
    cachedesc { reloid: 3429 as Oid, indoid: 3433 as Oid, nkeys: 2, key: [1, 2, 0, 0], nbuckets: 4 }, // STATEXTDATASTXOID
    cachedesc { reloid: 3381 as Oid, indoid: 3997 as Oid, nkeys: 2, key: [3, 4, 0, 0], nbuckets: 4 }, // STATEXTNAMENSP
    cachedesc { reloid: 3381 as Oid, indoid: 3380 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 4 }, // STATEXTOID
    cachedesc { reloid: 2619 as Oid, indoid: 2696 as Oid, nkeys: 3, key: [1, 2, 3, 0], nbuckets: 128 }, // STATRELATTINH
    cachedesc { reloid: 6100 as Oid, indoid: 6115 as Oid, nkeys: 2, key: [2, 4, 0, 0], nbuckets: 4 }, // SUBSCRIPTIONNAME
    cachedesc { reloid: 6100 as Oid, indoid: 6114 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 4 }, // SUBSCRIPTIONOID
    cachedesc { reloid: 6102 as Oid, indoid: 6117 as Oid, nkeys: 2, key: [2, 1, 0, 0], nbuckets: 64 }, // SUBSCRIPTIONRELMAP
    cachedesc { reloid: 1213 as Oid, indoid: 2697 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 4 }, // TABLESPACEOID
    cachedesc { reloid: 3576 as Oid, indoid: 3574 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 16 }, // TRFOID
    cachedesc { reloid: 3576 as Oid, indoid: 3575 as Oid, nkeys: 2, key: [2, 3, 0, 0], nbuckets: 16 }, // TRFTYPELANG
    cachedesc { reloid: 3603 as Oid, indoid: 3609 as Oid, nkeys: 3, key: [1, 2, 3, 0], nbuckets: 2 }, // TSCONFIGMAP
    cachedesc { reloid: 3602 as Oid, indoid: 3608 as Oid, nkeys: 2, key: [2, 3, 0, 0], nbuckets: 2 }, // TSCONFIGNAMENSP
    cachedesc { reloid: 3602 as Oid, indoid: 3712 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 2 }, // TSCONFIGOID
    cachedesc { reloid: 3600 as Oid, indoid: 3604 as Oid, nkeys: 2, key: [2, 3, 0, 0], nbuckets: 2 }, // TSDICTNAMENSP
    cachedesc { reloid: 3600 as Oid, indoid: 3605 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 2 }, // TSDICTOID
    cachedesc { reloid: 3601 as Oid, indoid: 3606 as Oid, nkeys: 2, key: [2, 3, 0, 0], nbuckets: 2 }, // TSPARSERNAMENSP
    cachedesc { reloid: 3601 as Oid, indoid: 3607 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 2 }, // TSPARSEROID
    cachedesc { reloid: 3764 as Oid, indoid: 3766 as Oid, nkeys: 2, key: [2, 3, 0, 0], nbuckets: 2 }, // TSTEMPLATENAMENSP
    cachedesc { reloid: 3764 as Oid, indoid: 3767 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 2 }, // TSTEMPLATEOID
    cachedesc { reloid: 1247 as Oid, indoid: 2704 as Oid, nkeys: 2, key: [2, 3, 0, 0], nbuckets: 64 }, // TYPENAMENSP
    cachedesc { reloid: 1247 as Oid, indoid: 2703 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 64 }, // TYPEOID
    cachedesc { reloid: 1418 as Oid, indoid: 174 as Oid, nkeys: 1, key: [1, 0, 0, 0], nbuckets: 2 }, // USERMAPPINGOID
    cachedesc { reloid: 1418 as Oid, indoid: 175 as Oid, nkeys: 2, key: [2, 3, 0, 0], nbuckets: 2 }, // USERMAPPINGUSERSERVER
];
