//! Translation of postgres/src/backend/nodes/equalfuncs.c - bootstrap stub.
//!
//! `equal(a, b)` performs a deep structural comparison of two nodes. The real
//! implementation is generated by gen_node_support.pl across every node type and
//! is large; it will be translated once enough node types exist. Until then this
//! stub supports the only equality the data-structure layer needs at runtime.
//!
//! TODO(pg-port): translate the full generated equalfuncs.c (_equalNNN per type).

use crate::nodes::nodes::{nodeTag, NodeTag};
use core::ffi::c_void;

/// `equal(a, b)`: are two nodes equal? Returns true for pointer-identical inputs
/// (including both NULL) and otherwise is not yet implemented.
///
/// # Safety
/// `a`/`b` must each be NULL or a valid node pointer.
pub unsafe fn equal(a: *const c_void, b: *const c_void) -> bool {
    if a == b {
        // Two identical pointers (or both NULL) are trivially equal.
        return true;
    }
    if a.is_null() || b.is_null() {
        return false;
    }
    // Different node types are never equal; this much we can do without the
    // per-type comparators.
    if nodeTag(a) != nodeTag(b) {
        return false;
    }
    // TODO(pg-port): per-type deep comparison (generated equalfuncs.c).
    unimplemented!("equal(): deep node comparison not yet translated (equalfuncs.c)");
}

/// Suppress the "unused import" lint until the per-type comparators arrive.
#[allow(dead_code)]
fn _uses(_t: NodeTag) {}
