//! Translated from PostgreSQL src/include/utils/wait_event_types.h
//!
//! Wait-event enums. In C `generate-wait_event_types.pl` emits these from
//! `wait_event_names.txt`; here one `#[repr(u32)]` enum per wait class, each
//! discriminant = `(class_id << 24) | index` (matching PG's wait_event_info
//! encoding). `name()` returns the display string pg_stat shows. Descriptions are
//! documentation-only in PG and omitted. Regenerate with ai/harness/gen_flat_tables.py.


#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum WaitEventActivity {
    ArchiverMain = 0x05000000,
    AutovacuumMain = 0x05000001,
    BgwriterHibernate = 0x05000002,
    BgwriterMain = 0x05000003,
    CheckpointerMain = 0x05000004,
    CheckpointerShutdown = 0x05000005,
    IoWorkerMain = 0x05000006,
    LogicalApplyMain = 0x05000007,
    LogicalLauncherMain = 0x05000008,
    LogicalParallelApplyMain = 0x05000009,
    RecoveryWalStream = 0x0500000A,
    ReplicationSlotsyncMain = 0x0500000B,
    ReplicationSlotsyncShutdown = 0x0500000C,
    SysloggerMain = 0x0500000D,
    WalReceiverMain = 0x0500000E,
    WalSenderMain = 0x0500000F,
    WalSummarizerWal = 0x05000010,
    WalWriterMain = 0x05000011,
}

impl WaitEventActivity {
    pub fn name(self) -> &'static str {
        match self {
            WaitEventActivity::ArchiverMain => "ArchiverMain",
            WaitEventActivity::AutovacuumMain => "AutovacuumMain",
            WaitEventActivity::BgwriterHibernate => "BgwriterHibernate",
            WaitEventActivity::BgwriterMain => "BgwriterMain",
            WaitEventActivity::CheckpointerMain => "CheckpointerMain",
            WaitEventActivity::CheckpointerShutdown => "CheckpointerShutdown",
            WaitEventActivity::IoWorkerMain => "IoWorkerMain",
            WaitEventActivity::LogicalApplyMain => "LogicalApplyMain",
            WaitEventActivity::LogicalLauncherMain => "LogicalLauncherMain",
            WaitEventActivity::LogicalParallelApplyMain => "LogicalParallelApplyMain",
            WaitEventActivity::RecoveryWalStream => "RecoveryWalStream",
            WaitEventActivity::ReplicationSlotsyncMain => "ReplicationSlotsyncMain",
            WaitEventActivity::ReplicationSlotsyncShutdown => "ReplicationSlotsyncShutdown",
            WaitEventActivity::SysloggerMain => "SysloggerMain",
            WaitEventActivity::WalReceiverMain => "WalReceiverMain",
            WaitEventActivity::WalSenderMain => "WalSenderMain",
            WaitEventActivity::WalSummarizerWal => "WalSummarizerWal",
            WaitEventActivity::WalWriterMain => "WalWriterMain",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum WaitEventClient {
    ClientRead = 0x06000000,
    ClientWrite = 0x06000001,
    GssOpenServer = 0x06000002,
    LibpqwalreceiverConnect = 0x06000003,
    LibpqwalreceiverReceive = 0x06000004,
    SslOpenServer = 0x06000005,
    WaitForStandbyConfirmation = 0x06000006,
    WalSenderWaitForWal = 0x06000007,
    WalSenderWriteData = 0x06000008,
}

impl WaitEventClient {
    pub fn name(self) -> &'static str {
        match self {
            WaitEventClient::ClientRead => "ClientRead",
            WaitEventClient::ClientWrite => "ClientWrite",
            WaitEventClient::GssOpenServer => "GssOpenServer",
            WaitEventClient::LibpqwalreceiverConnect => "LibpqwalreceiverConnect",
            WaitEventClient::LibpqwalreceiverReceive => "LibpqwalreceiverReceive",
            WaitEventClient::SslOpenServer => "SslOpenServer",
            WaitEventClient::WaitForStandbyConfirmation => "WaitForStandbyConfirmation",
            WaitEventClient::WalSenderWaitForWal => "WalSenderWaitForWal",
            WaitEventClient::WalSenderWriteData => "WalSenderWriteData",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum WaitEventIPC {
    AppendReady = 0x08000000,
    ArchiveCleanupCommand = 0x08000001,
    ArchiveCommand = 0x08000002,
    BackendTermination = 0x08000003,
    BackupWaitWalArchive = 0x08000004,
    BgworkerShutdown = 0x08000005,
    BgworkerStartup = 0x08000006,
    BtreePage = 0x08000007,
    BufferIo = 0x08000008,
    CheckpointDelayComplete = 0x08000009,
    CheckpointDelayStart = 0x0800000A,
    CheckpointDone = 0x0800000B,
    CheckpointStart = 0x0800000C,
    ExecuteGather = 0x0800000D,
    HashBatchAllocate = 0x0800000E,
    HashBatchElect = 0x0800000F,
    HashBatchLoad = 0x08000010,
    HashBuildAllocate = 0x08000011,
    HashBuildElect = 0x08000012,
    HashBuildHashInner = 0x08000013,
    HashBuildHashOuter = 0x08000014,
    HashGrowBatchesDecide = 0x08000015,
    HashGrowBatchesElect = 0x08000016,
    HashGrowBatchesFinish = 0x08000017,
    HashGrowBatchesReallocate = 0x08000018,
    HashGrowBatchesRepartition = 0x08000019,
    HashGrowBucketsElect = 0x0800001A,
    HashGrowBucketsReallocate = 0x0800001B,
    HashGrowBucketsReinsert = 0x0800001C,
    LogicalApplySendData = 0x0800001D,
    LogicalParallelApplyStateChange = 0x0800001E,
    LogicalSyncData = 0x0800001F,
    LogicalSyncStateChange = 0x08000020,
    MessageQueueInternal = 0x08000021,
    MessageQueuePutMessage = 0x08000022,
    MessageQueueReceive = 0x08000023,
    MessageQueueSend = 0x08000024,
    MultixactCreation = 0x08000025,
    ParallelBitmapScan = 0x08000026,
    ParallelCreateIndexScan = 0x08000027,
    ParallelFinish = 0x08000028,
    ProcarrayGroupUpdate = 0x08000029,
    ProcSignalBarrier = 0x0800002A,
    Promote = 0x0800002B,
    RecoveryConflictSnapshot = 0x0800002C,
    RecoveryConflictTablespace = 0x0800002D,
    RecoveryEndCommand = 0x0800002E,
    RecoveryPause = 0x0800002F,
    ReplicationOriginDrop = 0x08000030,
    ReplicationSlotDrop = 0x08000031,
    RestoreCommand = 0x08000032,
    SafeSnapshot = 0x08000033,
    SyncRep = 0x08000034,
    WalReceiverExit = 0x08000035,
    WalReceiverWaitStart = 0x08000036,
    WalSummaryReady = 0x08000037,
    XactGroupUpdate = 0x08000038,
}

impl WaitEventIPC {
    pub fn name(self) -> &'static str {
        match self {
            WaitEventIPC::AppendReady => "AppendReady",
            WaitEventIPC::ArchiveCleanupCommand => "ArchiveCleanupCommand",
            WaitEventIPC::ArchiveCommand => "ArchiveCommand",
            WaitEventIPC::BackendTermination => "BackendTermination",
            WaitEventIPC::BackupWaitWalArchive => "BackupWaitWalArchive",
            WaitEventIPC::BgworkerShutdown => "BgworkerShutdown",
            WaitEventIPC::BgworkerStartup => "BgworkerStartup",
            WaitEventIPC::BtreePage => "BtreePage",
            WaitEventIPC::BufferIo => "BufferIo",
            WaitEventIPC::CheckpointDelayComplete => "CheckpointDelayComplete",
            WaitEventIPC::CheckpointDelayStart => "CheckpointDelayStart",
            WaitEventIPC::CheckpointDone => "CheckpointDone",
            WaitEventIPC::CheckpointStart => "CheckpointStart",
            WaitEventIPC::ExecuteGather => "ExecuteGather",
            WaitEventIPC::HashBatchAllocate => "HashBatchAllocate",
            WaitEventIPC::HashBatchElect => "HashBatchElect",
            WaitEventIPC::HashBatchLoad => "HashBatchLoad",
            WaitEventIPC::HashBuildAllocate => "HashBuildAllocate",
            WaitEventIPC::HashBuildElect => "HashBuildElect",
            WaitEventIPC::HashBuildHashInner => "HashBuildHashInner",
            WaitEventIPC::HashBuildHashOuter => "HashBuildHashOuter",
            WaitEventIPC::HashGrowBatchesDecide => "HashGrowBatchesDecide",
            WaitEventIPC::HashGrowBatchesElect => "HashGrowBatchesElect",
            WaitEventIPC::HashGrowBatchesFinish => "HashGrowBatchesFinish",
            WaitEventIPC::HashGrowBatchesReallocate => "HashGrowBatchesReallocate",
            WaitEventIPC::HashGrowBatchesRepartition => "HashGrowBatchesRepartition",
            WaitEventIPC::HashGrowBucketsElect => "HashGrowBucketsElect",
            WaitEventIPC::HashGrowBucketsReallocate => "HashGrowBucketsReallocate",
            WaitEventIPC::HashGrowBucketsReinsert => "HashGrowBucketsReinsert",
            WaitEventIPC::LogicalApplySendData => "LogicalApplySendData",
            WaitEventIPC::LogicalParallelApplyStateChange => "LogicalParallelApplyStateChange",
            WaitEventIPC::LogicalSyncData => "LogicalSyncData",
            WaitEventIPC::LogicalSyncStateChange => "LogicalSyncStateChange",
            WaitEventIPC::MessageQueueInternal => "MessageQueueInternal",
            WaitEventIPC::MessageQueuePutMessage => "MessageQueuePutMessage",
            WaitEventIPC::MessageQueueReceive => "MessageQueueReceive",
            WaitEventIPC::MessageQueueSend => "MessageQueueSend",
            WaitEventIPC::MultixactCreation => "MultixactCreation",
            WaitEventIPC::ParallelBitmapScan => "ParallelBitmapScan",
            WaitEventIPC::ParallelCreateIndexScan => "ParallelCreateIndexScan",
            WaitEventIPC::ParallelFinish => "ParallelFinish",
            WaitEventIPC::ProcarrayGroupUpdate => "ProcarrayGroupUpdate",
            WaitEventIPC::ProcSignalBarrier => "ProcSignalBarrier",
            WaitEventIPC::Promote => "Promote",
            WaitEventIPC::RecoveryConflictSnapshot => "RecoveryConflictSnapshot",
            WaitEventIPC::RecoveryConflictTablespace => "RecoveryConflictTablespace",
            WaitEventIPC::RecoveryEndCommand => "RecoveryEndCommand",
            WaitEventIPC::RecoveryPause => "RecoveryPause",
            WaitEventIPC::ReplicationOriginDrop => "ReplicationOriginDrop",
            WaitEventIPC::ReplicationSlotDrop => "ReplicationSlotDrop",
            WaitEventIPC::RestoreCommand => "RestoreCommand",
            WaitEventIPC::SafeSnapshot => "SafeSnapshot",
            WaitEventIPC::SyncRep => "SyncRep",
            WaitEventIPC::WalReceiverExit => "WalReceiverExit",
            WaitEventIPC::WalReceiverWaitStart => "WalReceiverWaitStart",
            WaitEventIPC::WalSummaryReady => "WalSummaryReady",
            WaitEventIPC::XactGroupUpdate => "XactGroupUpdate",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum WaitEventTimeout {
    BaseBackupThrottle = 0x09000000,
    CheckpointWriteDelay = 0x09000001,
    PgSleep = 0x09000002,
    RecoveryApplyDelay = 0x09000003,
    RecoveryRetrieveRetryInterval = 0x09000004,
    RegisterSyncRequest = 0x09000005,
    SpinDelay = 0x09000006,
    VacuumDelay = 0x09000007,
    VacuumTruncate = 0x09000008,
    WalSummarizerError = 0x09000009,
}

impl WaitEventTimeout {
    pub fn name(self) -> &'static str {
        match self {
            WaitEventTimeout::BaseBackupThrottle => "BaseBackupThrottle",
            WaitEventTimeout::CheckpointWriteDelay => "CheckpointWriteDelay",
            WaitEventTimeout::PgSleep => "PgSleep",
            WaitEventTimeout::RecoveryApplyDelay => "RecoveryApplyDelay",
            WaitEventTimeout::RecoveryRetrieveRetryInterval => "RecoveryRetrieveRetryInterval",
            WaitEventTimeout::RegisterSyncRequest => "RegisterSyncRequest",
            WaitEventTimeout::SpinDelay => "SpinDelay",
            WaitEventTimeout::VacuumDelay => "VacuumDelay",
            WaitEventTimeout::VacuumTruncate => "VacuumTruncate",
            WaitEventTimeout::WalSummarizerError => "WalSummarizerError",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum WaitEventIO {
    AioIoCompletion = 0x0A000000,
    AioIoUringSubmit = 0x0A000001,
    AioIoUringExecution = 0x0A000002,
    BasebackupRead = 0x0A000003,
    BasebackupSync = 0x0A000004,
    BasebackupWrite = 0x0A000005,
    BuffileRead = 0x0A000006,
    BuffileWrite = 0x0A000007,
    BuffileTruncate = 0x0A000008,
    ControlFileRead = 0x0A000009,
    ControlFileSync = 0x0A00000A,
    ControlFileSyncUpdate = 0x0A00000B,
    ControlFileWrite = 0x0A00000C,
    ControlFileWriteUpdate = 0x0A00000D,
    CopyFileCopy = 0x0A00000E,
    CopyFileRead = 0x0A00000F,
    CopyFileWrite = 0x0A000010,
    DataFileExtend = 0x0A000011,
    DataFileFlush = 0x0A000012,
    DataFileImmediateSync = 0x0A000013,
    DataFilePrefetch = 0x0A000014,
    DataFileRead = 0x0A000015,
    DataFileSync = 0x0A000016,
    DataFileTruncate = 0x0A000017,
    DataFileWrite = 0x0A000018,
    DsmAllocate = 0x0A000019,
    DsmFillZeroWrite = 0x0A00001A,
    LockFileAddtodatadirRead = 0x0A00001B,
    LockFileAddtodatadirSync = 0x0A00001C,
    LockFileAddtodatadirWrite = 0x0A00001D,
    LockFileCreateRead = 0x0A00001E,
    LockFileCreateSync = 0x0A00001F,
    LockFileCreateWrite = 0x0A000020,
    LockFileRecheckdatadirRead = 0x0A000021,
    LogicalRewriteCheckpointSync = 0x0A000022,
    LogicalRewriteMappingSync = 0x0A000023,
    LogicalRewriteMappingWrite = 0x0A000024,
    LogicalRewriteSync = 0x0A000025,
    LogicalRewriteTruncate = 0x0A000026,
    LogicalRewriteWrite = 0x0A000027,
    RelationMapRead = 0x0A000028,
    RelationMapReplace = 0x0A000029,
    RelationMapWrite = 0x0A00002A,
    ReorderBufferRead = 0x0A00002B,
    ReorderBufferWrite = 0x0A00002C,
    ReorderLogicalMappingRead = 0x0A00002D,
    ReplicationSlotRead = 0x0A00002E,
    ReplicationSlotRestoreSync = 0x0A00002F,
    ReplicationSlotSync = 0x0A000030,
    ReplicationSlotWrite = 0x0A000031,
    SlruFlushSync = 0x0A000032,
    SlruRead = 0x0A000033,
    SlruSync = 0x0A000034,
    SlruWrite = 0x0A000035,
    SnapbuildRead = 0x0A000036,
    SnapbuildSync = 0x0A000037,
    SnapbuildWrite = 0x0A000038,
    TimelineHistoryFileSync = 0x0A000039,
    TimelineHistoryFileWrite = 0x0A00003A,
    TimelineHistoryRead = 0x0A00003B,
    TimelineHistorySync = 0x0A00003C,
    TimelineHistoryWrite = 0x0A00003D,
    TwophaseFileRead = 0x0A00003E,
    TwophaseFileSync = 0x0A00003F,
    TwophaseFileWrite = 0x0A000040,
    VersionFileSync = 0x0A000041,
    VersionFileWrite = 0x0A000042,
    WalsenderTimelineHistoryRead = 0x0A000043,
    WalBootstrapSync = 0x0A000044,
    WalBootstrapWrite = 0x0A000045,
    WalCopyRead = 0x0A000046,
    WalCopySync = 0x0A000047,
    WalCopyWrite = 0x0A000048,
    WalInitSync = 0x0A000049,
    WalInitWrite = 0x0A00004A,
    WalRead = 0x0A00004B,
    WalSummaryRead = 0x0A00004C,
    WalSummaryWrite = 0x0A00004D,
    WalSync = 0x0A00004E,
    WalSyncMethodAssign = 0x0A00004F,
    WalWrite = 0x0A000050,
}

impl WaitEventIO {
    pub fn name(self) -> &'static str {
        match self {
            WaitEventIO::AioIoCompletion => "AioIoCompletion",
            WaitEventIO::AioIoUringSubmit => "AioIoUringSubmit",
            WaitEventIO::AioIoUringExecution => "AioIoUringExecution",
            WaitEventIO::BasebackupRead => "BasebackupRead",
            WaitEventIO::BasebackupSync => "BasebackupSync",
            WaitEventIO::BasebackupWrite => "BasebackupWrite",
            WaitEventIO::BuffileRead => "BuffileRead",
            WaitEventIO::BuffileWrite => "BuffileWrite",
            WaitEventIO::BuffileTruncate => "BuffileTruncate",
            WaitEventIO::ControlFileRead => "ControlFileRead",
            WaitEventIO::ControlFileSync => "ControlFileSync",
            WaitEventIO::ControlFileSyncUpdate => "ControlFileSyncUpdate",
            WaitEventIO::ControlFileWrite => "ControlFileWrite",
            WaitEventIO::ControlFileWriteUpdate => "ControlFileWriteUpdate",
            WaitEventIO::CopyFileCopy => "CopyFileCopy",
            WaitEventIO::CopyFileRead => "CopyFileRead",
            WaitEventIO::CopyFileWrite => "CopyFileWrite",
            WaitEventIO::DataFileExtend => "DataFileExtend",
            WaitEventIO::DataFileFlush => "DataFileFlush",
            WaitEventIO::DataFileImmediateSync => "DataFileImmediateSync",
            WaitEventIO::DataFilePrefetch => "DataFilePrefetch",
            WaitEventIO::DataFileRead => "DataFileRead",
            WaitEventIO::DataFileSync => "DataFileSync",
            WaitEventIO::DataFileTruncate => "DataFileTruncate",
            WaitEventIO::DataFileWrite => "DataFileWrite",
            WaitEventIO::DsmAllocate => "DsmAllocate",
            WaitEventIO::DsmFillZeroWrite => "DsmFillZeroWrite",
            WaitEventIO::LockFileAddtodatadirRead => "LockFileAddtodatadirRead",
            WaitEventIO::LockFileAddtodatadirSync => "LockFileAddtodatadirSync",
            WaitEventIO::LockFileAddtodatadirWrite => "LockFileAddtodatadirWrite",
            WaitEventIO::LockFileCreateRead => "LockFileCreateRead",
            WaitEventIO::LockFileCreateSync => "LockFileCreateSync",
            WaitEventIO::LockFileCreateWrite => "LockFileCreateWrite",
            WaitEventIO::LockFileRecheckdatadirRead => "LockFileRecheckdatadirRead",
            WaitEventIO::LogicalRewriteCheckpointSync => "LogicalRewriteCheckpointSync",
            WaitEventIO::LogicalRewriteMappingSync => "LogicalRewriteMappingSync",
            WaitEventIO::LogicalRewriteMappingWrite => "LogicalRewriteMappingWrite",
            WaitEventIO::LogicalRewriteSync => "LogicalRewriteSync",
            WaitEventIO::LogicalRewriteTruncate => "LogicalRewriteTruncate",
            WaitEventIO::LogicalRewriteWrite => "LogicalRewriteWrite",
            WaitEventIO::RelationMapRead => "RelationMapRead",
            WaitEventIO::RelationMapReplace => "RelationMapReplace",
            WaitEventIO::RelationMapWrite => "RelationMapWrite",
            WaitEventIO::ReorderBufferRead => "ReorderBufferRead",
            WaitEventIO::ReorderBufferWrite => "ReorderBufferWrite",
            WaitEventIO::ReorderLogicalMappingRead => "ReorderLogicalMappingRead",
            WaitEventIO::ReplicationSlotRead => "ReplicationSlotRead",
            WaitEventIO::ReplicationSlotRestoreSync => "ReplicationSlotRestoreSync",
            WaitEventIO::ReplicationSlotSync => "ReplicationSlotSync",
            WaitEventIO::ReplicationSlotWrite => "ReplicationSlotWrite",
            WaitEventIO::SlruFlushSync => "SlruFlushSync",
            WaitEventIO::SlruRead => "SlruRead",
            WaitEventIO::SlruSync => "SlruSync",
            WaitEventIO::SlruWrite => "SlruWrite",
            WaitEventIO::SnapbuildRead => "SnapbuildRead",
            WaitEventIO::SnapbuildSync => "SnapbuildSync",
            WaitEventIO::SnapbuildWrite => "SnapbuildWrite",
            WaitEventIO::TimelineHistoryFileSync => "TimelineHistoryFileSync",
            WaitEventIO::TimelineHistoryFileWrite => "TimelineHistoryFileWrite",
            WaitEventIO::TimelineHistoryRead => "TimelineHistoryRead",
            WaitEventIO::TimelineHistorySync => "TimelineHistorySync",
            WaitEventIO::TimelineHistoryWrite => "TimelineHistoryWrite",
            WaitEventIO::TwophaseFileRead => "TwophaseFileRead",
            WaitEventIO::TwophaseFileSync => "TwophaseFileSync",
            WaitEventIO::TwophaseFileWrite => "TwophaseFileWrite",
            WaitEventIO::VersionFileSync => "VersionFileSync",
            WaitEventIO::VersionFileWrite => "VersionFileWrite",
            WaitEventIO::WalsenderTimelineHistoryRead => "WalsenderTimelineHistoryRead",
            WaitEventIO::WalBootstrapSync => "WalBootstrapSync",
            WaitEventIO::WalBootstrapWrite => "WalBootstrapWrite",
            WaitEventIO::WalCopyRead => "WalCopyRead",
            WaitEventIO::WalCopySync => "WalCopySync",
            WaitEventIO::WalCopyWrite => "WalCopyWrite",
            WaitEventIO::WalInitSync => "WalInitSync",
            WaitEventIO::WalInitWrite => "WalInitWrite",
            WaitEventIO::WalRead => "WalRead",
            WaitEventIO::WalSummaryRead => "WalSummaryRead",
            WaitEventIO::WalSummaryWrite => "WalSummaryWrite",
            WaitEventIO::WalSync => "WalSync",
            WaitEventIO::WalSyncMethodAssign => "WalSyncMethodAssign",
            WaitEventIO::WalWrite => "WalWrite",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum WaitEventBufferPin {
    BufferPin = 0x04000000,
}

impl WaitEventBufferPin {
    pub fn name(self) -> &'static str {
        match self {
            WaitEventBufferPin::BufferPin => "BufferPin",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum WaitEventExtension {
    Extension = 0x07000000,
}

impl WaitEventExtension {
    pub fn name(self) -> &'static str {
        match self {
            WaitEventExtension::Extension => "Extension",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum WaitEventLWLock {
    ShmemIndex = 0x01000000,
    OidGen = 0x01000001,
    XidGen = 0x01000002,
    ProcArray = 0x01000003,
    SInvalRead = 0x01000004,
    SInvalWrite = 0x01000005,
    WALBufMapping = 0x01000006,
    WALWrite = 0x01000007,
    ControlFile = 0x01000008,
    MultiXactGen = 0x01000009,
    RelCacheInit = 0x0100000A,
    CheckpointerComm = 0x0100000B,
    TwoPhaseState = 0x0100000C,
    TablespaceCreate = 0x0100000D,
    BtreeVacuum = 0x0100000E,
    AddinShmemInit = 0x0100000F,
    Autovacuum = 0x01000010,
    AutovacuumSchedule = 0x01000011,
    SyncScan = 0x01000012,
    RelationMapping = 0x01000013,
    NotifyQueue = 0x01000014,
    SerializableXactHash = 0x01000015,
    SerializableFinishedList = 0x01000016,
    SerializablePredicateList = 0x01000017,
    SyncRep = 0x01000018,
    BackgroundWorker = 0x01000019,
    DynamicSharedMemoryControl = 0x0100001A,
    AutoFile = 0x0100001B,
    ReplicationSlotAllocation = 0x0100001C,
    ReplicationSlotControl = 0x0100001D,
    CommitTs = 0x0100001E,
    ReplicationOrigin = 0x0100001F,
    MultiXactTruncation = 0x01000020,
    LogicalRepWorker = 0x01000021,
    XactTruncation = 0x01000022,
    WrapLimitsVacuum = 0x01000023,
    NotifyQueueTail = 0x01000024,
    WaitEventCustom = 0x01000025,
    WALSummarizer = 0x01000026,
    DSMRegistry = 0x01000027,
    InjectionPoint = 0x01000028,
    SerialControl = 0x01000029,
    AioWorkerSubmissionQueue = 0x0100002A,
    XactBuffer = 0x0100002B,
    CommitTsBuffer = 0x0100002C,
    SubtransBuffer = 0x0100002D,
    MultiXactOffsetBuffer = 0x0100002E,
    MultiXactMemberBuffer = 0x0100002F,
    NotifyBuffer = 0x01000030,
    SerialBuffer = 0x01000031,
    WALInsert = 0x01000032,
    BufferContent = 0x01000033,
    ReplicationOriginState = 0x01000034,
    ReplicationSlotIO = 0x01000035,
    LockFastPath = 0x01000036,
    BufferMapping = 0x01000037,
    LockManager = 0x01000038,
    PredicateLockManager = 0x01000039,
    ParallelHashJoin = 0x0100003A,
    ParallelBtreeScan = 0x0100003B,
    ParallelQueryDSA = 0x0100003C,
    PerSessionDSA = 0x0100003D,
    PerSessionRecordType = 0x0100003E,
    PerSessionRecordTypmod = 0x0100003F,
    SharedTupleStore = 0x01000040,
    SharedTidBitmap = 0x01000041,
    ParallelAppend = 0x01000042,
    PerXactPredicateList = 0x01000043,
    PgStatsDSA = 0x01000044,
    PgStatsHash = 0x01000045,
    PgStatsData = 0x01000046,
    LogicalRepLauncherDSA = 0x01000047,
    LogicalRepLauncherHash = 0x01000048,
    DSMRegistryDSA = 0x01000049,
    DSMRegistryHash = 0x0100004A,
    CommitTsSLRU = 0x0100004B,
    MultiXactOffsetSLRU = 0x0100004C,
    MultiXactMemberSLRU = 0x0100004D,
    NotifySLRU = 0x0100004E,
    SerialSLRU = 0x0100004F,
    SubtransSLRU = 0x01000050,
    XactSLRU = 0x01000051,
    ParallelVacuumDSA = 0x01000052,
    AioUringCompletion = 0x01000053,
}

impl WaitEventLWLock {
    pub fn name(self) -> &'static str {
        match self {
            WaitEventLWLock::ShmemIndex => "ShmemIndex",
            WaitEventLWLock::OidGen => "OidGen",
            WaitEventLWLock::XidGen => "XidGen",
            WaitEventLWLock::ProcArray => "ProcArray",
            WaitEventLWLock::SInvalRead => "SInvalRead",
            WaitEventLWLock::SInvalWrite => "SInvalWrite",
            WaitEventLWLock::WALBufMapping => "WALBufMapping",
            WaitEventLWLock::WALWrite => "WALWrite",
            WaitEventLWLock::ControlFile => "ControlFile",
            WaitEventLWLock::MultiXactGen => "MultiXactGen",
            WaitEventLWLock::RelCacheInit => "RelCacheInit",
            WaitEventLWLock::CheckpointerComm => "CheckpointerComm",
            WaitEventLWLock::TwoPhaseState => "TwoPhaseState",
            WaitEventLWLock::TablespaceCreate => "TablespaceCreate",
            WaitEventLWLock::BtreeVacuum => "BtreeVacuum",
            WaitEventLWLock::AddinShmemInit => "AddinShmemInit",
            WaitEventLWLock::Autovacuum => "Autovacuum",
            WaitEventLWLock::AutovacuumSchedule => "AutovacuumSchedule",
            WaitEventLWLock::SyncScan => "SyncScan",
            WaitEventLWLock::RelationMapping => "RelationMapping",
            WaitEventLWLock::NotifyQueue => "NotifyQueue",
            WaitEventLWLock::SerializableXactHash => "SerializableXactHash",
            WaitEventLWLock::SerializableFinishedList => "SerializableFinishedList",
            WaitEventLWLock::SerializablePredicateList => "SerializablePredicateList",
            WaitEventLWLock::SyncRep => "SyncRep",
            WaitEventLWLock::BackgroundWorker => "BackgroundWorker",
            WaitEventLWLock::DynamicSharedMemoryControl => "DynamicSharedMemoryControl",
            WaitEventLWLock::AutoFile => "AutoFile",
            WaitEventLWLock::ReplicationSlotAllocation => "ReplicationSlotAllocation",
            WaitEventLWLock::ReplicationSlotControl => "ReplicationSlotControl",
            WaitEventLWLock::CommitTs => "CommitTs",
            WaitEventLWLock::ReplicationOrigin => "ReplicationOrigin",
            WaitEventLWLock::MultiXactTruncation => "MultiXactTruncation",
            WaitEventLWLock::LogicalRepWorker => "LogicalRepWorker",
            WaitEventLWLock::XactTruncation => "XactTruncation",
            WaitEventLWLock::WrapLimitsVacuum => "WrapLimitsVacuum",
            WaitEventLWLock::NotifyQueueTail => "NotifyQueueTail",
            WaitEventLWLock::WaitEventCustom => "WaitEventCustom",
            WaitEventLWLock::WALSummarizer => "WALSummarizer",
            WaitEventLWLock::DSMRegistry => "DSMRegistry",
            WaitEventLWLock::InjectionPoint => "InjectionPoint",
            WaitEventLWLock::SerialControl => "SerialControl",
            WaitEventLWLock::AioWorkerSubmissionQueue => "AioWorkerSubmissionQueue",
            WaitEventLWLock::XactBuffer => "XactBuffer",
            WaitEventLWLock::CommitTsBuffer => "CommitTsBuffer",
            WaitEventLWLock::SubtransBuffer => "SubtransBuffer",
            WaitEventLWLock::MultiXactOffsetBuffer => "MultiXactOffsetBuffer",
            WaitEventLWLock::MultiXactMemberBuffer => "MultiXactMemberBuffer",
            WaitEventLWLock::NotifyBuffer => "NotifyBuffer",
            WaitEventLWLock::SerialBuffer => "SerialBuffer",
            WaitEventLWLock::WALInsert => "WALInsert",
            WaitEventLWLock::BufferContent => "BufferContent",
            WaitEventLWLock::ReplicationOriginState => "ReplicationOriginState",
            WaitEventLWLock::ReplicationSlotIO => "ReplicationSlotIO",
            WaitEventLWLock::LockFastPath => "LockFastPath",
            WaitEventLWLock::BufferMapping => "BufferMapping",
            WaitEventLWLock::LockManager => "LockManager",
            WaitEventLWLock::PredicateLockManager => "PredicateLockManager",
            WaitEventLWLock::ParallelHashJoin => "ParallelHashJoin",
            WaitEventLWLock::ParallelBtreeScan => "ParallelBtreeScan",
            WaitEventLWLock::ParallelQueryDSA => "ParallelQueryDSA",
            WaitEventLWLock::PerSessionDSA => "PerSessionDSA",
            WaitEventLWLock::PerSessionRecordType => "PerSessionRecordType",
            WaitEventLWLock::PerSessionRecordTypmod => "PerSessionRecordTypmod",
            WaitEventLWLock::SharedTupleStore => "SharedTupleStore",
            WaitEventLWLock::SharedTidBitmap => "SharedTidBitmap",
            WaitEventLWLock::ParallelAppend => "ParallelAppend",
            WaitEventLWLock::PerXactPredicateList => "PerXactPredicateList",
            WaitEventLWLock::PgStatsDSA => "PgStatsDSA",
            WaitEventLWLock::PgStatsHash => "PgStatsHash",
            WaitEventLWLock::PgStatsData => "PgStatsData",
            WaitEventLWLock::LogicalRepLauncherDSA => "LogicalRepLauncherDSA",
            WaitEventLWLock::LogicalRepLauncherHash => "LogicalRepLauncherHash",
            WaitEventLWLock::DSMRegistryDSA => "DSMRegistryDSA",
            WaitEventLWLock::DSMRegistryHash => "DSMRegistryHash",
            WaitEventLWLock::CommitTsSLRU => "CommitTsSLRU",
            WaitEventLWLock::MultiXactOffsetSLRU => "MultiXactOffsetSLRU",
            WaitEventLWLock::MultiXactMemberSLRU => "MultiXactMemberSLRU",
            WaitEventLWLock::NotifySLRU => "NotifySLRU",
            WaitEventLWLock::SerialSLRU => "SerialSLRU",
            WaitEventLWLock::SubtransSLRU => "SubtransSLRU",
            WaitEventLWLock::XactSLRU => "XactSLRU",
            WaitEventLWLock::ParallelVacuumDSA => "ParallelVacuumDSA",
            WaitEventLWLock::AioUringCompletion => "AioUringCompletion",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum WaitEventLock {
    Relation = 0x03000000,
    Extend = 0x03000001,
    Frozenid = 0x03000002,
    Page = 0x03000003,
    Tuple = 0x03000004,
    Transactionid = 0x03000005,
    Virtualxid = 0x03000006,
    Spectoken = 0x03000007,
    Object = 0x03000008,
    Userlock = 0x03000009,
    Advisory = 0x0300000A,
    Applytransaction = 0x0300000B,
}

impl WaitEventLock {
    pub fn name(self) -> &'static str {
        match self {
            WaitEventLock::Relation => "Relation",
            WaitEventLock::Extend => "Extend",
            WaitEventLock::Frozenid => "Frozenid",
            WaitEventLock::Page => "Page",
            WaitEventLock::Tuple => "Tuple",
            WaitEventLock::Transactionid => "Transactionid",
            WaitEventLock::Virtualxid => "Virtualxid",
            WaitEventLock::Spectoken => "Spectoken",
            WaitEventLock::Object => "Object",
            WaitEventLock::Userlock => "Userlock",
            WaitEventLock::Advisory => "Advisory",
            WaitEventLock::Applytransaction => "Applytransaction",
        }
    }
}
