//! Translated from PostgreSQL src/include/utils/wait_event_types.h
//!
//! Wait-event enums. In C `generate-wait_event_types.pl` emits these from
//! `wait_event_names.txt`; here one `#[repr(u32)]` enum per wait class, each
//! discriminant = `(class_id << 24) | index` (matching PG's wait_event_info
//! encoding). `name()` returns the display string pg_stat shows. Descriptions are
//! documentation-only in PG and omitted. Regenerate with ai/harness/gen_flat_tables.py.


#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum WaitEventActivity {
    ArchiverMain = 0x05000000,
    AutovacuumMain = 0x05000001,
    BgwriterHibernate = 0x05000002,
    BgwriterMain = 0x05000003,
    CheckpointerMain = 0x05000004,
    CheckpointerShutdown = 0x05000005,
    IoWorkerMain = 0x05000006,
    LogicalApplyMain = 0x05000007,
    LogicalLauncherMain = 0x05000008,
    LogicalParallelApplyMain = 0x05000009,
    RecoveryWalStream = 0x0500000A,
    ReplicationSlotsyncMain = 0x0500000B,
    ReplicationSlotsyncShutdown = 0x0500000C,
    SysloggerMain = 0x0500000D,
    WalReceiverMain = 0x0500000E,
    WalSenderMain = 0x0500000F,
    WalSummarizerWal = 0x05000010,
    WalWriterMain = 0x05000011,
}

impl WaitEventActivity {
    pub fn name(self) -> &'static str {
        match self {
            Self::ArchiverMain => "ArchiverMain",
            Self::AutovacuumMain => "AutovacuumMain",
            Self::BgwriterHibernate => "BgwriterHibernate",
            Self::BgwriterMain => "BgwriterMain",
            Self::CheckpointerMain => "CheckpointerMain",
            Self::CheckpointerShutdown => "CheckpointerShutdown",
            Self::IoWorkerMain => "IoWorkerMain",
            Self::LogicalApplyMain => "LogicalApplyMain",
            Self::LogicalLauncherMain => "LogicalLauncherMain",
            Self::LogicalParallelApplyMain => "LogicalParallelApplyMain",
            Self::RecoveryWalStream => "RecoveryWalStream",
            Self::ReplicationSlotsyncMain => "ReplicationSlotsyncMain",
            Self::ReplicationSlotsyncShutdown => "ReplicationSlotsyncShutdown",
            Self::SysloggerMain => "SysloggerMain",
            Self::WalReceiverMain => "WalReceiverMain",
            Self::WalSenderMain => "WalSenderMain",
            Self::WalSummarizerWal => "WalSummarizerWal",
            Self::WalWriterMain => "WalWriterMain",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum WaitEventClient {
    ClientRead = 0x06000000,
    ClientWrite = 0x06000001,
    GssOpenServer = 0x06000002,
    LibpqwalreceiverConnect = 0x06000003,
    LibpqwalreceiverReceive = 0x06000004,
    SslOpenServer = 0x06000005,
    WaitForStandbyConfirmation = 0x06000006,
    WalSenderWaitForWal = 0x06000007,
    WalSenderWriteData = 0x06000008,
}

impl WaitEventClient {
    pub fn name(self) -> &'static str {
        match self {
            Self::ClientRead => "ClientRead",
            Self::ClientWrite => "ClientWrite",
            Self::GssOpenServer => "GssOpenServer",
            Self::LibpqwalreceiverConnect => "LibpqwalreceiverConnect",
            Self::LibpqwalreceiverReceive => "LibpqwalreceiverReceive",
            Self::SslOpenServer => "SslOpenServer",
            Self::WaitForStandbyConfirmation => "WaitForStandbyConfirmation",
            Self::WalSenderWaitForWal => "WalSenderWaitForWal",
            Self::WalSenderWriteData => "WalSenderWriteData",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum WaitEventIPC {
    AppendReady = 0x08000000,
    ArchiveCleanupCommand = 0x08000001,
    ArchiveCommand = 0x08000002,
    BackendTermination = 0x08000003,
    BackupWaitWalArchive = 0x08000004,
    BgworkerShutdown = 0x08000005,
    BgworkerStartup = 0x08000006,
    BtreePage = 0x08000007,
    BufferIo = 0x08000008,
    CheckpointDelayComplete = 0x08000009,
    CheckpointDelayStart = 0x0800000A,
    CheckpointDone = 0x0800000B,
    CheckpointStart = 0x0800000C,
    ExecuteGather = 0x0800000D,
    HashBatchAllocate = 0x0800000E,
    HashBatchElect = 0x0800000F,
    HashBatchLoad = 0x08000010,
    HashBuildAllocate = 0x08000011,
    HashBuildElect = 0x08000012,
    HashBuildHashInner = 0x08000013,
    HashBuildHashOuter = 0x08000014,
    HashGrowBatchesDecide = 0x08000015,
    HashGrowBatchesElect = 0x08000016,
    HashGrowBatchesFinish = 0x08000017,
    HashGrowBatchesReallocate = 0x08000018,
    HashGrowBatchesRepartition = 0x08000019,
    HashGrowBucketsElect = 0x0800001A,
    HashGrowBucketsReallocate = 0x0800001B,
    HashGrowBucketsReinsert = 0x0800001C,
    LogicalApplySendData = 0x0800001D,
    LogicalParallelApplyStateChange = 0x0800001E,
    LogicalSyncData = 0x0800001F,
    LogicalSyncStateChange = 0x08000020,
    MessageQueueInternal = 0x08000021,
    MessageQueuePutMessage = 0x08000022,
    MessageQueueReceive = 0x08000023,
    MessageQueueSend = 0x08000024,
    MultixactCreation = 0x08000025,
    ParallelBitmapScan = 0x08000026,
    ParallelCreateIndexScan = 0x08000027,
    ParallelFinish = 0x08000028,
    ProcarrayGroupUpdate = 0x08000029,
    ProcSignalBarrier = 0x0800002A,
    Promote = 0x0800002B,
    RecoveryConflictSnapshot = 0x0800002C,
    RecoveryConflictTablespace = 0x0800002D,
    RecoveryEndCommand = 0x0800002E,
    RecoveryPause = 0x0800002F,
    ReplicationOriginDrop = 0x08000030,
    ReplicationSlotDrop = 0x08000031,
    RestoreCommand = 0x08000032,
    SafeSnapshot = 0x08000033,
    SyncRep = 0x08000034,
    WalReceiverExit = 0x08000035,
    WalReceiverWaitStart = 0x08000036,
    WalSummaryReady = 0x08000037,
    XactGroupUpdate = 0x08000038,
}

impl WaitEventIPC {
    pub fn name(self) -> &'static str {
        match self {
            Self::AppendReady => "AppendReady",
            Self::ArchiveCleanupCommand => "ArchiveCleanupCommand",
            Self::ArchiveCommand => "ArchiveCommand",
            Self::BackendTermination => "BackendTermination",
            Self::BackupWaitWalArchive => "BackupWaitWalArchive",
            Self::BgworkerShutdown => "BgworkerShutdown",
            Self::BgworkerStartup => "BgworkerStartup",
            Self::BtreePage => "BtreePage",
            Self::BufferIo => "BufferIo",
            Self::CheckpointDelayComplete => "CheckpointDelayComplete",
            Self::CheckpointDelayStart => "CheckpointDelayStart",
            Self::CheckpointDone => "CheckpointDone",
            Self::CheckpointStart => "CheckpointStart",
            Self::ExecuteGather => "ExecuteGather",
            Self::HashBatchAllocate => "HashBatchAllocate",
            Self::HashBatchElect => "HashBatchElect",
            Self::HashBatchLoad => "HashBatchLoad",
            Self::HashBuildAllocate => "HashBuildAllocate",
            Self::HashBuildElect => "HashBuildElect",
            Self::HashBuildHashInner => "HashBuildHashInner",
            Self::HashBuildHashOuter => "HashBuildHashOuter",
            Self::HashGrowBatchesDecide => "HashGrowBatchesDecide",
            Self::HashGrowBatchesElect => "HashGrowBatchesElect",
            Self::HashGrowBatchesFinish => "HashGrowBatchesFinish",
            Self::HashGrowBatchesReallocate => "HashGrowBatchesReallocate",
            Self::HashGrowBatchesRepartition => "HashGrowBatchesRepartition",
            Self::HashGrowBucketsElect => "HashGrowBucketsElect",
            Self::HashGrowBucketsReallocate => "HashGrowBucketsReallocate",
            Self::HashGrowBucketsReinsert => "HashGrowBucketsReinsert",
            Self::LogicalApplySendData => "LogicalApplySendData",
            Self::LogicalParallelApplyStateChange => "LogicalParallelApplyStateChange",
            Self::LogicalSyncData => "LogicalSyncData",
            Self::LogicalSyncStateChange => "LogicalSyncStateChange",
            Self::MessageQueueInternal => "MessageQueueInternal",
            Self::MessageQueuePutMessage => "MessageQueuePutMessage",
            Self::MessageQueueReceive => "MessageQueueReceive",
            Self::MessageQueueSend => "MessageQueueSend",
            Self::MultixactCreation => "MultixactCreation",
            Self::ParallelBitmapScan => "ParallelBitmapScan",
            Self::ParallelCreateIndexScan => "ParallelCreateIndexScan",
            Self::ParallelFinish => "ParallelFinish",
            Self::ProcarrayGroupUpdate => "ProcarrayGroupUpdate",
            Self::ProcSignalBarrier => "ProcSignalBarrier",
            Self::Promote => "Promote",
            Self::RecoveryConflictSnapshot => "RecoveryConflictSnapshot",
            Self::RecoveryConflictTablespace => "RecoveryConflictTablespace",
            Self::RecoveryEndCommand => "RecoveryEndCommand",
            Self::RecoveryPause => "RecoveryPause",
            Self::ReplicationOriginDrop => "ReplicationOriginDrop",
            Self::ReplicationSlotDrop => "ReplicationSlotDrop",
            Self::RestoreCommand => "RestoreCommand",
            Self::SafeSnapshot => "SafeSnapshot",
            Self::SyncRep => "SyncRep",
            Self::WalReceiverExit => "WalReceiverExit",
            Self::WalReceiverWaitStart => "WalReceiverWaitStart",
            Self::WalSummaryReady => "WalSummaryReady",
            Self::XactGroupUpdate => "XactGroupUpdate",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum WaitEventTimeout {
    BaseBackupThrottle = 0x09000000,
    CheckpointWriteDelay = 0x09000001,
    PgSleep = 0x09000002,
    RecoveryApplyDelay = 0x09000003,
    RecoveryRetrieveRetryInterval = 0x09000004,
    RegisterSyncRequest = 0x09000005,
    SpinDelay = 0x09000006,
    VacuumDelay = 0x09000007,
    VacuumTruncate = 0x09000008,
    WalSummarizerError = 0x09000009,
}

impl WaitEventTimeout {
    pub fn name(self) -> &'static str {
        match self {
            Self::BaseBackupThrottle => "BaseBackupThrottle",
            Self::CheckpointWriteDelay => "CheckpointWriteDelay",
            Self::PgSleep => "PgSleep",
            Self::RecoveryApplyDelay => "RecoveryApplyDelay",
            Self::RecoveryRetrieveRetryInterval => "RecoveryRetrieveRetryInterval",
            Self::RegisterSyncRequest => "RegisterSyncRequest",
            Self::SpinDelay => "SpinDelay",
            Self::VacuumDelay => "VacuumDelay",
            Self::VacuumTruncate => "VacuumTruncate",
            Self::WalSummarizerError => "WalSummarizerError",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum WaitEventIO {
    AioIoCompletion = 0x0A000000,
    AioIoUringSubmit = 0x0A000001,
    AioIoUringExecution = 0x0A000002,
    BasebackupRead = 0x0A000003,
    BasebackupSync = 0x0A000004,
    BasebackupWrite = 0x0A000005,
    BuffileRead = 0x0A000006,
    BuffileWrite = 0x0A000007,
    BuffileTruncate = 0x0A000008,
    ControlFileRead = 0x0A000009,
    ControlFileSync = 0x0A00000A,
    ControlFileSyncUpdate = 0x0A00000B,
    ControlFileWrite = 0x0A00000C,
    ControlFileWriteUpdate = 0x0A00000D,
    CopyFileCopy = 0x0A00000E,
    CopyFileRead = 0x0A00000F,
    CopyFileWrite = 0x0A000010,
    DataFileExtend = 0x0A000011,
    DataFileFlush = 0x0A000012,
    DataFileImmediateSync = 0x0A000013,
    DataFilePrefetch = 0x0A000014,
    DataFileRead = 0x0A000015,
    DataFileSync = 0x0A000016,
    DataFileTruncate = 0x0A000017,
    DataFileWrite = 0x0A000018,
    DsmAllocate = 0x0A000019,
    DsmFillZeroWrite = 0x0A00001A,
    LockFileAddtodatadirRead = 0x0A00001B,
    LockFileAddtodatadirSync = 0x0A00001C,
    LockFileAddtodatadirWrite = 0x0A00001D,
    LockFileCreateRead = 0x0A00001E,
    LockFileCreateSync = 0x0A00001F,
    LockFileCreateWrite = 0x0A000020,
    LockFileRecheckdatadirRead = 0x0A000021,
    LogicalRewriteCheckpointSync = 0x0A000022,
    LogicalRewriteMappingSync = 0x0A000023,
    LogicalRewriteMappingWrite = 0x0A000024,
    LogicalRewriteSync = 0x0A000025,
    LogicalRewriteTruncate = 0x0A000026,
    LogicalRewriteWrite = 0x0A000027,
    RelationMapRead = 0x0A000028,
    RelationMapReplace = 0x0A000029,
    RelationMapWrite = 0x0A00002A,
    ReorderBufferRead = 0x0A00002B,
    ReorderBufferWrite = 0x0A00002C,
    ReorderLogicalMappingRead = 0x0A00002D,
    ReplicationSlotRead = 0x0A00002E,
    ReplicationSlotRestoreSync = 0x0A00002F,
    ReplicationSlotSync = 0x0A000030,
    ReplicationSlotWrite = 0x0A000031,
    SlruFlushSync = 0x0A000032,
    SlruRead = 0x0A000033,
    SlruSync = 0x0A000034,
    SlruWrite = 0x0A000035,
    SnapbuildRead = 0x0A000036,
    SnapbuildSync = 0x0A000037,
    SnapbuildWrite = 0x0A000038,
    TimelineHistoryFileSync = 0x0A000039,
    TimelineHistoryFileWrite = 0x0A00003A,
    TimelineHistoryRead = 0x0A00003B,
    TimelineHistorySync = 0x0A00003C,
    TimelineHistoryWrite = 0x0A00003D,
    TwophaseFileRead = 0x0A00003E,
    TwophaseFileSync = 0x0A00003F,
    TwophaseFileWrite = 0x0A000040,
    VersionFileSync = 0x0A000041,
    VersionFileWrite = 0x0A000042,
    WalsenderTimelineHistoryRead = 0x0A000043,
    WalBootstrapSync = 0x0A000044,
    WalBootstrapWrite = 0x0A000045,
    WalCopyRead = 0x0A000046,
    WalCopySync = 0x0A000047,
    WalCopyWrite = 0x0A000048,
    WalInitSync = 0x0A000049,
    WalInitWrite = 0x0A00004A,
    WalRead = 0x0A00004B,
    WalSummaryRead = 0x0A00004C,
    WalSummaryWrite = 0x0A00004D,
    WalSync = 0x0A00004E,
    WalSyncMethodAssign = 0x0A00004F,
    WalWrite = 0x0A000050,
}

impl WaitEventIO {
    pub fn name(self) -> &'static str {
        match self {
            Self::AioIoCompletion => "AioIoCompletion",
            Self::AioIoUringSubmit => "AioIoUringSubmit",
            Self::AioIoUringExecution => "AioIoUringExecution",
            Self::BasebackupRead => "BasebackupRead",
            Self::BasebackupSync => "BasebackupSync",
            Self::BasebackupWrite => "BasebackupWrite",
            Self::BuffileRead => "BuffileRead",
            Self::BuffileWrite => "BuffileWrite",
            Self::BuffileTruncate => "BuffileTruncate",
            Self::ControlFileRead => "ControlFileRead",
            Self::ControlFileSync => "ControlFileSync",
            Self::ControlFileSyncUpdate => "ControlFileSyncUpdate",
            Self::ControlFileWrite => "ControlFileWrite",
            Self::ControlFileWriteUpdate => "ControlFileWriteUpdate",
            Self::CopyFileCopy => "CopyFileCopy",
            Self::CopyFileRead => "CopyFileRead",
            Self::CopyFileWrite => "CopyFileWrite",
            Self::DataFileExtend => "DataFileExtend",
            Self::DataFileFlush => "DataFileFlush",
            Self::DataFileImmediateSync => "DataFileImmediateSync",
            Self::DataFilePrefetch => "DataFilePrefetch",
            Self::DataFileRead => "DataFileRead",
            Self::DataFileSync => "DataFileSync",
            Self::DataFileTruncate => "DataFileTruncate",
            Self::DataFileWrite => "DataFileWrite",
            Self::DsmAllocate => "DsmAllocate",
            Self::DsmFillZeroWrite => "DsmFillZeroWrite",
            Self::LockFileAddtodatadirRead => "LockFileAddtodatadirRead",
            Self::LockFileAddtodatadirSync => "LockFileAddtodatadirSync",
            Self::LockFileAddtodatadirWrite => "LockFileAddtodatadirWrite",
            Self::LockFileCreateRead => "LockFileCreateRead",
            Self::LockFileCreateSync => "LockFileCreateSync",
            Self::LockFileCreateWrite => "LockFileCreateWrite",
            Self::LockFileRecheckdatadirRead => "LockFileRecheckdatadirRead",
            Self::LogicalRewriteCheckpointSync => "LogicalRewriteCheckpointSync",
            Self::LogicalRewriteMappingSync => "LogicalRewriteMappingSync",
            Self::LogicalRewriteMappingWrite => "LogicalRewriteMappingWrite",
            Self::LogicalRewriteSync => "LogicalRewriteSync",
            Self::LogicalRewriteTruncate => "LogicalRewriteTruncate",
            Self::LogicalRewriteWrite => "LogicalRewriteWrite",
            Self::RelationMapRead => "RelationMapRead",
            Self::RelationMapReplace => "RelationMapReplace",
            Self::RelationMapWrite => "RelationMapWrite",
            Self::ReorderBufferRead => "ReorderBufferRead",
            Self::ReorderBufferWrite => "ReorderBufferWrite",
            Self::ReorderLogicalMappingRead => "ReorderLogicalMappingRead",
            Self::ReplicationSlotRead => "ReplicationSlotRead",
            Self::ReplicationSlotRestoreSync => "ReplicationSlotRestoreSync",
            Self::ReplicationSlotSync => "ReplicationSlotSync",
            Self::ReplicationSlotWrite => "ReplicationSlotWrite",
            Self::SlruFlushSync => "SlruFlushSync",
            Self::SlruRead => "SlruRead",
            Self::SlruSync => "SlruSync",
            Self::SlruWrite => "SlruWrite",
            Self::SnapbuildRead => "SnapbuildRead",
            Self::SnapbuildSync => "SnapbuildSync",
            Self::SnapbuildWrite => "SnapbuildWrite",
            Self::TimelineHistoryFileSync => "TimelineHistoryFileSync",
            Self::TimelineHistoryFileWrite => "TimelineHistoryFileWrite",
            Self::TimelineHistoryRead => "TimelineHistoryRead",
            Self::TimelineHistorySync => "TimelineHistorySync",
            Self::TimelineHistoryWrite => "TimelineHistoryWrite",
            Self::TwophaseFileRead => "TwophaseFileRead",
            Self::TwophaseFileSync => "TwophaseFileSync",
            Self::TwophaseFileWrite => "TwophaseFileWrite",
            Self::VersionFileSync => "VersionFileSync",
            Self::VersionFileWrite => "VersionFileWrite",
            Self::WalsenderTimelineHistoryRead => "WalsenderTimelineHistoryRead",
            Self::WalBootstrapSync => "WalBootstrapSync",
            Self::WalBootstrapWrite => "WalBootstrapWrite",
            Self::WalCopyRead => "WalCopyRead",
            Self::WalCopySync => "WalCopySync",
            Self::WalCopyWrite => "WalCopyWrite",
            Self::WalInitSync => "WalInitSync",
            Self::WalInitWrite => "WalInitWrite",
            Self::WalRead => "WalRead",
            Self::WalSummaryRead => "WalSummaryRead",
            Self::WalSummaryWrite => "WalSummaryWrite",
            Self::WalSync => "WalSync",
            Self::WalSyncMethodAssign => "WalSyncMethodAssign",
            Self::WalWrite => "WalWrite",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum WaitEventBufferPin {
    BufferPin = 0x04000000,
}

impl WaitEventBufferPin {
    pub fn name(self) -> &'static str {
        match self {
            Self::BufferPin => "BufferPin",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum WaitEventExtension {
    Extension = 0x07000000,
}

impl WaitEventExtension {
    pub fn name(self) -> &'static str {
        match self {
            Self::Extension => "Extension",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum WaitEventLWLock {
    ShmemIndex = 0x01000000,
    OidGen = 0x01000001,
    XidGen = 0x01000002,
    ProcArray = 0x01000003,
    SInvalRead = 0x01000004,
    SInvalWrite = 0x01000005,
    WALBufMapping = 0x01000006,
    WALWrite = 0x01000007,
    ControlFile = 0x01000008,
    MultiXactGen = 0x01000009,
    RelCacheInit = 0x0100000A,
    CheckpointerComm = 0x0100000B,
    TwoPhaseState = 0x0100000C,
    TablespaceCreate = 0x0100000D,
    BtreeVacuum = 0x0100000E,
    AddinShmemInit = 0x0100000F,
    Autovacuum = 0x01000010,
    AutovacuumSchedule = 0x01000011,
    SyncScan = 0x01000012,
    RelationMapping = 0x01000013,
    NotifyQueue = 0x01000014,
    SerializableXactHash = 0x01000015,
    SerializableFinishedList = 0x01000016,
    SerializablePredicateList = 0x01000017,
    SyncRep = 0x01000018,
    BackgroundWorker = 0x01000019,
    DynamicSharedMemoryControl = 0x0100001A,
    AutoFile = 0x0100001B,
    ReplicationSlotAllocation = 0x0100001C,
    ReplicationSlotControl = 0x0100001D,
    CommitTs = 0x0100001E,
    ReplicationOrigin = 0x0100001F,
    MultiXactTruncation = 0x01000020,
    LogicalRepWorker = 0x01000021,
    XactTruncation = 0x01000022,
    WrapLimitsVacuum = 0x01000023,
    NotifyQueueTail = 0x01000024,
    WaitEventCustom = 0x01000025,
    WALSummarizer = 0x01000026,
    DSMRegistry = 0x01000027,
    InjectionPoint = 0x01000028,
    SerialControl = 0x01000029,
    AioWorkerSubmissionQueue = 0x0100002A,
    XactBuffer = 0x0100002B,
    CommitTsBuffer = 0x0100002C,
    SubtransBuffer = 0x0100002D,
    MultiXactOffsetBuffer = 0x0100002E,
    MultiXactMemberBuffer = 0x0100002F,
    NotifyBuffer = 0x01000030,
    SerialBuffer = 0x01000031,
    WALInsert = 0x01000032,
    BufferContent = 0x01000033,
    ReplicationOriginState = 0x01000034,
    ReplicationSlotIO = 0x01000035,
    LockFastPath = 0x01000036,
    BufferMapping = 0x01000037,
    LockManager = 0x01000038,
    PredicateLockManager = 0x01000039,
    ParallelHashJoin = 0x0100003A,
    ParallelBtreeScan = 0x0100003B,
    ParallelQueryDSA = 0x0100003C,
    PerSessionDSA = 0x0100003D,
    PerSessionRecordType = 0x0100003E,
    PerSessionRecordTypmod = 0x0100003F,
    SharedTupleStore = 0x01000040,
    SharedTidBitmap = 0x01000041,
    ParallelAppend = 0x01000042,
    PerXactPredicateList = 0x01000043,
    PgStatsDSA = 0x01000044,
    PgStatsHash = 0x01000045,
    PgStatsData = 0x01000046,
    LogicalRepLauncherDSA = 0x01000047,
    LogicalRepLauncherHash = 0x01000048,
    DSMRegistryDSA = 0x01000049,
    DSMRegistryHash = 0x0100004A,
    CommitTsSLRU = 0x0100004B,
    MultiXactOffsetSLRU = 0x0100004C,
    MultiXactMemberSLRU = 0x0100004D,
    NotifySLRU = 0x0100004E,
    SerialSLRU = 0x0100004F,
    SubtransSLRU = 0x01000050,
    XactSLRU = 0x01000051,
    ParallelVacuumDSA = 0x01000052,
    AioUringCompletion = 0x01000053,
}

impl WaitEventLWLock {
    pub fn name(self) -> &'static str {
        match self {
            Self::ShmemIndex => "ShmemIndex",
            Self::OidGen => "OidGen",
            Self::XidGen => "XidGen",
            Self::ProcArray => "ProcArray",
            Self::SInvalRead => "SInvalRead",
            Self::SInvalWrite => "SInvalWrite",
            Self::WALBufMapping => "WALBufMapping",
            Self::WALWrite => "WALWrite",
            Self::ControlFile => "ControlFile",
            Self::MultiXactGen => "MultiXactGen",
            Self::RelCacheInit => "RelCacheInit",
            Self::CheckpointerComm => "CheckpointerComm",
            Self::TwoPhaseState => "TwoPhaseState",
            Self::TablespaceCreate => "TablespaceCreate",
            Self::BtreeVacuum => "BtreeVacuum",
            Self::AddinShmemInit => "AddinShmemInit",
            Self::Autovacuum => "Autovacuum",
            Self::AutovacuumSchedule => "AutovacuumSchedule",
            Self::SyncScan => "SyncScan",
            Self::RelationMapping => "RelationMapping",
            Self::NotifyQueue => "NotifyQueue",
            Self::SerializableXactHash => "SerializableXactHash",
            Self::SerializableFinishedList => "SerializableFinishedList",
            Self::SerializablePredicateList => "SerializablePredicateList",
            Self::SyncRep => "SyncRep",
            Self::BackgroundWorker => "BackgroundWorker",
            Self::DynamicSharedMemoryControl => "DynamicSharedMemoryControl",
            Self::AutoFile => "AutoFile",
            Self::ReplicationSlotAllocation => "ReplicationSlotAllocation",
            Self::ReplicationSlotControl => "ReplicationSlotControl",
            Self::CommitTs => "CommitTs",
            Self::ReplicationOrigin => "ReplicationOrigin",
            Self::MultiXactTruncation => "MultiXactTruncation",
            Self::LogicalRepWorker => "LogicalRepWorker",
            Self::XactTruncation => "XactTruncation",
            Self::WrapLimitsVacuum => "WrapLimitsVacuum",
            Self::NotifyQueueTail => "NotifyQueueTail",
            Self::WaitEventCustom => "WaitEventCustom",
            Self::WALSummarizer => "WALSummarizer",
            Self::DSMRegistry => "DSMRegistry",
            Self::InjectionPoint => "InjectionPoint",
            Self::SerialControl => "SerialControl",
            Self::AioWorkerSubmissionQueue => "AioWorkerSubmissionQueue",
            Self::XactBuffer => "XactBuffer",
            Self::CommitTsBuffer => "CommitTsBuffer",
            Self::SubtransBuffer => "SubtransBuffer",
            Self::MultiXactOffsetBuffer => "MultiXactOffsetBuffer",
            Self::MultiXactMemberBuffer => "MultiXactMemberBuffer",
            Self::NotifyBuffer => "NotifyBuffer",
            Self::SerialBuffer => "SerialBuffer",
            Self::WALInsert => "WALInsert",
            Self::BufferContent => "BufferContent",
            Self::ReplicationOriginState => "ReplicationOriginState",
            Self::ReplicationSlotIO => "ReplicationSlotIO",
            Self::LockFastPath => "LockFastPath",
            Self::BufferMapping => "BufferMapping",
            Self::LockManager => "LockManager",
            Self::PredicateLockManager => "PredicateLockManager",
            Self::ParallelHashJoin => "ParallelHashJoin",
            Self::ParallelBtreeScan => "ParallelBtreeScan",
            Self::ParallelQueryDSA => "ParallelQueryDSA",
            Self::PerSessionDSA => "PerSessionDSA",
            Self::PerSessionRecordType => "PerSessionRecordType",
            Self::PerSessionRecordTypmod => "PerSessionRecordTypmod",
            Self::SharedTupleStore => "SharedTupleStore",
            Self::SharedTidBitmap => "SharedTidBitmap",
            Self::ParallelAppend => "ParallelAppend",
            Self::PerXactPredicateList => "PerXactPredicateList",
            Self::PgStatsDSA => "PgStatsDSA",
            Self::PgStatsHash => "PgStatsHash",
            Self::PgStatsData => "PgStatsData",
            Self::LogicalRepLauncherDSA => "LogicalRepLauncherDSA",
            Self::LogicalRepLauncherHash => "LogicalRepLauncherHash",
            Self::DSMRegistryDSA => "DSMRegistryDSA",
            Self::DSMRegistryHash => "DSMRegistryHash",
            Self::CommitTsSLRU => "CommitTsSLRU",
            Self::MultiXactOffsetSLRU => "MultiXactOffsetSLRU",
            Self::MultiXactMemberSLRU => "MultiXactMemberSLRU",
            Self::NotifySLRU => "NotifySLRU",
            Self::SerialSLRU => "SerialSLRU",
            Self::SubtransSLRU => "SubtransSLRU",
            Self::XactSLRU => "XactSLRU",
            Self::ParallelVacuumDSA => "ParallelVacuumDSA",
            Self::AioUringCompletion => "AioUringCompletion",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum WaitEventLock {
    Relation = 0x03000000,
    Extend = 0x03000001,
    Frozenid = 0x03000002,
    Page = 0x03000003,
    Tuple = 0x03000004,
    Transactionid = 0x03000005,
    Virtualxid = 0x03000006,
    Spectoken = 0x03000007,
    Object = 0x03000008,
    Userlock = 0x03000009,
    Advisory = 0x0300000A,
    Applytransaction = 0x0300000B,
}

impl WaitEventLock {
    pub fn name(self) -> &'static str {
        match self {
            Self::Relation => "Relation",
            Self::Extend => "Extend",
            Self::Frozenid => "Frozenid",
            Self::Page => "Page",
            Self::Tuple => "Tuple",
            Self::Transactionid => "Transactionid",
            Self::Virtualxid => "Virtualxid",
            Self::Spectoken => "Spectoken",
            Self::Object => "Object",
            Self::Userlock => "Userlock",
            Self::Advisory => "Advisory",
            Self::Applytransaction => "Applytransaction",
        }
    }
}
