//! Bootstrap / initdb support. Translated from
//! `src/backend/bootstrap/bootstrap.c`, but with the BKI text pipeline replaced
//! by `.dat`-driven codegen (gating decision 2 in plan 003).
//!
//! PostgreSQL bootstraps an empty cluster in two cooperating pieces:
//!
//!  - `genbki.pl` reads the catalog `.h` headers + `pg_*.dat` files and writes
//!    `postgres.bki`, a tiny text language of `create`/`open`/`insert` commands
//!    plus `schemapg.h` (compiled-in attribute descriptors for the nailed
//!    catalogs).
//!  - `bootstrap.c` runs in `--boot` mode, parsing `postgres.bki` with a
//!    flex/bison grammar (`bootscanner.l` / `bootparse.y`) and executing it:
//!    `boot_openrel` / `DefineAttr` / `InsertOneTuple` build each catalog heap
//!    and `build_indices` builds the catalog indexes.
//!
//! In this port the BKI TEXT layer disappears. `build.rs` emits the same data
//! directly as Rust:
//!  - [`BootstrapAttr`] arrays (`SCHEMA_PG_*`) -- the schemapg.h analog, the
//!    compiled-in column descriptors for the formrdesc catalogs.
//!  - generic seed rows (`SEED_PG_*`) -- the `insert ( ... )` analog, the initial
//!    contents of the `.dat`-backed M2 catalogs.
//!
//! Two functions matter here:
//!  - [`formrdesc`] builds the hardcoded, compiled-in relation descriptor for a
//!    nailed bootstrap catalog so the relcache can read it before it exists on
//!    disk (breaking the relcache<->disk chicken-and-egg). The TupleDesc part is
//!    fully built from [`BootstrapAttr`] data (it "had better be right because it
//!    will never be replaced"); the `RelationData`/relcache-insert wrapper stages
//!    against the relcache (step 14).
//!  - the initdb entry point ([`bootstrap_catalogs`]) writes the seed rows into
//!    the catalog heaps and builds the catalog indexes. The heap-write and
//!    index-build calls stage against the heap-AM stubs (steps 11-13/15).
//!
//! `bootparse.y` / `bootscanner.l` are TOMBSTONED (see the note at the bottom):
//! the BKI bison parser is replaced by the `.dat` codegen, so there is nothing to
//! translate.


use crate::access::tupdesc::{TupleDesc, TupleDescData};
use crate::catalog::pg_aggregate::{AggregateRelationId, AggregateRelation_Rowtype_Id};
use crate::catalog::pg_attribute::{AttributeRelationId, AttributeRelation_Rowtype_Id};
use crate::catalog::pg_cast::{CastRelationId, CastRelation_Rowtype_Id};
use crate::catalog::pg_class::{RelationRelationId, RelationRelation_Rowtype_Id};
use crate::catalog::pg_operator::{OperatorRelationId, OperatorRelation_Rowtype_Id};
use crate::catalog::pg_attrdef::{AttrDefaultRelationId, AttrDefaultRelation_Rowtype_Id};
use crate::catalog::pg_constraint::{ConstraintRelationId, ConstraintRelation_Rowtype_Id};
use crate::catalog::pg_database::{DatabaseRelationId, DatabaseRelation_Rowtype_Id};
use crate::catalog::pg_tablespace::TableSpaceRelationId;
use crate::catalog::pg_collation::CollationRelationId;
use crate::catalog::pg_conversion::ConversionRelationId;
use crate::catalog::pg_description::{DescriptionRelationId, DescriptionRelation_Rowtype_Id};
use crate::catalog::pg_namespace::{NamespaceRelationId, NamespaceRelation_Rowtype_Id};
use crate::catalog::pg_proc::{ProcedureRelationId, ProcedureRelation_Rowtype_Id};
use crate::catalog::pg_sequence::{SequenceRelationId, SequenceRelation_Rowtype_Id};
use crate::catalog::pg_type::{TypeRelationId, TypeRelation_Rowtype_Id};
use crate::postgres_ext::{InvalidOid, Oid};

/// Max number of attributes in a relation supported at bootstrap time. Re-exported
/// by the header. PG `MAXATTR`.
pub const MAXATTR: usize = 40;

/// A single compiled-in attribute descriptor (the genbki `Schema_pg_xxx` entry).
/// `build.rs` emits one array of these per formrdesc catalog from the catalog's
/// `CATALOG(...)` column list + the per-column physical type properties read from
/// `pg_type.dat` (genbki's `morph_row_for_pgattr`). [`formrdesc`] copies these
/// into the catalog's [`FormData_pg_attribute`] rows.
///
/// [`FormData_pg_attribute`]: crate::catalog::pg_attribute::FormData_pg_attribute
#[derive(Debug, Clone, Copy)]
pub struct BootstrapAttr {
    pub attname: &'static str,
    pub atttypid: u32,
    pub attlen: i16,
    pub attbyval: bool,
    pub attalign: i8,
    pub attstorage: i8,
    pub attnotnull: bool,
    pub attndims: i16,
    pub attcollation: u32,
    pub attnum: i16,
}

/// One seed row: the ordered `(column, value)` pairs of a single catalog tuple,
/// exactly as written in the upstream `.dat` (genbki's `insert ( ... )` line).
/// `value == "_null_"` denotes SQL NULL; `"-"` is the regproc/unknown sentinel.
pub type SeedRow = &'static [(&'static str, &'static str)];

// The genbki schemapg.h analog: SCHEMA_PG_{CLASS,ATTRIBUTE,PROC,TYPE} +
// NATTS_PG_*. Generated by build.rs from the catalog headers + pg_type.dat.
include!(concat!(env!("OUT_DIR"), "/bootstrap_schema_generated.rs"));

// The genbki BKI `insert` analog: SEED_PG_{AM,NAMESPACE,COLLATION,OPCLASS,AMOP,
// AMPROC}, each `&[&[(col, value)]]`. Generated by build.rs from the .dat files.
include!(concat!(env!("OUT_DIR"), "/bootstrap_seed_generated.rs"));

// M3: resolved pg_proc + pg_operator seed rows (SEED_PG_PROC_M3 / SEED_PG_OPERATOR_M3
// + the M3Proc / M3Operator structs). Generated by build.rs with type/proc names
// resolved to OIDs. These seed the int4 operator/function resolution path.
include!(concat!(env!("OUT_DIR"), "/bootstrap_m3_seed_generated.rs"));

// M4: resolved pg_cast + cast-support pg_proc seed rows (SEED_PG_CAST_M4 /
// SEED_PG_PROC_M4_CAST + the M4Cast struct; reuses M3Proc). Generated by build.rs.
// These seed the numeric/int/float cast tower so find_coercion_pathway resolves
// int4->numeric etc. via pg_cast.
include!(concat!(env!("OUT_DIR"), "/bootstrap_m4_cast_seed_generated.rs"));

// M5 (step 25B): resolved pg_aggregate + agg/transfn pg_proc seed rows
// (SEED_PG_AGGREGATE_M5 / SEED_PG_PROC_M5_AGG + the M5Aggregate struct; reuses
// M3Proc). Generated by build.rs. These seed the common aggregates so nodeAgg's
// AGGFNOID lookup resolves count/sum/min/max.
include!(concat!(env!("OUT_DIR"), "/bootstrap_m5_agg_seed_generated.rs"));

/// One nailed bootstrap catalog: its name, OID, rowtype OID, shared flag, and the
/// compiled-in attribute schema. This is the argument list PG passes to
/// `formrdesc` in `RelationCacheInitializePhase2/3`.
pub struct BootstrapCatalog {
    pub relname: &'static str,
    pub relid: Oid,
    pub reltype: Oid,
    pub isshared: bool,
    pub schema: &'static [BootstrapAttr],
}

/// One nailed formrdesc catalog, mirroring the genbki `CATALOG(...)` line.
/// `catalog!("pg_type", TypeRelationId, TypeRelation_Rowtype_Id, isshared => false, SCHEMA_PG_TYPE)`
/// expands to a [`BootstrapCatalog`] literal.
macro_rules! catalog {
    ($relname:expr, $relid:expr, $reltype:expr, isshared => $shared:expr, $schema:expr $(,)?) => {
        BootstrapCatalog {
            relname: $relname,
            relid: $relid,
            reltype: $reltype,
            isshared: $shared,
            schema: $schema,
        }
    };
}

/// The formrdesc catalog set: the relations whose relcache entries are faked up
/// before pg_class can be read (PG `RelationCacheInitializePhase2/3`). All four
/// are non-shared local catalogs (the shared ones -- pg_database/pg_authid/... --
/// are deep-deferred; they are not on the M2 path).
pub static FORMRDESC_CATALOGS: &[BootstrapCatalog] = &[
    catalog!("pg_type", TypeRelationId, TypeRelation_Rowtype_Id, isshared => false, SCHEMA_PG_TYPE),
    catalog!("pg_attribute", AttributeRelationId, AttributeRelation_Rowtype_Id, isshared => false, SCHEMA_PG_ATTRIBUTE),
    catalog!("pg_proc", ProcedureRelationId, ProcedureRelation_Rowtype_Id, isshared => false, SCHEMA_PG_PROC),
    catalog!("pg_class", RelationRelationId, RelationRelation_Rowtype_Id, isshared => false, SCHEMA_PG_CLASS),
    // M3: pg_operator is nailed so the operator-resolution syscaches (OPERNAMENSP /
    // OPEROID) can read its descriptor before it has a pg_class self-row. PG builds
    // pg_operator as an ordinary catalog; nailing it here reuses the proven
    // formrdesc path (the row contents are still real on-disk seed rows).
    catalog!("pg_operator", OperatorRelationId, OperatorRelation_Rowtype_Id, isshared => false, SCHEMA_PG_OPERATOR),
    // M4 (step 23): pg_cast is nailed so the CASTSOURCETARGET syscache can read its
    // descriptor before it has a pg_class self-row -- same rationale as pg_operator.
    catalog!("pg_cast", CastRelationId, CastRelation_Rowtype_Id, isshared => false, SCHEMA_PG_CAST),
    // M5 (step 25B): pg_aggregate is nailed so the AGGFNOID syscache can read its
    // descriptor before pg_aggregate has a pg_class self-row -- same rationale as
    // pg_cast/pg_operator.
    catalog!("pg_aggregate", AggregateRelationId, AggregateRelation_Rowtype_Id, isshared => false, SCHEMA_PG_AGGREGATE),
    // M10 (step 39): the object-DDL catalogs. pg_namespace is seeded (its standard
    // rows); pg_sequence/pg_attrdef/pg_constraint/pg_description start empty and are
    // filled by the runtime DDL (CREATE SEQUENCE, SET DEFAULT, ADD CONSTRAINT,
    // COMMENT). Nailing gives `relation_id_get_relation` their descriptor for those
    // inserts before they have pg_class self-rows.
    catalog!("pg_namespace", NamespaceRelationId, NamespaceRelation_Rowtype_Id, isshared => false, SCHEMA_PG_NAMESPACE),
    catalog!("pg_sequence", SequenceRelationId, SequenceRelation_Rowtype_Id, isshared => false, SCHEMA_PG_SEQUENCE),
    catalog!("pg_attrdef", AttrDefaultRelationId, AttrDefaultRelation_Rowtype_Id, isshared => false, SCHEMA_PG_ATTRDEF),
    catalog!("pg_constraint", ConstraintRelationId, ConstraintRelation_Rowtype_Id, isshared => false, SCHEMA_PG_CONSTRAINT),
    catalog!("pg_description", DescriptionRelationId, DescriptionRelation_Rowtype_Id, isshared => false, SCHEMA_PG_DESCRIPTION),
    // M10 (step 39B): the minor object-DDL catalogs. pg_database/pg_tablespace are
    // BKI_SHARED_RELATION in PG (db 0); the single-database port nails them local so
    // their storage lives in the active database. pg_database/pg_tablespace are seeded
    // (the bootstrap db/tablespace rows); pg_collation/pg_conversion start empty and
    // are filled by CREATE COLLATION / CREATE CONVERSION. The reltype for the three
    // catalogs without a BKI_ROWTYPE_OID is their relid (non-load-bearing single-db).
    catalog!("pg_database", DatabaseRelationId, DatabaseRelation_Rowtype_Id, isshared => false, SCHEMA_PG_DATABASE),
    catalog!("pg_tablespace", TableSpaceRelationId, TableSpaceRelationId, isshared => false, SCHEMA_PG_TABLESPACE),
    catalog!("pg_collation", CollationRelationId, CollationRelationId, isshared => false, SCHEMA_PG_COLLATION),
    catalog!("pg_conversion", ConversionRelationId, ConversionRelationId, isshared => false, SCHEMA_PG_CONVERSION),
];

/// Build the compiled-in `TupleDesc` for a nailed bootstrap catalog from its
/// [`BootstrapAttr`] schema. This is the load-bearing half of PG `formrdesc`: the
/// attribute data "had better be right because it will never be replaced" -- it
/// comes from the catalog headers via genbki, here via [`BootstrapAttr`].
///
/// Faithful to the `formrdesc` tupdesc loop: start from a template, copy each
/// attribute's fixed-part fields, set `attrelid`, mark the first attribute's
/// `attcacheoff = 0`, populate the compact-attribute cache, and record the
/// composite type identity.
///
/// PG `formrdesc` (the `CreateTemplateTupleDesc` + per-attr `memcpy` + first
/// `attcacheoff` + `populate_compact_attribute` portion). `relid` is the owning
/// catalog OID, which genbki stamps into every `attrelid` (PG's formrdesc reads
/// it back from `attrs[0].attrelid` to set `RelationGetRelid`).
#[must_use]
pub fn formrdesc_tupdesc(relid: Oid, reltype: Oid, attrs: &[BootstrapAttr]) -> TupleDesc {
    use crate::access::tupdesc::{
        CompactAttribute, TupleConstr, ATTNULLABLE_UNRESTRICTED, ATTNULLABLE_VALID,
    };
    use crate::c::{NameData, NAMEDATALEN};
    use crate::catalog::pg_type::{
        TYPALIGN_CHAR, TYPALIGN_DOUBLE, TYPALIGN_INT, TYPALIGN_SHORT, TYPSTORAGE_PLAIN,
    };
    use crate::pg_config::{ALIGNOF_DOUBLE, ALIGNOF_INT, ALIGNOF_SHORT};
    use crate::postgres_ext::Oid as OidT;

    /// Write `name` into a `NameData`, NUL-padded to `NAMEDATALEN` (C namestrcpy).
    fn namestrcpy(name: &mut NameData, src: &str) {
        let bytes = src.as_bytes();
        let n = bytes.len().min(NAMEDATALEN - 1);
        name.data = [0u8; NAMEDATALEN];
        name.data[..n].copy_from_slice(&bytes[..n]);
    }

    let natts = i32::try_from(attrs.len()).unwrap_or(0);
    let mut desc = TupleDescData::create_template(natts);
    desc.tdrefcount = 1; // mark as refcounted (formrdesc nails the entry)
    desc.tdtypeid = reltype;
    desc.tdtypmod = -1;

    let mut has_not_null = false;
    for (i, a) in attrs.iter().enumerate() {
        // Fill the fixed part directly from the compiled-in descriptor; mirrors the
        // `memcpy(TupleDescAttr(...), &attrs[i], ATTRIBUTE_FIXED_PART_SIZE)` in
        // formrdesc, field-by-field (no layout-punning needed).
        let att = &mut desc.attrs[i];
        att.attrelid = relid;
        namestrcpy(&mut att.attname, a.attname);
        att.atttypid = OidT::new(a.atttypid);
        att.attlen = a.attlen;
        att.attnum = a.attnum;
        att.attndims = a.attndims;
        att.attbyval = a.attbyval;
        att.attalign = a.attalign;
        att.attstorage = a.attstorage;
        att.attnotnull = a.attnotnull;
        att.attcollation = OidT::new(a.attcollation);
        att.attislocal = true;
        att.atttypmod = -1;
        has_not_null |= a.attnotnull;

        // Build the compact-attribute cache entry. We compute it inline rather
        // than calling `TupleDescData::populate_compact_attribute`, whose catalog
        // branch routes through `IsCatalogRelationOid` (not yet translated). Every
        // formrdesc relation IS a catalog, so a NOT NULL column is ATTNULLABLE_VALID
        // -- exactly what that branch returns for a catalog relid -- which lets the
        // nailed bootstrap descriptors be built before catalog.c lands.
        let alignby = match a.attalign {
            x if x == TYPALIGN_INT => u8::try_from(ALIGNOF_INT).unwrap_or(0),
            x if x == TYPALIGN_CHAR => 1,
            x if x == TYPALIGN_DOUBLE => u8::try_from(ALIGNOF_DOUBLE).unwrap_or(0),
            x if x == TYPALIGN_SHORT => u8::try_from(ALIGNOF_SHORT).unwrap_or(0),
            _ => 0,
        };
        desc.compact_attrs[i] = CompactAttribute {
            attcacheoff: -1,
            attlen: a.attlen,
            attbyval: a.attbyval,
            attispackable: a.attstorage != TYPSTORAGE_PLAIN,
            atthasmissing: false,
            attisdropped: false,
            attgenerated: false,
            attnullability: if a.attnotnull { ATTNULLABLE_VALID } else { ATTNULLABLE_UNRESTRICTED },
            attalignby: alignby,
        };
    }

    // First attribute's attcacheoff is 0 (cf RelationBuildTupleDesc / formrdesc).
    if let Some(first) = desc.compact_attrs.first_mut() {
        first.attcacheoff = 0;
    }

    if has_not_null {
        desc.constr = Some(Box::new(TupleConstr {
            defval: Vec::new(),
            check: Vec::new(),
            missing: None,
            has_not_null: true,
            has_generated_stored: false,
            has_generated_virtual: false,
        }));
    }

    std::sync::Arc::new(desc)
}

/// Build (and relcache-insert) the hardcoded relation descriptor for a nailed
/// bootstrap catalog, so it can be read before pg_class is loaded.
///
/// PG `formrdesc`. The TupleDesc -- the part that is never replaced -- is built
/// completely by [`formrdesc_tupdesc`]. The surrounding nailed [`RelationData`]
/// (its `rd_rel` Form_pg_class, relfilenode mapping, lock/physical addressing,
/// `RelationCacheInsert`) belongs to the relcache, which lands in step 14:
/// step 14 calls [`formrdesc_tupdesc`] for each [`FORMRDESC_CATALOGS`] entry to
/// fill the nailed entry's `rd_att`. This function therefore returns the finished
/// descriptor and documents the staged relcache wiring rather than fabricating a
/// raw-pointer `RelationData` the relcache does not yet own.
///
/// [`RelationData`]: crate::utils::rel::RelationData
#[must_use]
pub fn formrdesc(cat: &BootstrapCatalog) -> TupleDesc {
    let desc = formrdesc_tupdesc(cat.relid, cat.reltype, cat.schema);
    // STAGED (step 14, relcache RelationCacheInitializePhase2/3):
    //   let rel = palloc0::<RelationData>(); rel.rd_isnailed = true; rel.rd_refcnt = 1;
    //   rel.rd_rel = palloc0(CLASS_TUPLE_SIZE); namestrcpy(relname); relnamespace =
    //     PG_CATALOG_NAMESPACE; reltype; relisshared = cat.isshared; relkind = 'r';
    //     relnatts = natts; relam = HEAP_TABLE_AM_OID; ...
    //   rel.rd_att = Some(desc);
    //   RelationMapUpdateMap(relid, relid, isshared, true);  // bootstrap: filenode = oid
    //   RelationInitLockInfo(rel); RelationInitPhysicalAddr(rel);
    //   RelationCacheInsert(rel, false);
    // Until then, callers (step 14) take the returned descriptor.
    desc
}

// --- The C bootstrap-mode command API ------------------------------------------
//
// PG's bootparse.y drives bootstrap by calling these out of the BKI grammar. The
// grammar is tombstoned; the equivalent driver is `bootstrap_catalogs` below,
// which consumes the generated SCHEMA_/SEED_ data directly. These entry points
// are retained (the header re-exports them) and route through that data-driven
// path; the heap-write/index-build calls stage against the heap-AM stubs.

/// PG `BootstrapModeMain`: the `postgres --boot` entry. In this port there is no
/// BKI text to parse; bootstrap is driven by [`bootstrap_catalogs`]. Kept as the
/// named entry point (header re-exported); never returns in PG.
pub fn boot_strap_mode_main(argv: &[String], check_only: bool) -> ! {
    let _ = (argv, check_only);
    // STAGED: the real `postgres --boot` path runs InitPostgres in bootstrap
    // processing mode, then `bootstrap_catalogs`, then bootstrap-commit + proc_exit.
    // Wired when the bootstrap bin/initdb driver lands.
    unimplemented!("BootstrapModeMain: driven by bootstrap_catalogs once initdb bin lands")
}

/// The number of `.dat`-backed M2 catalogs `bootstrap_catalogs` seeds (the
/// inventory the BKI program would create). Kept for plumbing/unit tests.
#[must_use]
pub fn bootstrap_seed_inventory() -> usize {
    let seeded: &[(&str, &[SeedRow])] = &[
        ("pg_am", SEED_PG_AM),
        ("pg_namespace", SEED_PG_NAMESPACE),
        ("pg_collation", SEED_PG_COLLATION),
        ("pg_opclass", SEED_PG_OPCLASS),
        ("pg_amop", SEED_PG_AMOP),
        ("pg_amproc", SEED_PG_AMPROC),
    ];
    seeded.len()
}

/// One M2 built-in base type to seed into pg_type. The `.dat`-driven full pg_type
/// seed is not yet codegen'd (build.rs emits only the six `.dat` catalogs above);
/// these are the handful of base types the M2 `CREATE TABLE t(a int)` path needs
/// (its column type lookup resolves `int4` etc. by name). PG seeds these from
/// `pg_type.dat`; here they are an inline table (rules.md s4 -- the seed-codegen
/// for pg_type lands later; the on-disk rows are real either way).
struct BootBaseType {
    oid: Oid,
    name: &'static str,
    len: i16,
    byval: bool,
    align: i8,
    storage: i8,
    category: i8,
    preferred: bool,
    input: Oid,
    output: Oid,
}

/// One M2 built-in base type, mirroring a `pg_type.dat` base-type row.
/// `basetype!(BOOLOID, "bool", len => 1, byval => true, TYPALIGN_CHAR, TYPSTORAGE_PLAIN, TYPCATEGORY_BOOLEAN, preferred => false, f::F_BOOLIN, f::F_BOOLOUT)`
/// expands to a [`BootBaseType`] literal.
macro_rules! basetype {
    (
        $oid:expr, $name:expr, len => $len:expr, byval => $byval:expr,
        $align:expr, $storage:expr, $category:expr, preferred => $preferred:expr,
        $input:expr, $output:expr $(,)?
    ) => {
        BootBaseType {
            oid: $oid,
            name: $name,
            len: $len,
            byval: $byval,
            align: $align,
            storage: $storage,
            category: $category,
            preferred: $preferred,
            input: $input,
            output: $output,
        }
    };
}

/// The base-type seed set. The M2 set (oid/int2/int4/int8/bool/name/text) plus the
/// M4 cast-reachable numeric/float types (float4/float8/numeric) and date/time types
/// (date/timestamp). `typispreferred` matches pg_type.dat (float8 / int4 are the
/// preferred members of category N, so coercion picks them as common types).
fn m2_base_types() -> Vec<BootBaseType> {
    use crate::catalog::genbki::{
        BOOLOID, DATEOID, FLOAT4OID, FLOAT8OID, INT2OID, INT4OID, INT8OID, NAMEOID, NUMERICOID,
        OIDOID, TEXTOID, TIMESTAMPOID,
    };
    use crate::catalog::pg_type::{
        TYPALIGN_CHAR, TYPALIGN_DOUBLE, TYPALIGN_INT, TYPALIGN_SHORT, TYPCATEGORY_BOOLEAN,
        TYPCATEGORY_DATETIME, TYPCATEGORY_NUMERIC, TYPCATEGORY_STRING, TYPSTORAGE_EXTENDED,
        TYPSTORAGE_MAIN, TYPSTORAGE_PLAIN,
    };
    use crate::utils::fmgroids as f;
    // FLOAT8PASSBYVAL is true on 64-bit (Datum is 8 bytes); we target 64-bit only.
    vec![
        basetype!(BOOLOID, "bool", len => 1, byval => true, TYPALIGN_CHAR, TYPSTORAGE_PLAIN, TYPCATEGORY_BOOLEAN, preferred => false, f::F_BOOLIN, f::F_BOOLOUT),
        basetype!(NAMEOID, "name", len => 64, byval => false, TYPALIGN_CHAR, TYPSTORAGE_PLAIN, TYPCATEGORY_STRING, preferred => false, f::F_NAMEIN, f::F_NAMEOUT),
        basetype!(INT8OID, "int8", len => 8, byval => true, TYPALIGN_DOUBLE, TYPSTORAGE_PLAIN, TYPCATEGORY_NUMERIC, preferred => false, f::F_INT8IN, f::F_INT8OUT),
        basetype!(INT2OID, "int2", len => 2, byval => true, TYPALIGN_SHORT, TYPSTORAGE_PLAIN, TYPCATEGORY_NUMERIC, preferred => false, f::F_INT2IN, f::F_INT2OUT),
        basetype!(INT4OID, "int4", len => 4, byval => true, TYPALIGN_INT, TYPSTORAGE_PLAIN, TYPCATEGORY_NUMERIC, preferred => false, f::F_INT4IN, f::F_INT4OUT),
        basetype!(TEXTOID, "text", len => -1, byval => false, TYPALIGN_INT, TYPSTORAGE_EXTENDED, TYPCATEGORY_STRING, preferred => true, f::F_TEXTIN, f::F_TEXTOUT),
        basetype!(OIDOID, "oid", len => 4, byval => true, TYPALIGN_INT, TYPSTORAGE_PLAIN, TYPCATEGORY_NUMERIC, preferred => false, f::F_OIDIN, f::F_OIDOUT),
        basetype!(FLOAT4OID, "float4", len => 4, byval => true, TYPALIGN_INT, TYPSTORAGE_PLAIN, TYPCATEGORY_NUMERIC, preferred => false, f::F_FLOAT4IN, f::F_FLOAT4OUT),
        basetype!(FLOAT8OID, "float8", len => 8, byval => true, TYPALIGN_DOUBLE, TYPSTORAGE_PLAIN, TYPCATEGORY_NUMERIC, preferred => true, f::F_FLOAT8IN, f::F_FLOAT8OUT),
        basetype!(NUMERICOID, "numeric", len => -1, byval => false, TYPALIGN_INT, TYPSTORAGE_MAIN, TYPCATEGORY_NUMERIC, preferred => false, f::F_NUMERIC_IN, f::F_NUMERIC_OUT),
        basetype!(DATEOID, "date", len => 4, byval => true, TYPALIGN_INT, TYPSTORAGE_PLAIN, TYPCATEGORY_DATETIME, preferred => false, f::F_DATE_IN, f::F_DATE_OUT),
        basetype!(TIMESTAMPOID, "timestamp", len => 8, byval => true, TYPALIGN_DOUBLE, TYPSTORAGE_PLAIN, TYPCATEGORY_DATETIME, preferred => false, f::F_TIMESTAMP_IN, f::F_TIMESTAMP_OUT),
    ]
}

/// Create the main-fork storage file for a nailed catalog at its bootstrap locator
/// (relfilenode == oid, the current database, pg_default tablespace).
async fn create_catalog_storage(shared: &std::sync::Arc<crate::shared_state::SharedState>, relid: Oid) {
    let loc = crate::storage::relfilelocator::RelFileLocator {
        spcOid: crate::common::relpath::DEFAULTTABLESPACE_OID,
        dbOid: crate::session::current().database_id(),
        relNumber: relid,
    };
    let mut smgr = crate::storage::smgr::SmgrRelation::open(
        loc,
        crate::storage::procnumber::INVALID_PROC_NUMBER,
    );
    smgr.create(shared, crate::common::relpath::ForkNumber::MAIN_FORKNUM, false).await;
}

/// PG initdb's catalog-population pass, made data-driven (the BKI
/// `create`/`insert`/`build indices` program). Nails the formrdesc catalogs,
/// creates their heap storage, builds pg_type's unique indexes, then seeds the M2
/// base types into pg_type (via `CatalogTupleInsert`, which also fills the indexes).
///
/// After this runs, `SearchSysCache`/the relcache read the REAL on-disk catalogs
/// (a heap or index scan of pg_type/pg_class), so the int2/4/8 lsyscache fallback
/// from step 14 is only the cold-start (pre-initdb) path.
///
/// Must run inside the per-task scope stack (session / xact / snapmgr / relcache /
/// catalog-index registry / WAL insertion). Returns the number of base types
/// seeded.
///
/// STAGED (rules.md s4): the self-describing pg_class/pg_attribute rows for the
/// catalogs themselves, the six `.dat`-backed catalogs (pg_am, pg_namespace, and
/// the rest), and the full `.dat`-driven pg_type/pg_proc seed are deferred to the
/// seed-codegen + non-nailed-catalog initdb; the M2 type-resolution path needs only
/// the base types in pg_type, which are seeded here.
pub async fn bootstrap_catalogs(
    shared: &std::sync::Arc<crate::shared_state::SharedState>,
) -> usize {
    use crate::backend::catalog::index::{index_create, make_index_info};
    use crate::backend::catalog::pg_type::type_create;
    use crate::backend::utils::cache::relcache::{
        relation_cache_initialize_phase3, relation_id_get_relation, relation_close,
    };
    use crate::catalog::pg_namespace::PG_CATALOG_NAMESPACE;
    use crate::catalog::pg_type::{
        TypeNameNspIndexId, TypeOidIndexId, TypeRelationId, TYPCATEGORY_NUMERIC, TYPTYPE_BASE,
    };

    // 1. Nail the formrdesc catalogs (pg_class/pg_attribute/pg_proc/pg_type) so the
    //    relcache can read them before they exist on disk.
    relation_cache_initialize_phase3();

    // 2. Create the nailed catalogs' heap storage.
    for cat in FORMRDESC_CATALOGS {
        create_catalog_storage(shared, cat.relid).await;
    }

    // 3. Build pg_type's unique indexes over the (still empty) heap, so the seed
    //    inserts below populate them (gating decision 3: real btree catalog indexes).
    let pg_type = relation_id_get_relation(TypeRelationId)
        .unwrap_or_else(|| unreachable!("pg_type is nailed"));
    // pg_type_oid_index on (oid), pg_type_typname_nsp_index on (typname, typnamespace).
    let oid_info = make_index_info(&[crate::catalog::pg_type::Anum_pg_type_oid as i16], true);
    index_create(
        shared,
        &pg_type,
        "pg_type_oid_index",
        TypeOidIndexId,
        TypeOidIndexId,
        &oid_info,
        &["oid".to_owned()],
        Oid::new(403), // btree
        crate::common::relpath::DEFAULTTABLESPACE_OID,
        &[Oid::new(0)],
        &[Oid::new(1981)], // oid_ops
        &[0],
        false,
    )
    .await;
    relation_close(pg_type);

    // 4. Seed the M2 base types into pg_type (via CatalogTupleInsert -> heap +
    //    indexes). Each base type's row makes `int4` etc. resolvable by OID and by
    //    name from the real on-disk catalog.
    let types = m2_base_types();
    for ty in &types {
        type_create(
            shared,
            ty.oid,
            ty.name,
            PG_CATALOG_NAMESPACE,
            InvalidOid, // typrelid (base types have no rowtype relation)
            0,          // relation kind: none
            Oid::new(10),    // owner (bootstrap superuser)
            ty.len,
            TYPTYPE_BASE,
            ty.category,
            ty.preferred,
            b',' as i8,
            ty.input,
            ty.output,
            InvalidOid,
            InvalidOid,
            InvalidOid,
            InvalidOid,
            InvalidOid,
            InvalidOid,
            InvalidOid,
            false,
            InvalidOid, // array type (staged)
            InvalidOid,
            None,
            None,
            ty.byval,
            ty.align,
            ty.storage,
            -1,
            0,
            false,
            InvalidOid,
        )
        .await;
    }

    let _ = (TYPCATEGORY_NUMERIC, TypeNameNspIndexId); // (name index built with the table-create path)

    // 5. M3: bring up pg_proc + pg_operator (storage, indexes, seed rows) so the
    //    operator/function resolution syscaches resolve int4 +/>/etc. (the pg_proc
    //    seed also includes the M4 cast-support functions.)
    seed_pg_proc_m3(shared).await;
    seed_pg_operator_m3(shared).await;
    // 5b. M4 (step 23): bring up pg_cast (storage, indexes, seed rows) so
    //     find_coercion_pathway resolves int4->numeric/float8 etc. via pg_cast.
    seed_pg_cast_m4(shared).await;
    // 5c. M5 (step 25B): seed the aggregate support pg_proc rows + pg_aggregate so
    //     nodeAgg's AGGFNOID lookup resolves count/sum/min/max transfns.
    seed_pg_proc_m5_agg(shared).await;
    seed_pg_aggregate_m5(shared).await;
    // 5d. M10 (step 39): build the object-DDL catalogs' indexes and seed pg_namespace
    //     with the standard schemas (pg_catalog/public/pg_toast/information_schema).
    //     The other four (pg_sequence/pg_attrdef/pg_constraint/pg_description) start
    //     empty; the runtime DDL inserts into them.
    seed_object_ddl_catalogs(shared).await;

    // 6. Warm the operator/function-resolution syscaches for the seeded M3 set.
    //    The parser's operator resolution (make_op -> oper -> OpernameGetOprid) runs
    //    in SYNC context (transformExpr), so it can only hit ALREADY-WARM catcache
    //    entries (the index-scan miss path is async; staged). PG warms its critical
    //    caches at startup (InitCatalogCachePhase2); here we warm exactly the M3
    //    OPERNAMENSP / OPEROID / PROCOID / PROCNAMEARGSNSP entries the int4 operator
    //    and function resolution needs.
    //
    //    Make the just-inserted seed rows visible to the warm scans first: bump the
    //    command counter and drop the stale catalog snapshot so each warm heap-scan
    //    takes a fresh catalog snapshot that sees the new pg_operator/pg_proc rows.
    crate::backend::access::transam::xact::CommandCounterIncrement();
    crate::backend::utils::time::snapmgr::InvalidateCatalogSnapshot();
    warm_m3_resolution_caches(shared).await;

    types.len()
}

/// Warm the M3 operator/function resolution syscaches (OPERNAMENSP / OPEROID /
/// PROCOID / PROCNAMEARGSNSP) for the seeded int4 operators + support functions,
/// so the SYNC parser resolution path hits them. PG `InitCatalogCachePhase2` analog
/// for the M3-critical caches.
async fn warm_m3_resolution_caches(shared: &std::sync::Arc<crate::shared_state::SharedState>) {
    use crate::backend::catalog::heap::name_data;
    use crate::backend::utils::cache::syscache::{release_sys_cache, search_sys_cache_populate};
    use crate::catalog::pg_namespace::PG_CATALOG_NAMESPACE;
    use crate::postgres::{NameGetDatum, ObjectIdGetDatum, PointerGetDatum};
    use crate::utils::syscache::SysCacheIdentifier as Sc;

    for op in SEED_PG_OPERATOR_M3 {
        // OPERNAMENSP (oprname, oprleft, oprright, oprnamespace).
        let nd = name_data(op.name);
        let keys = [
            NameGetDatum(&nd),
            ObjectIdGetDatum(Oid::new(op.left)),
            ObjectIdGetDatum(Oid::new(op.right)),
            ObjectIdGetDatum(PG_CATALOG_NAMESPACE),
        ];
        if let Some(t) = search_sys_cache_populate(shared, Sc::OPERNAMENSP, &keys).await {
            release_sys_cache(t);
        }
        // OPEROID (oid).
        if let Some(t) =
            search_sys_cache_populate(shared, Sc::OPEROID, &[ObjectIdGetDatum(Oid::new(op.oid))]).await
        {
            release_sys_cache(t);
        }
    }

    for pr in SEED_PG_PROC_M3.iter().chain(SEED_PG_PROC_M4_CAST) {
        // PROCOID (oid) -- needed by get_func_retset in make_op and by the cast
        // FuncExpr resolution (the cast support functions).
        if let Some(t) =
            search_sys_cache_populate(shared, Sc::PROCOID, &[ObjectIdGetDatum(Oid::new(pr.oid))]).await
        {
            release_sys_cache(t);
        }
        // PROCNAMEARGSNSP (proname, proargtypes, pronamespace) -- function-by-name.
        let nd = name_data(pr.name);
        let argoids: Vec<Oid> = pr.argtypes.iter().map(|&o| Oid::new(o)).collect();
        let argvec = crate::utils::builtins::buildoidvector(&argoids);
        let keys = [
            NameGetDatum(&nd),
            PointerGetDatum(argvec.cast::<u8>()),
            ObjectIdGetDatum(PG_CATALOG_NAMESPACE),
        ];
        if let Some(t) = search_sys_cache_populate(shared, Sc::PROCNAMEARGSNSP, &keys).await {
            release_sys_cache(t);
        }
    }

    // M4 (step 23): warm CASTSOURCETARGET for each seeded cast, and TYPEOID for the
    // base types the cast resolution / I/O coercion reads (so the SYNC coercion path
    // -- find_coercion_pathway, getTypeOutputInfo/getTypeInputInfo -- hits a warm
    // cache over the wire).
    for ct in SEED_PG_CAST_M4 {
        let keys = [ObjectIdGetDatum(Oid::new(ct.source)), ObjectIdGetDatum(Oid::new(ct.target))];
        if let Some(t) = search_sys_cache_populate(shared, Sc::CASTSOURCETARGET, &keys).await {
            release_sys_cache(t);
        }
    }
    for ty in m2_base_types() {
        if let Some(t) =
            search_sys_cache_populate(shared, Sc::TYPEOID, &[ObjectIdGetDatum(ty.oid)]).await
        {
            release_sys_cache(t);
        }
    }

    // M5 (step 25B): warm AGGFNOID for each seeded aggregate so nodeAgg's sync
    // SearchSysCache1(AGGFNOID) hits at ExecInitAgg time.
    for agg in SEED_PG_AGGREGATE_M5 {
        if let Some(t) =
            search_sys_cache_populate(shared, Sc::AGGFNOID, &[ObjectIdGetDatum(Oid::new(agg.aggfnoid))]).await
        {
            release_sys_cache(t);
        }
    }
}

/// M3: create pg_proc storage, build its PROCOID + PROCNAMEARGSNSP indexes, and
/// seed the int4 operator support functions. pg_proc is nailed (formrdesc), so its
/// descriptor already exists.
async fn seed_pg_proc_m3(shared: &std::sync::Arc<crate::shared_state::SharedState>) {
    use crate::backend::access::common::heaptuple::{heap_form_tuple, heap_freetuple};
    use crate::backend::catalog::index::{index_create, make_index_info};
    use crate::backend::catalog::indexing::catalog_tuple_insert;
    use crate::backend::utils::cache::relcache::{relation_close, relation_id_get_relation};
    use crate::catalog::pg_namespace::PG_CATALOG_NAMESPACE;
    use crate::catalog::pg_proc::{
        self as p, ProcedureNameArgsNspIndexId, ProcedureOidIndexId, ProcedureRelationId,
        PROKIND_FUNCTION, PROPARALLEL_SAFE, PROVOLATILE_IMMUTABLE,
    };
    use crate::postgres::{
        BoolGetDatum, CharGetDatum, Datum, Float4GetDatum, Int16GetDatum, NameGetDatum,
        ObjectIdGetDatum, PointerGetDatum,
    };

    use crate::backend::catalog::heap::name_data;

    create_catalog_storage(shared, ProcedureRelationId).await;

    let pg_proc = relation_id_get_relation(ProcedureRelationId)
        .unwrap_or_else(|| unreachable!("pg_proc is nailed"));

    // pg_proc_oid_index on (oid). This is the only catalog index built at bootstrap
    // (matching pg_type): the M3 syscache lookups heap-scan and apply keys
    // post-fetch (the index-scan arm is staged), so PROCNAMEARGSNSP needs no
    // on-disk index. Building the (proname, proargtypes, pronamespace) index would
    // require an oidvector btree opclass that is not seeded yet; deferred with the
    // index-scan syscache path.
    let oid_info = make_index_info(&[p::Anum_pg_proc_oid as i16], true);
    index_create(
        shared, &pg_proc, "pg_proc_oid_index", ProcedureOidIndexId, ProcedureOidIndexId,
        &oid_info, &["oid".to_owned()], Oid::new(403), crate::common::relpath::DEFAULTTABLESPACE_OID,
        &[Oid::new(0)], &[Oid::new(1981)], &[0], false,
    ).await;
    let _ = ProcedureNameArgsNspIndexId;

    let desc = pg_proc.rd_att.clone().unwrap_or_else(|| unreachable!("pg_proc has a descriptor"));
    let natts = desc.natts as usize;

    // The M3 operator-support functions plus the M4 cast-support functions
    // (int4_numeric, i4tod, numeric_int4, ...) share this seed pass.
    for pr in SEED_PG_PROC_M3.iter().chain(SEED_PG_PROC_M4_CAST) {
        let mut values = vec![Datum(0); natts];
        let mut isnull = vec![false; natts];
        let set = |v: &mut [Datum], anum: i32, d: Datum| v[(anum - 1) as usize] = d;

        let argoids: Vec<Oid> = pr.argtypes.iter().map(|&o| Oid::new(o)).collect();
        let argvec = crate::utils::builtins::buildoidvector(&argoids);
        let name = name_data(pr.name);
        set(&mut values, p::Anum_pg_proc_oid, ObjectIdGetDatum(Oid::new(pr.oid)));
        set(&mut values, p::Anum_pg_proc_proname, NameGetDatum(&name));
        set(&mut values, p::Anum_pg_proc_pronamespace, ObjectIdGetDatum(PG_CATALOG_NAMESPACE));
        set(&mut values, p::Anum_pg_proc_proowner, ObjectIdGetDatum(Oid::new(10)));
        set(&mut values, p::Anum_pg_proc_prolang, ObjectIdGetDatum(Oid::new(12))); // internal
        set(&mut values, p::Anum_pg_proc_procost, Float4GetDatum(1.0));
        set(&mut values, p::Anum_pg_proc_prorows, Float4GetDatum(0.0));
        set(&mut values, p::Anum_pg_proc_provariadic, ObjectIdGetDatum(InvalidOid));
        set(&mut values, p::Anum_pg_proc_prosupport, ObjectIdGetDatum(InvalidOid));
        set(&mut values, p::Anum_pg_proc_prokind, CharGetDatum(PROKIND_FUNCTION));
        set(&mut values, p::Anum_pg_proc_prosecdef, BoolGetDatum(false));
        set(&mut values, p::Anum_pg_proc_proleakproof, BoolGetDatum(false));
        set(&mut values, p::Anum_pg_proc_proisstrict, BoolGetDatum(pr.strict));
        set(&mut values, p::Anum_pg_proc_proretset, BoolGetDatum(pr.retset));
        set(&mut values, p::Anum_pg_proc_provolatile, CharGetDatum(PROVOLATILE_IMMUTABLE));
        set(&mut values, p::Anum_pg_proc_proparallel, CharGetDatum(PROPARALLEL_SAFE));
        set(&mut values, p::Anum_pg_proc_pronargs, Int16GetDatum(i16::try_from(pr.argtypes.len()).unwrap_or(0)));
        set(&mut values, p::Anum_pg_proc_pronargdefaults, Int16GetDatum(0));
        set(&mut values, p::Anum_pg_proc_prorettype, ObjectIdGetDatum(Oid::new(pr.rettype)));
        set(&mut values, p::Anum_pg_proc_proargtypes, PointerGetDatum(argvec.cast::<u8>()));
        set(&mut values, p::Anum_pg_proc_prosrc, crate::utils::builtins::CStringGetTextDatum(pr.prosrc));

        // Nullable varlen tail columns (IN-only, no defaults): all NULL.
        for anum in [
            p::Anum_pg_proc_proallargtypes, p::Anum_pg_proc_proargmodes,
            p::Anum_pg_proc_proargnames, p::Anum_pg_proc_proargdefaults,
            p::Anum_pg_proc_protrftypes, p::Anum_pg_proc_probin,
            p::Anum_pg_proc_prosqlbody, p::Anum_pg_proc_proconfig, p::Anum_pg_proc_proacl,
        ] {
            isnull[(anum - 1) as usize] = true;
        }

        let mut tuple = heap_form_tuple(&desc, &values, &isnull);
        catalog_tuple_insert(shared, &pg_proc, &mut tuple).await;
        heap_freetuple(tuple);
    }
    relation_close(pg_proc);
}

/// M3: create pg_operator storage, build its OPEROID + OPERNAMENSP indexes, and
/// seed the int4 arithmetic/comparison operators. pg_operator is nailed.
async fn seed_pg_operator_m3(shared: &std::sync::Arc<crate::shared_state::SharedState>) {
    use crate::backend::access::common::heaptuple::{heap_form_tuple, heap_freetuple};
    use crate::backend::catalog::index::{index_create, make_index_info};
    use crate::backend::catalog::indexing::catalog_tuple_insert;
    use crate::backend::utils::cache::relcache::{relation_close, relation_id_get_relation};
    use crate::catalog::pg_namespace::PG_CATALOG_NAMESPACE;
    use crate::catalog::pg_operator::{
        self as o, OperatorNameNspIndexId, OperatorOidIndexId, OperatorRelationId,
    };
    use crate::postgres::{
        BoolGetDatum, CharGetDatum, Datum, NameGetDatum, ObjectIdGetDatum,
    };

    use crate::backend::catalog::heap::name_data;

    create_catalog_storage(shared, OperatorRelationId).await;

    let pg_operator = relation_id_get_relation(OperatorRelationId)
        .unwrap_or_else(|| unreachable!("pg_operator is nailed"));

    // pg_operator_oid_index on (oid) -- the only operator index built at bootstrap.
    // The OPERNAMENSP lookup heap-scans (the index-scan syscache arm is staged), so
    // the (oprname, oprleft, oprright, oprnamespace) index is not needed on disk.
    let oid_info = make_index_info(&[o::Anum_pg_operator_oid as i16], true);
    index_create(
        shared, &pg_operator, "pg_operator_oid_index", OperatorOidIndexId, OperatorOidIndexId,
        &oid_info, &["oid".to_owned()], Oid::new(403), crate::common::relpath::DEFAULTTABLESPACE_OID,
        &[Oid::new(0)], &[Oid::new(1981)], &[0], false,
    ).await;
    let _ = OperatorNameNspIndexId;

    let desc = pg_operator.rd_att.clone().unwrap_or_else(|| unreachable!("pg_operator has a descriptor"));
    let natts = desc.natts as usize;

    for op in SEED_PG_OPERATOR_M3 {
        let mut values = vec![Datum(0); natts];
        let isnull = vec![false; natts];
        let set = |v: &mut [Datum], anum: i32, d: Datum| v[(anum - 1) as usize] = d;

        let name = name_data(op.name);
        set(&mut values, o::Anum_pg_operator_oid, ObjectIdGetDatum(Oid::new(op.oid)));
        set(&mut values, o::Anum_pg_operator_oprname, NameGetDatum(&name));
        set(&mut values, o::Anum_pg_operator_oprnamespace, ObjectIdGetDatum(PG_CATALOG_NAMESPACE));
        set(&mut values, o::Anum_pg_operator_oprowner, ObjectIdGetDatum(Oid::new(10)));
        set(&mut values, o::Anum_pg_operator_oprkind, CharGetDatum(op.kind as i8));
        set(&mut values, o::Anum_pg_operator_oprcanmerge, BoolGetDatum(false));
        set(&mut values, o::Anum_pg_operator_oprcanhash, BoolGetDatum(false));
        set(&mut values, o::Anum_pg_operator_oprleft, ObjectIdGetDatum(Oid::new(op.left)));
        set(&mut values, o::Anum_pg_operator_oprright, ObjectIdGetDatum(Oid::new(op.right)));
        set(&mut values, o::Anum_pg_operator_oprresult, ObjectIdGetDatum(Oid::new(op.result)));
        // commutator/negator references are not needed for M3 resolution.
        set(&mut values, o::Anum_pg_operator_oprcom, ObjectIdGetDatum(InvalidOid));
        set(&mut values, o::Anum_pg_operator_oprnegate, ObjectIdGetDatum(InvalidOid));
        set(&mut values, o::Anum_pg_operator_oprcode, ObjectIdGetDatum(Oid::new(op.code)));
        set(&mut values, o::Anum_pg_operator_oprrest, ObjectIdGetDatum(InvalidOid));
        set(&mut values, o::Anum_pg_operator_oprjoin, ObjectIdGetDatum(InvalidOid));

        let mut tuple = heap_form_tuple(&desc, &values, &isnull);
        catalog_tuple_insert(shared, &pg_operator, &mut tuple).await;
        heap_freetuple(tuple);
    }
    relation_close(pg_operator);
}

/// M4 (step 23): create pg_cast storage, build its CastOid + CastSourceTarget
/// indexes, and seed the numeric/int/float cast tower. pg_cast is NOT nailed, so
/// its relcache entry + descriptor come from the on-disk pg_class/pg_attribute
/// (built by the table-create path); here we create the storage and seed rows like
/// the other M3 catalogs. The CASTSOURCETARGET syscache (wired in cacheinfo) reads
/// these rows so `find_coercion_pathway` resolves int4->numeric etc.
async fn seed_pg_cast_m4(shared: &std::sync::Arc<crate::shared_state::SharedState>) {
    use crate::backend::access::common::heaptuple::{heap_form_tuple, heap_freetuple};
    use crate::backend::catalog::index::{index_create, make_index_info};
    use crate::backend::catalog::indexing::catalog_tuple_insert;
    use crate::backend::utils::cache::relcache::{relation_close, relation_id_get_relation};
    use crate::catalog::pg_cast::{
        self as c, CastOidIndexId, CastRelationId, CastSourceTargetIndexId,
    };
    use crate::postgres::{CharGetDatum, Datum, ObjectIdGetDatum};

    create_catalog_storage(shared, CastRelationId).await;

    let pg_cast = relation_id_get_relation(CastRelationId)
        .unwrap_or_else(|| unreachable!("pg_cast relcache entry exists post table-create"));

    // pg_cast_oid_index on (oid) and pg_cast_source_target_index on
    // (castsource, casttarget). Both are unique. The CASTSOURCETARGET syscache
    // heap-scans + applies the two keys post-fetch (the index-scan arm is staged),
    // matching the other M3 catalogs; the source/target index is still built so the
    // on-disk catalog is complete.
    let oid_info = make_index_info(&[c::Anum_pg_cast_oid as i16], true);
    index_create(
        shared, &pg_cast, "pg_cast_oid_index", CastOidIndexId, CastOidIndexId,
        &oid_info, &["oid".to_owned()], Oid::new(403), crate::common::relpath::DEFAULTTABLESPACE_OID,
        &[Oid::new(0)], &[Oid::new(1981)], &[0], false,
    ).await;
    let st_info = make_index_info(
        &[c::Anum_pg_cast_castsource as i16, c::Anum_pg_cast_casttarget as i16],
        true,
    );
    index_create(
        shared, &pg_cast, "pg_cast_source_target_index", CastSourceTargetIndexId,
        CastSourceTargetIndexId, &st_info,
        &["castsource".to_owned(), "casttarget".to_owned()], Oid::new(403),
        crate::common::relpath::DEFAULTTABLESPACE_OID,
        &[Oid::new(0), Oid::new(0)], &[Oid::new(1981), Oid::new(1981)], &[0, 0], false,
    ).await;

    let desc = pg_cast.rd_att.clone().unwrap_or_else(|| unreachable!("pg_cast has a descriptor"));
    let natts = desc.natts as usize;

    for ct in SEED_PG_CAST_M4 {
        let mut values = vec![Datum(0); natts];
        let isnull = vec![false; natts];
        let set = |v: &mut [Datum], anum: i32, d: Datum| v[(anum - 1) as usize] = d;

        set(&mut values, c::Anum_pg_cast_oid, ObjectIdGetDatum(Oid::new(ct.oid)));
        set(&mut values, c::Anum_pg_cast_castsource, ObjectIdGetDatum(Oid::new(ct.source)));
        set(&mut values, c::Anum_pg_cast_casttarget, ObjectIdGetDatum(Oid::new(ct.target)));
        set(&mut values, c::Anum_pg_cast_castfunc, ObjectIdGetDatum(Oid::new(ct.func)));
        set(&mut values, c::Anum_pg_cast_castcontext, CharGetDatum(ct.context as i8));
        set(&mut values, c::Anum_pg_cast_castmethod, CharGetDatum(ct.method as i8));

        let mut tuple = heap_form_tuple(&desc, &values, &isnull);
        catalog_tuple_insert(shared, &pg_cast, &mut tuple).await;
        heap_freetuple(tuple);
    }
    relation_close(pg_cast);
}

/// M5 (step 25B): seed the aggregate support pg_proc rows -- the aggregate procs
/// themselves (prokind 'a', e.g. count/sum/min/max) and their transition/final
/// functions (int8inc/int4_sum/int4larger/...). pg_proc storage + its oid index
/// already exist (seed_pg_proc_m3); we reopen the nailed relation and insert.
/// Rows whose OID was already seeded by M3/M4 are skipped (transfns like int4larger
/// may overlap once more types land; the M5 set is disjoint today, but the guard
/// keeps it idempotent).
async fn seed_pg_proc_m5_agg(shared: &std::sync::Arc<crate::shared_state::SharedState>) {
    use crate::backend::access::common::heaptuple::{heap_form_tuple, heap_freetuple};
    use crate::backend::catalog::heap::name_data;
    use crate::backend::catalog::indexing::catalog_tuple_insert;
    use crate::backend::utils::cache::relcache::{relation_close, relation_id_get_relation};
    use crate::catalog::pg_namespace::PG_CATALOG_NAMESPACE;
    use crate::catalog::pg_proc::{
        self as p, ProcedureRelationId, PROKIND_AGGREGATE, PROKIND_FUNCTION, PROPARALLEL_SAFE,
        PROVOLATILE_IMMUTABLE,
    };
    use crate::postgres::{
        BoolGetDatum, CharGetDatum, Datum, Float4GetDatum, Int16GetDatum, NameGetDatum,
        ObjectIdGetDatum, PointerGetDatum,
    };

    let pg_proc = relation_id_get_relation(ProcedureRelationId)
        .unwrap_or_else(|| unreachable!("pg_proc is nailed"));
    let desc = pg_proc.rd_att.clone().unwrap_or_else(|| unreachable!("pg_proc has a descriptor"));
    let natts = desc.natts as usize;

    for pr in SEED_PG_PROC_M5_AGG {
        // The aggregate procs use prosrc "aggregate_dummy" (never fmgr-called);
        // prokind 'a' for them, 'f' for the support functions.
        let prokind = if pr.prosrc == "aggregate_dummy" { PROKIND_AGGREGATE } else { PROKIND_FUNCTION };

        let mut values = vec![Datum(0); natts];
        let mut isnull = vec![false; natts];
        let set = |v: &mut [Datum], anum: i32, d: Datum| v[(anum - 1) as usize] = d;

        let argoids: Vec<Oid> = pr.argtypes.iter().map(|&o| Oid::new(o)).collect();
        let argvec = crate::utils::builtins::buildoidvector(&argoids);
        let name = name_data(pr.name);
        set(&mut values, p::Anum_pg_proc_oid, ObjectIdGetDatum(Oid::new(pr.oid)));
        set(&mut values, p::Anum_pg_proc_proname, NameGetDatum(&name));
        set(&mut values, p::Anum_pg_proc_pronamespace, ObjectIdGetDatum(PG_CATALOG_NAMESPACE));
        set(&mut values, p::Anum_pg_proc_proowner, ObjectIdGetDatum(Oid::new(10)));
        set(&mut values, p::Anum_pg_proc_prolang, ObjectIdGetDatum(Oid::new(12))); // internal
        set(&mut values, p::Anum_pg_proc_procost, Float4GetDatum(1.0));
        set(&mut values, p::Anum_pg_proc_prorows, Float4GetDatum(0.0));
        set(&mut values, p::Anum_pg_proc_provariadic, ObjectIdGetDatum(InvalidOid));
        set(&mut values, p::Anum_pg_proc_prosupport, ObjectIdGetDatum(InvalidOid));
        set(&mut values, p::Anum_pg_proc_prokind, CharGetDatum(prokind));
        set(&mut values, p::Anum_pg_proc_prosecdef, BoolGetDatum(false));
        set(&mut values, p::Anum_pg_proc_proleakproof, BoolGetDatum(false));
        set(&mut values, p::Anum_pg_proc_proisstrict, BoolGetDatum(pr.strict));
        set(&mut values, p::Anum_pg_proc_proretset, BoolGetDatum(pr.retset));
        set(&mut values, p::Anum_pg_proc_provolatile, CharGetDatum(PROVOLATILE_IMMUTABLE));
        set(&mut values, p::Anum_pg_proc_proparallel, CharGetDatum(PROPARALLEL_SAFE));
        set(&mut values, p::Anum_pg_proc_pronargs, Int16GetDatum(i16::try_from(pr.argtypes.len()).unwrap_or(0)));
        set(&mut values, p::Anum_pg_proc_pronargdefaults, Int16GetDatum(0));
        set(&mut values, p::Anum_pg_proc_prorettype, ObjectIdGetDatum(Oid::new(pr.rettype)));
        set(&mut values, p::Anum_pg_proc_proargtypes, PointerGetDatum(argvec.cast::<u8>()));
        set(&mut values, p::Anum_pg_proc_prosrc, crate::utils::builtins::CStringGetTextDatum(pr.prosrc));

        for anum in [
            p::Anum_pg_proc_proallargtypes, p::Anum_pg_proc_proargmodes,
            p::Anum_pg_proc_proargnames, p::Anum_pg_proc_proargdefaults,
            p::Anum_pg_proc_protrftypes, p::Anum_pg_proc_probin,
            p::Anum_pg_proc_prosqlbody, p::Anum_pg_proc_proconfig, p::Anum_pg_proc_proacl,
        ] {
            isnull[(anum - 1) as usize] = true;
        }

        let mut tuple = heap_form_tuple(&desc, &values, &isnull);
        catalog_tuple_insert(shared, &pg_proc, &mut tuple).await;
        heap_freetuple(tuple);
    }
    relation_close(pg_proc);
}

/// M5 (step 25B): create pg_aggregate storage, build its AGGFNOID index, and seed
/// the common aggregates (count/sum/min/max). pg_aggregate is nailed (formrdesc).
/// The AGGFNOID syscache heap-scans + applies the aggfnoid key post-fetch (the
/// index-scan arm is staged), matching the M3 catalogs; the index is still built so
/// the on-disk catalog is complete.
async fn seed_pg_aggregate_m5(shared: &std::sync::Arc<crate::shared_state::SharedState>) {
    use crate::backend::access::common::heaptuple::{heap_form_tuple, heap_freetuple};
    use crate::backend::catalog::index::{index_create, make_index_info};
    use crate::backend::catalog::indexing::catalog_tuple_insert;
    use crate::backend::utils::cache::relcache::{relation_close, relation_id_get_relation};
    use crate::catalog::pg_aggregate::{self as a, AggregateFnoidIndexId, AggregateRelationId};
    use crate::postgres::{BoolGetDatum, CharGetDatum, Datum, Int16GetDatum, ObjectIdGetDatum};

    create_catalog_storage(shared, AggregateRelationId).await;

    let pg_aggregate = relation_id_get_relation(AggregateRelationId)
        .unwrap_or_else(|| unreachable!("pg_aggregate relcache entry exists post table-create"));

    // pg_aggregate_fnoid_index on (aggfnoid). Unique; the AGGFNOID syscache heap-scans
    // + applies the key post-fetch (the index-scan arm is staged).
    let oid_info = make_index_info(&[a::Anum_pg_aggregate_aggfnoid as i16], true);
    index_create(
        shared, &pg_aggregate, "pg_aggregate_fnoid_index", AggregateFnoidIndexId,
        AggregateFnoidIndexId, &oid_info, &["aggfnoid".to_owned()], Oid::new(403),
        crate::common::relpath::DEFAULTTABLESPACE_OID,
        &[Oid::new(0)], &[Oid::new(1981)], &[0], false,
    ).await;

    let desc = pg_aggregate.rd_att.clone().unwrap_or_else(|| unreachable!("pg_aggregate has a descriptor"));
    let natts = desc.natts as usize;

    for agg in SEED_PG_AGGREGATE_M5 {
        let mut values = vec![Datum(0); natts];
        let mut isnull = vec![false; natts];
        let set = |v: &mut [Datum], anum: i32, d: Datum| v[(anum - 1) as usize] = d;

        set(&mut values, a::Anum_pg_aggregate_aggfnoid, ObjectIdGetDatum(Oid::new(agg.aggfnoid)));
        set(&mut values, a::Anum_pg_aggregate_aggkind, CharGetDatum(agg.aggkind as i8));
        set(&mut values, a::Anum_pg_aggregate_aggnumdirectargs, Int16GetDatum(0));
        set(&mut values, a::Anum_pg_aggregate_aggtransfn, ObjectIdGetDatum(Oid::new(agg.aggtransfn)));
        set(&mut values, a::Anum_pg_aggregate_aggfinalfn, ObjectIdGetDatum(Oid::new(agg.aggfinalfn)));
        set(&mut values, a::Anum_pg_aggregate_aggcombinefn, ObjectIdGetDatum(InvalidOid));
        set(&mut values, a::Anum_pg_aggregate_aggserialfn, ObjectIdGetDatum(InvalidOid));
        set(&mut values, a::Anum_pg_aggregate_aggdeserialfn, ObjectIdGetDatum(InvalidOid));
        set(&mut values, a::Anum_pg_aggregate_aggmtransfn, ObjectIdGetDatum(InvalidOid));
        set(&mut values, a::Anum_pg_aggregate_aggminvtransfn, ObjectIdGetDatum(InvalidOid));
        set(&mut values, a::Anum_pg_aggregate_aggmfinalfn, ObjectIdGetDatum(InvalidOid));
        set(&mut values, a::Anum_pg_aggregate_aggfinalextra, BoolGetDatum(false));
        set(&mut values, a::Anum_pg_aggregate_aggmfinalextra, BoolGetDatum(false));
        set(&mut values, a::Anum_pg_aggregate_aggfinalmodify, CharGetDatum(b'r' as i8));
        set(&mut values, a::Anum_pg_aggregate_aggmfinalmodify, CharGetDatum(b'r' as i8));
        set(&mut values, a::Anum_pg_aggregate_aggsortop, ObjectIdGetDatum(InvalidOid));
        set(&mut values, a::Anum_pg_aggregate_aggtranstype, ObjectIdGetDatum(Oid::new(agg.aggtranstype)));
        set(&mut values, a::Anum_pg_aggregate_aggtransspace, crate::postgres::Int32GetDatum(0));
        set(&mut values, a::Anum_pg_aggregate_aggmtranstype, ObjectIdGetDatum(InvalidOid));
        set(&mut values, a::Anum_pg_aggregate_aggmtransspace, crate::postgres::Int32GetDatum(0));

        // agginitval / aggminitval are nullable varlen text. Seed the running
        // initval where present (count's "0"); aggminitval is always NULL here.
        match agg.initval {
            Some(s) => set(&mut values, a::Anum_pg_aggregate_agginitval, crate::utils::builtins::CStringGetTextDatum(s)),
            None => isnull[(a::Anum_pg_aggregate_agginitval - 1) as usize] = true,
        }
        isnull[(a::Anum_pg_aggregate_aggminitval - 1) as usize] = true;

        let mut tuple = heap_form_tuple(&desc, &values, &isnull);
        catalog_tuple_insert(shared, &pg_aggregate, &mut tuple).await;
        heap_freetuple(tuple);
    }
    relation_close(pg_aggregate);
}

/// M10 (step 39): bring up the object-DDL catalogs. Build the oid (pkey) index for
/// each so `catalog_tuple_insert` populates it, then seed pg_namespace's standard
/// schema rows (pg_catalog/public/pg_toast/information_schema) so `CREATE SCHEMA`
/// inserts alongside them and schema-name resolution heap-scans real rows. The other
/// four catalogs (pg_sequence/pg_attrdef/pg_constraint/pg_description) start empty;
/// the runtime DDL inserts into them. Their storage was created by the FORMRDESC
/// loop above.
async fn seed_object_ddl_catalogs(shared: &std::sync::Arc<crate::shared_state::SharedState>) {
    use crate::backend::access::common::heaptuple::{heap_form_tuple, heap_freetuple};
    use crate::backend::catalog::heap::name_data;
    use crate::backend::catalog::index::{index_create, make_index_info};
    use crate::backend::catalog::indexing::catalog_tuple_insert;
    use crate::backend::utils::cache::relcache::{relation_close, relation_id_get_relation};
    use crate::catalog::pg_attrdef::AttrDefaultOidIndexId;
    use crate::catalog::pg_constraint::ConstraintOidIndexId;
    use crate::catalog::pg_namespace::{
        self as ns, NamespaceOidIndexId, PG_CATALOG_NAMESPACE,
    };
    use crate::catalog::pg_sequence::SequenceRelidIndexId;
    use crate::postgres::{Datum, NameGetDatum, ObjectIdGetDatum};

    // Build each catalog's oid/pkey index (so inserts maintain it). pg_sequence's
    // pkey is on seqrelid (an oid); the rest are on oid. pg_description's pkey is a
    // 3-column index -- not built here (its rows are looked up by heap scan; the
    // multi-col index needs an oid+oid+int4 opclass set not yet seeded). The oid
    // indexes use the seeded oid_ops btree opclass (1981).
    let build_oid_index = async |relid: Oid, index_id: Oid, index_name: &str, col: &str, attno: i16| {
        let Some(rel) = relation_id_get_relation(relid) else { return };
        let info = make_index_info(&[attno], true);
        index_create(
            shared, &rel, index_name, index_id, index_id, &info, &[col.to_owned()],
            Oid::new(403), crate::common::relpath::DEFAULTTABLESPACE_OID,
            &[Oid::new(0)], &[Oid::new(1981)], &[0], false,
        )
        .await;
        relation_close(rel);
    };

    build_oid_index(
        NamespaceRelationId, NamespaceOidIndexId, "pg_namespace_oid_index", "oid",
        ns::Anum_pg_namespace_oid as i16,
    )
    .await;
    build_oid_index(
        SequenceRelationId, SequenceRelidIndexId, "pg_sequence_seqrelid_index", "seqrelid",
        crate::catalog::pg_sequence::Anum_pg_sequence_seqrelid as i16,
    )
    .await;
    build_oid_index(
        AttrDefaultRelationId, AttrDefaultOidIndexId, "pg_attrdef_oid_index", "oid",
        crate::catalog::pg_attrdef::Anum_pg_attrdef_oid as i16,
    )
    .await;
    build_oid_index(
        ConstraintRelationId, ConstraintOidIndexId, "pg_constraint_oid_index", "oid",
        crate::catalog::pg_constraint::Anum_pg_constraint_oid as i16,
    )
    .await;
    // M10 (step 39B): the minor object-DDL catalogs' oid indexes. The pkey index OIDs
    // are the upstream DECLARE_UNIQUE_INDEX_PKEY values (defined inline -- the catalog
    // headers carry them only as comments on M10).
    build_oid_index(
        DatabaseRelationId, Oid::new(2672), "pg_database_oid_index", "oid",
        crate::catalog::pg_database::Anum_pg_database_oid as i16,
    )
    .await;
    build_oid_index(
        TableSpaceRelationId, Oid::new(2697), "pg_tablespace_oid_index", "oid",
        crate::catalog::pg_tablespace::Anum_pg_tablespace_oid as i16,
    )
    .await;
    build_oid_index(
        CollationRelationId, Oid::new(3085), "pg_collation_oid_index", "oid",
        crate::catalog::pg_collation::Anum_pg_collation_oid as i16,
    )
    .await;
    build_oid_index(
        ConversionRelationId, Oid::new(2670), "pg_conversion_oid_index", "oid",
        crate::catalog::pg_conversion::Anum_pg_conversion_oid as i16,
    )
    .await;

    // Seed pg_namespace with the standard schema rows from SEED_PG_NAMESPACE (the
    // .dat-driven oid/nspname/nspowner; nspacl is NULL).
    let Some(pg_namespace) = relation_id_get_relation(NamespaceRelationId) else { return };
    let desc = pg_namespace.rd_att.clone().unwrap_or_else(|| unreachable!("pg_namespace desc"));
    let natts = desc.natts as usize;
    for row in SEED_PG_NAMESPACE {
        let oid: u32 = row.iter().find(|(c, _)| *c == "oid").map_or(0, |(_, v)| v.parse().unwrap_or(0));
        let name = row.iter().find(|(c, _)| *c == "nspname").map_or("", |(_, v)| v);
        let nsp_name = name_data(name); // kept alive to back NameGetDatum

        let mut values = vec![Datum(0); natts];
        let mut isnull = vec![false; natts];
        values[(ns::Anum_pg_namespace_oid - 1) as usize] = ObjectIdGetDatum(Oid::new(oid));
        values[(ns::Anum_pg_namespace_nspname - 1) as usize] = NameGetDatum(&nsp_name);
        // BKI_DEFAULT(POSTGRES): the bootstrap superuser (oid 10).
        values[(ns::Anum_pg_namespace_nspowner - 1) as usize] = ObjectIdGetDatum(Oid::new(10));
        // nspacl is NULL (no initial ACL).
        isnull[(ns::Anum_pg_namespace_nspacl - 1) as usize] = true;

        let mut tuple = heap_form_tuple(&desc, &values, &isnull);
        catalog_tuple_insert(shared, &pg_namespace, &mut tuple).await;
        heap_freetuple(tuple);
    }
    relation_close(pg_namespace);
    let _ = PG_CATALOG_NAMESPACE;

    seed_pg_tablespace(shared).await;
    seed_pg_database(shared).await;
}

/// Seed pg_tablespace with the two bootstrap tablespaces (pg_default/pg_global) from
/// SEED_PG_TABLESPACE. spcacl/spcoptions are NULL.
async fn seed_pg_tablespace(shared: &std::sync::Arc<crate::shared_state::SharedState>) {
    use crate::backend::access::common::heaptuple::{heap_form_tuple, heap_freetuple};
    use crate::backend::catalog::heap::name_data;
    use crate::backend::catalog::indexing::catalog_tuple_insert;
    use crate::backend::utils::cache::relcache::{relation_close, relation_id_get_relation};
    use crate::catalog::pg_tablespace as ts;
    use crate::postgres::{Datum, NameGetDatum, ObjectIdGetDatum};

    let Some(pg_tablespace) = relation_id_get_relation(TableSpaceRelationId) else { return };
    let desc = pg_tablespace.rd_att.clone().unwrap_or_else(|| unreachable!("pg_tablespace desc"));
    let natts = desc.natts as usize;
    for row in SEED_PG_TABLESPACE {
        let oid: u32 = row.iter().find(|(c, _)| *c == "oid").map_or(0, |(_, v)| v.parse().unwrap_or(0));
        let name = row.iter().find(|(c, _)| *c == "spcname").map_or("", |(_, v)| v);
        let spc_name = name_data(name);

        let mut values = vec![Datum(0); natts];
        let mut isnull = vec![false; natts];
        values[(ts::Anum_pg_tablespace_oid - 1) as usize] = ObjectIdGetDatum(Oid::new(oid));
        values[(ts::Anum_pg_tablespace_spcname - 1) as usize] = NameGetDatum(&spc_name);
        values[(ts::Anum_pg_tablespace_spcowner - 1) as usize] = ObjectIdGetDatum(Oid::new(10));
        isnull[(ts::Anum_pg_tablespace_spcacl - 1) as usize] = true;
        isnull[(ts::Anum_pg_tablespace_spcoptions - 1) as usize] = true;

        let mut tuple = heap_form_tuple(&desc, &values, &isnull);
        catalog_tuple_insert(shared, &pg_tablespace, &mut tuple).await;
        heap_freetuple(tuple);
    }
    relation_close(pg_tablespace);
}

/// Seed pg_database with the bootstrap rows: template1 (oid 1), template0 (oid 4),
/// postgres (oid 5). PG's `.dat` carries only template1 (template0/postgres are made
/// by initdb's bootstrap script); the single-database port seeds all three so DROP
/// DATABASE against the standard names removes a real row and CREATE DATABASE inserts
/// alongside them. The varlena locale columns are NULL (single-db: no per-db locale).
async fn seed_pg_database(shared: &std::sync::Arc<crate::shared_state::SharedState>) {
    use crate::backend::access::common::heaptuple::{heap_form_tuple, heap_freetuple};
    use crate::backend::catalog::heap::name_data;
    use crate::backend::catalog::indexing::catalog_tuple_insert;
    use crate::backend::utils::cache::relcache::{relation_close, relation_id_get_relation};
    use crate::catalog::pg_database as db;
    use crate::postgres::{BoolGetDatum, CharGetDatum, Datum, Int32GetDatum, NameGetDatum, ObjectIdGetDatum, TransactionIdGetDatum};

    let Some(pg_database) = relation_id_get_relation(DatabaseRelationId) else { return };
    let desc = pg_database.rd_att.clone().unwrap_or_else(|| unreachable!("pg_database desc"));
    let natts = desc.natts as usize;

    // (oid, name, istemplate, allowconn) for the three bootstrap databases.
    let rows: [(u32, &str, bool, bool); 3] = [
        (1, "template1", true, true),
        (db::Template0DbOid.get(), "template0", true, false),
        (db::PostgresDbOid.get(), "postgres", false, true),
    ];
    for (oid, name, istemplate, allowconn) in rows {
        let dat_name = name_data(name);
        let mut values = vec![Datum(0); natts];
        let mut isnull = vec![false; natts];
        values[(db::Anum_pg_database_oid - 1) as usize] = ObjectIdGetDatum(Oid::new(oid));
        values[(db::Anum_pg_database_datname - 1) as usize] = NameGetDatum(&dat_name);
        values[(db::Anum_pg_database_datdba - 1) as usize] = ObjectIdGetDatum(Oid::new(10));
        values[(db::Anum_pg_database_encoding - 1) as usize] = Int32GetDatum(crate::mb::pg_wchar::pg_enc::PG_UTF8 as i32);
        values[(db::Anum_pg_database_datlocprovider - 1) as usize] = CharGetDatum(crate::catalog::pg_collation::COLLPROVIDER_LIBC);
        values[(db::Anum_pg_database_datistemplate - 1) as usize] = BoolGetDatum(istemplate);
        values[(db::Anum_pg_database_datallowconn - 1) as usize] = BoolGetDatum(allowconn);
        values[(db::Anum_pg_database_dathasloginevt - 1) as usize] = BoolGetDatum(false);
        values[(db::Anum_pg_database_datconnlimit - 1) as usize] = Int32GetDatum(db::DATCONNLIMIT_UNLIMITED);
        values[(db::Anum_pg_database_datfrozenxid - 1) as usize] = TransactionIdGetDatum(crate::c::TransactionId(0));
        values[(db::Anum_pg_database_datminmxid - 1) as usize] = TransactionIdGetDatum(crate::c::TransactionId(1));
        values[(db::Anum_pg_database_dattablespace - 1) as usize] = ObjectIdGetDatum(crate::common::relpath::DEFAULTTABLESPACE_OID);
        // The varlena locale columns + datacl: NULL on the single-db port.
        isnull[(db::Anum_pg_database_datcollate - 1) as usize] = true;
        isnull[(db::Anum_pg_database_datctype - 1) as usize] = true;
        isnull[(db::Anum_pg_database_datlocale - 1) as usize] = true;
        isnull[(db::Anum_pg_database_daticurules - 1) as usize] = true;
        isnull[(db::Anum_pg_database_datcollversion - 1) as usize] = true;
        isnull[(db::Anum_pg_database_datacl - 1) as usize] = true;

        let mut tuple = heap_form_tuple(&desc, &values, &isnull);
        catalog_tuple_insert(shared, &pg_database, &mut tuple).await;
        heap_freetuple(tuple);
    }
    relation_close(pg_database);
}

/// PG `boot_get_type_io_data`: 8 out-params folded into a named struct. Returns
/// the I/O + layout metadata bootstrap needs to interpret a column value string.
pub struct BootTypeIoData {
    pub typlen: i16,
    pub typbyval: bool,
    pub typalign: u8,
    pub typdelim: u8,
    pub typioparam: Oid,
    pub typinput: Oid,
    pub typoutput: Oid,
}

/// PG `boot_get_type_io_data`. STAGED against the syscache/type-cache path that
/// lands with the type-I/O milestone; the bootstrap seed-value conversion uses it.
pub fn boot_get_type_io_data(typid: Oid) -> BootTypeIoData {
    let _ = typid;
    unimplemented!("boot_get_type_io_data: type I/O lookup lands with the adt milestone")
}

// =============================================================================
// TOMBSTONE: bootparse.y + bootscanner.l (the BKI flex/bison grammar).
//
// PostgreSQL's bootstrap mode parses a generated `postgres.bki` text program with
// `bootscanner.l` (flex) and `bootparse.y` (bison), executing `create` / `open` /
// `insert` / `declare index` / `build indices` commands. In this port the BKI
// TEXT layer does not exist: `build.rs` emits the catalog schema (SCHEMA_PG_*)
// and seed rows (SEED_PG_*) directly as Rust data, and `bootstrap_catalogs`
// executes the equivalent program over that data. There is therefore nothing to
// translate from `bootparse.y` / `bootscanner.l` -- they are intentionally NOT
// ported (replaced by the .dat codegen). The old C entry points (`boot_yyparse`,
// `boot_yylex`, `DefineAttr`, `InsertOneTuple`, `boot_openrel`, ...) have no
// counterpart here; their work is done by the data-driven path above.
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use crate::catalog::genbki::{INT2OID, NAMEOID, OIDOID};
    use crate::catalog::pg_attribute::Natts_pg_attribute;
    use crate::catalog::pg_class::Natts_pg_class;
    use crate::catalog::pg_proc::Natts_pg_proc;
    use crate::catalog::pg_type::Natts_pg_type;

    /// The generated schema arrays must have exactly the attribute count the
    /// `#[derive(Catalog)]` `Natts_pg_*` constants report from the FormData struct
    /// field layout -- i.e. the genbki schema and the struct agree.
    #[test]
    fn schema_attr_counts_match_catalog_structs() {
        assert_eq!(NATTS_PG_TYPE, Natts_pg_type as usize);
        assert_eq!(NATTS_PG_ATTRIBUTE, Natts_pg_attribute as usize);
        assert_eq!(NATTS_PG_PROC, Natts_pg_proc as usize);
        assert_eq!(NATTS_PG_CLASS, Natts_pg_class as usize);
        // and the static arrays carry exactly that many entries.
        assert_eq!(SCHEMA_PG_TYPE.len(), NATTS_PG_TYPE);
        assert_eq!(SCHEMA_PG_CLASS.len(), NATTS_PG_CLASS);
    }

    /// Attribute numbers are 1-based and contiguous in declaration order.
    #[test]
    fn schema_attnums_are_contiguous() {
        for schema in [SCHEMA_PG_TYPE, SCHEMA_PG_ATTRIBUTE, SCHEMA_PG_PROC, SCHEMA_PG_CLASS] {
            for (i, a) in schema.iter().enumerate() {
                assert_eq!(a.attnum as usize, i + 1, "attr {} out of order", a.attname);
            }
        }
    }

    /// Spot-check the genbki morph: the first column of pg_class is `oid` (oid
    /// type, 4-byte by-value), the second `relname` (name, 64-byte by-ref), and
    /// the leading fixed-width columns are NOT NULL (priorfixedwidth rule).
    #[test]
    fn schema_physical_types_match_genbki() {
        let oid_col = &SCHEMA_PG_CLASS[0];
        assert_eq!(oid_col.attname, "oid");
        assert_eq!(oid_col.atttypid, OIDOID.get());
        assert_eq!(oid_col.attlen, 4);
        assert!(oid_col.attbyval);
        assert!(oid_col.attnotnull);

        let name_col = &SCHEMA_PG_CLASS[1];
        assert_eq!(name_col.attname, "relname");
        assert_eq!(name_col.atttypid, NAMEOID.get());
        assert_eq!(name_col.attlen, 64);
        assert!(!name_col.attbyval);
        assert!(name_col.attnotnull);

        // pg_attribute.attlen is int2 (the int16 -> int2 rename path).
        let attlen_col = SCHEMA_PG_ATTRIBUTE
            .iter()
            .find(|a| a.attname == "attlen")
            .expect("attlen column");
        assert_eq!(attlen_col.atttypid, INT2OID.get());
        assert_eq!(attlen_col.attlen, 2);
    }

    /// genbki morph_row_for_pgattr resolves a `foo[]` column through the
    /// auto-generated array type (Catalog.pm GenerateArrayTypes): atttypid is the
    /// element's array_type_oid, attlen -1, by-ref, extended storage, attndims 1,
    /// attalign 'd' iff the element is double-aligned else 'i', and attcollation
    /// C_COLLATION_OID (950) iff the element is collatable else 0.
    #[test]
    fn schema_array_columns_resolve_to_array_type() {
        const D: i8 = b'd' as i8;
        const I: i8 = b'i' as i8;
        const X: i8 = b'x' as i8;
        let find = |schema: &'static [BootstrapAttr], name: &str| -> &'static BootstrapAttr {
            schema.iter().find(|a| a.attname == name).expect("column present")
        };

        // pg_class.relacl -> _aclitem (1034): aclitem is double-aligned and NOT
        // collatable, so attalign 'd', attcollation 0.
        let relacl = find(SCHEMA_PG_CLASS, "relacl");
        assert_eq!(relacl.atttypid, 1034);
        assert_eq!(relacl.attlen, -1);
        assert!(!relacl.attbyval);
        assert_eq!(relacl.attalign, D);
        assert_eq!(relacl.attstorage, X);
        assert_eq!(relacl.attndims, 1);
        assert_eq!(relacl.attcollation, 0);

        // pg_class.reloptions -> _text (1009): text is int-aligned and collatable,
        // so attalign 'i', attcollation C_COLLATION_OID (950) -- genbki always
        // stamps C collation on a collatable catalog column.
        let reloptions = find(SCHEMA_PG_CLASS, "reloptions");
        assert_eq!(reloptions.atttypid, 1009);
        assert_eq!(reloptions.attalign, I);
        assert_eq!(reloptions.attcollation, 950);
        assert_eq!(reloptions.attndims, 1);

        // pg_attribute.attacl -> _aclitem (1034), align 'd', collation 0.
        let attacl = find(SCHEMA_PG_ATTRIBUTE, "attacl");
        assert_eq!(attacl.atttypid, 1034);
        assert_eq!(attacl.attalign, D);
        assert_eq!(attacl.attcollation, 0);

        // pg_proc.proallargtypes -> _oid (1028): oid is not collatable.
        let proallargtypes = find(SCHEMA_PG_PROC, "proallargtypes");
        assert_eq!(proallargtypes.atttypid, 1028);
        assert_eq!(proallargtypes.attalign, I);
        assert_eq!(proallargtypes.attcollation, 0);

        // pg_proc.proargmodes -> _char (1002): char is not collatable; the array
        // is int-aligned (char is single-byte 'c', not 'd').
        let proargmodes = find(SCHEMA_PG_PROC, "proargmodes");
        assert_eq!(proargmodes.atttypid, 1002);
        assert_eq!(proargmodes.attalign, I);
        assert_eq!(proargmodes.attcollation, 0);

        // pg_proc.proargtypes is `oidvector` -- a fixed-ish scalar type (OID 30),
        // NOT an array column, and FORCE_NOT_NULL.
        let proargtypes = find(SCHEMA_PG_PROC, "proargtypes");
        assert_eq!(proargtypes.atttypid, 30);
        assert_eq!(proargtypes.attndims, 1); // oidvector is typcategory 'A'
        assert!(proargtypes.attnotnull);
    }

    /// formrdesc_tupdesc reproduces the formrdesc invariants: right natts, the
    /// composite type id, refcounted, first attcacheoff = 0, and the
    /// has-not-null constraint flag set (every catalog has NOT NULL columns).
    #[test]
    fn formrdesc_tupdesc_pg_class_shape() {
        let cat = FORMRDESC_CATALOGS
            .iter()
            .find(|c| c.relname == "pg_class")
            .expect("pg_class in formrdesc set");
        let desc = formrdesc_tupdesc(cat.relid, cat.reltype, cat.schema);

        assert_eq!(desc.natts as usize, NATTS_PG_CLASS);
        assert_eq!(desc.attrs.len(), NATTS_PG_CLASS);
        assert_eq!(desc.tdtypeid, cat.reltype);
        assert_eq!(desc.tdtypmod, -1);
        assert_eq!(desc.tdrefcount, 1);
        assert_eq!(desc.compact_attrs[0].attcacheoff, 0);
        assert_eq!(desc.attr(0).attname.data[..3].to_vec(), b"oid".to_vec());
        assert_eq!(desc.attr(1).attlen, 64); // relname is a Name
        let constr = desc.constr.as_ref().expect("pg_class has NOT NULL columns");
        assert!(constr.has_not_null);
    }

    /// Every formrdesc catalog builds a descriptor whose natts matches its schema.
    #[test]
    fn formrdesc_builds_all_bootstrap_catalogs() {
        for cat in FORMRDESC_CATALOGS {
            let desc = formrdesc(cat);
            assert_eq!(
                desc.natts as usize,
                cat.schema.len(),
                "{} natts mismatch",
                cat.relname
            );
        }
    }

    /// The seed-row codegen produced the expected M2 catalogs, and the well-known
    /// rows are present and well-formed (ordered (col,value) pairs).
    #[test]
    fn seed_rows_well_formed() {
        // pg_am seeds at least heap + btree.
        assert!(SEED_PG_AM.iter().any(|r| r.contains(&("amname", "heap"))));
        assert!(SEED_PG_AM.iter().any(|r| r.contains(&("amname", "btree"))));
        // pg_namespace seeds pg_catalog + public.
        assert!(SEED_PG_NAMESPACE.iter().any(|r| r.contains(&("nspname", "pg_catalog"))));
        assert!(SEED_PG_NAMESPACE.iter().any(|r| r.contains(&("nspname", "public"))));
        // every row has an oid as its first pair (genbki insert order).
        for r in SEED_PG_AM {
            assert_eq!(r.first().map(|p| p.0), Some("oid"));
        }
        // the int4/oid/name/text btree opclasses are seeded for the catalog indexes.
        assert!(!SEED_PG_OPCLASS.is_empty());
        assert!(!SEED_PG_AMOP.is_empty());
        assert!(!SEED_PG_AMPROC.is_empty());
    }

    /// bootstrap seeds all six .dat-backed M2 catalogs (inventory plumbing).
    #[test]
    fn bootstrap_catalogs_inventory() {
        assert_eq!(bootstrap_seed_inventory(), 6);
    }
}
