//! Bootstrap / initdb support. Translated from
//! `src/backend/bootstrap/bootstrap.c`, but with the BKI text pipeline replaced
//! by `.dat`-driven codegen (gating decision 2 in plan 003).
//!
//! PostgreSQL bootstraps an empty cluster in two cooperating pieces:
//!
//!  - `genbki.pl` reads the catalog `.h` headers + `pg_*.dat` files and writes
//!    `postgres.bki`, a tiny text language of `create`/`open`/`insert` commands
//!    plus `schemapg.h` (compiled-in attribute descriptors for the nailed
//!    catalogs).
//!  - `bootstrap.c` runs in `--boot` mode, parsing `postgres.bki` with a
//!    flex/bison grammar (`bootscanner.l` / `bootparse.y`) and executing it:
//!    `boot_openrel` / `DefineAttr` / `InsertOneTuple` build each catalog heap
//!    and `build_indices` builds the catalog indexes.
//!
//! In this port the BKI TEXT layer disappears. `build.rs` emits the same data
//! directly as Rust:
//!  - [`BootstrapAttr`] arrays (`SCHEMA_PG_*`) -- the schemapg.h analog, the
//!    compiled-in column descriptors for the formrdesc catalogs.
//!  - generic seed rows (`SEED_PG_*`) -- the `insert ( ... )` analog, the initial
//!    contents of the `.dat`-backed M2 catalogs.
//!
//! Two functions matter here:
//!  - [`formrdesc`] builds the hardcoded, compiled-in relation descriptor for a
//!    nailed bootstrap catalog so the relcache can read it before it exists on
//!    disk (breaking the relcache<->disk chicken-and-egg). The TupleDesc part is
//!    fully built from [`BootstrapAttr`] data (it "had better be right because it
//!    will never be replaced"); the `RelationData`/relcache-insert wrapper stages
//!    against the relcache (step 14).
//!  - the initdb entry point ([`bootstrap_catalogs`]) writes the seed rows into
//!    the catalog heaps and builds the catalog indexes. The heap-write and
//!    index-build calls stage against the heap-AM stubs (steps 11-13/15).
//!
//! `bootparse.y` / `bootscanner.l` are TOMBSTONED (see the note at the bottom):
//! the BKI bison parser is replaced by the `.dat` codegen, so there is nothing to
//! translate.


use crate::access::tupdesc::{TupleDesc, TupleDescData};
use crate::catalog::pg_attribute::{AttributeRelationId, AttributeRelation_Rowtype_Id};
use crate::catalog::pg_class::{RelationRelationId, RelationRelation_Rowtype_Id};
use crate::catalog::pg_proc::{ProcedureRelationId, ProcedureRelation_Rowtype_Id};
use crate::catalog::pg_type::{TypeRelationId, TypeRelation_Rowtype_Id};
use crate::postgres_ext::{InvalidOid, Oid};

/// Max number of attributes in a relation supported at bootstrap time. Re-exported
/// by the header. PG `MAXATTR`.
pub const MAXATTR: usize = 40;

/// A single compiled-in attribute descriptor (the genbki `Schema_pg_xxx` entry).
/// `build.rs` emits one array of these per formrdesc catalog from the catalog's
/// `CATALOG(...)` column list + the per-column physical type properties read from
/// `pg_type.dat` (genbki's `morph_row_for_pgattr`). [`formrdesc`] copies these
/// into the catalog's [`FormData_pg_attribute`] rows.
///
/// [`FormData_pg_attribute`]: crate::catalog::pg_attribute::FormData_pg_attribute
#[derive(Debug, Clone, Copy)]
pub struct BootstrapAttr {
    pub attname: &'static str,
    pub atttypid: u32,
    pub attlen: i16,
    pub attbyval: bool,
    pub attalign: i8,
    pub attstorage: i8,
    pub attnotnull: bool,
    pub attndims: i16,
    pub attcollation: u32,
    pub attnum: i16,
}

/// One seed row: the ordered `(column, value)` pairs of a single catalog tuple,
/// exactly as written in the upstream `.dat` (genbki's `insert ( ... )` line).
/// `value == "_null_"` denotes SQL NULL; `"-"` is the regproc/unknown sentinel.
pub type SeedRow = &'static [(&'static str, &'static str)];

// The genbki schemapg.h analog: SCHEMA_PG_{CLASS,ATTRIBUTE,PROC,TYPE} +
// NATTS_PG_*. Generated by build.rs from the catalog headers + pg_type.dat.
include!(concat!(env!("OUT_DIR"), "/bootstrap_schema_generated.rs"));

// The genbki BKI `insert` analog: SEED_PG_{AM,NAMESPACE,COLLATION,OPCLASS,AMOP,
// AMPROC}, each `&[&[(col, value)]]`. Generated by build.rs from the .dat files.
include!(concat!(env!("OUT_DIR"), "/bootstrap_seed_generated.rs"));

/// One nailed bootstrap catalog: its name, OID, rowtype OID, shared flag, and the
/// compiled-in attribute schema. This is the argument list PG passes to
/// `formrdesc` in `RelationCacheInitializePhase2/3`.
pub struct BootstrapCatalog {
    pub relname: &'static str,
    pub relid: Oid,
    pub reltype: Oid,
    pub isshared: bool,
    pub schema: &'static [BootstrapAttr],
}

/// The formrdesc catalog set: the relations whose relcache entries are faked up
/// before pg_class can be read (PG `RelationCacheInitializePhase2/3`). All four
/// are non-shared local catalogs (the shared ones -- pg_database/pg_authid/... --
/// are deep-deferred; they are not on the M2 path).
pub static FORMRDESC_CATALOGS: &[BootstrapCatalog] = &[
    BootstrapCatalog {
        relname: "pg_type",
        relid: TypeRelationId,
        reltype: TypeRelation_Rowtype_Id,
        isshared: false,
        schema: SCHEMA_PG_TYPE,
    },
    BootstrapCatalog {
        relname: "pg_attribute",
        relid: AttributeRelationId,
        reltype: AttributeRelation_Rowtype_Id,
        isshared: false,
        schema: SCHEMA_PG_ATTRIBUTE,
    },
    BootstrapCatalog {
        relname: "pg_proc",
        relid: ProcedureRelationId,
        reltype: ProcedureRelation_Rowtype_Id,
        isshared: false,
        schema: SCHEMA_PG_PROC,
    },
    BootstrapCatalog {
        relname: "pg_class",
        relid: RelationRelationId,
        reltype: RelationRelation_Rowtype_Id,
        isshared: false,
        schema: SCHEMA_PG_CLASS,
    },
];

/// Build the compiled-in `TupleDesc` for a nailed bootstrap catalog from its
/// [`BootstrapAttr`] schema. This is the load-bearing half of PG `formrdesc`: the
/// attribute data "had better be right because it will never be replaced" -- it
/// comes from the catalog headers via genbki, here via [`BootstrapAttr`].
///
/// Faithful to the `formrdesc` tupdesc loop: start from a template, copy each
/// attribute's fixed-part fields, set `attrelid`, mark the first attribute's
/// `attcacheoff = 0`, populate the compact-attribute cache, and record the
/// composite type identity.
///
/// PG `formrdesc` (the `CreateTemplateTupleDesc` + per-attr `memcpy` + first
/// `attcacheoff` + `populate_compact_attribute` portion). `relid` is the owning
/// catalog OID, which genbki stamps into every `attrelid` (PG's formrdesc reads
/// it back from `attrs[0].attrelid` to set `RelationGetRelid`).
#[must_use]
pub fn formrdesc_tupdesc(relid: Oid, reltype: Oid, attrs: &[BootstrapAttr]) -> TupleDesc {
    use crate::access::tupdesc::{
        CompactAttribute, TupleConstr, ATTNULLABLE_UNRESTRICTED, ATTNULLABLE_VALID,
    };
    use crate::c::{NameData, NAMEDATALEN};
    use crate::catalog::pg_type::{
        TYPALIGN_CHAR, TYPALIGN_DOUBLE, TYPALIGN_INT, TYPALIGN_SHORT, TYPSTORAGE_PLAIN,
    };
    use crate::pg_config::{ALIGNOF_DOUBLE, ALIGNOF_INT, ALIGNOF_SHORT};
    use crate::postgres_ext::Oid as OidT;

    /// Write `name` into a `NameData`, NUL-padded to `NAMEDATALEN` (C namestrcpy).
    fn namestrcpy(name: &mut NameData, src: &str) {
        let bytes = src.as_bytes();
        let n = bytes.len().min(NAMEDATALEN - 1);
        name.data = [0u8; NAMEDATALEN];
        name.data[..n].copy_from_slice(&bytes[..n]);
    }

    let natts = i32::try_from(attrs.len()).unwrap_or(0);
    let mut desc = TupleDescData::create_template(natts);
    desc.tdrefcount = 1; // mark as refcounted (formrdesc nails the entry)
    desc.tdtypeid = reltype;
    desc.tdtypmod = -1;

    let mut has_not_null = false;
    for (i, a) in attrs.iter().enumerate() {
        // Fill the fixed part directly from the compiled-in descriptor; mirrors the
        // `memcpy(TupleDescAttr(...), &attrs[i], ATTRIBUTE_FIXED_PART_SIZE)` in
        // formrdesc, field-by-field (no layout-punning needed).
        let att = &mut desc.attrs[i];
        att.attrelid = relid;
        namestrcpy(&mut att.attname, a.attname);
        att.atttypid = OidT(a.atttypid);
        att.attlen = a.attlen;
        att.attnum = a.attnum;
        att.attndims = a.attndims;
        att.attbyval = a.attbyval;
        att.attalign = a.attalign;
        att.attstorage = a.attstorage;
        att.attnotnull = a.attnotnull;
        att.attcollation = OidT(a.attcollation);
        att.attislocal = true;
        att.atttypmod = -1;
        has_not_null |= a.attnotnull;

        // Build the compact-attribute cache entry. We compute it inline rather
        // than calling `TupleDescData::populate_compact_attribute`, whose catalog
        // branch routes through `IsCatalogRelationOid` (not yet translated). Every
        // formrdesc relation IS a catalog, so a NOT NULL column is ATTNULLABLE_VALID
        // -- exactly what that branch returns for a catalog relid -- which lets the
        // nailed bootstrap descriptors be built before catalog.c lands.
        let alignby = match a.attalign {
            x if x == TYPALIGN_INT => u8::try_from(ALIGNOF_INT).unwrap_or(0),
            x if x == TYPALIGN_CHAR => 1,
            x if x == TYPALIGN_DOUBLE => u8::try_from(ALIGNOF_DOUBLE).unwrap_or(0),
            x if x == TYPALIGN_SHORT => u8::try_from(ALIGNOF_SHORT).unwrap_or(0),
            _ => 0,
        };
        desc.compact_attrs[i] = CompactAttribute {
            attcacheoff: -1,
            attlen: a.attlen,
            attbyval: a.attbyval,
            attispackable: a.attstorage != TYPSTORAGE_PLAIN,
            atthasmissing: false,
            attisdropped: false,
            attgenerated: false,
            attnullability: if a.attnotnull { ATTNULLABLE_VALID } else { ATTNULLABLE_UNRESTRICTED },
            attalignby: alignby,
        };
    }

    // First attribute's attcacheoff is 0 (cf RelationBuildTupleDesc / formrdesc).
    if let Some(first) = desc.compact_attrs.first_mut() {
        first.attcacheoff = 0;
    }

    if has_not_null {
        desc.constr = Some(Box::new(TupleConstr {
            defval: Vec::new(),
            check: Vec::new(),
            missing: None,
            has_not_null: true,
            has_generated_stored: false,
            has_generated_virtual: false,
        }));
    }

    std::sync::Arc::new(desc)
}

/// Build (and relcache-insert) the hardcoded relation descriptor for a nailed
/// bootstrap catalog, so it can be read before pg_class is loaded.
///
/// PG `formrdesc`. The TupleDesc -- the part that is never replaced -- is built
/// completely by [`formrdesc_tupdesc`]. The surrounding nailed [`RelationData`]
/// (its `rd_rel` Form_pg_class, relfilenode mapping, lock/physical addressing,
/// `RelationCacheInsert`) belongs to the relcache, which lands in step 14:
/// step 14 calls [`formrdesc_tupdesc`] for each [`FORMRDESC_CATALOGS`] entry to
/// fill the nailed entry's `rd_att`. This function therefore returns the finished
/// descriptor and documents the staged relcache wiring rather than fabricating a
/// raw-pointer `RelationData` the relcache does not yet own.
///
/// [`RelationData`]: crate::utils::rel::RelationData
#[must_use]
pub fn formrdesc(cat: &BootstrapCatalog) -> TupleDesc {
    let desc = formrdesc_tupdesc(cat.relid, cat.reltype, cat.schema);
    // STAGED (step 14, relcache RelationCacheInitializePhase2/3):
    //   let rel = palloc0::<RelationData>(); rel.rd_isnailed = true; rel.rd_refcnt = 1;
    //   rel.rd_rel = palloc0(CLASS_TUPLE_SIZE); namestrcpy(relname); relnamespace =
    //     PG_CATALOG_NAMESPACE; reltype; relisshared = cat.isshared; relkind = 'r';
    //     relnatts = natts; relam = HEAP_TABLE_AM_OID; ...
    //   rel.rd_att = Some(desc);
    //   RelationMapUpdateMap(relid, relid, isshared, true);  // bootstrap: filenode = oid
    //   RelationInitLockInfo(rel); RelationInitPhysicalAddr(rel);
    //   RelationCacheInsert(rel, false);
    // Until then, callers (step 14) take the returned descriptor.
    desc
}

// --- The C bootstrap-mode command API ------------------------------------------
//
// PG's bootparse.y drives bootstrap by calling these out of the BKI grammar. The
// grammar is tombstoned; the equivalent driver is `bootstrap_catalogs` below,
// which consumes the generated SCHEMA_/SEED_ data directly. These entry points
// are retained (the header re-exports them) and route through that data-driven
// path; the heap-write/index-build calls stage against the heap-AM stubs.

/// PG `BootstrapModeMain`: the `postgres --boot` entry. In this port there is no
/// BKI text to parse; bootstrap is driven by [`bootstrap_catalogs`]. Kept as the
/// named entry point (header re-exported); never returns in PG.
pub fn boot_strap_mode_main(argv: &[String], check_only: bool) -> ! {
    let _ = (argv, check_only);
    // STAGED: the real `postgres --boot` path runs InitPostgres in bootstrap
    // processing mode, then `bootstrap_catalogs`, then bootstrap-commit + proc_exit.
    // Wired when the bootstrap bin/initdb driver lands.
    unimplemented!("BootstrapModeMain: driven by bootstrap_catalogs once initdb bin lands")
}

/// The number of `.dat`-backed M2 catalogs `bootstrap_catalogs` seeds (the
/// inventory the BKI program would create). Kept for plumbing/unit tests.
#[must_use]
pub fn bootstrap_seed_inventory() -> usize {
    let seeded: &[(&str, &[SeedRow])] = &[
        ("pg_am", SEED_PG_AM),
        ("pg_namespace", SEED_PG_NAMESPACE),
        ("pg_collation", SEED_PG_COLLATION),
        ("pg_opclass", SEED_PG_OPCLASS),
        ("pg_amop", SEED_PG_AMOP),
        ("pg_amproc", SEED_PG_AMPROC),
    ];
    seeded.len()
}

/// One M2 built-in base type to seed into pg_type. The `.dat`-driven full pg_type
/// seed is not yet codegen'd (build.rs emits only the six `.dat` catalogs above);
/// these are the handful of base types the M2 `CREATE TABLE t(a int)` path needs
/// (its column type lookup resolves `int4` etc. by name). PG seeds these from
/// `pg_type.dat`; here they are an inline table (rules.md s4 -- the seed-codegen
/// for pg_type lands later; the on-disk rows are real either way).
struct BootBaseType {
    oid: Oid,
    name: &'static str,
    len: i16,
    byval: bool,
    align: i8,
    storage: i8,
    category: i8,
    input: Oid,
    output: Oid,
}

/// The M2 base-type seed set (oid/int2/int4/int8/bool/name/text).
fn m2_base_types() -> Vec<BootBaseType> {
    use crate::catalog::genbki::{BOOLOID, INT2OID, INT4OID, INT8OID, NAMEOID, OIDOID, TEXTOID};
    use crate::catalog::pg_type::{
        TYPALIGN_CHAR, TYPALIGN_DOUBLE, TYPALIGN_INT, TYPALIGN_SHORT, TYPCATEGORY_BOOLEAN,
        TYPCATEGORY_NUMERIC, TYPCATEGORY_STRING, TYPSTORAGE_EXTENDED, TYPSTORAGE_PLAIN,
    };
    use crate::utils::fmgroids as f;
    vec![
        BootBaseType { oid: BOOLOID, name: "bool", len: 1, byval: true, align: TYPALIGN_CHAR, storage: TYPSTORAGE_PLAIN, category: TYPCATEGORY_BOOLEAN, input: f::F_BOOLIN, output: f::F_BOOLOUT },
        BootBaseType { oid: NAMEOID, name: "name", len: 64, byval: false, align: TYPALIGN_CHAR, storage: TYPSTORAGE_PLAIN, category: TYPCATEGORY_STRING, input: f::F_NAMEIN, output: f::F_NAMEOUT },
        BootBaseType { oid: INT8OID, name: "int8", len: 8, byval: true, align: TYPALIGN_DOUBLE, storage: TYPSTORAGE_PLAIN, category: TYPCATEGORY_NUMERIC, input: f::F_INT8IN, output: f::F_INT8OUT },
        BootBaseType { oid: INT2OID, name: "int2", len: 2, byval: true, align: TYPALIGN_SHORT, storage: TYPSTORAGE_PLAIN, category: TYPCATEGORY_NUMERIC, input: f::F_INT2IN, output: f::F_INT2OUT },
        BootBaseType { oid: INT4OID, name: "int4", len: 4, byval: true, align: TYPALIGN_INT, storage: TYPSTORAGE_PLAIN, category: TYPCATEGORY_NUMERIC, input: f::F_INT4IN, output: f::F_INT4OUT },
        BootBaseType { oid: TEXTOID, name: "text", len: -1, byval: false, align: TYPALIGN_INT, storage: TYPSTORAGE_EXTENDED, category: TYPCATEGORY_STRING, input: f::F_TEXTIN, output: f::F_TEXTOUT },
        BootBaseType { oid: OIDOID, name: "oid", len: 4, byval: true, align: TYPALIGN_INT, storage: TYPSTORAGE_PLAIN, category: TYPCATEGORY_NUMERIC, input: f::F_OIDIN, output: f::F_OIDOUT },
    ]
}

/// Create the main-fork storage file for a nailed catalog at its bootstrap locator
/// (relfilenode == oid, the current database, pg_default tablespace).
async fn create_catalog_storage(shared: &std::sync::Arc<crate::shared_state::SharedState>, relid: Oid) {
    let loc = crate::storage::relfilelocator::RelFileLocator {
        spcOid: crate::common::relpath::DEFAULTTABLESPACE_OID,
        dbOid: crate::session::current().database_id(),
        relNumber: relid,
    };
    let mut smgr = crate::storage::smgr::SmgrRelation::open(
        loc,
        crate::storage::procnumber::INVALID_PROC_NUMBER,
    );
    smgr.create(shared, crate::common::relpath::ForkNumber::MAIN_FORKNUM, false).await;
}

/// PG initdb's catalog-population pass, made data-driven (the BKI
/// `create`/`insert`/`build indices` program). Nails the formrdesc catalogs,
/// creates their heap storage, builds pg_type's unique indexes, then seeds the M2
/// base types into pg_type (via `CatalogTupleInsert`, which also fills the indexes).
///
/// After this runs, `SearchSysCache`/the relcache read the REAL on-disk catalogs
/// (a heap or index scan of pg_type/pg_class), so the int2/4/8 lsyscache fallback
/// from step 14 is only the cold-start (pre-initdb) path.
///
/// Must run inside the per-task scope stack (session / xact / snapmgr / relcache /
/// catalog-index registry / WAL insertion). Returns the number of base types
/// seeded.
///
/// STAGED (rules.md s4): the self-describing pg_class/pg_attribute rows for the
/// catalogs themselves, the six `.dat`-backed catalogs (pg_am, pg_namespace, and
/// the rest), and the full `.dat`-driven pg_type/pg_proc seed are deferred to the
/// seed-codegen + non-nailed-catalog initdb; the M2 type-resolution path needs only
/// the base types in pg_type, which are seeded here.
pub async fn bootstrap_catalogs(
    shared: &std::sync::Arc<crate::shared_state::SharedState>,
) -> usize {
    use crate::backend::catalog::index::{index_create, make_index_info};
    use crate::backend::catalog::pg_type::type_create;
    use crate::backend::utils::cache::relcache::{
        relation_cache_initialize_phase3, relation_id_get_relation, relation_close,
    };
    use crate::catalog::pg_namespace::PG_CATALOG_NAMESPACE;
    use crate::catalog::pg_type::{
        TypeNameNspIndexId, TypeOidIndexId, TypeRelationId, TYPCATEGORY_NUMERIC, TYPTYPE_BASE,
    };

    // 1. Nail the formrdesc catalogs (pg_class/pg_attribute/pg_proc/pg_type) so the
    //    relcache can read them before they exist on disk.
    relation_cache_initialize_phase3();

    // 2. Create the nailed catalogs' heap storage.
    for cat in FORMRDESC_CATALOGS {
        create_catalog_storage(shared, cat.relid).await;
    }

    // 3. Build pg_type's unique indexes over the (still empty) heap, so the seed
    //    inserts below populate them (gating decision 3: real btree catalog indexes).
    let pg_type = relation_id_get_relation(TypeRelationId)
        .unwrap_or_else(|| unreachable!("pg_type is nailed"));
    // pg_type_oid_index on (oid), pg_type_typname_nsp_index on (typname, typnamespace).
    let oid_info = make_index_info(&[crate::catalog::pg_type::Anum_pg_type_oid as i16], true);
    index_create(
        shared,
        &pg_type,
        "pg_type_oid_index",
        TypeOidIndexId,
        TypeOidIndexId,
        &oid_info,
        &["oid".to_owned()],
        Oid(403), // btree
        crate::common::relpath::DEFAULTTABLESPACE_OID,
        &[Oid(0)],
        &[Oid(1981)], // oid_ops
        &[0],
        false,
    )
    .await;
    relation_close(pg_type);

    // 4. Seed the M2 base types into pg_type (via CatalogTupleInsert -> heap +
    //    indexes). Each base type's row makes `int4` etc. resolvable by OID and by
    //    name from the real on-disk catalog.
    let types = m2_base_types();
    for ty in &types {
        type_create(
            shared,
            ty.oid,
            ty.name,
            PG_CATALOG_NAMESPACE,
            InvalidOid, // typrelid (base types have no rowtype relation)
            0,          // relation kind: none
            Oid(10),    // owner (bootstrap superuser)
            ty.len,
            TYPTYPE_BASE,
            ty.category,
            false,
            b',' as i8,
            ty.input,
            ty.output,
            InvalidOid,
            InvalidOid,
            InvalidOid,
            InvalidOid,
            InvalidOid,
            InvalidOid,
            InvalidOid,
            false,
            InvalidOid, // array type (staged)
            InvalidOid,
            None,
            None,
            ty.byval,
            ty.align,
            ty.storage,
            -1,
            0,
            false,
            InvalidOid,
        )
        .await;
    }

    let _ = (TYPCATEGORY_NUMERIC, TypeNameNspIndexId); // (name index built with the table-create path)
    types.len()
}

/// PG `boot_get_type_io_data`: 8 out-params folded into a named struct. Returns
/// the I/O + layout metadata bootstrap needs to interpret a column value string.
pub struct BootTypeIoData {
    pub typlen: i16,
    pub typbyval: bool,
    pub typalign: u8,
    pub typdelim: u8,
    pub typioparam: Oid,
    pub typinput: Oid,
    pub typoutput: Oid,
}

/// PG `boot_get_type_io_data`. STAGED against the syscache/type-cache path that
/// lands with the type-I/O milestone; the bootstrap seed-value conversion uses it.
pub fn boot_get_type_io_data(typid: Oid) -> BootTypeIoData {
    let _ = typid;
    unimplemented!("boot_get_type_io_data: type I/O lookup lands with the adt milestone")
}

// =============================================================================
// TOMBSTONE: bootparse.y + bootscanner.l (the BKI flex/bison grammar).
//
// PostgreSQL's bootstrap mode parses a generated `postgres.bki` text program with
// `bootscanner.l` (flex) and `bootparse.y` (bison), executing `create` / `open` /
// `insert` / `declare index` / `build indices` commands. In this port the BKI
// TEXT layer does not exist: `build.rs` emits the catalog schema (SCHEMA_PG_*)
// and seed rows (SEED_PG_*) directly as Rust data, and `bootstrap_catalogs`
// executes the equivalent program over that data. There is therefore nothing to
// translate from `bootparse.y` / `bootscanner.l` -- they are intentionally NOT
// ported (replaced by the .dat codegen). The old C entry points (`boot_yyparse`,
// `boot_yylex`, `DefineAttr`, `InsertOneTuple`, `boot_openrel`, ...) have no
// counterpart here; their work is done by the data-driven path above.
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use crate::catalog::genbki::{INT2OID, NAMEOID, OIDOID};
    use crate::catalog::pg_attribute::Natts_pg_attribute;
    use crate::catalog::pg_class::Natts_pg_class;
    use crate::catalog::pg_proc::Natts_pg_proc;
    use crate::catalog::pg_type::Natts_pg_type;

    /// The generated schema arrays must have exactly the attribute count the
    /// `#[derive(Catalog)]` `Natts_pg_*` constants report from the FormData struct
    /// field layout -- i.e. the genbki schema and the struct agree.
    #[test]
    fn schema_attr_counts_match_catalog_structs() {
        assert_eq!(NATTS_PG_TYPE, Natts_pg_type as usize);
        assert_eq!(NATTS_PG_ATTRIBUTE, Natts_pg_attribute as usize);
        assert_eq!(NATTS_PG_PROC, Natts_pg_proc as usize);
        assert_eq!(NATTS_PG_CLASS, Natts_pg_class as usize);
        // and the static arrays carry exactly that many entries.
        assert_eq!(SCHEMA_PG_TYPE.len(), NATTS_PG_TYPE);
        assert_eq!(SCHEMA_PG_CLASS.len(), NATTS_PG_CLASS);
    }

    /// Attribute numbers are 1-based and contiguous in declaration order.
    #[test]
    fn schema_attnums_are_contiguous() {
        for schema in [SCHEMA_PG_TYPE, SCHEMA_PG_ATTRIBUTE, SCHEMA_PG_PROC, SCHEMA_PG_CLASS] {
            for (i, a) in schema.iter().enumerate() {
                assert_eq!(a.attnum as usize, i + 1, "attr {} out of order", a.attname);
            }
        }
    }

    /// Spot-check the genbki morph: the first column of pg_class is `oid` (oid
    /// type, 4-byte by-value), the second `relname` (name, 64-byte by-ref), and
    /// the leading fixed-width columns are NOT NULL (priorfixedwidth rule).
    #[test]
    fn schema_physical_types_match_genbki() {
        let oid_col = &SCHEMA_PG_CLASS[0];
        assert_eq!(oid_col.attname, "oid");
        assert_eq!(oid_col.atttypid, OIDOID.0);
        assert_eq!(oid_col.attlen, 4);
        assert!(oid_col.attbyval);
        assert!(oid_col.attnotnull);

        let name_col = &SCHEMA_PG_CLASS[1];
        assert_eq!(name_col.attname, "relname");
        assert_eq!(name_col.atttypid, NAMEOID.0);
        assert_eq!(name_col.attlen, 64);
        assert!(!name_col.attbyval);
        assert!(name_col.attnotnull);

        // pg_attribute.attlen is int2 (the int16 -> int2 rename path).
        let attlen_col = SCHEMA_PG_ATTRIBUTE
            .iter()
            .find(|a| a.attname == "attlen")
            .expect("attlen column");
        assert_eq!(attlen_col.atttypid, INT2OID.0);
        assert_eq!(attlen_col.attlen, 2);
    }

    /// genbki morph_row_for_pgattr resolves a `foo[]` column through the
    /// auto-generated array type (Catalog.pm GenerateArrayTypes): atttypid is the
    /// element's array_type_oid, attlen -1, by-ref, extended storage, attndims 1,
    /// attalign 'd' iff the element is double-aligned else 'i', and attcollation
    /// C_COLLATION_OID (950) iff the element is collatable else 0.
    #[test]
    fn schema_array_columns_resolve_to_array_type() {
        const D: i8 = b'd' as i8;
        const I: i8 = b'i' as i8;
        const X: i8 = b'x' as i8;
        let find = |schema: &'static [BootstrapAttr], name: &str| -> &'static BootstrapAttr {
            schema.iter().find(|a| a.attname == name).expect("column present")
        };

        // pg_class.relacl -> _aclitem (1034): aclitem is double-aligned and NOT
        // collatable, so attalign 'd', attcollation 0.
        let relacl = find(SCHEMA_PG_CLASS, "relacl");
        assert_eq!(relacl.atttypid, 1034);
        assert_eq!(relacl.attlen, -1);
        assert!(!relacl.attbyval);
        assert_eq!(relacl.attalign, D);
        assert_eq!(relacl.attstorage, X);
        assert_eq!(relacl.attndims, 1);
        assert_eq!(relacl.attcollation, 0);

        // pg_class.reloptions -> _text (1009): text is int-aligned and collatable,
        // so attalign 'i', attcollation C_COLLATION_OID (950) -- genbki always
        // stamps C collation on a collatable catalog column.
        let reloptions = find(SCHEMA_PG_CLASS, "reloptions");
        assert_eq!(reloptions.atttypid, 1009);
        assert_eq!(reloptions.attalign, I);
        assert_eq!(reloptions.attcollation, 950);
        assert_eq!(reloptions.attndims, 1);

        // pg_attribute.attacl -> _aclitem (1034), align 'd', collation 0.
        let attacl = find(SCHEMA_PG_ATTRIBUTE, "attacl");
        assert_eq!(attacl.atttypid, 1034);
        assert_eq!(attacl.attalign, D);
        assert_eq!(attacl.attcollation, 0);

        // pg_proc.proallargtypes -> _oid (1028): oid is not collatable.
        let proallargtypes = find(SCHEMA_PG_PROC, "proallargtypes");
        assert_eq!(proallargtypes.atttypid, 1028);
        assert_eq!(proallargtypes.attalign, I);
        assert_eq!(proallargtypes.attcollation, 0);

        // pg_proc.proargmodes -> _char (1002): char is not collatable; the array
        // is int-aligned (char is single-byte 'c', not 'd').
        let proargmodes = find(SCHEMA_PG_PROC, "proargmodes");
        assert_eq!(proargmodes.atttypid, 1002);
        assert_eq!(proargmodes.attalign, I);
        assert_eq!(proargmodes.attcollation, 0);

        // pg_proc.proargtypes is `oidvector` -- a fixed-ish scalar type (OID 30),
        // NOT an array column, and FORCE_NOT_NULL.
        let proargtypes = find(SCHEMA_PG_PROC, "proargtypes");
        assert_eq!(proargtypes.atttypid, 30);
        assert_eq!(proargtypes.attndims, 1); // oidvector is typcategory 'A'
        assert!(proargtypes.attnotnull);
    }

    /// formrdesc_tupdesc reproduces the formrdesc invariants: right natts, the
    /// composite type id, refcounted, first attcacheoff = 0, and the
    /// has-not-null constraint flag set (every catalog has NOT NULL columns).
    #[test]
    fn formrdesc_tupdesc_pg_class_shape() {
        let cat = FORMRDESC_CATALOGS
            .iter()
            .find(|c| c.relname == "pg_class")
            .expect("pg_class in formrdesc set");
        let desc = formrdesc_tupdesc(cat.relid, cat.reltype, cat.schema);

        assert_eq!(desc.natts as usize, NATTS_PG_CLASS);
        assert_eq!(desc.attrs.len(), NATTS_PG_CLASS);
        assert_eq!(desc.tdtypeid, cat.reltype);
        assert_eq!(desc.tdtypmod, -1);
        assert_eq!(desc.tdrefcount, 1);
        assert_eq!(desc.compact_attrs[0].attcacheoff, 0);
        assert_eq!(desc.attr(0).attname.data[..3].to_vec(), b"oid".to_vec());
        assert_eq!(desc.attr(1).attlen, 64); // relname is a Name
        let constr = desc.constr.as_ref().expect("pg_class has NOT NULL columns");
        assert!(constr.has_not_null);
    }

    /// Every formrdesc catalog builds a descriptor whose natts matches its schema.
    #[test]
    fn formrdesc_builds_all_bootstrap_catalogs() {
        for cat in FORMRDESC_CATALOGS {
            let desc = formrdesc(cat);
            assert_eq!(
                desc.natts as usize,
                cat.schema.len(),
                "{} natts mismatch",
                cat.relname
            );
        }
    }

    /// The seed-row codegen produced the expected M2 catalogs, and the well-known
    /// rows are present and well-formed (ordered (col,value) pairs).
    #[test]
    fn seed_rows_well_formed() {
        // pg_am seeds at least heap + btree.
        assert!(SEED_PG_AM.iter().any(|r| r.contains(&("amname", "heap"))));
        assert!(SEED_PG_AM.iter().any(|r| r.contains(&("amname", "btree"))));
        // pg_namespace seeds pg_catalog + public.
        assert!(SEED_PG_NAMESPACE.iter().any(|r| r.contains(&("nspname", "pg_catalog"))));
        assert!(SEED_PG_NAMESPACE.iter().any(|r| r.contains(&("nspname", "public"))));
        // every row has an oid as its first pair (genbki insert order).
        for r in SEED_PG_AM {
            assert_eq!(r.first().map(|p| p.0), Some("oid"));
        }
        // the int4/oid/name/text btree opclasses are seeded for the catalog indexes.
        assert!(!SEED_PG_OPCLASS.is_empty());
        assert!(!SEED_PG_AMOP.is_empty());
        assert!(!SEED_PG_AMPROC.is_empty());
    }

    /// bootstrap seeds all six .dat-backed M2 catalogs (inventory plumbing).
    #[test]
    fn bootstrap_catalogs_inventory() {
        assert_eq!(bootstrap_seed_inventory(), 6);
    }
}
