-- CASE, COALESCE, NULLIF
CREATE TABLE cv (a int, b int);
INSERT INTO cv VALUES (1, 10);
INSERT INTO cv VALUES (2, 20);
INSERT INTO cv VALUES (3, 30);

-- Searched CASE
SELECT a, CASE WHEN a = 1 THEN 'one' WHEN a = 2 THEN 'two' ELSE 'other' END FROM cv ORDER BY a;

-- Simple CASE
SELECT a, CASE a WHEN 1 THEN 'first' WHEN 2 THEN 'second' ELSE 'rest' END FROM cv ORDER BY a;

-- CASE without ELSE (returns NULL)
SELECT a, CASE WHEN a = 1 THEN 'yes' END FROM cv ORDER BY a;

-- COALESCE
SELECT COALESCE(NULL, NULL, 3);
SELECT COALESCE(1, 2, 3);

-- COALESCE with table data
CREATE TABLE cn (a int, b int);
INSERT INTO cn VALUES (1, NULL);
INSERT INTO cn VALUES (NULL, 20);
INSERT INTO cn VALUES (3, 30);
SELECT COALESCE(a, b) FROM cn ORDER BY COALESCE(a, b);

-- NULLIF
SELECT NULLIF(1, 1);
SELECT NULLIF(1, 2);
SELECT NULLIF('a', 'b');
