-- DELETE statement
CREATE TABLE del (a int, b int);
INSERT INTO del VALUES (1, 10);
INSERT INTO del VALUES (2, 20);
INSERT INTO del VALUES (3, 30);
INSERT INTO del VALUES (4, 40);
-- DELETE with WHERE
DELETE FROM del WHERE a = 2;
SELECT * FROM del ORDER BY a;
-- DELETE multiple rows
DELETE FROM del WHERE b > 25;
SELECT * FROM del ORDER BY a;
-- DELETE all
DELETE FROM del;
SELECT * FROM del;
