-- LIMIT and OFFSET
CREATE TABLE lim (a int, b int);
INSERT INTO lim VALUES (1, 10);
INSERT INTO lim VALUES (2, 20);
INSERT INTO lim VALUES (3, 30);
INSERT INTO lim VALUES (4, 40);
INSERT INTO lim VALUES (5, 50);

-- Basic LIMIT
SELECT * FROM lim ORDER BY a LIMIT 3;

-- OFFSET
SELECT * FROM lim ORDER BY a OFFSET 2;

-- LIMIT + OFFSET
SELECT * FROM lim ORDER BY a LIMIT 2 OFFSET 1;

-- LIMIT 0
SELECT * FROM lim ORDER BY a LIMIT 0;

-- LIMIT greater than row count
SELECT * FROM lim ORDER BY a LIMIT 100;

-- OFFSET greater than row count
SELECT * FROM lim ORDER BY a OFFSET 100;

-- OFFSET with no LIMIT
SELECT * FROM lim ORDER BY a OFFSET 4;
