-- ORDER BY variations
CREATE TABLE t2 (x int, y int);
INSERT INTO t2 VALUES (3, 10);
INSERT INTO t2 VALUES (1, 30);
INSERT INTO t2 VALUES (2, 20);
INSERT INTO t2 VALUES (1, 10);
-- Basic ORDER BY
SELECT * FROM t2 ORDER BY x;
SELECT * FROM t2 ORDER BY y DESC;
-- Multi-column ORDER BY
SELECT * FROM t2 ORDER BY x ASC, y DESC;
