-- Subqueries and set operations
CREATE TABLE t1 (a int, b int);
INSERT INTO t1 VALUES (1, 10);
INSERT INTO t1 VALUES (2, 20);
INSERT INTO t1 VALUES (3, 30);
INSERT INTO t1 VALUES (4, 40);

CREATE TABLE t2 (x int, y int);
INSERT INTO t2 VALUES (2, 200);
INSERT INTO t2 VALUES (4, 400);
INSERT INTO t2 VALUES (6, 600);

-- IN subquery
SELECT * FROM t1 WHERE a IN (SELECT x FROM t2) ORDER BY a;

-- NOT IN subquery
SELECT * FROM t1 WHERE a NOT IN (SELECT x FROM t2) ORDER BY a;

-- EXISTS subquery
SELECT * FROM t1 WHERE EXISTS (SELECT 1 FROM t2 WHERE t2.x = t1.a) ORDER BY a;

-- NOT EXISTS
SELECT * FROM t1 WHERE NOT EXISTS (SELECT 1 FROM t2 WHERE t2.x = t1.a) ORDER BY a;

-- Scalar subquery
SELECT a, (SELECT MAX(x) FROM t2) AS max_x FROM t1 ORDER BY a;

-- Subquery in FROM
SELECT sub.a, sub.b FROM (SELECT * FROM t1 WHERE b > 15) sub ORDER BY sub.a;

-- UNION
SELECT a FROM t1 UNION SELECT x FROM t2 ORDER BY a;

-- UNION ALL
SELECT a FROM t1 UNION ALL SELECT x FROM t2 ORDER BY a;

-- INTERSECT
SELECT a FROM t1 INTERSECT SELECT x FROM t2 ORDER BY a;

-- EXCEPT
SELECT a FROM t1 EXCEPT SELECT x FROM t2 ORDER BY a;
