#![doc = "PepperDB: a single-process, async Rust port of PostgreSQL."]
#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals)]
#![allow(dead_code, unused_imports, unused_variables)]
#![allow(unsafe_op_in_unsafe_fn)]

// === scaffold: child modules (Phase 0) ===
#[path = "access/mod.rs"]
pub mod access;
#[path = "archive/mod.rs"]
pub mod archive;
#[path = "backup/mod.rs"]
pub mod backup;
#[path = "bootstrap/mod.rs"]
pub mod bootstrap;
pub mod c;
#[path = "catalog/mod.rs"]
pub mod catalog;
#[path = "commands/mod.rs"]
pub mod commands;
#[path = "common/mod.rs"]
pub mod common;
#[path = "datatype/mod.rs"]
pub mod datatype;
#[path = "executor/mod.rs"]
pub mod executor;
#[path = "fe_utils/mod.rs"]
pub mod fe_utils;
pub mod fmgr;
#[path = "foreign/mod.rs"]
pub mod foreign;
pub mod funcapi;
pub mod getopt_long;
#[path = "jit/mod.rs"]
pub mod jit;
#[path = "lib/mod.rs"]
pub mod lib;
#[path = "libpq/mod.rs"]
pub mod libpq;
#[path = "mb/mod.rs"]
pub mod mb;
pub mod miscadmin;
#[path = "nodes/mod.rs"]
pub mod nodes;
#[path = "optimizer/mod.rs"]
pub mod optimizer;
#[path = "parser/mod.rs"]
pub mod parser;
#[path = "partitioning/mod.rs"]
pub mod partitioning;
#[path = "pch/mod.rs"]
pub mod pch;
pub mod pg_config;
pub mod pg_config_ext;
pub mod pg_config_manual;
pub mod pg_config_os;
pub mod pg_getopt;
pub mod pg_trace;
pub mod pgstat;
pub mod pgtar;
pub mod pgtime;
pub mod port;
#[path = "portability/mod.rs"]
pub mod portability;
pub mod postgres;
pub mod postgres_ext;
pub mod postgres_fe;
#[path = "postmaster/mod.rs"]
pub mod postmaster;
#[path = "regex/mod.rs"]
pub mod regex;
#[path = "replication/mod.rs"]
pub mod replication;
#[path = "rewrite/mod.rs"]
pub mod rewrite;
#[path = "snowball/mod.rs"]
pub mod snowball;
#[path = "statistics/mod.rs"]
pub mod statistics;
#[path = "storage/mod.rs"]
pub mod storage;
#[path = "tcop/mod.rs"]
pub mod tcop;
#[path = "tsearch/mod.rs"]
pub mod tsearch;
#[path = "utils/mod.rs"]
pub mod utils;
pub mod varatt;
pub mod windowapi;
// === end scaffold ===
