//! Translated from PostgreSQL src/include/pg_config_ext.h
//!
//! Generated by configure from pg_config_ext.h.in. It defines client-visible
//! width typedefs; on our 64-bit targets `int64`/`uint64` are the native 64-bit
//! integers, mapped directly to Rust primitives. Tombstone: nothing else carries
//! over.

pub type PG_INT64_TYPE = i64;
