//! Translated from PostgreSQL src/include/pg_config.h
//!
//! pg_config.h is generated by configure/meson from pg_config.h.in. Most of its
//! symbols are HAVE_* feature probes that map onto Rust std/cfg and are dropped.
//! Only the values that carry into the port (sizes, alignment, on-disk block
//! geometry, version) are translated, fixed for our targets: Linux x86_64 and
//! macOS aarch64 (64-bit, little-endian, 8-byte alignment), PostgreSQL 18.4.

// On-disk block geometry (changing any requires initdb).
pub const BLCKSZ: u32 = 8192; // size of a disk block / heap page
pub const XLOG_BLCKSZ: u32 = 8192; // size of a WAL file block
pub const RELSEG_SIZE: u32 = 131072; // max blocks per segment file (1GB/BLCKSZ)

// Alignment (8-byte MAXALIGN on both targets).
pub const MAXIMUM_ALIGNOF: usize = 8;
pub const ALIGNOF_SHORT: usize = 2;
pub const ALIGNOF_INT: usize = 4;
pub const ALIGNOF_LONG: usize = 8;
pub const ALIGNOF_DOUBLE: usize = 8;
pub const ALIGNOF_INT64_T: usize = 8;
pub const ALIGNOF_PG_INT128_TYPE: usize = 16;

// Type sizes (LP64).
pub const SIZEOF_VOID_P: usize = 8;
pub const SIZEOF_LONG: usize = 8;
pub const SIZEOF_LONG_LONG: usize = 8;
pub const SIZEOF_SIZE_T: usize = 8;

// 8-byte Datum is passed by value on 64-bit platforms.
pub const FLOAT8PASSBYVAL: bool = true;
pub const USE_FLOAT8_BYVAL: bool = true;

/// 128-bit integer support (both targets have __int128).
pub type PG_INT128_TYPE = i128;

// Version identification.
pub const PG_VERSION: &str = "18.4";
pub const PG_VERSION_NUM: u32 = 180004;
pub const PG_MAJORVERSION: &str = "18";
pub const PG_MAJORVERSION_NUM: u32 = 18;
pub const PG_VERSION_STR: &str = "PostgreSQL 18.4 (PepperDB)";
