//! Translation of postgres/src/common/compression.c
//!                + postgres/src/include/common/compression.h (the
//!                  pg_compress_algorithm enum + pg_compress_specification
//!                  struct + the PG_COMPRESSION_OPTION_* flag bits)
//!
//! compression.c
//!   Shared code for compression methods and specifications.
//!
//! A compression specification specifies the parameters that should be used
//! when performing compression with a specific algorithm. The simplest
//! possible compression specification is an integer, which sets the
//! compression level.
//!
//! Otherwise, a compression specification is a comma-separated list of items,
//! each having the form keyword or keyword=value.
//!
//! Currently, the supported keywords are "level", "long", and "workers".
//!
//! Portions Copyright (c) 1996-2025, PostgreSQL Global Development Group
//!
//! IDENTIFICATION
//!   src/common/compression.c
//!
//! Port notes:
//!   - This unit is pure string parsing of a compression *specification*; it
//!     does no actual compression. We translate the BACKEND path (`#ifndef
//!     FRONTEND`) which uses palloc/pstrdup; `parse_compress_options` lives
//!     under `#ifdef FRONTEND` in the C, but it is pure string slicing with no
//!     backend-only dependency, so we port it REAL as well.
//!   - The C `_()` gettext macro is a translation no-op at runtime; we drop it
//!     and build the literal message text directly.
//!   - The C uses `psprintf()`/`pstrdup()` to build `result->parse_error`. The
//!     crate has no psprintf, so we provide a local `psprintf_into` helper that
//!     formats a Rust `String`, then copies it into a palloc'd, NUL-terminated
//!     C buffer (matching psprintf's palloc-owned `char *` contract; the caller
//!     may pfree it).
//!   - zstd.h / zlib.h are #included in the C only for level-bound constants
//!     and the default-level macros. liblz4 / libzstd / libz are NOT built here
//!     (USE_LZ4 / USE_ZSTD / HAVE_LIBZ are all undefined), so:
//!       * parse_compress_specification sets parse_error for LZ4/ZSTD/GZIP to
//!         "this build does not support compression with %s", exactly as the C
//!         #else branches do.
//!       * The default-level for gzip (Z_DEFAULT_COMPRESSION) and zstd
//!         (ZSTD_CLEVEL_DEFAULT) is gated behind HAVE_LIBZ / USE_ZSTD in the C,
//!         so in this build `result->level` stays at its prior value in those
//!         #else branches -- we reproduce that (no default-level assignment).
//!       * validate_compress_specification's ZSTD bounds (ZSTD_maxCLevel /
//!         ZSTD_minCLevel) are inside `#ifdef USE_ZSTD`, so they are skipped
//!         here, leaving min_level=1, max_level=1, default_level=0 for ZSTD.
//!   - C `char *` keyword/value/specification args are kept as `*mut c_char`.
//!     pg_strcasecmp, strcmp, strtol, strchr, memcpy, strlen are bound to libc
//!     / the crate's port routine, matching the C exactly.

#![allow(clippy::missing_safety_doc)]

use crate::prelude::*;
use core::ffi::{c_char, c_int, c_long};

// pg_strcasecmp from port/pgstrcasecmp.c (expect_boolean_value uses it).
use crate::port::pgstrcasecmp::pg_strcasecmp;

// libc routines used by the parser, bound exactly as the C uses them.
extern "C" {
    fn strcmp(s1: *const c_char, s2: *const c_char) -> c_int;
    fn strchr(s: *const c_char, c: c_int) -> *mut c_char;
    fn strtol(s: *const c_char, endptr: *mut *mut c_char, base: c_int) -> c_long;
    fn memcpy(dst: *mut c_void, src: *const c_void, n: Size) -> *mut c_void;
    fn strlen(s: *const c_char) -> Size;
}

// ----------------------------------------------------------------
//   Declarations from common/compression.h
// ----------------------------------------------------------------

/*
 * These values are stored in disk, for example in files generated by pg_dump.
 * Create the necessary backwards compatibility layers if their order changes.
 *
 *   typedef enum pg_compress_algorithm
 *   {
 *       PG_COMPRESSION_NONE,
 *       PG_COMPRESSION_GZIP,
 *       PG_COMPRESSION_LZ4,
 *       PG_COMPRESSION_ZSTD,
 *   } pg_compress_algorithm;
 */
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[repr(C)]
pub enum pg_compress_algorithm {
    PG_COMPRESSION_NONE = 0,
    PG_COMPRESSION_GZIP = 1,
    PG_COMPRESSION_LZ4 = 2,
    PG_COMPRESSION_ZSTD = 3,
}
// Bring the variants into scope so the body can name them bare, as the C does.
pub use pg_compress_algorithm::*;

// #define PG_COMPRESSION_OPTION_WORKERS        (1 << 0)
pub const PG_COMPRESSION_OPTION_WORKERS: uint32 = 1 << 0;
// #define PG_COMPRESSION_OPTION_LONG_DISTANCE  (1 << 1)
pub const PG_COMPRESSION_OPTION_LONG_DISTANCE: uint32 = 1 << 1;

/*
 *   typedef struct pg_compress_specification
 *   {
 *       pg_compress_algorithm algorithm;
 *       unsigned    options;        - OR of PG_COMPRESSION_OPTION constants
 *       int         level;
 *       int         workers;
 *       bool        long_distance;
 *       char       *parse_error;    - NULL if parsing was OK, else message
 *   } pg_compress_specification;
 */
#[repr(C)]
pub struct pg_compress_specification {
    pub algorithm: pg_compress_algorithm,
    /// OR of PG_COMPRESSION_OPTION constants
    pub options: uint32,
    pub level: c_int,
    pub workers: c_int,
    pub long_distance: bool,
    /// NULL if parsing was OK, else message
    pub parse_error: *mut c_char,
}

impl Default for pg_compress_specification {
    fn default() -> Self {
        pg_compress_specification {
            algorithm: PG_COMPRESSION_NONE,
            options: 0,
            level: 0,
            workers: 0,
            long_distance: false,
            parse_error: null_mut(),
        }
    }
}

// ----------------------------------------------------------------
//   Hardcoded level bounds / default-level constants
//
// In the C these come from <zlib.h> and <zstd.h>. We pin the exact values the
// C uses so the bounds logic is faithful even though the libs are not built.
// ----------------------------------------------------------------

// zlib.h:  #define Z_DEFAULT_COMPRESSION  (-1)
#[allow(dead_code)]
const Z_DEFAULT_COMPRESSION: c_int = -1;
// zstd.h:  #define ZSTD_CLEVEL_DEFAULT  3
#[allow(dead_code)]
const ZSTD_CLEVEL_DEFAULT: c_int = 3;

// ----------------------------------------------------------------
//   psprintf shim: format a Rust string into a palloc'd C string
// ----------------------------------------------------------------

/// Copy a Rust `&str` into a freshly palloc'd, NUL-terminated C string,
/// mirroring psprintf()'s "returns a palloc'd char*" contract. The caller owns
/// the result and may pfree it (as the C comment on parse_error notes).
unsafe fn cstring_from_str(s: &str) -> *mut c_char {
    let bytes = s.as_bytes();
    let len = bytes.len();
    let p = palloc(len + 1) as *mut c_char;
    if len > 0 {
        memcpy(p as *mut c_void, bytes.as_ptr() as *const c_void, len);
    }
    *p.add(len) = 0;
    p
}

/// Render a `*const c_char` (assumed valid UTF-8 / ASCII) as a Rust `&str` for
/// embedding into an error message via "{}". Used where the C splices a `%s`.
unsafe fn cstr_to_str<'a>(p: *const c_char) -> &'a str {
    let len = strlen(p);
    let slice = core::slice::from_raw_parts(p as *const u8, len);
    // The keywords/values are caller-supplied bytes; fall back lossily-but the
    // common path is ASCII keywords, so from_utf8 succeeds.
    core::str::from_utf8(slice).unwrap_or("")
}

// ----------------------------------------------------------------
//   common/compression.c
// ----------------------------------------------------------------

/*
 * Look up a compression algorithm by name. Returns true and sets *algorithm
 * if the name is recognized. Otherwise returns false.
 */
pub unsafe fn parse_compress_algorithm(
    name: *mut c_char,
    algorithm: *mut pg_compress_algorithm,
) -> bool {
    if strcmp(name, c"none".as_ptr()) == 0 {
        *algorithm = PG_COMPRESSION_NONE;
    } else if strcmp(name, c"gzip".as_ptr()) == 0 {
        *algorithm = PG_COMPRESSION_GZIP;
    } else if strcmp(name, c"lz4".as_ptr()) == 0 {
        *algorithm = PG_COMPRESSION_LZ4;
    } else if strcmp(name, c"zstd".as_ptr()) == 0 {
        *algorithm = PG_COMPRESSION_ZSTD;
    } else {
        return false;
    }
    true
}

/*
 * Get the human-readable name corresponding to a particular compression
 * algorithm.
 *
 * The C returns a `const char *` to a string literal. We return a *const
 * c_char to a static NUL-terminated byte string with identical contents.
 */
pub unsafe fn get_compress_algorithm_name(algorithm: pg_compress_algorithm) -> *const c_char {
    match algorithm {
        PG_COMPRESSION_NONE => c"none".as_ptr(),
        PG_COMPRESSION_GZIP => c"gzip".as_ptr(),
        PG_COMPRESSION_LZ4 => c"lz4".as_ptr(),
        PG_COMPRESSION_ZSTD => c"zstd".as_ptr(),
        // no default, to provoke compiler warnings if values are added
    }
    // The C has a trailing `Assert(false); return "???";` after the switch,
    // unreachable because the match above is exhaustive.
}

/*
 * Parse a compression specification for a specified algorithm.
 *
 * See the file header comments for a brief description of what a compression
 * specification is expected to look like.
 *
 * On return, all fields of the result object will be initialized.
 * In particular, result->parse_error will be NULL if no errors occurred
 * during parsing, and will otherwise contain an appropriate error message.
 * The caller may free this error message string using pfree, if desired.
 * Note, however, even if there's no parse error, the string might not make
 * sense: e.g. for gzip, level=12 is not sensible, but it does parse OK.
 *
 * The compression level is assigned by default if not directly specified
 * by the specification.
 *
 * Use validate_compress_specification() to find out whether a compression
 * specification is semantically sensible.
 */
pub unsafe fn parse_compress_specification(
    algorithm: pg_compress_algorithm,
    specification: *mut c_char,
    result: *mut pg_compress_specification,
) {
    // Initial setup of result object.
    (*result).algorithm = algorithm;
    (*result).options = 0;
    (*result).parse_error = null_mut();

    /*
     * Assign a default level depending on the compression method.  This may
     * be enforced later.
     */
    match (*result).algorithm {
        PG_COMPRESSION_NONE => {
            (*result).level = 0;
        }
        PG_COMPRESSION_LZ4 => {
            // #ifdef USE_LZ4: result->level = 0;  (fast compression mode)
            // #else: this build does not support compression with LZ4
            (*result).parse_error =
                cstring_from_str("this build does not support compression with LZ4");
        }
        PG_COMPRESSION_ZSTD => {
            // #ifdef USE_ZSTD: result->level = ZSTD_CLEVEL_DEFAULT;
            // #else: this build does not support compression with ZSTD
            (*result).parse_error =
                cstring_from_str("this build does not support compression with ZSTD");
        }
        PG_COMPRESSION_GZIP => {
            // #ifdef HAVE_LIBZ: result->level = Z_DEFAULT_COMPRESSION;
            // #else: this build does not support compression with gzip
            (*result).parse_error =
                cstring_from_str("this build does not support compression with gzip");
        }
    }

    // If there is no specification, we're done already.
    if specification.is_null() {
        return;
    }

    // As a special case, the specification can be a bare integer.
    let mut bare_level_endp: *mut c_char = null_mut();
    let bare_level = strtol(specification, &mut bare_level_endp, 10) as c_int;
    if specification != bare_level_endp && *bare_level_endp == 0 {
        (*result).level = bare_level;
        return;
    }

    // Look for comma-separated keyword or keyword=value entries.
    let mut specification = specification;
    loop {
        let kwstart: *mut c_char;
        let mut kwend: *mut c_char;
        let vstart: *mut c_char;
        let mut vend: *mut c_char;
        let kwlen: c_int;
        let vlen: c_int;
        let has_value: bool;
        let keyword: *mut c_char;
        let value: *mut c_char;

        // Figure start, end, and length of next keyword and any value.
        kwstart = specification;
        kwend = specification;
        while *kwend != 0 && *kwend != b',' as c_char && *kwend != b'=' as c_char {
            kwend = kwend.add(1);
        }
        kwlen = kwend.offset_from(kwstart) as c_int;
        if *kwend != b'=' as c_char {
            vstart = null_mut();
            vend = null_mut();
            vlen = 0;
            has_value = false;
        } else {
            vstart = kwend.add(1);
            vend = kwend.add(1);
            while *vend != 0 && *vend != b',' as c_char {
                vend = vend.add(1);
            }
            vlen = vend.offset_from(vstart) as c_int;
            has_value = true;
        }

        // Reject empty keyword.
        if kwlen == 0 {
            (*result).parse_error =
                cstring_from_str("found empty string where a compression option was expected");
            break;
        }

        // Extract keyword and value as separate C strings.
        keyword = palloc((kwlen + 1) as Size) as *mut c_char;
        memcpy(
            keyword as *mut c_void,
            kwstart as *const c_void,
            kwlen as Size,
        );
        *keyword.add(kwlen as usize) = 0;
        if !has_value {
            value = null_mut();
        } else {
            value = palloc((vlen + 1) as Size) as *mut c_char;
            memcpy(value as *mut c_void, vstart as *const c_void, vlen as Size);
            *value.add(vlen as usize) = 0;
        }

        // Handle whatever keyword we found.
        if strcmp(keyword, c"level".as_ptr()) == 0 {
            (*result).level = expect_integer_value(keyword, value, result);

            /*
             * No need to set a flag in "options", there is a default level
             * set at least thanks to the logic above.
             */
        } else if strcmp(keyword, c"workers".as_ptr()) == 0 {
            (*result).workers = expect_integer_value(keyword, value, result);
            (*result).options |= PG_COMPRESSION_OPTION_WORKERS;
        } else if strcmp(keyword, c"long".as_ptr()) == 0 {
            (*result).long_distance = expect_boolean_value(keyword, value, result);
            (*result).options |= PG_COMPRESSION_OPTION_LONG_DISTANCE;
        } else {
            (*result).parse_error = cstring_from_str(&format!(
                "unrecognized compression option: \"{}\"",
                cstr_to_str(keyword)
            ));
        }

        // Release memory, just to be tidy.
        pfree(keyword as *mut c_void);
        if !value.is_null() {
            pfree(value as *mut c_void);
        }

        /*
         * If we got an error or have reached the end of the string, stop.
         *
         * If there is no value, then the end of the keyword might have been
         * the end of the string. If there is a value, then the end of the
         * keyword cannot have been the end of the string, but the end of the
         * value might have been.
         */
        if !(*result).parse_error.is_null()
            || (if vend.is_null() {
                *kwend == 0
            } else {
                *vend == 0
            })
        {
            break;
        }

        // Advance to next entry and loop around.
        specification = if vend.is_null() {
            kwend.add(1)
        } else {
            vend.add(1)
        };
    }
}

/*
 * Parse 'value' as an integer and return the result.
 *
 * If parsing fails, set result->parse_error to an appropriate message
 * and return -1.
 */
unsafe fn expect_integer_value(
    keyword: *mut c_char,
    value: *mut c_char,
    result: *mut pg_compress_specification,
) -> c_int {
    if value.is_null() {
        (*result).parse_error = cstring_from_str(&format!(
            "compression option \"{}\" requires a value",
            cstr_to_str(keyword)
        ));
        return -1;
    }

    let mut ivalue_endp: *mut c_char = null_mut();
    let ivalue = strtol(value, &mut ivalue_endp, 10) as c_int;
    if ivalue_endp == value || *ivalue_endp != 0 {
        (*result).parse_error = cstring_from_str(&format!(
            "value for compression option \"{}\" must be an integer",
            cstr_to_str(keyword)
        ));
        return -1;
    }
    ivalue
}

/*
 * Parse 'value' as a boolean and return the result.
 *
 * If parsing fails, set result->parse_error to an appropriate message
 * and return -1.  The caller must check result->parse_error to determine if
 * the call was successful.
 *
 * Valid values are: yes, no, on, off, 1, 0.
 *
 * Inspired by ParseVariableBool().
 */
unsafe fn expect_boolean_value(
    keyword: *mut c_char,
    value: *mut c_char,
    result: *mut pg_compress_specification,
) -> bool {
    if value.is_null() {
        return true;
    }

    if pg_strcasecmp(value, c"yes".as_ptr()) == 0 {
        return true;
    }
    if pg_strcasecmp(value, c"on".as_ptr()) == 0 {
        return true;
    }
    if pg_strcasecmp(value, c"1".as_ptr()) == 0 {
        return true;
    }

    if pg_strcasecmp(value, c"no".as_ptr()) == 0 {
        return false;
    }
    if pg_strcasecmp(value, c"off".as_ptr()) == 0 {
        return false;
    }
    if pg_strcasecmp(value, c"0".as_ptr()) == 0 {
        return false;
    }

    (*result).parse_error = cstring_from_str(&format!(
        "value for compression option \"{}\" must be a Boolean value",
        cstr_to_str(keyword)
    ));
    false
}

/*
 * Returns NULL if the compression specification string was syntactically
 * valid and semantically sensible.  Otherwise, returns an error message.
 *
 * Does not test whether this build of PostgreSQL supports the requested
 * compression method.
 */
pub unsafe fn validate_compress_specification(
    spec: *mut pg_compress_specification,
) -> *mut c_char {
    // min_level is only reassigned in the USE_ZSTD branch (compiled out here).
    let min_level: c_int = 1;
    let mut max_level: c_int = 1;
    let mut default_level: c_int = 0;

    // If it didn't even parse OK, it's definitely no good.
    if !(*spec).parse_error.is_null() {
        return (*spec).parse_error;
    }

    /*
     * Check that the algorithm expects a compression level and it is within
     * the legal range for the algorithm.
     */
    match (*spec).algorithm {
        PG_COMPRESSION_GZIP => {
            max_level = 9;
            // #ifdef HAVE_LIBZ: default_level = Z_DEFAULT_COMPRESSION; (skipped)
        }
        PG_COMPRESSION_LZ4 => {
            max_level = 12;
            default_level = 0; // fast mode
        }
        PG_COMPRESSION_ZSTD => {
            // #ifdef USE_ZSTD:
            //   max_level = ZSTD_maxCLevel();
            //   min_level = ZSTD_minCLevel();
            //   default_level = ZSTD_CLEVEL_DEFAULT;
            // Not built here, so min_level=1, max_level=1, default_level=0.
        }
        PG_COMPRESSION_NONE => {
            if (*spec).level != 0 {
                return cstring_from_str(&format!(
                    "compression algorithm \"{}\" does not accept a compression level",
                    cstr_to_str(get_compress_algorithm_name((*spec).algorithm))
                ));
            }
        }
    }

    if ((*spec).level < min_level || (*spec).level > max_level) && (*spec).level != default_level {
        return cstring_from_str(&format!(
            "compression algorithm \"{}\" expects a compression level between {} and {} (default at {})",
            cstr_to_str(get_compress_algorithm_name((*spec).algorithm)),
            min_level,
            max_level,
            default_level
        ));
    }

    /*
     * Of the compression algorithms that we currently support, only zstd
     * allows parallel workers.
     */
    if ((*spec).options & PG_COMPRESSION_OPTION_WORKERS) != 0
        && (*spec).algorithm != PG_COMPRESSION_ZSTD
    {
        return cstring_from_str(&format!(
            "compression algorithm \"{}\" does not accept a worker count",
            cstr_to_str(get_compress_algorithm_name((*spec).algorithm))
        ));
    }

    /*
     * Of the compression algorithms that we currently support, only zstd
     * supports long-distance mode.
     */
    if ((*spec).options & PG_COMPRESSION_OPTION_LONG_DISTANCE) != 0
        && (*spec).algorithm != PG_COMPRESSION_ZSTD
    {
        return cstring_from_str(&format!(
            "compression algorithm \"{}\" does not support long-distance mode",
            cstr_to_str(get_compress_algorithm_name((*spec).algorithm))
        ));
    }

    null_mut()
}

/*
 * Basic parsing of a value specified through a command-line option, commonly
 * -Z/--compress.
 *
 * The parsing consists of a METHOD:DETAIL string fed later to
 * parse_compress_specification().  This only extracts METHOD and DETAIL.
 * If only an integer is found, the method is implied by the value specified.
 *
 * NOTE: in the C this is guarded by `#ifdef FRONTEND`; it is pure string
 * slicing and is ported REAL here.
 */
pub unsafe fn parse_compress_options(
    option: *const c_char,
    algorithm: *mut *mut c_char,
    detail: *mut *mut c_char,
) {
    /*
     * Check whether the compression specification consists of a bare integer.
     *
     * For backward-compatibility, assume "none" if the integer found is zero
     * and "gzip" otherwise.
     */
    let mut endp: *mut c_char = null_mut();
    let result = strtol(option, &mut endp, 10);
    if *endp == 0 {
        if result == 0 {
            *algorithm = pstrdup(c"none".as_ptr());
            *detail = null_mut();
        } else {
            *algorithm = pstrdup(c"gzip".as_ptr());
            *detail = pstrdup(option);
        }
        return;
    }

    // Check whether there is a compression detail following the algorithm name.
    let sep = strchr(option, b':' as c_int);
    if sep.is_null() {
        *algorithm = pstrdup(option);
        *detail = null_mut();
    } else {
        let n = sep.offset_from(option) as usize;
        let alg = palloc((n + 1) as Size) as *mut c_char;
        memcpy(alg as *mut c_void, option as *const c_void, n as Size);
        *alg.add(n) = 0;

        *algorithm = alg;
        *detail = pstrdup(sep.add(1));
    }
}

// ----------------------------------------------------------------
//   Tests exercising the REAL parsing logic.
// ----------------------------------------------------------------
#[cfg(test)]
mod tests {
    use super::*;

    // strlen for the test assertions on returned C strings.
    unsafe fn rs(p: *const c_char) -> String {
        if p.is_null() {
            return String::from("<null>");
        }
        let len = strlen(p);
        let slice = core::slice::from_raw_parts(p as *const u8, len);
        String::from_utf8_lossy(slice).into_owned()
    }

    #[test]
    fn test_parse_compress_algorithm() {
        unsafe {
            let mut alg = PG_COMPRESSION_NONE;
            assert!(parse_compress_algorithm(
                c"gzip".as_ptr() as *mut c_char,
                &mut alg
            ));
            assert_eq!(alg, PG_COMPRESSION_GZIP);

            assert!(parse_compress_algorithm(
                c"lz4".as_ptr() as *mut c_char,
                &mut alg
            ));
            assert_eq!(alg, PG_COMPRESSION_LZ4);

            assert!(parse_compress_algorithm(
                c"none".as_ptr() as *mut c_char,
                &mut alg
            ));
            assert_eq!(alg, PG_COMPRESSION_NONE);

            assert!(parse_compress_algorithm(
                c"zstd".as_ptr() as *mut c_char,
                &mut alg
            ));
            assert_eq!(alg, PG_COMPRESSION_ZSTD);

            assert!(!parse_compress_algorithm(
                c"bogus".as_ptr() as *mut c_char,
                &mut alg
            ));
        }
    }

    #[test]
    fn test_get_compress_algorithm_name_roundtrips() {
        unsafe {
            for &a in &[
                PG_COMPRESSION_NONE,
                PG_COMPRESSION_GZIP,
                PG_COMPRESSION_LZ4,
                PG_COMPRESSION_ZSTD,
            ] {
                let name = get_compress_algorithm_name(a);
                let mut back = PG_COMPRESSION_NONE;
                assert!(parse_compress_algorithm(name as *mut c_char, &mut back));
                assert_eq!(a, back);
            }
            assert_eq!(rs(get_compress_algorithm_name(PG_COMPRESSION_GZIP)), "gzip");
        }
    }

    #[test]
    fn test_parse_specification_bare_level() {
        unsafe {
            let mut spec = pg_compress_specification::default();
            parse_compress_specification(
                PG_COMPRESSION_NONE,
                c"9".as_ptr() as *mut c_char,
                &mut spec,
            );
            // Bare integer overrides any default-level handling.
            assert_eq!(spec.level, 9);
            assert!(spec.parse_error.is_null());
        }
    }

    #[test]
    fn test_parse_specification_level_keyword() {
        unsafe {
            let mut spec = pg_compress_specification::default();
            parse_compress_specification(
                PG_COMPRESSION_NONE,
                c"level=6".as_ptr() as *mut c_char,
                &mut spec,
            );
            assert_eq!(spec.level, 6);
            assert!(spec.parse_error.is_null());
        }
    }

    #[test]
    fn test_parse_specification_bad_keyword_sets_error() {
        unsafe {
            let mut spec = pg_compress_specification::default();
            parse_compress_specification(
                PG_COMPRESSION_GZIP,
                c"bogus=1".as_ptr() as *mut c_char,
                &mut spec,
            );
            assert!(!spec.parse_error.is_null());
            assert_eq!(
                rs(spec.parse_error),
                "unrecognized compression option: \"bogus\""
            );
        }
    }

    #[test]
    fn test_parse_specification_workers_and_long() {
        unsafe {
            let mut spec = pg_compress_specification::default();
            parse_compress_specification(
                PG_COMPRESSION_NONE,
                c"workers=3,long".as_ptr() as *mut c_char,
                &mut spec,
            );
            assert_eq!(spec.workers, 3);
            assert!(spec.long_distance);
            assert_ne!(spec.options & PG_COMPRESSION_OPTION_WORKERS, 0);
            assert_ne!(spec.options & PG_COMPRESSION_OPTION_LONG_DISTANCE, 0);
        }
    }

    #[test]
    fn test_level_requires_integer() {
        unsafe {
            let mut spec = pg_compress_specification::default();
            parse_compress_specification(
                PG_COMPRESSION_GZIP,
                c"level=abc".as_ptr() as *mut c_char,
                &mut spec,
            );
            assert_eq!(
                rs(spec.parse_error),
                "value for compression option \"level\" must be an integer"
            );
        }
    }

    #[test]
    fn test_lz4_unsupported_build_sets_error() {
        unsafe {
            // No specification: only the default-level switch runs, which sets
            // the "this build does not support compression with LZ4" message.
            let mut spec = pg_compress_specification::default();
            parse_compress_specification(PG_COMPRESSION_LZ4, null_mut(), &mut spec);
            assert_eq!(
                rs(spec.parse_error),
                "this build does not support compression with LZ4"
            );
        }
    }

    #[test]
    fn test_validate_none_rejects_level() {
        unsafe {
            let mut spec = pg_compress_specification::default();
            spec.algorithm = PG_COMPRESSION_NONE;
            spec.level = 5;
            let err = validate_compress_specification(&mut spec);
            assert!(!err.is_null());
            assert_eq!(
                rs(err),
                "compression algorithm \"none\" does not accept a compression level"
            );
        }
    }

    #[test]
    fn test_validate_gzip_level_out_of_range() {
        unsafe {
            let mut spec = pg_compress_specification::default();
            spec.algorithm = PG_COMPRESSION_GZIP;
            spec.level = 99;
            let err = validate_compress_specification(&mut spec);
            assert_eq!(
                rs(err),
                "compression algorithm \"gzip\" expects a compression level between 1 and 9 (default at 0)"
            );
        }
    }

    #[test]
    fn test_validate_workers_rejected_for_gzip() {
        unsafe {
            let mut spec = pg_compress_specification::default();
            spec.algorithm = PG_COMPRESSION_GZIP;
            spec.level = 1;
            spec.options = PG_COMPRESSION_OPTION_WORKERS;
            let err = validate_compress_specification(&mut spec);
            assert_eq!(
                rs(err),
                "compression algorithm \"gzip\" does not accept a worker count"
            );
        }
    }

    #[test]
    fn test_parse_compress_options_bare_integer() {
        unsafe {
            let mut alg: *mut c_char = null_mut();
            let mut detail: *mut c_char = null_mut();

            parse_compress_options(c"0".as_ptr(), &mut alg, &mut detail);
            assert_eq!(rs(alg), "none");
            assert!(detail.is_null());

            parse_compress_options(c"5".as_ptr(), &mut alg, &mut detail);
            assert_eq!(rs(alg), "gzip");
            assert_eq!(rs(detail), "5");
        }
    }

    #[test]
    fn test_parse_compress_options_method_detail() {
        unsafe {
            let mut alg: *mut c_char = null_mut();
            let mut detail: *mut c_char = null_mut();

            parse_compress_options(c"zstd:level=7".as_ptr(), &mut alg, &mut detail);
            assert_eq!(rs(alg), "zstd");
            assert_eq!(rs(detail), "level=7");

            parse_compress_options(c"lz4".as_ptr(), &mut alg, &mut detail);
            assert_eq!(rs(alg), "lz4");
            assert!(detail.is_null());
        }
    }
}
