//! Translated from PostgreSQL src/include/common/kwlookup.h

/// Perfect hash function used by `ScanKeywordLookup`.
pub type ScanKeywordHashFunc = fn(key: &[u8]) -> i32;

/// Data needed by `ScanKeywordLookup` to search a keyword set.
/// Typically generated by gen_keywordlist.pl from PG_KEYWORD macros.
pub struct ScanKeywordList {
    /// All keywords in order, separated by \0.
    pub kw_string: &'static str,
    /// Offsets to the start of each keyword.
    pub kw_offsets: &'static [u16],
    /// Perfect hash function for keywords.
    pub hash: ScanKeywordHashFunc,
    /// Number of keywords.
    pub num_keywords: i32,
    /// Length of the longest keyword.
    pub max_kw_len: i32,
}

/// Look up `s` in `keywords`; returns the keyword index, or None if absent.
/// The keyword set is ASCII-sorted, so this is a binary search (the C code uses
/// the generated perfect hash; binary search is the equivalent without codegen).
/// `s` must be lower-cased by the caller, matching the all-lowercase keyword set.
pub fn scan_keyword_lookup(s: &str, keywords: &ScanKeywordList) -> Option<i32> {
    if s.is_empty() || s.len() as i32 > keywords.max_kw_len {
        return None;
    }
    let (mut lo, mut hi) = (0i32, keywords.num_keywords - 1);
    while lo <= hi {
        let mid = i32::midpoint(lo, hi);
        match get_scan_keyword(mid, keywords).cmp(s) {
            core::cmp::Ordering::Less => lo = mid + 1,
            core::cmp::Ordering::Greater => hi = mid - 1,
            core::cmp::Ordering::Equal => return Some(mid),
        }
    }
    None
}

/// Retrieve the text of the N'th keyword (the \0-terminated slice at its offset).
pub fn get_scan_keyword(n: i32, keywords: &ScanKeywordList) -> &str {
    let off = keywords.kw_offsets[n as usize] as usize;
    let rest = &keywords.kw_string[off..];
    #[allow(clippy::option_if_let_else, reason = "borrow of rest prevents map_or here")]
    match rest.find('\0') {
        Some(end) => &rest[..end],
        None => rest,
    }
}
