//! Key word lookup for PostgreSQL.
//!
//! Translated from:
//!   - src/include/common/kwlookup.h
//!   - src/common/kwlookup.c
//!
//! Portions Copyright (c) 1996-2025, PostgreSQL Global Development Group
//! Portions Copyright (c) 1994, Regents of the University of California

use crate::prelude::*;

/* Hash function used by ScanKeywordLookup */
pub type ScanKeywordHashFunc =
    Option<unsafe extern "C" fn(key: *const c_void, keylen: usize) -> c_int>;

/*
 * This struct contains the data needed by ScanKeywordLookup to perform a
 * search within a set of keywords.  The contents are typically generated by
 * src/tools/gen_keywordlist.pl from a header containing PG_KEYWORD macros.
 */
#[repr(C)]
pub struct ScanKeywordList {
    pub kw_string: *const c_char,  /* all keywords in order, separated by \0 */
    pub kw_offsets: *const uint16, /* offsets to the start of each keyword */
    pub hash: ScanKeywordHashFunc, /* perfect hash function for keywords */
    pub num_keywords: c_int,       /* number of keywords */
    pub max_kw_len: c_int,         /* length of longest keyword */
}

/// Code that wants to retrieve the text of the N'th keyword should use this.
#[inline]
pub unsafe fn GetScanKeyword(n: c_int, keywords: *const ScanKeywordList) -> *const c_char {
    (*keywords)
        .kw_string
        .add(*(*keywords).kw_offsets.add(n as usize) as usize)
}

// TODO(pg-port): the prelude does not export strlen; provide a private helper.
unsafe fn strlen(s: *const c_char) -> usize {
    let mut len: usize = 0;
    while *s.add(len) != 0 {
        len += 1;
    }
    len
}

/*
 * ScanKeywordLookup - see if a given word is a keyword
 *
 * The list of keywords to be matched against is passed as a ScanKeywordList.
 *
 * Returns the keyword number (0..N-1) of the keyword, or -1 if no match.
 * Callers typically use the keyword number to index into information
 * arrays, but that is no concern of this code.
 *
 * The match is done case-insensitively.  Note that we deliberately use a
 * dumbed-down case conversion that will only translate 'A'-'Z' into 'a'-'z',
 * even if we are in a locale where tolower() would produce more or different
 * translations.  This is to conform to the SQL99 spec, which says that
 * keywords are to be matched in this way even though non-keyword identifiers
 * receive a different case-normalization mapping.
 */
pub unsafe fn ScanKeywordLookup(str: *const c_char, keywords: *const ScanKeywordList) -> c_int {
    let len: usize;
    let h: c_int;
    let mut kw: *const c_char;

    /*
     * Reject immediately if too long to be any keyword.  This saves useless
     * hashing and downcasing work on long strings.
     */
    len = strlen(str);
    if len > (*keywords).max_kw_len as usize {
        return -1;
    }

    /*
     * Compute the hash function.  We assume it was generated to produce
     * case-insensitive results.  Since it's a perfect hash, we need only
     * match to the specific keyword it identifies.
     */
    h = ((*keywords).hash.expect("ScanKeywordList.hash is NULL"))(str as *const c_void, len);

    /* An out-of-range result implies no match */
    if h < 0 || h >= (*keywords).num_keywords {
        return -1;
    }

    /*
     * Compare character-by-character to see if we have a match, applying an
     * ASCII-only downcasing to the input characters.  We must not use
     * tolower() since it may produce the wrong translation in some locales
     * (eg, Turkish).
     */
    kw = GetScanKeyword(h, keywords);
    let mut str = str;
    while *str != 0 {
        let mut ch: c_char = *str;
        str = str.add(1);

        if ch >= b'A' as c_char && ch <= b'Z' as c_char {
            ch += (b'a' - b'A') as c_char;
        }
        if ch != *kw {
            return -1;
        }
        kw = kw.add(1);
    }
    if *kw != 0 {
        return -1;
    }

    /* Success! */
    h
}
