//! Translated from PostgreSQL src/include/common/kwlookup.h

/// Perfect hash function used by `ScanKeywordLookup`.
pub type ScanKeywordHashFunc = fn(key: &[u8]) -> i32;

/// Data needed by `ScanKeywordLookup` to search a keyword set.
/// Typically generated by gen_keywordlist.pl from PG_KEYWORD macros.
pub struct ScanKeywordList {
    /// All keywords in order, separated by \0.
    pub kw_string: &'static str,
    /// Offsets to the start of each keyword.
    pub kw_offsets: &'static [u16],
    /// Perfect hash function for keywords.
    pub hash: ScanKeywordHashFunc,
    /// Number of keywords.
    pub num_keywords: i32,
    /// Length of the longest keyword.
    pub max_kw_len: i32,
}

/// Look up `str` in `keywords`; returns the keyword index, or None if absent.
pub fn scan_keyword_lookup(s: &str, keywords: &ScanKeywordList) -> Option<i32> {
    let _ = (s, keywords);
    unimplemented!()
}

/// Retrieve the text of the N'th keyword.
pub fn get_scan_keyword(n: i32, keywords: &ScanKeywordList) -> &str {
    let off = keywords.kw_offsets[n as usize] as usize;
    &keywords.kw_string[off..]
}
