//! Translated from PostgreSQL src/include/common/md5.h
// Crypto: signatures only (impl via a crate / md5_common.c port later).

/// Size of result generated by MD5 computation.
pub const MD5_DIGEST_LENGTH: usize = 16;
/// Block size for MD5.
pub const MD5_BLOCK_SIZE: usize = 64;

/// Allowed characters in an MD5-derived password hash.
pub const MD5_PASSWD_CHARSET: &str = "0123456789abcdef";
/// Length of an "md5..." password string (incl. nul in C).
pub const MD5_PASSWD_LEN: usize = 35;

/// Compute the MD5 hash of `buff` as a hex string. Err carries the error text.
pub fn pg_md5_hash(buff: &[u8]) -> Result<String, String> {
    let _ = buff;
    unimplemented!()
}

/// Compute the raw MD5 digest of `buff`. Err carries the error text.
pub fn pg_md5_binary(buff: &[u8]) -> Result<[u8; MD5_DIGEST_LENGTH], String> {
    let _ = buff;
    unimplemented!()
}

/// Build an "md5..." encrypted password from passwd + salt. Err carries error text.
pub fn pg_md5_encrypt(passwd: &str, salt: &[u8]) -> Result<String, String> {
    let _ = (passwd, salt);
    unimplemented!()
}
