/*-------------------------------------------------------------------------
 *
 *	md5.c
 *	  Implements the MD5 Message-Digest Algorithm
 *
 * Fallback implementation of MD5, as specified in RFC 1321.  This
 * implementation is a simple one, in that it needs every input byte
 * to be buffered before doing any calculations.
 *
 *	Portions Copyright (c) 1996-2025, PostgreSQL Global Development Group
 *	Portions Copyright (c) 1994, Regents of the University of California
 *
 * IDENTIFICATION
 *	  src/common/md5.c
 *
 *-------------------------------------------------------------------------
 */

// Combined translation of:
//   PUBLIC HEADER:   src/include/common/md5.h
//   INTERNAL HEADER: src/common/md5_int.h
//   IMPLEMENTATION:  src/common/md5.c
//
// This is the portable in-tree fallback implementation of MD5 (RFC 1321).
// MD5 is a LITTLE-ENDIAN algorithm.  We translate the BACKEND, NON-OPENSSL
// path; the C source has no USE_OPENSSL branch in these files (that lives in
// md5_common.c / the OpenSSL-backed implementation, which is a separate unit).
// The higher-level pg_md5_hash() / pg_md5_binary() / pg_md5_encrypt() routines
// from md5_common.c are NOT translated here, only their `extern` decls from
// md5.h are reproduced as comments for fidelity.
//
//    $KAME: md5.c,v 1.3 2000/02/22 14:01:17 itojun Exp $
//
// Copyright (C) 1995, 1996, 1997, and 1998 WIDE Project.
// All rights reserved.  (See the BSD-style license in the original md5.c /
// md5_int.h headers.)

#![allow(clippy::missing_safety_doc)]

use crate::prelude::*;

/* ---------------------------------------------------------------------------
 * From the public header src/include/common/md5.h
 * ------------------------------------------------------------------------- */

/* Size of result generated by MD5 computation */
pub const MD5_DIGEST_LENGTH: usize = 16;
/* Block size for MD5 */
pub const MD5_BLOCK_SIZE: usize = 64;

/* password-related data */
pub const MD5_PASSWD_CHARSET: &[u8] = b"0123456789abcdef";
pub const MD5_PASSWD_LEN: usize = 35;

/*
 * Utilities common to all the MD5 implementations, as of md5_common.c.
 * These are implemented in md5_common.c (a SEPARATE source file) and are only
 * declared here in C's md5.h.  They are intentionally NOT translated in this
 * module:
 *
 *   extern bool pg_md5_hash(const void *buff, size_t len, char *hexsum,
 *                           const char **errstr);
 *   extern bool pg_md5_binary(const void *buff, size_t len, uint8 *outbuf,
 *                             const char **errstr);
 *   extern bool pg_md5_encrypt(const char *passwd, const uint8 *salt,
 *                              size_t salt_len, char *buf,
 *                              const char **errstr);
 */

/* ---------------------------------------------------------------------------
 * From the internal header src/common/md5_int.h
 * ------------------------------------------------------------------------- */

pub const MD5_BUFLEN: usize = 64;

/*
 * Context data for MD5.
 *
 * The C struct uses two anonymous unions plus a flock of `#define` field
 * aliases (md5_sta/md5_stb/.../md5_st8 over md5_st, and md5_n/md5_n8 over
 * md5_count).  We reproduce the exact #[repr(C)] memory layout with two Rust
 * unions, and provide the aliases as #[inline] accessor helpers (named after
 * the C macros) so the implementation reads the same as the original C.
 *
 *	union {
 *		uint32	md5_state32[4];
 *		uint8	md5_state8[16];
 *	} md5_st;
 *	#define md5_sta md5_st.md5_state32[0]   ...etc
 *
 *	union {
 *		uint64	md5_count64;
 *		uint8	md5_count8[8];
 *	} md5_count;
 *	#define md5_n  md5_count.md5_count64
 *	#define md5_n8 md5_count.md5_count8
 */
#[repr(C)]
#[derive(Clone, Copy)]
pub union md5_st_union {
    pub md5_state32: [uint32; 4],
    pub md5_state8: [uint8; 16],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union md5_count_union {
    pub md5_count64: uint64,
    pub md5_count8: [uint8; 8],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct pg_md5_ctx {
    pub md5_st: md5_st_union,
    pub md5_count: md5_count_union,
    pub md5_i: c_uint,
    pub md5_buf: [uint8; MD5_BUFLEN],
}

/*
 * Field-alias accessors corresponding to the C preprocessor `#define`s:
 *   #define md5_sta md5_st.md5_state32[0]
 *   #define md5_stb md5_st.md5_state32[1]
 *   #define md5_stc md5_st.md5_state32[2]
 *   #define md5_std md5_st.md5_state32[3]
 *   #define md5_st8 md5_st.md5_state8
 *   #define md5_n   md5_count.md5_count64
 *   #define md5_n8  md5_count.md5_count8
 *
 * The unions make these unsafe (union field reads).
 */
impl pg_md5_ctx {
    #[inline]
    unsafe fn md5_sta(&self) -> uint32 {
        self.md5_st.md5_state32[0]
    }
    #[inline]
    unsafe fn md5_stb(&self) -> uint32 {
        self.md5_st.md5_state32[1]
    }
    #[inline]
    unsafe fn md5_stc(&self) -> uint32 {
        self.md5_st.md5_state32[2]
    }
    #[inline]
    unsafe fn md5_std(&self) -> uint32 {
        self.md5_st.md5_state32[3]
    }
    #[inline]
    unsafe fn set_md5_sta(&mut self, v: uint32) {
        self.md5_st.md5_state32[0] = v;
    }
    #[inline]
    unsafe fn set_md5_stb(&mut self, v: uint32) {
        self.md5_st.md5_state32[1] = v;
    }
    #[inline]
    unsafe fn set_md5_stc(&mut self, v: uint32) {
        self.md5_st.md5_state32[2] = v;
    }
    #[inline]
    unsafe fn set_md5_std(&mut self, v: uint32) {
        self.md5_st.md5_state32[3] = v;
    }
    /* md5_st8 -> the 16-byte view of the state */
    #[inline]
    unsafe fn md5_st8(&self) -> *const uint8 {
        self.md5_st.md5_state8.as_ptr()
    }
    /* md5_n -> the 64-bit bit-count */
    #[inline]
    unsafe fn md5_n(&self) -> uint64 {
        self.md5_count.md5_count64
    }
    #[inline]
    unsafe fn set_md5_n(&mut self, v: uint64) {
        self.md5_count.md5_count64 = v;
    }
    /* md5_n8 -> the 8-byte view of the bit-count */
    #[inline]
    unsafe fn md5_n8(&self) -> *const uint8 {
        self.md5_count.md5_count8.as_ptr()
    }
}

/*
 * Interface routines for MD5 (declared `extern` in md5_int.h):
 *   extern void pg_md5_init(pg_md5_ctx *ctx);
 *   extern void pg_md5_update(pg_md5_ctx *ctx, const uint8 *data, size_t len);
 *   extern void pg_md5_final(pg_md5_ctx *ctx, uint8 *dest);
 * They are defined below.
 */

/* ---------------------------------------------------------------------------
 * From the implementation src/common/md5.c
 * ------------------------------------------------------------------------- */

/*
 * #define SHIFT(X, s) (((X) << (s)) | ((X) >> (32 - (s))))
 *
 * This is a 32-bit left-rotate.  In C the shifts/OR wrap modulo 2^32; we use
 * rotate_left to get identical semantics without triggering Rust's debug
 * overflow checks.
 */
#[inline(always)]
fn SHIFT(x: uint32, s: u32) -> uint32 {
    x.rotate_left(s)
}

/*
 * #define F(X, Y, Z) (((X) & (Y)) | ((~X) & (Z)))
 * #define G(X, Y, Z) (((X) & (Z)) | ((Y) & (~Z)))
 * #define H(X, Y, Z) ((X) ^ (Y) ^ (Z))
 * #define I(X, Y, Z) ((Y) ^ ((X) | (~Z)))
 *
 * Bitwise-only; no arithmetic overflow possible, but kept as helpers.
 */
#[inline(always)]
fn F(x: uint32, y: uint32, z: uint32) -> uint32 {
    (x & y) | (!x & z)
}
#[inline(always)]
fn G(x: uint32, y: uint32, z: uint32) -> uint32 {
    (x & z) | (y & !z)
}
#[inline(always)]
fn H(x: uint32, y: uint32, z: uint32) -> uint32 {
    x ^ y ^ z
}
#[inline(always)]
fn I(x: uint32, y: uint32, z: uint32) -> uint32 {
    y ^ (x | !z)
}

/*
 * The four round macros.  Every `+` here adds 32-bit state words, the message
 * schedule X[k], and the sine table T[i]; in C these wrap modulo 2^32, so we
 * MUST use wrapping_add to avoid debug-build overflow panics.
 *
 * #define ROUND1(a, b, c, d, k, s, i) \
 * do { \
 *     (a) = (a) + F((b), (c), (d)) + X[(k)] + T[(i)]; \
 *     (a) = SHIFT((a), (s)); \
 *     (a) = (b) + (a); \
 * } while (0)
 * ... ROUND2 uses G, ROUND3 uses H, ROUND4 uses I.
 *
 * Implemented as macro_rules so the a/b/c/d identifiers (rotated each step,
 * as in the C call sequence) operate on the local A/B/C/D variables.  $X and
 * $T are the message schedule and sine table in scope.
 */
macro_rules! ROUND1 {
    ($a:expr, $b:expr, $c:expr, $d:expr, $k:expr, $s:expr, $i:expr, $X:expr, $T:expr) => {{
        $a = $a
            .wrapping_add(F($b, $c, $d))
            .wrapping_add($X[$k])
            .wrapping_add($T[$i]);
        $a = SHIFT($a, $s);
        $a = $b.wrapping_add($a);
    }};
}
macro_rules! ROUND2 {
    ($a:expr, $b:expr, $c:expr, $d:expr, $k:expr, $s:expr, $i:expr, $X:expr, $T:expr) => {{
        $a = $a
            .wrapping_add(G($b, $c, $d))
            .wrapping_add($X[$k])
            .wrapping_add($T[$i]);
        $a = SHIFT($a, $s);
        $a = $b.wrapping_add($a);
    }};
}
macro_rules! ROUND3 {
    ($a:expr, $b:expr, $c:expr, $d:expr, $k:expr, $s:expr, $i:expr, $X:expr, $T:expr) => {{
        $a = $a
            .wrapping_add(H($b, $c, $d))
            .wrapping_add($X[$k])
            .wrapping_add($T[$i]);
        $a = SHIFT($a, $s);
        $a = $b.wrapping_add($a);
    }};
}
macro_rules! ROUND4 {
    ($a:expr, $b:expr, $c:expr, $d:expr, $k:expr, $s:expr, $i:expr, $X:expr, $T:expr) => {{
        $a = $a
            .wrapping_add(I($b, $c, $d))
            .wrapping_add($X[$k])
            .wrapping_add($T[$i]);
        $a = SHIFT($a, $s);
        $a = $b.wrapping_add($a);
    }};
}

/* Per-round shift amounts. */
const Sa: u32 = 7;
const Sb: u32 = 12;
const Sc: u32 = 17;
const Sd: u32 = 22;

const Se: u32 = 5;
const Sf: u32 = 9;
const Sg: u32 = 14;
const Sh: u32 = 20;

const Si: u32 = 4;
const Sj: u32 = 11;
const Sk: u32 = 16;
const Sl: u32 = 23;

const Sm: u32 = 6;
const Sn: u32 = 10;
const So: u32 = 15;
const Sp: u32 = 21;

const MD5_A0: uint32 = 0x67452301;
const MD5_B0: uint32 = 0xefcdab89;
const MD5_C0: uint32 = 0x98badcfe;
const MD5_D0: uint32 = 0x10325476;

/* Integer part of 4294967296 times abs(sin(i)), where i is in radians. */
static T: [uint32; 65] = [
    0,
    0xd76aa478, 0xe8c7b756, 0x242070db, 0xc1bdceee,
    0xf57c0faf, 0x4787c62a, 0xa8304613, 0xfd469501,
    0x698098d8, 0x8b44f7af, 0xffff5bb1, 0x895cd7be,
    0x6b901122, 0xfd987193, 0xa679438e, 0x49b40821,

    0xf61e2562, 0xc040b340, 0x265e5a51, 0xe9b6c7aa,
    0xd62f105d, 0x2441453, 0xd8a1e681, 0xe7d3fbc8,
    0x21e1cde6, 0xc33707d6, 0xf4d50d87, 0x455a14ed,
    0xa9e3e905, 0xfcefa3f8, 0x676f02d9, 0x8d2a4c8a,

    0xfffa3942, 0x8771f681, 0x6d9d6122, 0xfde5380c,
    0xa4beea44, 0x4bdecfa9, 0xf6bb4b60, 0xbebfbc70,
    0x289b7ec6, 0xeaa127fa, 0xd4ef3085, 0x4881d05,
    0xd9d4d039, 0xe6db99e5, 0x1fa27cf8, 0xc4ac5665,

    0xf4292244, 0x432aff97, 0xab9423a7, 0xfc93a039,
    0x655b59c3, 0x8f0ccc92, 0xffeff47d, 0x85845dd1,
    0x6fa87e4f, 0xfe2ce6e0, 0xa3014314, 0x4e0811a1,
    0xf7537e82, 0xbd3af235, 0x2ad7d2bb, 0xeb86d391,
];

static md5_paddat: [uint8; MD5_BUFLEN] = [
    0x80, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
];

unsafe fn md5_calc(b64: *const uint8, ctx: *mut pg_md5_ctx) {
    let mut A: uint32 = (*ctx).md5_sta();
    let mut B: uint32 = (*ctx).md5_stb();
    let mut C: uint32 = (*ctx).md5_stc();
    let mut D: uint32 = (*ctx).md5_std();

    /*
     * #ifndef WORDS_BIGENDIAN
     *     const uint32 *X = (const uint32 *) b64;
     *
     * LITTLE-ENDIAN path: reinterpret the 64-byte block as 16 little-endian
     * 32-bit words.  b64 is not guaranteed 4-byte aligned (it can be `data + i`
     * from a caller's buffer), so we read each word with an unaligned little-
     * endian load instead of forming a `*const uint32` (which would require
     * alignment).  This is equivalent to the C reinterpret on a little-endian
     * host with relaxed alignment.
     *
     * TODO(pg-port): the #ifdef WORDS_BIGENDIAN branch (byte-swapping b64 into
     * a local uint32 X[16]) is not translated; PepperDB targets little-endian.
     */
    let mut X: [uint32; 16] = [0; 16];
    {
        let mut idx = 0usize;
        while idx < 16 {
            let off = idx * 4;
            X[idx] = (*b64.add(off) as uint32)
                | ((*b64.add(off + 1) as uint32) << 8)
                | ((*b64.add(off + 2) as uint32) << 16)
                | ((*b64.add(off + 3) as uint32) << 24);
            idx += 1;
        }
    }

    ROUND1!(A, B, C, D, 0, Sa, 1, X, T);
    ROUND1!(D, A, B, C, 1, Sb, 2, X, T);
    ROUND1!(C, D, A, B, 2, Sc, 3, X, T);
    ROUND1!(B, C, D, A, 3, Sd, 4, X, T);
    ROUND1!(A, B, C, D, 4, Sa, 5, X, T);
    ROUND1!(D, A, B, C, 5, Sb, 6, X, T);
    ROUND1!(C, D, A, B, 6, Sc, 7, X, T);
    ROUND1!(B, C, D, A, 7, Sd, 8, X, T);
    ROUND1!(A, B, C, D, 8, Sa, 9, X, T);
    ROUND1!(D, A, B, C, 9, Sb, 10, X, T);
    ROUND1!(C, D, A, B, 10, Sc, 11, X, T);
    ROUND1!(B, C, D, A, 11, Sd, 12, X, T);
    ROUND1!(A, B, C, D, 12, Sa, 13, X, T);
    ROUND1!(D, A, B, C, 13, Sb, 14, X, T);
    ROUND1!(C, D, A, B, 14, Sc, 15, X, T);
    ROUND1!(B, C, D, A, 15, Sd, 16, X, T);

    ROUND2!(A, B, C, D, 1, Se, 17, X, T);
    ROUND2!(D, A, B, C, 6, Sf, 18, X, T);
    ROUND2!(C, D, A, B, 11, Sg, 19, X, T);
    ROUND2!(B, C, D, A, 0, Sh, 20, X, T);
    ROUND2!(A, B, C, D, 5, Se, 21, X, T);
    ROUND2!(D, A, B, C, 10, Sf, 22, X, T);
    ROUND2!(C, D, A, B, 15, Sg, 23, X, T);
    ROUND2!(B, C, D, A, 4, Sh, 24, X, T);
    ROUND2!(A, B, C, D, 9, Se, 25, X, T);
    ROUND2!(D, A, B, C, 14, Sf, 26, X, T);
    ROUND2!(C, D, A, B, 3, Sg, 27, X, T);
    ROUND2!(B, C, D, A, 8, Sh, 28, X, T);
    ROUND2!(A, B, C, D, 13, Se, 29, X, T);
    ROUND2!(D, A, B, C, 2, Sf, 30, X, T);
    ROUND2!(C, D, A, B, 7, Sg, 31, X, T);
    ROUND2!(B, C, D, A, 12, Sh, 32, X, T);

    ROUND3!(A, B, C, D, 5, Si, 33, X, T);
    ROUND3!(D, A, B, C, 8, Sj, 34, X, T);
    ROUND3!(C, D, A, B, 11, Sk, 35, X, T);
    ROUND3!(B, C, D, A, 14, Sl, 36, X, T);
    ROUND3!(A, B, C, D, 1, Si, 37, X, T);
    ROUND3!(D, A, B, C, 4, Sj, 38, X, T);
    ROUND3!(C, D, A, B, 7, Sk, 39, X, T);
    ROUND3!(B, C, D, A, 10, Sl, 40, X, T);
    ROUND3!(A, B, C, D, 13, Si, 41, X, T);
    ROUND3!(D, A, B, C, 0, Sj, 42, X, T);
    ROUND3!(C, D, A, B, 3, Sk, 43, X, T);
    ROUND3!(B, C, D, A, 6, Sl, 44, X, T);
    ROUND3!(A, B, C, D, 9, Si, 45, X, T);
    ROUND3!(D, A, B, C, 12, Sj, 46, X, T);
    ROUND3!(C, D, A, B, 15, Sk, 47, X, T);
    ROUND3!(B, C, D, A, 2, Sl, 48, X, T);

    ROUND4!(A, B, C, D, 0, Sm, 49, X, T);
    ROUND4!(D, A, B, C, 7, Sn, 50, X, T);
    ROUND4!(C, D, A, B, 14, So, 51, X, T);
    ROUND4!(B, C, D, A, 5, Sp, 52, X, T);
    ROUND4!(A, B, C, D, 12, Sm, 53, X, T);
    ROUND4!(D, A, B, C, 3, Sn, 54, X, T);
    ROUND4!(C, D, A, B, 10, So, 55, X, T);
    ROUND4!(B, C, D, A, 1, Sp, 56, X, T);
    ROUND4!(A, B, C, D, 8, Sm, 57, X, T);
    ROUND4!(D, A, B, C, 15, Sn, 58, X, T);
    ROUND4!(C, D, A, B, 6, So, 59, X, T);
    ROUND4!(B, C, D, A, 13, Sp, 60, X, T);
    ROUND4!(A, B, C, D, 4, Sm, 61, X, T);
    ROUND4!(D, A, B, C, 11, Sn, 62, X, T);
    ROUND4!(C, D, A, B, 2, So, 63, X, T);
    ROUND4!(B, C, D, A, 9, Sp, 64, X, T);

    /* All four add-backs wrap modulo 2^32. */
    let nsta = (*ctx).md5_sta().wrapping_add(A);
    let nstb = (*ctx).md5_stb().wrapping_add(B);
    let nstc = (*ctx).md5_stc().wrapping_add(C);
    let nstd = (*ctx).md5_std().wrapping_add(D);
    (*ctx).set_md5_sta(nsta);
    (*ctx).set_md5_stb(nstb);
    (*ctx).set_md5_stc(nstc);
    (*ctx).set_md5_std(nstd);
}

unsafe fn md5_pad(ctx: *mut pg_md5_ctx) {
    let gap: c_uint;

    /* Don't count up padding. Keep md5_n. */
    gap = MD5_BUFLEN as c_uint - (*ctx).md5_i;
    if gap > 8 {
        /*
         * memmove(ctx->md5_buf + ctx->md5_i, md5_paddat,
         *         gap - sizeof(ctx->md5_n));
         * sizeof(ctx->md5_n) == sizeof(uint64) == 8.
         */
        core::ptr::copy(
            md5_paddat.as_ptr(),
            (*ctx).md5_buf.as_mut_ptr().add((*ctx).md5_i as usize),
            gap as usize - core::mem::size_of::<uint64>(),
        );
    } else {
        /* including gap == 8 */
        core::ptr::copy(
            md5_paddat.as_ptr(),
            (*ctx).md5_buf.as_mut_ptr().add((*ctx).md5_i as usize),
            gap as usize,
        );
        md5_calc((*ctx).md5_buf.as_ptr(), ctx);
        core::ptr::copy(
            md5_paddat.as_ptr().add(gap as usize),
            (*ctx).md5_buf.as_mut_ptr(),
            MD5_BUFLEN - core::mem::size_of::<uint64>(),
        );
    }

    /* 8 byte word */
    /*
     * #ifndef WORDS_BIGENDIAN
     *     memmove(&ctx->md5_buf[56], &ctx->md5_n8[0], 8);
     *
     * LITTLE-ENDIAN path: append the bit count, little-endian, into the last
     * 8 bytes of the block.
     *
     * TODO(pg-port): the #ifdef WORDS_BIGENDIAN branch (byte-reversed copy of
     * md5_n8) is not translated; PepperDB targets little-endian.
     */
    core::ptr::copy_nonoverlapping(
        (*ctx).md5_n8(),
        (*ctx).md5_buf.as_mut_ptr().add(56),
        8,
    );

    md5_calc((*ctx).md5_buf.as_ptr(), ctx);
}

unsafe fn md5_result(digest: *mut uint8, ctx: *const pg_md5_ctx) {
    /* 4 byte words */
    /*
     * #ifndef WORDS_BIGENDIAN
     *     memmove(digest, &ctx->md5_st8[0], 16);
     *
     * LITTLE-ENDIAN path: the state words are already stored little-endian in
     * md5_st8, so a straight copy of 16 bytes produces the digest.
     *
     * TODO(pg-port): the #ifdef WORDS_BIGENDIAN branch (byte-reversed copy of
     * md5_st8) is not translated; PepperDB targets little-endian.
     */
    core::ptr::copy_nonoverlapping((*ctx).md5_st8(), digest, 16);
}


/* External routines for this MD5 implementation */

/*
 * pg_md5_init
 *
 * Initialize a MD5 context.
 */
pub unsafe fn pg_md5_init(ctx: *mut pg_md5_ctx) {
    (*ctx).set_md5_n(0);
    (*ctx).md5_i = 0;
    (*ctx).set_md5_sta(MD5_A0);
    (*ctx).set_md5_stb(MD5_B0);
    (*ctx).set_md5_stc(MD5_C0);
    (*ctx).set_md5_std(MD5_D0);
    core::ptr::write_bytes((*ctx).md5_buf.as_mut_ptr(), 0, (*ctx).md5_buf.len());
}


/*
 * pg_md5_update
 *
 * Update a MD5 context.
 */
pub unsafe fn pg_md5_update(ctx: *mut pg_md5_ctx, data: *const uint8, len: Size) {
    let gap: c_uint;
    let mut i: c_uint;

    let new_n = (*ctx).md5_n().wrapping_add((len as uint64) * 8); /* byte to bit */
    (*ctx).set_md5_n(new_n);
    gap = MD5_BUFLEN as c_uint - (*ctx).md5_i;

    if len >= gap as Size {
        core::ptr::copy(
            data,
            (*ctx).md5_buf.as_mut_ptr().add((*ctx).md5_i as usize),
            gap as usize,
        );
        md5_calc((*ctx).md5_buf.as_ptr(), ctx);

        i = gap;
        while i as Size + MD5_BUFLEN as Size <= len {
            md5_calc(data.add(i as usize), ctx);
            i += MD5_BUFLEN as c_uint;
        }

        (*ctx).md5_i = (len - i as Size) as c_uint;
        core::ptr::copy(
            data.add(i as usize),
            (*ctx).md5_buf.as_mut_ptr(),
            (*ctx).md5_i as usize,
        );
    } else {
        core::ptr::copy(
            data,
            (*ctx).md5_buf.as_mut_ptr().add((*ctx).md5_i as usize),
            len as usize,
        );
        (*ctx).md5_i += len as c_uint;
    }
}

/*
 * pg_md5_final
 *
 * Finalize a MD5 context.
 */
pub unsafe fn pg_md5_final(ctx: *mut pg_md5_ctx, dest: *mut uint8) {
    md5_pad(ctx);
    md5_result(dest, ctx);
}

#[cfg(test)]
mod tests {
    use super::*;

    /* Run the full init/update/final pipeline over `input`, return the digest. */
    unsafe fn md5_of(input: &[u8]) -> [u8; 16] {
        let mut ctx: pg_md5_ctx = core::mem::zeroed();
        pg_md5_init(&mut ctx);
        pg_md5_update(&mut ctx, input.as_ptr(), input.len() as Size);
        let mut out = [0u8; 16];
        pg_md5_final(&mut ctx, out.as_mut_ptr());
        out
    }

    fn hex(d: &[u8; 16]) -> String {
        let mut s = String::with_capacity(32);
        for b in d {
            s.push_str(&format!("{:02x}", b));
        }
        s
    }

    /* RFC 1321 / standard MD5 test vectors. */
    #[test]
    fn rfc1321_vectors() {
        unsafe {
            assert_eq!(hex(&md5_of(b"")), "d41d8cd98f00b204e9800998ecf8427e");
            assert_eq!(hex(&md5_of(b"a")), "0cc175b9c0f1b6a831c399e269772661");
            assert_eq!(hex(&md5_of(b"abc")), "900150983cd24fb0d6963f7d28e17f72");
            assert_eq!(
                hex(&md5_of(b"message digest")),
                "f96b697d7cb7938d525a2f31aaf161d0"
            );
            assert_eq!(
                hex(&md5_of(b"abcdefghijklmnopqrstuvwxyz")),
                "c3fcd3d76192e4007dfb496cca67e13b"
            );
            assert_eq!(
                hex(&md5_of(
                    b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
                )),
                "d174ab98d277d9f5a5611c2c9f419d9f"
            );
            assert_eq!(
                hex(&md5_of(
                    b"12345678901234567890123456789012345678901234567890123456789012345678901234567890"
                )),
                "57edf4a22be3c955ac49da2e2107b67a"
            );
        }
    }

    /* Exercise the multi-block / streaming update path with a long input that
     * crosses several 64-byte boundaries and a non-aligned residue. */
    #[test]
    fn long_input_streaming() {
        unsafe {
            let input = vec![b'x'; 1000];
            // Reference value computed by the well-known MD5 of 1000 'x' bytes.
            let one_shot = md5_of(&input);

            // Feed the same data in awkward chunk sizes to exercise buffering.
            let mut ctx: pg_md5_ctx = core::mem::zeroed();
            pg_md5_init(&mut ctx);
            let chunks = [1usize, 7, 56, 64, 65, 100, 200, 507];
            let mut off = 0usize;
            for &c in chunks.iter() {
                let n = c.min(input.len() - off);
                pg_md5_update(&mut ctx, input.as_ptr().add(off), n as Size);
                off += n;
            }
            // remainder
            if off < input.len() {
                pg_md5_update(&mut ctx, input.as_ptr().add(off), (input.len() - off) as Size);
            }
            let mut streamed = [0u8; 16];
            pg_md5_final(&mut ctx, streamed.as_mut_ptr());
            assert_eq!(streamed, one_shot);
        }
    }
}

#[cfg(test)]
mod kat_tests {
    use super::*;
    fn hex(b: &[u8]) -> String { b.iter().map(|x| format!("{:02x}", x)).collect() }
    #[test]
    fn md5_known_answer() {
        unsafe {
            let mut ctx: pg_md5_ctx = core::mem::zeroed();
            pg_md5_init(&mut ctx);
            let msg = b"abc";
            pg_md5_update(&mut ctx, msg.as_ptr(), msg.len() as Size);
            let mut out = [0u8; 16];
            pg_md5_final(&mut ctx, out.as_mut_ptr());
            assert_eq!(hex(&out), "900150983cd24fb0d6963f7d28e17f72");
        }
    }
}
