//! Translated from PostgreSQL src/include/common/sha1.h

/// Size of result generated by SHA1 computation.
pub const SHA1_DIGEST_LENGTH: usize = 20;
/// Block size for SHA1.
pub const SHA1_BLOCK_SIZE: usize = 64;
