/*-------------------------------------------------------------------------
 *
 *	sha1.c
 *	  Implements the SHA1 Secure Hash Algorithm
 *
 * Fallback implementation of SHA1, as specified in RFC 3174.
 *
 * Portions Copyright (c) 1996-2025, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * IDENTIFICATION
 *	  src/common/sha1.c
 *
 *-------------------------------------------------------------------------
 */

// Combined translation of:
//   PUBLIC HEADER:   src/include/common/sha1.h
//   INTERNAL HEADER: src/common/sha1_int.h
//   IMPL:            src/common/sha1.c
//
// sha1.h
//	  Constants related to SHA1.
//
// sha1_int.h
//	  Internal headers for fallback implementation of SHA1.
//
// $KAME: sha1.c,v 1.3 2000/02/22 14:01:18 itojun Exp $
//
// Copyright (C) 1995, 1996, 1997, and 1998 WIDE Project.
// All rights reserved. (BSD-3 license; full text retained in the original C
// source headers.)
//
// FIPS pub 180-1: Secure Hash Algorithm (SHA-1)
// based on: http://www.itl.nist.gov/fipspubs/fip180-1.htm
// implemented by Jun-ichiro itojun Itoh <itojun@itojun.org>
//
// Porting notes:
//   - The C compiles either the backend (postgres.h) or frontend (postgres_fe.h)
//     path; we translate the BACKEND path. There is no error reporting in this
//     module, so the distinction is cosmetic here.
//   - PostgreSQL defines WORDS_BIGENDIAN only on big-endian targets. The common
//     x86/ARM build is little-endian, so the active translation is the
//     `#ifndef WORDS_BIGENDIAN` / `#else` (little-endian) branches. The
//     big-endian branches are preserved as comments and marked TODO(pg-port).
//   - The 80-round compression does heavy 32-bit additions and rotations that
//     overflow a u32; we use wrapping_add and rotate_left to match C's modular
//     unsigned arithmetic.

#![allow(clippy::missing_safety_doc)]

use crate::prelude::*;

// #ifndef FRONTEND
// #include "postgres.h"
// #else
// #include "postgres_fe.h"
// #endif
// TODO(pg-port): FRONTEND branch (postgres_fe.h) not ported; backend path active.
//
// #include <sys/param.h>
// #include "sha1_int.h"

/*
 * sha1.h --- Constants related to SHA1.
 */

/* Size of result generated by SHA1 computation */
pub const SHA1_DIGEST_LENGTH: usize = 20;
/* Block size for SHA1 */
pub const SHA1_BLOCK_SIZE: usize = 64;

/*
 * sha1_int.h --- pg_sha1_ctx.
 *
 * The C type uses three anonymous unions:
 *   h: { uint8 b8[20]; uint32 b32[5]; }   -- the running state words
 *   c: { uint8 b8[8];  uint64 b64[1]; }   -- the bit count
 *   m: { uint8 b8[64]; uint32 b32[16]; }  -- the message block
 *
 * Rust does not have C-style anonymous unions over differently typed views of
 * the same storage, so each union is represented as a fixed-size byte array and
 * the word views (b32 / b64) are reconstructed via helper accessors that read
 * and write the bytes in native (host) order, exactly matching the aliasing the
 * C code relies on.
 */
#[repr(C)]
#[derive(Clone, Copy)]
pub struct pg_sha1_ctx {
    pub h: [uint8; 20], /* union { uint8 b8[20]; uint32 b32[5]; } h; */
    pub c: [uint8; 8],  /* union { uint8 b8[8];  uint64 b64[1]; } c; */
    pub m: [uint8; 64], /* union { uint8 b8[64]; uint32 b32[16]; } m; */
    pub count: uint8,
}

// ---------------------------------------------------------------------------
// Native-order word accessors over the union byte storage.
//
// In C, `ctx->h.b32[n]` reads/writes 4 bytes of `h` interpreted as a uint32 in
// host byte order; `ctx->c.b64[0]` does the same with 8 bytes as a uint64; and
// `ctx->m.b32[n]` with 4 bytes of `m`. These helpers replicate that aliasing
// using native-endian packing so behavior matches the host the C compiles for.
// ---------------------------------------------------------------------------

#[inline]
unsafe fn h_get(ctx: *const pg_sha1_ctx, n: usize) -> uint32 {
    let base = (*ctx).h.as_ptr().add(n * 4);
    let mut bytes = [0u8; 4];
    core::ptr::copy_nonoverlapping(base, bytes.as_mut_ptr(), 4);
    uint32::from_ne_bytes(bytes)
}

#[inline]
unsafe fn h_set(ctx: *mut pg_sha1_ctx, n: usize, val: uint32) {
    let base = (*ctx).h.as_mut_ptr().add(n * 4);
    let bytes = val.to_ne_bytes();
    core::ptr::copy_nonoverlapping(bytes.as_ptr(), base, 4);
}

#[inline]
unsafe fn w_get(ctx: *const pg_sha1_ctx, n: usize) -> uint32 {
    let base = (*ctx).m.as_ptr().add(n * 4);
    let mut bytes = [0u8; 4];
    core::ptr::copy_nonoverlapping(base, bytes.as_mut_ptr(), 4);
    uint32::from_ne_bytes(bytes)
}

#[inline]
unsafe fn w_set(ctx: *mut pg_sha1_ctx, n: usize, val: uint32) {
    let base = (*ctx).m.as_mut_ptr().add(n * 4);
    let bytes = val.to_ne_bytes();
    core::ptr::copy_nonoverlapping(bytes.as_ptr(), base, 4);
}

#[inline]
unsafe fn bcount_get(ctx: *const pg_sha1_ctx) -> uint64 {
    let mut bytes = [0u8; 8];
    core::ptr::copy_nonoverlapping((*ctx).c.as_ptr(), bytes.as_mut_ptr(), 8);
    uint64::from_ne_bytes(bytes)
}

#[inline]
unsafe fn bcount_add(ctx: *mut pg_sha1_ctx, add: uint64) {
    let cur = bcount_get(ctx);
    let bytes = cur.wrapping_add(add).to_ne_bytes();
    core::ptr::copy_nonoverlapping(bytes.as_ptr(), (*ctx).c.as_mut_ptr(), 8);
}

/* constant table */
static _K: [uint32; 4] = [0x5a827999, 0x6ed9eba1, 0x8f1bbcdc, 0xca62c1d6];

/* #define K(t)	_K[(t) / 20] */
#[inline]
fn K(t: usize) -> uint32 {
    _K[t / 20]
}

/* #define F0(b, c, d) (((b) & (c)) | ((~(b)) & (d))) */
#[inline]
fn F0(b: uint32, c: uint32, d: uint32) -> uint32 {
    (b & c) | ((!b) & d)
}
/* #define F1(b, c, d) (((b) ^ (c)) ^ (d)) */
#[inline]
fn F1(b: uint32, c: uint32, d: uint32) -> uint32 {
    (b ^ c) ^ d
}
/* #define F2(b, c, d) (((b) & (c)) | ((b) & (d)) | ((c) & (d))) */
#[inline]
fn F2(b: uint32, c: uint32, d: uint32) -> uint32 {
    (b & c) | (b & d) | (c & d)
}
/* #define F3(b, c, d) (((b) ^ (c)) ^ (d)) */
#[inline]
fn F3(b: uint32, c: uint32, d: uint32) -> uint32 {
    (b ^ c) ^ d
}

/*
 * #define S(n, x)		(((x) << (n)) | ((x) >> (32 - (n))))
 *
 * A 32-bit left rotate.  This overflows a u32 in Rust's debug arithmetic, so it
 * maps to rotate_left.
 */
#[inline]
fn S(n: u32, x: uint32) -> uint32 {
    x.rotate_left(n)
}

/*
 * #define H(n)	(ctx->h.b32[(n)])   -> h_get / h_set
 * #define COUNT	(ctx->count)        -> (*ctx).count
 * #define BCOUNT	(ctx->c.b64[0] / 8) -> bcount_get(ctx) / 8 (unused below)
 * #define W(n)	(ctx->m.b32[(n)])   -> w_get / w_set
 */

/*
 * #define PUTPAD(x) \
 * do { \
 *     ctx->m.b8[(COUNT % 64)] = (x);		\
 *     COUNT++;				\
 *     COUNT %= 64;				\
 *     if (COUNT % 64 == 0)			\
 *         sha1_step(ctx);		\
 * } while (0)
 */
#[inline]
unsafe fn PUTPAD(ctx: *mut pg_sha1_ctx, x: uint8) {
    (*ctx).m[((*ctx).count % 64) as usize] = x;
    (*ctx).count = (*ctx).count.wrapping_add(1);
    (*ctx).count %= 64;
    if (*ctx).count % 64 == 0 {
        sha1_step(ctx);
    }
}

unsafe fn sha1_step(ctx: *mut pg_sha1_ctx) {
    let a: uint32;
    let mut b: uint32;
    let mut c: uint32;
    let mut d: uint32;
    let mut e: uint32;
    let mut t: usize;
    let mut s: usize;
    let mut tmp: uint32;

    // #ifndef WORDS_BIGENDIAN  (little-endian, active path)
    //
    // Byte-swap each of the sixteen 32-bit words of the message block in place,
    // so that the host-order b32 view sees the big-endian message words SHA-1
    // operates on.
    {
        let mut tctx = pg_sha1_ctx {
            h: [0; 20],
            c: [0; 8],
            m: [0; 64],
            count: 0,
        };

        core::ptr::copy(
            (*ctx).m.as_ptr(),
            tctx.m.as_mut_ptr(),
            64,
        );
        (*ctx).m[0] = tctx.m[3];
        (*ctx).m[1] = tctx.m[2];
        (*ctx).m[2] = tctx.m[1];
        (*ctx).m[3] = tctx.m[0];
        (*ctx).m[4] = tctx.m[7];
        (*ctx).m[5] = tctx.m[6];
        (*ctx).m[6] = tctx.m[5];
        (*ctx).m[7] = tctx.m[4];
        (*ctx).m[8] = tctx.m[11];
        (*ctx).m[9] = tctx.m[10];
        (*ctx).m[10] = tctx.m[9];
        (*ctx).m[11] = tctx.m[8];
        (*ctx).m[12] = tctx.m[15];
        (*ctx).m[13] = tctx.m[14];
        (*ctx).m[14] = tctx.m[13];
        (*ctx).m[15] = tctx.m[12];
        (*ctx).m[16] = tctx.m[19];
        (*ctx).m[17] = tctx.m[18];
        (*ctx).m[18] = tctx.m[17];
        (*ctx).m[19] = tctx.m[16];
        (*ctx).m[20] = tctx.m[23];
        (*ctx).m[21] = tctx.m[22];
        (*ctx).m[22] = tctx.m[21];
        (*ctx).m[23] = tctx.m[20];
        (*ctx).m[24] = tctx.m[27];
        (*ctx).m[25] = tctx.m[26];
        (*ctx).m[26] = tctx.m[25];
        (*ctx).m[27] = tctx.m[24];
        (*ctx).m[28] = tctx.m[31];
        (*ctx).m[29] = tctx.m[30];
        (*ctx).m[30] = tctx.m[29];
        (*ctx).m[31] = tctx.m[28];
        (*ctx).m[32] = tctx.m[35];
        (*ctx).m[33] = tctx.m[34];
        (*ctx).m[34] = tctx.m[33];
        (*ctx).m[35] = tctx.m[32];
        (*ctx).m[36] = tctx.m[39];
        (*ctx).m[37] = tctx.m[38];
        (*ctx).m[38] = tctx.m[37];
        (*ctx).m[39] = tctx.m[36];
        (*ctx).m[40] = tctx.m[43];
        (*ctx).m[41] = tctx.m[42];
        (*ctx).m[42] = tctx.m[41];
        (*ctx).m[43] = tctx.m[40];
        (*ctx).m[44] = tctx.m[47];
        (*ctx).m[45] = tctx.m[46];
        (*ctx).m[46] = tctx.m[45];
        (*ctx).m[47] = tctx.m[44];
        (*ctx).m[48] = tctx.m[51];
        (*ctx).m[49] = tctx.m[50];
        (*ctx).m[50] = tctx.m[49];
        (*ctx).m[51] = tctx.m[48];
        (*ctx).m[52] = tctx.m[55];
        (*ctx).m[53] = tctx.m[54];
        (*ctx).m[54] = tctx.m[53];
        (*ctx).m[55] = tctx.m[52];
        (*ctx).m[56] = tctx.m[59];
        (*ctx).m[57] = tctx.m[58];
        (*ctx).m[58] = tctx.m[57];
        (*ctx).m[59] = tctx.m[56];
        (*ctx).m[60] = tctx.m[63];
        (*ctx).m[61] = tctx.m[62];
        (*ctx).m[62] = tctx.m[61];
        (*ctx).m[63] = tctx.m[60];
    }
    // #endif  (on WORDS_BIGENDIAN the block is already in the right order)
    // TODO(pg-port): big-endian (WORDS_BIGENDIAN) build skips the swap above.

    let mut a_var = h_get(ctx, 0);
    b = h_get(ctx, 1);
    c = h_get(ctx, 2);
    d = h_get(ctx, 3);
    e = h_get(ctx, 4);

    t = 0;
    while t < 20 {
        s = t & 0x0f;
        if t >= 16 {
            w_set(
                ctx,
                s,
                S(
                    1,
                    w_get(ctx, (s + 13) & 0x0f)
                        ^ w_get(ctx, (s + 8) & 0x0f)
                        ^ w_get(ctx, (s + 2) & 0x0f)
                        ^ w_get(ctx, s),
                ),
            );
        }
        tmp = S(5, a_var)
            .wrapping_add(F0(b, c, d))
            .wrapping_add(e)
            .wrapping_add(w_get(ctx, s))
            .wrapping_add(K(t));
        e = d;
        d = c;
        c = S(30, b);
        b = a_var;
        a_var = tmp;
        t += 1;
    }
    t = 20;
    while t < 40 {
        s = t & 0x0f;
        w_set(
            ctx,
            s,
            S(
                1,
                w_get(ctx, (s + 13) & 0x0f)
                    ^ w_get(ctx, (s + 8) & 0x0f)
                    ^ w_get(ctx, (s + 2) & 0x0f)
                    ^ w_get(ctx, s),
            ),
        );
        tmp = S(5, a_var)
            .wrapping_add(F1(b, c, d))
            .wrapping_add(e)
            .wrapping_add(w_get(ctx, s))
            .wrapping_add(K(t));
        e = d;
        d = c;
        c = S(30, b);
        b = a_var;
        a_var = tmp;
        t += 1;
    }
    t = 40;
    while t < 60 {
        s = t & 0x0f;
        w_set(
            ctx,
            s,
            S(
                1,
                w_get(ctx, (s + 13) & 0x0f)
                    ^ w_get(ctx, (s + 8) & 0x0f)
                    ^ w_get(ctx, (s + 2) & 0x0f)
                    ^ w_get(ctx, s),
            ),
        );
        tmp = S(5, a_var)
            .wrapping_add(F2(b, c, d))
            .wrapping_add(e)
            .wrapping_add(w_get(ctx, s))
            .wrapping_add(K(t));
        e = d;
        d = c;
        c = S(30, b);
        b = a_var;
        a_var = tmp;
        t += 1;
    }
    t = 60;
    while t < 80 {
        s = t & 0x0f;
        w_set(
            ctx,
            s,
            S(
                1,
                w_get(ctx, (s + 13) & 0x0f)
                    ^ w_get(ctx, (s + 8) & 0x0f)
                    ^ w_get(ctx, (s + 2) & 0x0f)
                    ^ w_get(ctx, s),
            ),
        );
        tmp = S(5, a_var)
            .wrapping_add(F3(b, c, d))
            .wrapping_add(e)
            .wrapping_add(w_get(ctx, s))
            .wrapping_add(K(t));
        e = d;
        d = c;
        c = S(30, b);
        b = a_var;
        a_var = tmp;
        t += 1;
    }

    a = a_var;

    h_set(ctx, 0, h_get(ctx, 0).wrapping_add(a));
    h_set(ctx, 1, h_get(ctx, 1).wrapping_add(b));
    h_set(ctx, 2, h_get(ctx, 2).wrapping_add(c));
    h_set(ctx, 3, h_get(ctx, 3).wrapping_add(d));
    h_set(ctx, 4, h_get(ctx, 4).wrapping_add(e));

    core::ptr::write_bytes((*ctx).m.as_mut_ptr(), 0, 64);
}

unsafe fn sha1_pad(ctx: *mut pg_sha1_ctx) {
    let mut padlen: usize; /* pad length in bytes */
    let mut padstart: usize;

    PUTPAD(ctx, 0x80);

    padstart = ((*ctx).count % 64) as usize;
    padlen = 64 - padstart;
    if padlen < 8 {
        core::ptr::write_bytes((*ctx).m.as_mut_ptr().add(padstart), 0, padlen);
        (*ctx).count = (*ctx).count.wrapping_add(padlen as uint8);
        (*ctx).count %= 64;
        sha1_step(ctx);
        padstart = ((*ctx).count % 64) as usize; /* should be 0 */
        padlen = 64 - padstart; /* should be 64 */
    }
    core::ptr::write_bytes((*ctx).m.as_mut_ptr().add(padstart), 0, padlen - 8);
    (*ctx).count = (*ctx).count.wrapping_add((padlen - 8) as uint8);
    (*ctx).count %= 64;

    // #ifdef WORDS_BIGENDIAN
    //     PUTPAD(ctx->c.b8[0]); ... PUTPAD(ctx->c.b8[7]);
    // #else  (little-endian, active path)
    PUTPAD(ctx, (*ctx).c[7]);
    PUTPAD(ctx, (*ctx).c[6]);
    PUTPAD(ctx, (*ctx).c[5]);
    PUTPAD(ctx, (*ctx).c[4]);
    PUTPAD(ctx, (*ctx).c[3]);
    PUTPAD(ctx, (*ctx).c[2]);
    PUTPAD(ctx, (*ctx).c[1]);
    PUTPAD(ctx, (*ctx).c[0]);
    // #endif
    // TODO(pg-port): big-endian build emits c.b8[0..8] in forward order.
}

unsafe fn sha1_result(digest0: *mut uint8, ctx: *mut pg_sha1_ctx) {
    let digest: *mut uint8 = digest0;

    // #ifdef WORDS_BIGENDIAN
    //     memmove(digest, &ctx->h.b8[0], 20);
    // #else  (little-endian, active path)
    *digest.add(0) = (*ctx).h[3];
    *digest.add(1) = (*ctx).h[2];
    *digest.add(2) = (*ctx).h[1];
    *digest.add(3) = (*ctx).h[0];
    *digest.add(4) = (*ctx).h[7];
    *digest.add(5) = (*ctx).h[6];
    *digest.add(6) = (*ctx).h[5];
    *digest.add(7) = (*ctx).h[4];
    *digest.add(8) = (*ctx).h[11];
    *digest.add(9) = (*ctx).h[10];
    *digest.add(10) = (*ctx).h[9];
    *digest.add(11) = (*ctx).h[8];
    *digest.add(12) = (*ctx).h[15];
    *digest.add(13) = (*ctx).h[14];
    *digest.add(14) = (*ctx).h[13];
    *digest.add(15) = (*ctx).h[12];
    *digest.add(16) = (*ctx).h[19];
    *digest.add(17) = (*ctx).h[18];
    *digest.add(18) = (*ctx).h[17];
    *digest.add(19) = (*ctx).h[16];
    // #endif
    // TODO(pg-port): big-endian build copies h.b8[0..20] verbatim.
}

/* External routines for this SHA1 implementation */

/*
 * pg_sha1_init
 *
 * Initialize a SHA1 context.
 */
pub unsafe fn pg_sha1_init(ctx: *mut pg_sha1_ctx) {
    core::ptr::write_bytes(ctx, 0, 1); /* memset(ctx, 0, sizeof(pg_sha1_ctx)) */
    h_set(ctx, 0, 0x67452301);
    h_set(ctx, 1, 0xefcdab89);
    h_set(ctx, 2, 0x98badcfe);
    h_set(ctx, 3, 0x10325476);
    h_set(ctx, 4, 0xc3d2e1f0);
}

/*
 * pg_sha1_update
 *
 * Update a SHA1 context.
 */
pub unsafe fn pg_sha1_update(ctx: *mut pg_sha1_ctx, data: *const uint8, len: usize) {
    let input: *const uint8;
    let mut gaplen: usize;
    let mut gapstart: usize;
    let mut off: usize;
    let mut copysiz: usize;

    input = data;
    off = 0;

    while off < len {
        gapstart = ((*ctx).count % 64) as usize;
        gaplen = 64 - gapstart;

        copysiz = if gaplen < len - off { gaplen } else { len - off };
        core::ptr::copy(
            input.add(off),
            (*ctx).m.as_mut_ptr().add(gapstart),
            copysiz,
        );
        (*ctx).count = (*ctx).count.wrapping_add(copysiz as uint8);
        (*ctx).count %= 64;
        bcount_add(ctx, (copysiz as uint64) * 8);
        if (*ctx).count % 64 == 0 {
            sha1_step(ctx);
        }
        off += copysiz;
    }
}

/*
 * pg_sha1_final
 *
 * Finalize a SHA1 context.
 */
pub unsafe fn pg_sha1_final(ctx: *mut pg_sha1_ctx, dest: *mut uint8) {
    sha1_pad(ctx);
    sha1_result(dest, ctx);
}

#[cfg(test)]
mod tests {
    use super::*;
    fn hex(b: &[u8]) -> String { b.iter().map(|x| format!("{:02x}", x)).collect() }
    #[test]
    fn sha1_known_answer() {
        unsafe {
            let mut ctx: pg_sha1_ctx = core::mem::zeroed();
            pg_sha1_init(&mut ctx);
            let msg = b"abc";
            pg_sha1_update(&mut ctx, msg.as_ptr(), msg.len());
            let mut out = [0u8; SHA1_DIGEST_LENGTH];
            pg_sha1_final(&mut ctx, out.as_mut_ptr());
            assert_eq!(hex(&out), "a9993e364706816aba3e25717850c26c9cd0d89d");
        }
    }
}
